(function(){'use strict';
const $=id=>document.getElementById(id),cloud=()=>parent!==window?parent.TTCloud:null,esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),stamp=t=>Number.isFinite(t)?new Date(t).toLocaleString('ro-RO'):'Nicio verificare',errors={monitor_credentials_missing:'Salvează întâi conexiunea Invest în cloud.',monitor_account_changed:'Conexiunea cloud s-a schimbat. Reactivează monitorizarea pentru noul cont.',monitor_schema_invalid:'Lista de poziții sau soldul nu sunt verificabile.',rate_limited:'Limita Trading 212 a fost atinsă; următoarea rulare va reîncerca.',broker_permission_missing:'Cheia API nu are permisiunea de citire necesară.',broker_credentials_invalid:'Conexiunea Trading 212 nu mai este validă.',broker_timeout:'Brokerul nu a răspuns în limita de timp.',monitor_broker_unavailable:'Brokerul nu poate fi verificat momentan.',session_required:'Conectează Google pentru inbox.',session_expired:'Reconectează Google.'};
let last=null,owner=null,busy=false,error='',loaded=0;
function render(){const c=cloud(),s=c?.state()||{},m=last?.monitor, scheduler=last?.scheduler||s.monitor,capable=scheduler?.protocol==='tt-account-monitor-v1',connected=s.connected&&s.ready;
 const disabled=busy||s.busy||s.checking||!connected||!capable;
 $('monitorEnable').disabled=disabled||s.trading212?.cloud!==true||s.trading212?.environment!=='live';$('monitorDisable').disabled=disabled||!m?.enabled;$('monitorCheck').disabled=disabled||!m?.enabled;$('monitorRefresh').disabled=disabled;
 const stale=!Number.isFinite(m?.lastChecked)||Date.now()-m.lastChecked>600000;
 $('monitorState').textContent=error||(!capable?'Monitorul necesită actualizarea Workerului; datele locale rămân păstrate.':!connected?'Conectează Google pentru a activa monitorizarea și a citi inboxul.':busy?'Verific monitorul…':!m?.enabled?'Monitorizare oprită. Activează pentru contul Invest salvat în cloud.':m.lastError?'Verificare cu eroare: '+(errors[m.lastError.code]||m.lastError.code):!scheduler?.schedulerFresh?'Monitorizare solicitată · rularea periodică nu este încă confirmată.':stale?'Monitorizare activă · ultima citire este veche sau absentă.':'Monitorizare activă · scheduler și broker verificați.');
 const cov=m?.report?.coverage;$('monitorCoverage').textContent='Scheduler: '+stamp(scheduler?.schedulerAt)+' · Ultima citire broker reușită: '+stamp(m?.lastChecked)+(cov?' · prețuri '+cov.prices+'/'+cov.positions+' · stopuri '+cov.stops+'/'+cov.positions+' · ținte '+cov.targets+'/'+cov.positions:'')+(m?.lastError?' · ultima încercare: '+stamp(m.lastError.at):'');
 $('monitorInbox').innerHTML='<h3>Inbox · alerte păstrate pe server</h3>'+(m?.events?.length?'<ul>'+m.events.slice(0,30).map(a=>'<li><b>'+esc(a.ticker||'Conexiune')+'</b> · '+esc(a.type==='error'?errors[a.text]||a.text:a.text)+' <small class="muted">'+esc(stamp(a.at))+'</small></li>').join('')+'</ul>':'<p class="muted">Nicio alertă păstrată. '+(!m?.enabled?'Monitorul este oprit.':m.lastChecked?'Acoperirea este afișată mai sus; absența unei alerte nu confirmă lipsa riscului.':'Aștept prima citire broker reușită.')+'</p>');
}
async function refresh(action=null){const c=cloud(),s=c?.state();if(busy||!s?.connected||!s.ready||s.monitor?.protocol!=='tt-account-monitor-v1')return;const identity=s.email;busy=true;error='';render();try{const result=action?await action(c):await c.monitor();if(cloud()?.state().email===identity){last=result;loaded=Date.now();}}catch(e){error=errors[e.message]||'Monitor indisponibil: '+e.message;}finally{busy=false;render();}}
function state(){const s=cloud()?.state(),identity=s?.connected?s.email:null;if(identity!==owner){owner=identity;last=null;loaded=0;error='';}render();if(identity&&!busy&&Date.now()-loaded>60000)void refresh();}
 $('monitorEnable').onclick=()=>refresh(c=>c.configureMonitor(true));$('monitorDisable').onclick=()=>refresh(c=>c.configureMonitor(false));$('monitorCheck').onclick=()=>refresh(c=>c.runMonitor());$('monitorRefresh').onclick=()=>refresh();
 window.addEventListener('message',e=>{if(e.source===parent&&e.origin===location.origin&&e.data?.ttCloudState)state();});document.addEventListener('visibilitychange',()=>{if(!document.hidden)state();});setInterval(()=>{if(!document.hidden)state();},60000);state();
})();
