(function(){'use strict';
const $=id=>document.getElementById(id),cloud=()=>parent!==window?parent.TTCloud:null,stamp=t=>Number.isFinite(t)?new Date(t).toLocaleString('ro-RO'):'—';
let owner=null,devices=[],deviceId=null,busy=false,message='',readAt=0;
const supported=()=>isSecureContext&&'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const s=cloud()?.state(),ready=s?.connected&&s.ready&&s.push?.protocol==='tt-web-push-v1'&&s.push.available,device=devices.find(d=>d.id===deviceId),last=device?.last;
 $('pushEnable').disabled=busy||!ready||!supported();$('pushDisable').disabled=busy||!ready||!device;$('pushTest').disabled=busy||!ready||!device;
 $('pushState').textContent=message||(!supported()?'Browserul nu oferă push. Pe Android, folosește Chrome și permite notificările aplicației.':!s?.connected?'Conectează Google pentru notificările acestui dispozitiv.':!ready?'Serviciul push necesită Workerul actualizat.':Notification.permission==='denied'?'Notificările sunt blocate în setările browserului.':device?'Acest dispozitiv este înregistrat pentru notificări.':'Notificările nu sunt activate pe acest dispozitiv.');
 $('pushDelivery').innerHTML=last?'<p>Ultima trimitere: <b>'+esc({sending:'În curs',cancelled:'Oprită înainte de trimitere',accepted:'Acceptată de serviciul push',expired:'Abonament expirat',failed:'Eșuată'}[last.state]||last.state)+'</b> · '+esc(stamp(last.at))+'</p><p>Primire confirmată de browser: '+esc(stamp(last.receivedAt))+' · Deschidere confirmată: '+esc(stamp(last.openedAt))+'</p>':'<p class="muted">Nicio trimitere pentru acest dispozitiv. Primirea se confirmă numai când browserul răspunde.</p>';
}
const bytes=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
async function registration(){return await navigator.serviceWorker.getRegistration(new URL('../',location.href).href)||await navigator.serviceWorker.register('../sw.js',{scope:'../',updateViaCache:'none'});}
async function localId(){if(!supported())return null;const reg=await navigator.serviceWorker.getRegistration(new URL('../',location.href).href),sub=await reg?.pushManager.getSubscription();if(!sub)return null;return btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(sub.endpoint))))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
async function refresh(){const c=cloud(),s=c?.state();if(busy||!s?.connected||!s.ready||s.push?.protocol!=='tt-web-push-v1')return;const identity=s.email;busy=true;render();try{const r=await c.push(),id=await localId();if(cloud()?.state().email===identity){devices=r.devices;deviceId=id;readAt=Date.now();}}catch(e){message='Push indisponibil: '+e.message;}finally{busy=false;render();}}
async function enable(){if(busy||!supported())return;const identity=cloud()?.state().email;busy=true;message='';render();let created=null;try{const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Permite notificările pentru acest site din setările browserului.');const r=await cloud().push(),reg=await registration();if(!reg.active)await navigator.serviceWorker.ready;if(cloud()?.state().email!==identity)throw Error('Contul Google s-a schimbat.');let sub=await reg.pushManager.getSubscription();if(!sub){sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes(r.publicKey)});created=sub;}const saved=await cloud().subscribePush(sub.toJSON());if(cloud()?.state().email!==identity)throw Error('Contul Google s-a schimbat.');devices=saved.devices;deviceId=saved.deviceId;message='Notificări activate pe acest dispozitiv. Poți trimite un test.';}catch(e){if(created)try{await created.unsubscribe();}catch{}message=e.message==='push_owned_by_other_account'?'Abonamentul aparține altui cont Google. Conectează contul inițial și oprește notificările înainte de schimbare.':'Activarea nu a reușit: '+e.message;}finally{busy=false;render();}}
async function disable(){if(busy||!deviceId)return;const identity=cloud()?.state().email;busy=true;message='';render();try{const result=await cloud().removePush(deviceId),reg=await registration(),sub=await reg.pushManager.getSubscription();if(cloud()?.state().email!==identity)throw Error('Contul Google s-a schimbat.');devices=result.devices;deviceId=null;if(sub&&!await sub.unsubscribe())throw Error('Serverul a oprit trimiterile; browserul nu a confirmat ștergerea abonamentului.');message='Notificările acestui dispozitiv sunt oprite.';}catch(e){message='Oprire: '+e.message;}finally{busy=false;render();}}
async function test(){if(busy||!deviceId)return;const identity=cloud()?.state().email;busy=true;message='';render();try{const result=await cloud().testPush(deviceId);if(cloud()?.state().email!==identity)throw Error('Contul Google s-a schimbat.');devices=result.devices;message='Test trimis. Confirmarea primirii apare după răspunsul browserului.';}catch(e){message='Test nereușit: '+e.message;}finally{busy=false;readAt=0;render();}}
function state(){const s=cloud()?.state(),identity=s?.connected?s.email:null;if(identity!==owner){owner=identity;devices=[];deviceId=null;message='';readAt=0;}render();if(identity&&!busy&&Date.now()-readAt>60000)void refresh();}
 $('pushEnable').onclick=enable;$('pushDisable').onclick=disable;$('pushTest').onclick=test;$('pushRefresh').onclick=()=>{message='';void refresh();};
 window.addEventListener('message',e=>{if(e.source===parent&&e.origin===location.origin&&e.data?.ttCloudState)state();});document.addEventListener('visibilitychange',()=>{if(!document.hidden)state();});setInterval(()=>{if(!document.hidden)state();},60000);state();
})();
