(function(){'use strict';
const $=id=>document.getElementById(id),cloud=()=>parent!==window?parent.TTCloud:null,stamp=t=>Number.isFinite(t)?new Date(t).toLocaleString('ro-RO'):'—';
let owner=null,devices=[],deviceId=null,busy=false,message='',readAt=0,generation=0;
const supported=()=>isSecureContext&&'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const identity=()=>{const s=cloud()?.state();return s?.connected?s.email:null;};
const ticket=()=>({email:identity(),generation});
const current=t=>!!t.email&&identity()===t.email&&generation===t.generation;
function guard(t){if(!current(t))throw Error('Contul Google s-a schimbat. Reia acțiunea în contul curent.');}
function ready(){const s=cloud()?.state();return s?.connected&&s.ready&&s.push?.protocol==='tt-web-push-v1'&&s.push.available;}
function render(){const s=cloud()?.state(),device=devices.find(d=>d.id===deviceId),last=device?.last,permission=supported()?Notification.permission:null;
 $('pushEnable').disabled=busy||!ready()||!supported()||permission==='denied';$('pushEnable').textContent=device&&last?.state==='expired'?'Reactivează notificările aici':'Activează notificările aici';
 $('pushDisable').disabled=busy||!ready()||!device;$('pushTest').disabled=busy||!ready()||!device||permission!=='granted'||last?.state==='expired';
 $('pushState').textContent=message||(!supported()?'Browserul nu oferă push. Pe Android, folosește Chrome și permite notificările aplicației.':!s?.connected?'Conectează Google pentru notificările acestui dispozitiv.':!ready()?'Serviciul push necesită Workerul actualizat.':permission==='denied'?'Notificările sunt blocate. În Chrome: informațiile site-ului → Permisiuni → Notificări, apoi revino și verifică livrarea.':last?.state==='expired'?'Abonamentul a expirat. Apasă „Reactivează notificările aici”, apoi trimite un test.':device&&permission!=='granted'?'Dispozitiv înregistrat; permisiunea de notificări trebuie acordată din nou.':device?'Acest dispozitiv este înregistrat pentru notificări.':'Notificările nu sunt activate pe acest dispozitiv.');
 $('pushDelivery').innerHTML=last?'<p>Ultima trimitere: <b>'+esc({sending:'În curs',cancelled:'Oprită înainte de trimitere',accepted:'Acceptată de serviciul push',expired:'Abonament expirat',failed:'Eșuată'}[last.state]||last.state)+'</b> · '+esc(stamp(last.at))+'</p><p>Primire confirmată de browser: '+esc(stamp(last.receivedAt))+' · Deschidere confirmată: '+esc(stamp(last.openedAt))+'</p>':'<p class="muted">Nicio trimitere pentru acest dispozitiv. Primirea se confirmă numai când browserul răspunde.</p>';
}
const bytes=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
async function registration(){return await navigator.serviceWorker.getRegistration(new URL('../',location.href).href)||await navigator.serviceWorker.register('../sw.js',{scope:'../',updateViaCache:'none'});}
async function idFor(sub){if(!sub)return null;return btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(sub.endpoint))))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
async function localId(){if(!supported())return null;const reg=await navigator.serviceWorker.getRegistration(new URL('../',location.href).href);return idFor(await reg?.pushManager.getSubscription());}
async function refresh(){if(busy||!ready())return;const t=ticket();busy=true;render();try{const r=await cloud().push();guard(t);const id=await localId();guard(t);devices=r.devices;deviceId=id;message='';}catch(e){if(current(t))message='Push indisponibil: '+e.message;}finally{readAt=Date.now();busy=false;state();}}
async function activeRegistration(reg){if(reg.active)return;let timeout;try{await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error('Serviciul de notificări nu s-a activat. Reîncarcă aplicația și reîncearcă.')),10000);})]);}finally{clearTimeout(timeout);}}
async function enable(){if(busy||!supported()||!ready())return;const t=ticket();busy=true;message='';render();let created=null;try{
 const permission=await Notification.requestPermission();guard(t);if(permission!=='granted')throw Error('Permite notificările pentru acest site din setările browserului.');const r=await cloud().push();guard(t);const reg=await registration();guard(t);await activeRegistration(reg);guard(t);let sub=await reg.pushManager.getSubscription();guard(t);
 if(sub){const id=await idFor(sub);guard(t);const device=r.devices.find(d=>d.id===id),key=sub.options?.applicationServerKey,expected=bytes(r.publicKey),actual=key?new Uint8Array(key):null,changed=actual&&(actual.length!==expected.length||actual.some((v,i)=>v!==expected[i]));
  if(changed&&!device)throw Error('Abonamentul local trebuie oprit din contul Google în care a fost activat.');if(device&&(device.last?.state==='expired'||changed)){await cloud().removePush(id);guard(t);devices=r.devices.filter(d=>d.id!==id);deviceId=null;if(!await sub.unsubscribe())throw Error('Serverul a oprit vechiul abonament; browserul nu a confirmat înlocuirea lui. Reîncearcă din setările site-ului.');guard(t);sub=null;}
 }
 if(!sub){sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes(r.publicKey)});created=sub;guard(t);}guard(t);const saved=await cloud().subscribePush(sub.toJSON());guard(t);devices=saved.devices;deviceId=saved.deviceId;message='Notificări activate pe acest dispozitiv. Poți trimite un test.';
 }catch(e){if(created)try{await created.unsubscribe();}catch{}if(current(t))message=e.message==='push_owned_by_other_account'?'Abonamentul aparține altui cont Google. Conectează contul inițial și oprește notificările înainte de schimbare.':'Activarea nu a reușit: '+e.message;}finally{busy=false;readAt=Date.now();state();}}
async function disable(){if(busy||!deviceId||!ready())return;const t=ticket();busy=true;message='';render();try{const result=await cloud().removePush(deviceId);guard(t);devices=result.devices;deviceId=null;const reg=await registration();guard(t);const sub=await reg.pushManager.getSubscription();guard(t);if(sub&&!await sub.unsubscribe())throw Error('Serverul a oprit trimiterile; browserul nu a confirmat ștergerea abonamentului.');guard(t);message='Notificările acestui dispozitiv sunt oprite.';}catch(e){if(current(t))message='Oprire: '+e.message;}finally{busy=false;readAt=Date.now();state();}}
async function test(){if(busy||!deviceId||!ready()||!supported()||Notification.permission!=='granted'||devices.find(d=>d.id===deviceId)?.last?.state==='expired')return;const t=ticket(),id=deviceId;busy=true;message='';render();try{const result=await cloud().testPush(id);guard(t);devices=result.devices;const last=devices.find(d=>d.id===id)?.last;message=last?.state==='accepted'?(last.receivedAt?'Test primit și confirmat de browser.':'Test acceptat de serviciul push; primirea de către browser încă nu este confirmată.'):last?.state==='expired'?'Testul a confirmat un abonament expirat. Reactivează notificările și reîncearcă.':last?.state==='failed'?'Testul nu a fost acceptat de serviciul push. Verifică internetul și reîncearcă.':'Trimiterea testului nu este confirmată. Apasă „Verifică livrarea”.';}catch(e){if(current(t))message='Test nereușit: '+e.message;}finally{busy=false;readAt=Date.now();state();}}
function state(){const next=identity();if(next!==owner){owner=next;generation++;devices=[];deviceId=null;message='';readAt=0;}render();if(next&&!busy&&Date.now()-readAt>60000)void refresh();}
 $('pushEnable').onclick=enable;$('pushDisable').onclick=disable;$('pushTest').onclick=test;$('pushRefresh').onclick=()=>{message='';void refresh();};
 window.addEventListener('message',e=>{if(e.source===parent&&e.origin===location.origin&&e.data?.ttCloudState)state();});document.addEventListener('visibilitychange',()=>{if(!document.hidden)state();});setInterval(()=>{if(!document.hidden)state();},60000);state();
})();
