(function(){'use strict';const $=id=>document.getElementById(id),cloud=()=>parent!==window?parent.TTCloud:null;let googleLoaded=false,nonce='';
const messages={cloud_not_configured:'Serviciul PC ↔ telefon nu este activat încă. Datele rămân local; autentificarea Google și baza de date trebuie configurate.',session_expired:'Sesiunea Google a expirat. Reconectează-te pentru sincronizare.',session_required:'Conectează contul Google pentru sincronizare.',account_mismatch:'Acest dispozitiv conține date asociate altui cont Google. Folosește contul inițial; sincronizarea este blocată pentru a nu amesteca datele.',cloud_unavailable:'Serviciul cloud nu răspunde. Modificările tale rămân local.',invalid_google_token:'Autentificarea Google nu a putut fi verificată. Reîncepe conectarea.'};
function render(s){$('status').textContent=s.error?(messages[s.error]||s.error):s.busy?'Sincronizez și verific diferențele…':s.connected?s.conflicts.length?'Sincronizare parțială · există modificări care cer alegerea ta.':'Cont conectat · sincronizare automată activă.':'Serviciu disponibil · conectează contul Google.';$('prepare').disabled=!s.ready||s.busy;$('prepare').hidden=s.connected;$('identity').textContent=s.email?'Cont: '+s.email:'';['sync','restore','deleteKey','publishKey'].forEach(id=>$(id).disabled=!s.connected||s.busy);$('logout').hidden=!s.connected;$('logout').disabled=s.busy;$('stamp').textContent=s.lastSync?'Ultima reconciliere: '+new Date(s.lastSync).toLocaleString('ro-RO'):'Încă nu există o sincronizare confirmată.';$('conflicts').hidden=!s.conflicts.length;$('choices').replaceChildren();for(const key of s.conflicts){const row=document.createElement('div');row.className='conflict';const title=document.createElement('p');title.textContent=key;row.append(title);const view=cloud().conflictView(key);for(const [name,text] of [['Pe acest dispozitiv',view.local],['În cloud',view.remote]]){const details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent=name;pre.textContent=text;pre.style.cssText='white-space:pre-wrap;overflow-wrap:anywhere;max-height:240px;overflow:auto;font-size:13px';details.append(summary,pre);row.append(details);}for(const [choice,label] of [['local','Păstrează varianta acestui dispozitiv'],['remote','Folosește varianta cloud']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>action(()=>cloud().resolve(key,choice));row.append(b);}$('choices').append(row);}}
async function action(fn){try{await fn();render(cloud().state());}catch(e){$('status').textContent=messages[e.message]||e.message;}}
$('prepare').onclick=()=>action(async()=>{const c=cloud();if(!c?.state().ready)throw Error('cloud_not_configured');nonce=(await c.challenge()).nonce;if(!googleLoaded)await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.onload=()=>{googleLoaded=true;resolve();};script.onerror=()=>reject(Error('Google nu poate fi încărcat. Verifică internetul.'));document.head.append(script);});google.accounts.id.initialize({client_id:c.clientId,nonce,auto_select:false,callback:r=>action(()=>c.login(r.credential,nonce))});google.accounts.id.renderButton($('googleButton'),{theme:'outline',size:'large',text:'signin_with',width:280});$('status').textContent='Apasă butonul Google și alege același cont pe ambele dispozitive.';});
$('sync').onclick=()=>action(()=>cloud().sync());$('logout').onclick=()=>action(()=>cloud().logout());$('restore').onclick=()=>action(()=>cloud().restore());$('publishKey').onclick=()=>action(()=>cloud().publishCredentials());$('deleteKey').onclick=()=>action(()=>cloud().deleteCredentials());
window.addEventListener('message',e=>{if(e.source===parent&&e.origin===location.origin&&e.data?.ttCloudState)render(e.data.ttCloudState);});
if(cloud())render(cloud().state());else $('status').textContent='Deschide această pagină din aplicația Trading Tools → Cont & sincronizare.';
})();
