(function(){'use strict';const $=id=>document.getElementById(id),cloud=()=>parent!==window?parent.TTCloud:null;let googleLoaded=false,nonce='';
const labels={tt_europe_signals_v1:'Istoricul semnalelor Europa',tt_europe_risk_settings_v1:'Bugetul și setările de risc Europa',tt_journal_v1:'Jurnal manual',tt_trade_plans_v1:'Planuri de tranzacționare',tt_ticket_capital:'Capitalul planului',tt_journal_settings_v1:'Setările jurnalului',tt_trading212_fills_v1:'Execuții Trading 212',tt_trading212_portfolio_v1:'Portofoliu Trading 212',tt_holdings_theses_v1:'Ipoteze dețineri',tt_holdings_symbols_v1:'Asocierea tickerelor',tt_holdings_benchmarks_v1:'Benchmark dețineri',wl_stocks:'Watchlist',tt_theme:'Tema aplicației',tt_pf_account:'Contul selectat',cloud_credentials:'Conexiunea Trading 212'};
const messages={cloud_not_configured:'Serviciul PC ↔ telefon așteaptă configurarea. Datele rămân pe acest dispozitiv. După activarea serviciului, apasă „Reverifică serviciul”.',cloud_worker_missing:'Serviciul de sincronizare nu este încă publicat. Conectarea Google devine disponibilă după activarea lui; datele rămân pe acest dispozitiv.',cloud_protocol_mismatch:'Serviciul cloud trebuie actualizat înainte de conectare. Datele rămân pe acest dispozitiv.',session_expired:'Sesiunea Google a expirat. Reconectează-te pentru sincronizare.',session_required:'Conectează contul Google pentru sincronizare.',account_mismatch:'Acest dispozitiv conține date asociate altui cont Google. Folosește contul inițial; sincronizarea este blocată pentru a nu amesteca datele.',cloud_unavailable:'Serviciul cloud nu răspunde. Modificările tale rămân local.',invalid_google_token:'Autentificarea Google nu a putut fi verificată. Reîncepe conectarea.'};
function render(s){$('status').textContent=s.checking?'Verific disponibilitatea serviciului…':s.error?(messages[s.error]||s.error):s.busy?'Sincronizez și verific diferențele…':s.connected?s.conflicts.length?'Sincronizare parțială · există modificări care cer alegerea ta.':'Cont conectat · sincronizare automată activă.':'Serviciu disponibil · conectează contul Google.';$('recheck').disabled=s.busy||s.checking;$('prepare').disabled=!s.ready||s.busy||s.checking;$('prepare').hidden=s.connected;$('identity').textContent=s.email?'Cont: '+s.email:'';['sync','restore','deleteKey','publishKey'].forEach(id=>$(id).disabled=!s.connected||!s.ready||s.busy||s.checking);$('logout').hidden=!s.connected;$('logout').disabled=s.busy||s.checking;$('stamp').textContent=s.lastSync?'Ultima reconciliere: '+new Date(s.lastSync).toLocaleString('ro-RO'):'Încă nu există o sincronizare confirmată.';$('setup').hidden=!s.setup;$('checks').replaceChildren();if(s.setup)for(const [key,label] of [['database','Bază de date'],['schema','Stocarea jurnalului'],['google','Conectare Google'],['encryption','Criptare cloud']]){const li=document.createElement('li');li.textContent=label+' · '+(s.setup[key]?'verificat':'de configurat');$('checks').append(li);}$('europeScope').textContent=!s.ready?'Europa: istoricul și setările de risc rămân local până la activarea serviciului.':s.supportedKeys?.includes('tt_europe_signals_v1')&&s.supportedKeys?.includes('tt_europe_risk_settings_v1')?'Europa: istoricul semnalelor și setările de risc sunt incluse după conectarea Google.':'Europa: serverul trebuie actualizat pentru istoricul semnalelor și setările de risc; acestea rămân local.';$('conflicts').hidden=!s.conflicts.length;$('choices').replaceChildren();for(const key of s.conflicts){const row=document.createElement('div');row.className='conflict';const title=document.createElement('p');title.textContent=labels[key]||key;row.append(title);const view=cloud().conflictView(key);for(const [name,text] of [['Pe acest dispozitiv',view.local],['În cloud',view.remote]]){const details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent=name;pre.textContent=text;pre.style.cssText='white-space:pre-wrap;overflow-wrap:anywhere;max-height:240px;overflow:auto;font-size:13px';details.append(summary,pre);row.append(details);}for(const [choice,label] of [['local','Păstrează varianta acestui dispozitiv'],['remote','Folosește varianta cloud']]){const b=document.createElement('button');b.textContent=label;b.disabled=s.busy||s.checking;b.onclick=()=>action(()=>cloud().resolve(key,choice));row.append(b);}$('choices').append(row);}}
async function action(fn){try{await fn();render(cloud().state());}catch(e){$('status').textContent=messages[e.message]||e.message;}}
$('prepare').onclick=()=>action(async()=>{const c=cloud();if(!c?.state().ready)throw Error('cloud_not_configured');nonce=(await c.challenge()).nonce;if(!googleLoaded)await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.onload=()=>{googleLoaded=true;resolve();};script.onerror=()=>reject(Error('Google nu poate fi încărcat. Verifică internetul.'));document.head.append(script);});google.accounts.id.initialize({client_id:c.clientId,nonce,auto_select:false,callback:r=>action(()=>c.login(r.credential,nonce))});google.accounts.id.renderButton($('googleButton'),{theme:'outline',size:'large',text:'signin_with',width:280});$('status').textContent='Apasă butonul Google și alege același cont pe ambele dispozitive.';});
$('recheck').onclick=()=>action(()=>cloud().recheck());
$('sync').onclick=()=>action(()=>cloud().sync());$('logout').onclick=()=>action(()=>cloud().logout());$('restore').onclick=()=>action(()=>cloud().restore());$('publishKey').onclick=()=>action(()=>cloud().publishCredentials());$('deleteKey').onclick=()=>action(()=>cloud().deleteCredentials());
window.addEventListener('message',e=>{if(e.source===parent&&e.origin===location.origin&&e.data?.ttCloudState)render(e.data.ttCloudState);});
if(cloud())render(cloud().state());else $('status').textContent='Deschide această pagină din aplicația Trading Tools → Cont & sincronizare.';
})();
