(function(g){
'use strict';
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(v,c='')=>Number.isFinite(v)?v.toLocaleString('ro-RO',{maximumFractionDigits:2})+(c?' '+c:''):'—',signed=(v,c)=>(v>0?'+':'')+fmt(v,c),day=at=>new Date(at).toLocaleString('ro-RO');let selectedAt=null,current=null;
function point(index){if(!current?.analysis.curve.length)return;const {analysis:a,currency:c}=current,x=a.curve[Math.max(0,Math.min(a.curve.length-1,Number(index)))];selectedAt=x.at;const out=document.getElementById('pnlPoint'),slider=document.getElementById('pnlPointSlider');out.textContent=day(x.at)+' · P&L cumulat '+signed(x.cumulative,c)+' · rezultat la acest timp '+signed(x.pnl,c)+' · scădere față de vârf '+fmt(x.drawdown,c);slider.setAttribute('aria-valuetext',out.textContent);}
function render(report){
 const host=document.getElementById('performanceAnalytics');if(!host||!g.T212Performance)return;const a=g.T212Performance.analyse(report),c=report.currency;current={analysis:a,currency:c};
 let chart='<p>Curba apare după prima execuție SELL cu P&L raportat în moneda selectată.</p>';
 if(a.error)chart='<p>Agregatele nu sunt calculabile; verifică execuțiile importate.</p>';
 else if(a.curve.length){
  const points=[{at:a.curve[0].at-1,cumulative:0},...a.curve],low=points.reduce((n,x)=>Math.min(n,x.cumulative),0),high=points.reduce((n,x)=>Math.max(n,x.cumulative),0),span=high-low||1,from=points[0].at,to=points.at(-1).at,plot=x=>[64+(x.at-from)/Math.max(1,to-from)*630,160-(x.cumulative-low)/span*125],path=points.map((x,i)=>(i?'L':'M')+plot(x).map(v=>v.toFixed(2)).join(' ')).join(' '),zero=160-(0-low)/span*125;
  chart='<svg viewBox="0 0 740 190" role="img" aria-label="P&L realizat cumulat, '+esc(c)+'; scădere maximă '+esc(fmt(a.maxDrawdown,c))+'"><title>Curba P&L realizat din execuțiile selectate</title><line x1="64" x2="694" y1="'+zero+'" y2="'+zero+'" stroke="currentColor" opacity=".3"/><path d="'+path+'" fill="none" stroke="var(--accent,#46c5a8)" stroke-width="2.5"/><text x="4" y="35" fill="currentColor">'+esc(fmt(high))+'</text><text x="4" y="163" fill="currentColor">'+esc(fmt(low))+'</text><text x="64" y="184" fill="currentColor">'+esc(new Date(from).toLocaleDateString('ro-RO'))+'</text><text x="694" y="184" text-anchor="end" fill="currentColor">'+esc(new Date(to).toLocaleDateString('ro-RO'))+'</text></svg><label class="pnl-slider">Inspectează un moment al curbei<input id="pnlPointSlider" type="range" min="0" max="'+(a.curve.length-1)+'" value="'+Math.max(0,selectedAt===null?a.curve.length-1:a.curve.findIndex(x=>x.at===selectedAt))+'" aria-label="Moment pe curba P&L"></label><p id="pnlPoint" role="status"></p>';
 }
 const markup='<section class="pnl-analytics"><h3>Evoluția rezultatului realizat</h3><div class="pnl-highlights">'+[['Scădere maximă de la vârf',fmt(a.maxDrawdown,c)],['Cea mai bună ieșire',signed(a.best,c)],['Cea mai slabă ieșire',signed(a.worst,c)]].map(([l,v])=>'<div><small>'+esc(l)+'</small><b>'+esc(v)+'</b></div>').join('')+'</div>'+chart+'<p class="performance-status">Curba pornește de la zero la începutul filtrului. Scăderea este în '+esc(c||'moneda selectată')+', pe P&L realizat; nu este drawdown-ul valorii contului și nu include pozițiile deschise, depunerile sau dividendele. Execuțiile la același timp sunt grupate.</p><details><summary>Unde se acumulează câștigurile, pierderile și costurile</summary><div class="broker-performance-table"><table><thead><tr><th>Instrument</th><th>Ieșiri cu P&L</th><th>Win rate</th><th>Total raportat</th><th>Medie / ieșire</th></tr></thead><tbody>'+(a.symbols.length?a.symbols.map(x=>'<tr><td><button data-performance-ticker="'+esc(x.ticker)+'">'+esc(x.ticker)+'</button></td><td>'+x.count+'</td><td>'+esc(fmt(x.winRate))+'%</td><td class="'+(x.total>=0?'positive':'negative')+'">'+esc(signed(x.total,c))+'</td><td>'+esc(signed(x.average,c))+'</td></tr>').join(''):'<tr><td colspan="5">Nicio ieșire cu rezultat verificat.</td></tr>')+'</tbody></table></div><p>Costuri raportate în execuțiile filtrate: '+esc(a.fees.map(x=>fmt(x.total,x.currency)+' · '+x.count+' elemente').join(' / ')||'niciun cost verificat')+'.'+(a.unknownCosts?' '+a.unknownCosts+' execuții cu costuri neverificate.':'')+' Sumele pe monede rămân separate; costurile nu se scad din nou din P&L.</p></details></section>';
 if(host.innerHTML!==markup)host.innerHTML=markup;
 const slider=document.getElementById('pnlPointSlider');if(slider){slider.oninput=()=>point(slider.value);point(slider.value);}
 host.querySelectorAll('[data-performance-ticker]').forEach(b=>b.onclick=()=>{const s=document.getElementById('performanceTicker');s.value=b.dataset.performanceTicker;s.onchange();});
}
g.TTDeskAnalytics={render,point};
})(window);
