(function(g){
'use strict';
const E=g.TradeEvidence,$=id=>document.getElementById(id),esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(v,c='')=>Number.isFinite(v)?v.toLocaleString('ro-RO',{maximumFractionDigits:2})+(c?' '+c:''):'—',date=t=>new Date(t).toLocaleString('ro-RO'),NAMES={verdict:'Verdict',neural:'Neural',boosting:'Boosting',hmm:'HMM',isolation:'Isolation',quantile:'Quantile',garch:'GARCH',knn:'KNN'},DIRECTIONS={'0':'Descendent','1':'Mixt','2':'Ascendent',missing:'Indisponibil',abstain:'Abținere',context:'Context'},STATES={pending:'Așteaptă BUY',expired:'Fereastră expirată',open:'Poziție în curs',closed:'Închis și asociat',ambiguous:'Asociere ambiguă',unverified:'Închidere neverificată'};
let context=null,message='',busy=false,limit=20,demoData=null;const memory=new Map(),demoStorage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};
function data(){
 if(context?.demo){if(!demoData){demoData=E.demo();demoStorage.setItem(E.KEY,JSON.stringify({version:E.VERSION,entries:demoData.records}));}return {storage:demoStorage,scope:demoData.history.scope,snapshot:{fetchedAt:new Date().toISOString(),positions:[]},history:demoData.history};}
 const selected=g.T212Snapshot?.read('live');return {storage:g.localStorage,scope:selected?.[0]||null,snapshot:selected?.[1]||null,history:g.T212Performance?.read({selectedCurrency:selected?.[1].summary?.currency})||{rows:[],scope:null}};
}
function baseline(d,candidate){const xs=d.snapshot?.positions;if(!d.scope||!g.T212Snapshot.fresh(d.snapshot)||!Array.isArray(xs)||xs.some(p=>!p||typeof p.ticker!=='string'||!Number.isFinite(p.quantity)||p.quantity<0)||new Set(xs.map(p=>p.ticker)).size!==xs.length)return null;return xs.find(x=>x.ticker===candidate?.symbol+'_US_EQ')?.quantity||0;}
async function capture(quiet=false,chosen=null){
 if(busy||!context?.candidate)return false;busy=true;let saved=false;
 try{const c=chosen?.candidate||context.candidate,d=data(),quantity=baseline(d,c),report=chosen?.report||context.prepare?.()||context.report,model=g.TTDecisionBridge?.find(g.TTDecisionVerdict.sourceOf(c));
  if(!context.demo&&chosen?.scope&&chosen.scope!==d.scope)throw Error('Contul selectat s-a schimbat; analiza planului nu este asociată altui cont.');
  if(quantity===null)throw Error('Sincronizează contul și lista completă a pozițiilor înaintea capturii.');
  const previous=E.read(d.storage).entries.find(x=>x.scope===d.scope&&x.symbol===c.symbol&&x.verdict.snapshotId===report.snapshotId&&x.expiresAt>Date.now());
  if(previous){message='Analiza pentru '+c.symbol+' este deja păstrată până la '+date(previous.expiresAt)+'.';saved=true;}
  else{const r=E.snapshot(c,report,model,{scope:d.scope,baselineQuantity:quantity,baselineAt:Date.parse(d.snapshot.fetchedAt),simulation:context.demo});if(!r)throw Error('Sursa, nivelurile sau moneda nu permit capturarea unei analize actuale.');await E.save(r,{storage:d.storage,simulation:context.demo});message=(context.demo?'DEMO FICTIV · ':'')+'Analiza '+r.symbol+' este fixată. BUY trebuie să fie ulterior capturii și până la '+date(r.expiresAt)+'.'+(quantity?' Poziție preexistentă: rezultatul adăugării rămâne exclus până la o asociere verificabilă.':'');saved=true;}
 }catch(e){message='Analiza nu a fost salvată: '+e.message;if(!quiet)$('entryTrackingStatus').textContent=message;}
 finally{busy=false;if(context)render(context);}
 return saved;
}
function render(c){
 context=c;if(!$('entryTracking')||!E)return;const d=data(),candidate=c.candidate,quantity=candidate?baseline(d,candidate):null;
 $('trackEntry').disabled=busy||quantity===null||!g.TTDecisionVerdict?.sourceCurrent(candidate)||candidate?.currency!=='USD'||!c.report?.snapshotId||![candidate?.entryLow,candidate?.entryHigh,candidate?.stop,candidate?.target].every(x=>Number.isFinite(x)&&x>0);
 $('entryTrackingStatus').textContent=message||(c.demo?'DEMO FICTIV · Exemple simulate; nimic nu se salvează în cont.':!d.scope?'Conectează Invest pentru urmărirea analizelor înaintea intrărilor reale.':'Analiza se fixează pe acest dispozitiv; următorul BUY este asociat automat în maximum 30 minute. Un plan salvat păstrează și această analiză.');
 let records=[],outcomes=[],error=null;
 try{records=E.read(d.storage).entries;outcomes=E.evaluate(records,d.history);}catch(e){error=e.message;}
 const cutoff=c.days?Date.now()-c.days*86400000:-Infinity;outcomes=outcomes.filter(x=>(!c.ticker||x.record.ticker===c.ticker)&&(x.closedAt??x.record.createdAt)>=cutoff);const chosenCurrency=c.currency||d.history.currency,summary=E.summarize(outcomes,chosenCurrency),closed=summary.count;
 $('entryEvidenceCount').textContent=(c.demo?'DEMO FICTIV · ':'')+outcomes.length+' analize · '+closed+' poziții închise asociate';
 const groupRows=summary.groups.sort((a,b)=>a.model.localeCompare(b.model)||a.direction.localeCompare(b.direction));
 $('entryTracking').innerHTML='<p class="performance-status" role="status">'+esc(error||'Analiza originală rămâne fixă. Tranzacțiile vechi nu primesc retrospectiv un verdict. Sunt evaluate numai pozițiile noi, asociate fără ambiguitate, cu istoric complet.')+'</p><div class="pnl-highlights"><div><small>Poziții închise asociate</small><b>'+closed+'</b></div><div><small>P&L raportat · '+esc(chosenCurrency||'monedă neverificată')+'</small><b>'+esc(fmt(summary.total,chosenCurrency))+'</b></div><div><small>În curs / fără rezultat final</small><b>'+outcomes.filter(x=>x.state==='open'||x.state==='pending').length+'</b></div></div><div class="broker-performance-table"><table><thead><tr><th>Analiză păstrată</th><th>Intrare / închidere</th><th>Stare / rezultat</th><th>Verdict și modele fixate</th></tr></thead><tbody>'+(outcomes.length?outcomes.slice(0,limit).map(x=>'<tr><td><b>'+esc(x.record.symbol)+'</b><small>'+esc(date(x.record.createdAt))+'</small></td><td>'+esc(x.entryAt?date(x.entryAt):'Aștept BUY')+'<small>'+esc(x.closedAt?date(x.closedAt):x.remaining!==null?'Cantitate rămasă: '+fmt(x.remaining):'Până la '+date(x.record.expiresAt))+'</small></td><td>'+esc(STATES[x.state])+'<small>'+esc(x.pnl!==null?fmt(x.pnl,x.pnlCurrency)+(x.priceR!==null?' · '+fmt(x.priceR)+'R brut USD':''):x.reason)+'</small></td><td><details><summary>'+esc(x.record.verdict.code)+' · '+x.record.models.filter(m=>m.available).length+'/7 modele</summary><p>'+esc(x.record.source.asOf+' · '+x.record.mode+' · stop '+fmt(x.record.stop,x.record.currency))+'</p>'+x.record.models.map(m=>'<p>'+esc(NAMES[m.id])+': '+esc(!m.available?'Indisponibil':!m.eligible?'Abținere':DIRECTIONS[String(m.direction)]||'Context')+'</p>').join('')+'<p>'+esc(x.reason)+'</p></details></td></tr>').join(''):'<tr><td colspan="4">Nicio analiză păstrată pentru acest cont. Selectează un simbol și apasă „Păstrează analiza”.</td></tr>')+'</tbody></table></div>'+(outcomes.length>limit?'<button id="evidenceMore">Arată încă 20 de analize</button>':'')+'<details><summary>Rezultate pe verdict și model, inclusiv KNN</summary><p>P&L descriptiv pe grupurile semnalelor păstrate. Nu este acuratețea unei prognoze de 5 sesiuni și nu dovedește că modelul a produs câștigul. Selecția și momentul ieșirii influențează rezultatul; eșantioanele mici nu confirmă un avantaj.</p><div class="broker-performance-table"><table><thead><tr><th>Model / verdict</th><th>Semnal la captură</th><th>Poziții închise</th><th>Win rate</th><th>P&L raportat</th></tr></thead><tbody>'+(groupRows.length?groupRows.map(x=>'<tr><td>'+esc(NAMES[x.model])+'</td><td>'+esc(DIRECTIONS[x.direction]||x.direction)+'</td><td>'+x.count+'</td><td>'+esc(fmt(x.winRate))+'%</td><td>'+esc(fmt(x.total,chosenCurrency))+'</td></tr>').join(''):'<tr><td colspan="5">Aștept primele poziții închise asociate.</td></tr>')+'</tbody></table></div></details><button id="evidenceExport">Exportă analizele și asocierile</button>';
 $('trackEntry').onclick=()=>capture();const more=$('evidenceMore');if(more)more.onclick=()=>{limit+=20;render(context);};
 $('evidenceExport').onclick=()=>{const raw=error?d.storage.getItem(E.KEY):JSON.stringify({version:E.VERSION,exportedAt:Date.now(),simulation:c.demo,entries:records,outcomes},null,2),url=URL.createObjectURL(new Blob([raw||''],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='analize-intrare-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
}
g.TTDeskEvidence={render,capture};
})(window);
