(function(g){
'use strict';
const V=g.TTDecisionValidation,F=g.HoldingsForecast,cache=new Map(),reader=V.createReader(),names={neural:'Neural',boosting:'Boosting',knn:'KNN',quantile:'Cuantile',hmm:'HMM',isolation:'Isolation',garch:'GARCH',verdict:'Verdict cumulat'},esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=(v,n=2)=>Number.isFinite(v)?v.toLocaleString('ro-RO',{maximumFractionDigits:n}):'—';
let context=null,generation=0,busy=false,message='';const attempts=new Map();
function identity(c=context){return c?.candidate&&c.scope?{scope:c.scope,ticker:c.candidate.symbol+'_US_EQ',symbol:c.candidate.symbol,currency:c.candidate.currency,kind:c.demo?'synthetic':'market'}:null;}
function same(e){return F.key(e)===F.key(identity());}
function summaryOf(row){if(!row?.item)return null;if(!row.summary||Date.now()-row.builtAt>=30000){row.summary=V.build(row.item);row.builtAt=Date.now();}return row.summary;}
function peek(candidate,scope){const e=identity({candidate,scope,demo:context?.demo}),row=cache.get(F.key(e));return row?.item?{...summaryOf(row),readAt:row.at}:null;}
function metric(r){if(!r)return 'Fără rezultate';if(r.descriptive)return r.n+' contexte · fără acuratețe predictivă';if(!r.n)return 'Aștept rezultatele';if(r.model==='garch')return 'QLIKE '+num(r.score,3)+' · constant '+num(r.constantScore,3)+' / EWMA '+num(r.ewmaScore,3);if(r.model==='quantile')return 'Interval '+num(r.coverage*100)+'% acoperire · reper '+num(r.baselineCoverage*100)+'%; scor '+num(r.score)+' / '+num(r.baselineScore)+' ATR';if(r.model==='verdict')return r.directional+' direcții · '+r.abstentions+' abțineri · '+num(r.accuracy===null?null:r.accuracy*100)+'% clasă corectă';return num(r.accuracy*100)+'% clasă corectă · reper '+num(r.baselineAccuracy*100)+'%';}
function render(){
 const host=g.document.getElementById('focusValidation');if(!host||!context)return;const e=identity(),stored=cache.get(F.key(e)),summary=summaryOf(stored),open=host.querySelector('details')?.open;
 if(!e){host.innerHTML='<p class="detail-note">Validarea modelelor apare după selectarea unui simbol și a contului Invest.</p>';return;}
 const withForecast=summary?.rows.filter(r=>r.entries>0).length||0,review=summary?.rows.filter(r=>['review','blocked','stale'].includes(r.state)).length||0;
 host.innerHTML='<details class="validation-evidence"><summary>Dovezi prospective · '+esc(e.symbol)+' · '+withForecast+' / 9 rapoarte cu estimări'+(review?' · '+review+' de verificat':'')+'</summary><p class="detail-note" role="status">'+esc(message||stored?.error||(context.demo?'DEMO FICTIV · nu citesc registrele contului real.':stored?.loading?'Încarc estimările originale…':summary?.total?'Rezultate din prognozele păstrate înaintea evoluției prețului.':'Nu există estimări originale pe acest dispozitiv pentru instrumentul și contul selectate.'))+'</p>'+(summary?.ok?'<div class="broker-performance-table"><table><thead><tr><th>Model / orizont</th><th>Rezultat și reper</th><th>Dovezi disponibile</th></tr></thead><tbody>'+summary.rows.map(row=>'<tr><td>'+esc(names[row.model])+' · '+row.horizon+' sesiuni</td><td>'+esc(metric(row.report))+'</td><td>'+esc(row.label)+'<small>'+row.report.n+' orizonturi separate · '+row.report.pending+' în așteptare · '+row.report.unverifiable+' neverificabile'+(row.restored?' · '+row.restored+' restaurate, excluse':'')+(row.legacy?' · '+row.legacy+' versiuni vechi, excluse':'')+'</small><small>'+esc(row.reason)+'</small></td></tr>').join('')+'</tbody></table></div>':'')+'<button id="validationCheck" '+(busy||context.demo||!summary?.total?'disabled':'')+'>Verifică rezultatele pentru '+esc(e.symbol)+'</button> <button id="validationOpen">DESCHIDE REGISTRUL MODELELOR →</button><p class="detail-note">Clasă la ±1 ATR inițial pentru Neural, Boosting și KNN; interval pentru Cuantile; QLIKE pentru GARCH. HMM și Isolation descriu contextul. Estimările restaurate nu autentifică momentul prognozei și nu susțin verdictul. Sub 20 orizonturi separate: eșantion mic. Avantajul observat nu garantează rezultatele viitoare.</p><p class="detail-note">Istoricul prognozelor este pe acest dispozitiv; capturile analizelor de intrare se sincronizează separat. Verificarea se reia automat pentru EOD nou cât timp Desk-ul este deschis, vizibil și simbolul este selectat. Păstrează originalele și exclude sursele revizuite.</p></details>';
 if(open!==undefined)host.querySelector('details').open=open;
 const button=host.querySelector('#validationCheck');if(button)button.onclick=check;
 const show=host.querySelector('#validationOpen');if(show)show.onclick=()=>context.onOpen?.('holdings/');
}
async function load(e){const key=F.key(e),row=cache.get(key);if(!key||row?.loading||row&&Date.now()-row.at<30000)return;cache.set(key,{...row,loading:true,at:row?.at||0});render();try{const item=await reader.read(e);cache.set(key,{item,at:Date.now(),loading:false});}catch(error){cache.set(key,{error:error.message,at:Date.now(),loading:false});}if(same(e)){render();context.onChange?.();const s=summaryOf(cache.get(key));if(!g.document.hidden&&s?.rows.some(r=>r.freshness?.needsCheck)&&Date.now()-(attempts.get(key)||0)>=900000)void check();}}
function setContext(c){const before=F.key(identity());context=c;if(before!==F.key(identity())){generation++;busy=false;message='';}render();const e=identity();if(F.identity(e)&&!c.demo)void load(e);}
async function check(){
 const e=identity();if(busy||!F.identity(e)||context.demo)return;const token=generation,candidate=context.candidate;attempts.set(F.key(e),Date.now());busy=true;message='Verific închiderile efective la orizontul fiecărui model…';render();
 try{
  const bars=await g.D.fetchStock(e.symbol,{range:'5y',interval:'1d',ttl:0}),source=g.DailySeries.read(bars,e.symbol),now=Date.now();
  if(token!==generation||!same(e)||g.T212Snapshot?.read('live')?.[0]!==e.scope||context.candidate.trend?.historyKey!==candidate.trend?.historyKey)return;
  const item=await reader.check(e,{...source,symbol:e.symbol,kind:'market',retrievedAt:now},{now});if(token!==generation||!same(e)||g.T212Snapshot?.read('live')?.[0]!==e.scope)return;cache.set(F.key(e),{item,at:Date.now(),loading:false});message='Verificare încheiată. Estimările originale au rămas fixe; rezultatele revizuite sau incomplete sunt excluse.';
 }catch(error){if(token===generation&&same(e))message='Verificare indisponibilă: '+error.message+' Originalele sunt păstrate.';}
 finally{if(token===generation){busy=false;render();context.onChange?.();}}
}
g.TTDeskValidation={setContext,peek,render,check,metric};
})(window);
