import {KEYS,mergeRecord,validateValue,EvidenceCloud} from '../lib/cloud-sync-model.mjs?v=26.10.09.1548';
const EvidenceStore=EvidenceCloud.createStore(localStorage);
const PlanStore=window.TTPlanStore?.create(localStorage);
const Store=window.TTCloudStore,LOCAL_KEYS=KEYS.filter(k=>k!=='cloud_credentials'&&!EvidenceCloud.isBucket(k)),rawKeys=['tt_theme','tt_pf_account','tt_ticket_capital'];
const PERFORMANCE_KEYS=['tt_trading212_account_history_v1','tt_trading212_cash_v1'];
const EUROPE_KEYS=['tt_europe_signals_v1','tt_europe_risk_settings_v1'];let activeKeys=[];
let backupPaused=false,brokerBeforeBackup=null;
let endpoint='',ready=false,session=null,busy=false,baseline={},conflicts={},lastSync=null,error='',timer=null,checking=false,setup=null,initialization=null,poll=null,monitorCapability=null;
const emptyConnection=()=>({local:null,cloud:null,synced:false,environment:null,checkedAt:null,message:''});let trading212=emptyConnection();
const sameConnection=(a,b)=>!!a&&!!b&&a.key===b.key&&a.secret===b.secret&&a.environment===b.environment;
function connectionState(local,record){const remote=record?.value;trading212={local:!!local,cloud:!!remote,synced:sameConnection(local,remote),environment:remote?.environment||local?.environment||null,checkedAt:Date.now(),message:sameConnection(local,remote)?trading212.message:''};}
const state=()=>({ready,backupPaused,connected:!!session,email:session?.email||null,busy,checking,setup,lastSync,error,conflicts:Object.keys(conflicts),supportedKeys:[...activeKeys,...(EvidenceCloud.keys.every(k=>activeKeys.includes(k))?[EvidenceCloud.KEY]:[])],trading212:{...trading212},monitor:monitorCapability});
function broadcast(){window.dispatchEvent(new CustomEvent('tt-cloud-state',{detail:state()}));document.querySelectorAll('iframe').forEach(f=>f.contentWindow?.postMessage({ttCloudState:state()},location.origin));}
function local(key){const raw=localStorage.getItem(key);if(raw===null)return undefined;if(rawKeys.includes(key))return raw;try{return JSON.parse(raw);}catch(_){throw Error('Date locale incompatibile: '+key);}}
async function deviceOwner(){const stored=await Store.get('owner'),legacy=localStorage.getItem('tt_cloud_owner');if(stored!==null&&typeof stored!=='string')throw Error('account_mismatch');if(stored&&legacy&&stored!==legacy)throw Error('account_mismatch');return stored||legacy;}
async function value(key){if(EvidenceCloud.isBucket(key))return EvidenceStore.value(key);if(key==='tt_trade_plans_v1'){if(!PlanStore)throw Error('Modulul planurilor nu s-a încărcat. Reîncarcă aplicația înainte de sincronizare.');const record=await PlanStore.read();return record.raw===null?undefined:record.plans;}return key==='cloud_credentials'?(await window.T212Vault.read()||undefined):local(key);}
async function api(path,method='GET',data,anonymous=false){const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);try{const r=await fetch(endpoint+'/api/cloud/'+path,{method,cache:'no-store',credentials:'omit',redirect:'error',signal:c.signal,headers:{...(data?{'Content-Type':'application/json'}:{}),...(!anonymous&&session?{Authorization:'Bearer '+session.token}:{})},...(data?{body:JSON.stringify(data)}:{})});let b;try{b=await r.json();}catch{b={error:'cloud_unavailable'};}if(!r.ok){if(r.status===401&&path!=='auth'&&!anonymous){session=null;await Store.remove('session');}const e=Error(path==='status'&&r.status===404?'cloud_worker_missing':b.error||'cloud_unavailable');e.status=r.status;throw e;}return b;}finally{clearTimeout(t);}}
function notifyStorage(key,oldValue,newValue){document.querySelectorAll('iframe').forEach(f=>{try{f.contentWindow.dispatchEvent(new StorageEvent('storage',{key,oldValue,newValue,url:location.href,storageArea:localStorage}));}catch(_){}});window.dispatchEvent(new StorageEvent('storage',{key,oldValue,newValue,url:location.href,storageArea:localStorage}));}
async function apply(key,next,expected,locked=false){if((key==='tt_europe_signals_v1'||EvidenceCloud.isKey(key))&&!locked&&navigator.locks?.request)return navigator.locks.request(EvidenceCloud.isKey(key)?EvidenceCloud.KEY:key,()=>apply(key,next,expected,true));if(next!==undefined&&next!==null)validateValue(key,next);if(JSON.stringify(await value(key))!==JSON.stringify(expected))return false;if(EvidenceCloud.isBucket(key)){const before=localStorage.getItem(EvidenceCloud.KEY),saved=EvidenceStore.replace(key,expected,next);if(saved)notifyStorage(EvidenceCloud.KEY,before,localStorage.getItem(EvidenceCloud.KEY));return saved;}if(key==='cloud_credentials'){if(next){await window.T212Vault.save(next);const broker=document.getElementById('brokerFrame');if(broker)broker.src='../broker/?app=decision-mobile-v2&cloud='+Date.now();}return true;}if(key==='tt_trade_plans_v1'&&PlanStore){const saved=await PlanStore.replace(expected,next===null?undefined:next);if(saved)notifyStorage(key,JSON.stringify(expected)||null,JSON.stringify(next)||null);return saved;}const oldValue=localStorage.getItem(key);if(next===undefined||next===null)localStorage.removeItem(key);else localStorage.setItem(key,rawKeys.includes(key)?String(next):JSON.stringify(next));notifyStorage(key,oldValue,localStorage.getItem(key));return true;}
async function backup(){const list=await Store.get('backups:'+session.subject)||[],snapshot={};for(const k of LOCAL_KEYS){const v=await value(k);if(v!==undefined)snapshot[k]=v;}list.unshift({at:Date.now(),snapshot});await Store.put('backups:'+session.subject,list.slice(0,5));}
async function performSync(){if(!ready||!session||busy||checking||navigator.onLine===false)return;busy=true;error='';broadcast();try{
 backupPaused=await Store.get('backup-pause')===true;if(backupPaused)return;
 const owner=await deviceOwner();if(owner&&owner!==session.subject)throw Error('account_mismatch');await Store.put('owner',session.subject);
 const remote=(await api('records')).records;let backedUp=false;
 for(const key of activeKeys){
  if(conflicts[key]&&key!=='cloud_credentials')continue;const current=await value(key),record=remote[key],base=baseline[key];if(key==='cloud_credentials')connectionState(current,record);if(conflicts[key])continue;
  // Forgetting a local connection is not an instruction to erase the cloud key.
  if(key==='cloud_credentials'&&current===undefined&&base?.value){continue;}
  if(key==='cloud_credentials'&&record?.value===null){baseline[key]=record;continue;}
  const remoteValue=record?.value===null?undefined:record?.value;
  const result=mergeRecord(key,base?.value,current,remoteValue);
  if(result.conflicts.length){conflicts[key]={paths:result.conflicts,remote:record,local:current};continue;}
  const next=result.value;
  if(JSON.stringify(next)!==JSON.stringify(remoteValue)){
   if(next!==undefined)validateValue(key,next);
   const saved=await api('record','PUT',{key,value:next===undefined?null:next,revision:record?.revision||0});remote[key]={...saved,value:next};
  }
  if(JSON.stringify(next)!==JSON.stringify(current)){
   if(!backedUp&&key!=='cloud_credentials'){await backup();backedUp=true;}
   if(!await apply(key,next,current)){baseline[key]=remote[key]||{value:undefined,revision:0};continue;}
  }
  baseline[key]=remote[key]||{value:undefined,revision:0};if(key==='cloud_credentials')connectionState(await value(key),remote[key]);
 }
 // Ownership is durable before any upload; the legacy mirror may be full.
 try{localStorage.setItem('tt_cloud_owner',session.subject);}catch{}await Store.put('baseline:'+session.subject,baseline);lastSync=Date.now();
 }catch(e){error=e.status===409?'Datele au fost modificate pe celălalt dispozitiv. Reconcilierea se reia la următoarea sincronizare.':e.message;}finally{busy=false;broadcast();}}
async function sync(){if(navigator.locks)return navigator.locks.request('tt-cloud-sync',{ifAvailable:true},lock=>lock?performSync():undefined);return performSync();}
async function login(credential,nonce){if(!ready)throw Error('cloud_not_configured');const owner=await deviceOwner();const result=await api('auth','POST',{credential,nonce});if(owner&&owner!==result.subject){session={...result};await api('session','DELETE');session=null;throw Error('account_mismatch');}session=result;await Store.put('session',session);baseline=await Store.get('baseline:'+session.subject)||{};conflicts={};await sync();broadcast();}
async function logout(){if(session){try{await api('session','DELETE');}catch(_){}}session=null;conflicts={};trading212=emptyConnection();await Store.remove('session');error='';broadcast();}
async function resolve(key,choice){if(!conflicts[key]||!['local','remote'].includes(choice))return;const current=await value(key),records=(await api('records')).records,r=records[key];if(JSON.stringify(r)!==JSON.stringify(conflicts[key].remote)){conflicts[key]={...conflicts[key],remote:r};error='Datele cloud s-au schimbat. Verifică din nou alegerea.';broadcast();return;}await backup();if(EvidenceCloud.isBucket(key)){const next=EvidenceCloud.resolve(key,baseline[key]?.value,current,r?.value,choice).value;let saved=r;if(JSON.stringify(next)!==JSON.stringify(r?.value)){saved={...await api('record','PUT',{key,value:next===undefined?null:next,revision:r?.revision||0}),value:next};}if(!await apply(key,next,current))throw Error('Datele locale s-au modificat. Reîncearcă.');baseline[key]=saved||{revision:0};}else if(choice==='remote'){if(!await apply(key,r?.value===null?undefined:r?.value,current))throw Error('Datele locale s-au modificat. Reîncearcă.');baseline[key]=r||{revision:0};}else{const saved=await api('record','PUT',{key,value:current===undefined?null:current,revision:r?.revision||0});baseline[key]={...saved,value:current};}delete conflicts[key];await Store.put('baseline:'+session.subject,baseline);error='';broadcast();await sync();}
async function deleteCredentials(){if(!session)throw Error('session_required');const r=(await api('records')).records.cloud_credentials;await api('record','PUT',{key:'cloud_credentials',value:null,revision:r?.revision||0});await window.T212Vault.clear();baseline.cloud_credentials={value:undefined};delete conflicts.cloud_credentials;await Store.put('baseline:'+session.subject,baseline);const broker=document.getElementById('brokerFrame');if(broker)broker.src='../broker/?app=decision-mobile-v2&cloud-clear='+Date.now();await sync();}
async function credentialSession(){if(!session)throw Error('session_required');if(!ready)throw Error('cloud_not_configured');const owner=await deviceOwner();if(owner&&owner!==session.subject)throw Error('account_mismatch');await Store.put('owner',session.subject);trading212.message='';}
async function publishCredentials(){await credentialSession();const v=await window.T212Vault.read();if(!v)throw Error('Conectează întâi Trading 212 pe acest dispozitiv.');validateValue('cloud_credentials',v);const r=(await api('records')).records.cloud_credentials;await api('record','PUT',{key:'cloud_credentials',value:v,revision:r?.revision||0});const verified=(await api('records')).records.cloud_credentials;connectionState(await window.T212Vault.read(),verified);if(!sameConnection(v,verified?.value))throw Error('cloud_credentials_changed');baseline.cloud_credentials=verified;delete conflicts.cloud_credentials;await Store.put('baseline:'+session.subject,baseline);trading212.message='Conexiune Trading 212 salvată în cloud și verificată. Pe celălalt dispozitiv, folosește același cont Google și apasă „Preia conexiunea din cloud”.';}
async function restoreCredentials(){await credentialSession();const record=(await api('records')).records.cloud_credentials,current=await value('cloud_credentials');connectionState(current,record);if(!record?.value)throw Error('cloud_credentials_missing');validateValue('cloud_credentials',record.value);if(!await apply('cloud_credentials',record.value,current))throw Error('Datele locale s-au modificat. Reîncearcă.');const saved=await window.T212Vault.read();connectionState(saved,record);if(!sameConnection(saved,record.value))throw Error('Conexiunea Trading 212 nu a putut fi verificată pe acest dispozitiv.');baseline.cloud_credentials=record;delete conflicts.cloud_credentials;await Store.put('baseline:'+session.subject,baseline);trading212.message='Conexiune Trading 212 preluată din cloud și salvată pe acest dispozitiv. Reconectarea brokerului a pornit automat.';}
async function restore(){if(!session)return;const list=await Store.get('backups:'+session.subject)||[];if(!list.length)throw Error('Nu există o copie locală de restaurat.');const saved=list[0];for(const k of LOCAL_KEYS)await apply(k,saved.snapshot[k],await value(k));error='Copie locală restaurată. Următoarea sincronizare va verifica diferențele.';broadcast();}
function conflictView(key){const c=conflicts[key];if(!c)return null;const preview=v=>v===undefined?'Fără înregistrare':JSON.stringify(v,null,2).slice(0,4000);return key==='cloud_credentials'?{local:'Conexiune Trading 212 locală · '+(c.local?.environment||'absentă'),remote:'Conexiune Trading 212 cloud · '+(c.remote?.value?.environment||'absentă')}:{local:preview(c.local),remote:preview(c.remote?.value)};}
async function mutation(fn){if(busy||checking)throw Error('Sincronizare în curs. Așteaptă finalizarea înainte de această acțiune.');busy=true;error='';broadcast();try{return await fn();}catch(e){error=e.message;throw e;}finally{busy=false;broadcast();}}
const wrapped={};for(const [name,fn] of Object.entries({login,logout,resolve,deleteCredentials,publishCredentials,restoreCredentials,restore})){wrapped[name]=async(...args)=>{await mutation(()=>fn(...args));if(!['logout','restore'].includes(name))await sync();};}
async function pauseForBackup(){return mutation(async()=>{await Store.put('backup-pause',true);backupPaused=true;clearTimeout(timer);const broker=document.getElementById('brokerFrame');if(broker){brokerBeforeBackup=broker.src;broker.src='about:blank';}});}
async function resumeAfterBackup(){await mutation(async()=>{await Store.remove('backup-pause');backupPaused=false;const broker=document.getElementById('brokerFrame');if(broker&&brokerBeforeBackup){broker.src=brokerBeforeBackup;brokerBeforeBackup=null;}});await sync();}
window.TTCloud={pauseForBackup,resumeAfterBackup,monitor:()=>api('monitor'),configureMonitor:enabled=>api('monitor','PUT',{enabled}),runMonitor:()=>api('monitor/check','POST',{}),conflictView,state,sync,recheck,login,logout,resolve,deleteCredentials,publishCredentials,restoreCredentials,restore,challenge:()=>api('challenge','POST',{}),config:()=>({endpoint}),...wrapped};
window.addEventListener('storage',e=>{if(KEYS.includes(e.key)&&!busy){clearTimeout(timer);timer=setTimeout(sync,2500);}});
function plansChanged(){if(!busy){clearTimeout(timer);timer=setTimeout(sync,2500);}}
window.addEventListener('tt-plan-store-changed',plansChanged);PlanStore?.subscribe(plansChanged);
window.addEventListener('online',()=>ready?sync():recheck());document.addEventListener('visibilitychange',()=>{if(!document.hidden)(ready?sync():recheck());});
async function initialize(){let available=false;checking=true;error='';setup=null;activeKeys=[];broadcast();try{
 const cfg=await fetch('cloud-sync-config.json',{cache:'no-store'}).then(r=>r.json());if(cfg.enabled!==true&&cfg.autoActivate!==true)throw Error('cloud_not_configured');
 const u=new URL(cfg.endpoint);if(u.origin!=='https://premarket-scanner-html.mferent80.workers.dev'||u.pathname!=='/'||u.search||u.hash||u.username||u.password)throw Error('Endpoint cloud incompatibil.');endpoint=u.origin;
 // Readiness is public: no session, journal or broker credentials accompany this request.
 const status=await api('status','GET',undefined,true);monitorCapability=status.monitor||null;if(status.protocol!=='tt-cloud-sync-v1')throw Error('cloud_protocol_mismatch');
 setup=Object.fromEntries(['database','google','encryption','schema'].map(k=>[k,status.checks?.[k]===true]));
 if(status.enabled!==true||Object.values(setup).some(v=>!v))throw Error('cloud_not_configured');if(!/^[A-Za-z0-9_-]+\.apps\.googleusercontent\.com$/.test(status.clientId||''))throw Error('cloud_not_configured');
 const evidenceReady=Array.isArray(status.supportedKeys)&&EvidenceCloud.keys.every(k=>status.supportedKeys.includes(k));activeKeys=KEYS.filter(k=>k!==EvidenceCloud.KEY&&(!EvidenceCloud.isBucket(k)||evidenceReady)&&(!EUROPE_KEYS.includes(k)||status.supportedKeys?.includes(k))&&(!PERFORMANCE_KEYS.includes(k)||status.supportedKeys?.includes(k)));
 ready=true;available=true;window.TTCloud.clientId=status.clientId;
 if(poll===null)poll=setInterval(()=>{if(!document.hidden)sync();},30000);
 backupPaused=await Store.get('backup-pause')===true;if(backupPaused){const broker=document.getElementById('brokerFrame');if(broker){brokerBeforeBackup=broker.src;broker.src='about:blank';}}
 session=await Store.get('session');if(session){const verified=await api('session');if(verified.subject!==session.subject){session=null;await Store.remove('session');throw Error('session_expired');}baseline=await Store.get('baseline:'+session.subject)||{};}
 }catch(e){ready=available;error=e.message;}finally{checking=false;broadcast();}if(ready&&session&&!error)await sync();}
function recheck(){if(busy)return Promise.resolve();if(initialization)return initialization;initialization=initialize().finally(()=>{initialization=null;});return initialization;}
recheck();
