import {readPrivate,writePrivate} from './cloud-private-store.mjs';
import {base64url,createPushKeys,sendPush,validSubscription} from './web-push.mjs';
export const PUSH_KEY='__push_devices_v1';
const SERVICE='__push_service__',CONFIG='__push_config_v1',APP='https://mferent80-source.github.io/premarket_scanner.html/app/?module=app%2Fsync%2F';
const idFor=async s=>base64url(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));
async function keys(env,deps){let r=await readPrivate(SERVICE,CONFIG,env,deps);if(r)return r.value;const value=await createPushKeys();await writePrivate(SERVICE,CONFIG,value,0,env,deps);r=await readPrivate(SERVICE,CONFIG,env,deps);if(!r)throw Error('push_unavailable');return r.value;}
function safe(devices){return devices.map(d=>({id:d.id,createdAt:d.createdAt,last:d.last||null}));}
export async function handlePush({request,subject,env,deps,parseBody,upstream=fetch}){const path=new URL(request.url).pathname,reply=(body,status=200)=>({body,status}),row=await readPrivate(subject,PUSH_KEY,env,deps),devices=row?.value.devices||[],now=Date.now();
 if(path==='/api/cloud/push'&&request.method==='GET'){const config=await keys(env,deps);return reply({protocol:'tt-web-push-v1',publicKey:config.publicKey,devices:safe(devices)});}
 if(path==='/api/cloud/push'&&request.method==='PUT'){const b=await parseBody(request,5000);if(Object.keys(b).some(k=>k!=='subscription')||!validSubscription(b.subscription))return reply({error:'invalid_push'},400);try{await crypto.subtle.importKey('raw',Uint8Array.from(atob(b.subscription.keys.p256dh.replace(/-/g,'+').replace(/_/g,'/')),x=>x.charCodeAt(0)),{name:'ECDH',namedCurve:'P-256'},false,[]);}catch{return reply({error:'invalid_push'},400);}const id=await idFor(b.subscription.endpoint);if(!devices.some(d=>d.id===id)&&devices.length>=5)return reply({error:'push_device_limit'},400);const owner=await readPrivate(SERVICE,'__push_owner__:'+id,env,deps);if(owner&&owner.value.subject!==subject)return reply({error:'push_owned_by_other_account'},409);if(!owner&&!await writePrivate(SERVICE,'__push_owner__:'+id,{subject},0,env,deps))return reply({error:'revision_conflict'},409);const old=devices.find(d=>d.id===id),device={id,subscription:{endpoint:b.subscription.endpoint,keys:{p256dh:b.subscription.keys.p256dh,auth:b.subscription.keys.auth}},createdAt:old?.createdAt||now,last:old?.last?.state==='expired'?null:old?.last||null},next=[...devices.filter(d=>d.id!==id),device];return await writePrivate(subject,PUSH_KEY,{devices:next},row?.revision||0,env,deps)?reply({devices:safe(next),deviceId:id}):reply({error:'revision_conflict'},409);}
 if(path==='/api/cloud/push'&&request.method==='DELETE'){const b=await parseBody(request,1000);if(typeof b.id!=='string'||!devices.some(d=>d.id===b.id)||Object.keys(b).some(k=>k!=='id'))return reply({error:'invalid_push'},400);const next=devices.filter(d=>d.id!==b.id);if(!await writePrivate(subject,PUSH_KEY,{devices:next},row?.revision||0,env,deps))return reply({error:'revision_conflict'},409);await env.CLOUD_DB.prepare('DELETE FROM cloud_records WHERE subject=? AND key=?').bind(SERVICE,'__push_owner__:'+b.id).run();return reply({devices:safe(next)});}
 if(path==='/api/cloud/push/test'&&request.method==='POST'){const b=await parseBody(request,1000);if(typeof b.id!=='string'||!devices.some(d=>d.id===b.id))return reply({error:'push_device_missing'},400);const next=await deliverPush(subject,{id:'test:'+now},env,deps,upstream,now,b.id);return reply({devices:safe(next)});}
 return reply({error:'not_found'},404);
}
export async function deliverPush(subject,event,env,deps,upstream=fetch,now=Date.now(),only=null){
 const row=await readPrivate(subject,PUSH_KEY,env,deps);if(!row?.value.devices?.length)return [];const config=await keys(env,deps),pending=[];
 const selected=new Set(row.value.devices.filter(d=>(!only||d.id===only)&&d.last?.state!=='expired'&&(d.last?.eventId!==event.id||['failed','sending'].includes(d.last.state)&&(d.last.attempts||0)<3&&now-d.last.at>=300000)).map(d=>d.id));
 const reserved=row.value.devices.map(d=>selected.has(d.id)?{...d,last:{state:'sending',status:null,at:now,eventId:event.id,attempts:d.last?.eventId===event.id?(d.last.attempts||0)+1:1,receivedAt:null,openedAt:null}}:d);
 if(!selected.size)return row.value.devices;if(!await writePrivate(subject,PUSH_KEY,{devices:reserved},row.revision,env,deps,now))return row.value.devices;
 for(const d of reserved){if(!selected.has(d.id))continue;if(!only){const monitor=await readPrivate(subject,'__account_monitor_v1',env,deps);if(!monitor?.value.enabled){for(let i=0;i<3;i++){const current=await readPrivate(subject,PUSH_KEY,env,deps);if(!current)break;const devices=current.value.devices.map(x=>selected.has(x.id)&&x.last?.eventId===event.id&&x.last.state==='sending'?{...x,last:{...x.last,state:'cancelled'}}:x);if(await writePrivate(subject,PUSH_KEY,{devices},current.revision,env,deps,now))break;}break;}}
  const live=await readPrivate(subject,PUSH_KEY,env,deps);if(!live?.value.devices.some(x=>x.id===d.id&&x.last?.eventId===event.id))continue;
  const receipt=await deps.seal({subject,id:d.id,eventId:event.id,expires:now+3600000},env.CLOUD_ENCRYPTION_KEY,'push-receipt-v1'),result=await sendPush(d.subscription,{title:'Trading Tools',body:only?'Notificare de test.':'Ai alerte noi în inbox. Deschide aplicația pentru detalii.',url:APP,receipt,receiptUrl:'https://premarket-scanner-html.mferent80.workers.dev/api/cloud/push/receipt'},config,upstream,now);
  for(let i=0;i<3;i++){const current=await readPrivate(subject,PUSH_KEY,env,deps);if(!current?.value.devices.some(x=>x.id===d.id&&x.last?.eventId===event.id))break;const devices=current.value.devices.map(x=>x.id===d.id?{...x,last:{...x.last,...result}}:x);if(await writePrivate(subject,PUSH_KEY,{devices},current.revision,env,deps,now))break;}
 }
 return (await readPrivate(subject,PUSH_KEY,env,deps))?.value.devices||pending;
}
export async function pushReceipt(request,env,deps,parseBody){const b=await parseBody(request,5000);if(!['received','opened'].includes(b.phase)||typeof b.token!=='string')return {body:{error:'invalid_push_receipt'},status:400};let claim;try{claim=await deps.unseal(b.token,env.CLOUD_ENCRYPTION_KEY,'push-receipt-v1');}catch{return {body:{error:'invalid_push_receipt'},status:401};}const now=Date.now();if(!Number.isFinite(claim.expires)||claim.expires<now||claim.expires>now+3600000)return {body:{error:'push_receipt_expired'},status:401};for(let i=0;i<3;i++){const row=await readPrivate(claim.subject,PUSH_KEY,env,deps),device=row?.value.devices.find(d=>d.id===claim.id);if(!device||device.last?.eventId!==claim.eventId)return {body:{ignored:true},status:200};const field=b.phase==='opened'?'openedAt':'receivedAt',devices=row.value.devices.map(d=>d.id===claim.id?{...d,last:{...d.last,[field]:d.last[field]||now}}:d);if(await writePrivate(claim.subject,PUSH_KEY,{devices},row.revision,env,deps))return {body:{confirmed:b.phase},status:200};}return {body:{error:'revision_conflict'},status:409};}
