(function(g){'use strict';
function parts(t,zone){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(t)).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));}
function date(t,zone){const p=parts(t,zone);return p.year+'-'+p.month+'-'+p.day;}
function expected(now,zone,closeMinutes){if(typeof zone!=='string'||!Number.isFinite(closeMinutes)||closeMinutes<0||closeMinutes>=1440)throw Error('Programul bursei nu poate fi verificat.');const id=g.ExchangeCalendar?.infer(zone,closeMinutes);if(id)return g.ExchangeCalendar.latest(now,id).day;const p=parts(now,zone),d=new Date(p.year+'-'+p.month+'-'+p.day+'T12:00:00Z');if(d.getUTCDay()>0&&d.getUTCDay()<6&&Number(p.hour)*60+Number(p.minute)<closeMinutes+15)d.setUTCDate(d.getUTCDate()-1);while(d.getUTCDay()===0||d.getUTCDay()===6)d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10);}
function read(input,symbol,now=Date.now()){
 const meta=input?.meta;if(!Array.isArray(input)||!meta||meta.symbol?.toUpperCase()!==symbol?.toUpperCase())throw Error('Identitatea seriei nu poate fi verificată.');
 const zone=meta.timezone,end=meta.regularEnd;if(!Number.isFinite(end)||Math.abs(end-now)>10*86400000)throw Error('Programul sursei este indisponibil sau vechi.');
 const calendarId=g.ExchangeCalendar?.resolve(meta),market=calendarId?g.ExchangeCalendar.markets[calendarId]:null,p=parts(end,zone),closeMinutes=market?.close??Number(p.hour)*60+Number(p.minute),expectedDate=calendarId?g.ExchangeCalendar.latest(now,calendarId).day:expected(now,zone,closeMinutes),days=new Map();
 for(const b of input){if(![b.t,b.o,b.h,b.l,b.c].every(Number.isFinite)||b.t>now+60000||b.o<=0||b.l<=0||b.c<=0||b.h<Math.max(b.o,b.c)||b.l>Math.min(b.o,b.c))throw Error('Serie zilnică invalidă.');const day=date(b.t,zone);if(calendarId&&g.ExchangeCalendar.session(calendarId,day).state==='closed')continue;if(day<=expectedDate&&(!days.has(day)||days.get(day).t<b.t))days.set(day,b);}
 const bars=[...days.values()].sort((a,b)=>a.t-b.t);if(!bars.length)throw Error('Nicio sesiune încheiată.');const asOf=date(bars[bars.length-1].t,zone);if(asOf!==expectedDate)throw Error('DATE STALE: '+asOf+'; sesiune așteptată '+expectedDate+'. Verifică disponibilitatea sursei și calendarul pieței.');return {bars,asOf,expected:expectedDate,timezone:zone,closeMinutes,calendarId,currency:/^[A-Z]{3}$/.test(meta.currency||'')?meta.currency:meta.currency==='GBp'?'GBX':null,dataQuality:quality(meta,bars,asOf)};
}
function quality(meta,bars,asOf){const id=g.ExchangeCalendar?.resolve(meta),session=id?g.ExchangeCalendar.session(id,asOf):null;return {provider:meta.provider||null,exchange:meta.exchange||null,timezone:meta.timezone||null,session:asOf,interval:meta.interval||null,readAt:Number.isFinite(meta.readAt)?meta.readAt:null,retrievedAt:Number.isFinite(meta.retrievedAt)?meta.retrievedAt:null,quoteAt:Number.isFinite(meta.quoteAt)?meta.quoteAt:null,delayMinutes:Number.isFinite(meta.delayMinutes)?meta.delayMinutes:null,validBars:Number.isSafeInteger(meta.validBars)?meta.validBars:null,inputBars:Number.isSafeInteger(meta.inputBars)?meta.inputBars:null,completedBars:bars.length,calendar:session&&session.state!=='unknown'?'Calendar oficial '+id+' · verificat '+session.reviewedAt+' · '+session.source:'Sesiuni lucrătoare și program provider; calendar oficial neconfirmat',priceBasis:meta.priceBasis||'Ajustări corporate neconfirmate'};}
function qualityMarkup(q){const esc=s=>String(s??'Neverificat').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),stamp=t=>Number.isFinite(t)?new Date(t).toLocaleString('ro-RO'):'Neverificat';return '<details class="data-quality"><summary>Calitatea datelor · '+esc(q?.provider||'sursă neconfirmată')+' · sesiune '+esc(q?.session)+'</summary><dl>'+[['Provider / bursă',(q?.provider||'Neverificat')+' / '+(q?.exchange||'Neverificat')],['Fus orar / interval',(q?.timezone||'Neverificat')+' / '+(q?.interval||'Neverificat')],['Citire / cache',stamp(q?.readAt)+' / '+stamp(q?.retrievedAt)],['Ultima cotație raportată',stamp(q?.quoteAt)],['Întârziere declarată de provider',Number.isFinite(q?.delayMinutes)?q.delayMinutes+' minute':'Neverificată; nu este feed live certificat'],['Bare valide / primite / EOD',q?.validBars!=null&&q?.inputBars!=null?q.validBars+' / '+q.inputBars+' / '+q.completedBars:'Acoperire neconfirmată'],['Calendar',q?.calendar||'Sărbători neconfirmate'],['Prețuri și corporate actions',q?.priceBasis||'Ajustări neconfirmate']].map(([l,v])=>'<dt>'+esc(l)+'</dt><dd>'+esc(v)+'</dd>').join('')+'</dl><p>Date prin releu sau proxy; providerul și timestampurile nu certifică o cotație executabilă la broker.</p></details>';}
function usable(candidate,now=Date.now()){try{return !!candidate&&candidate.sourceDate===expected(now,candidate.sourceTimezone,candidate.sourceCloseMinutes)&&Number.isFinite(candidate.ts)&&candidate.ts<=now+60000;}catch(_){return false;}}
function continuity(days,zone,close){const id=g.ExchangeCalendar?.infer(zone,close);return id?g.ExchangeCalendar.contiguous(days,id):true;}
g.DailySeries={read,date,expected,usable,quality,qualityMarkup,continuity};
})(typeof window!=='undefined'?window:globalThis);
