(function(g){
'use strict';
const VERSION='holdings-mlp-v1',HORIZON=5,FEATURES=['Randament 5','Randament 20','Randament 60','Distanță EMA21','Distanță EMA50','Distanță EMA200','Pantă EMA21','RSI14','ATR / preț','Volum relativ'],CLASSES=['Declin','Mixt','Avans'];
const finite=n=>typeof n==='number'&&Number.isFinite(n),mean=xs=>xs.reduce((a,b)=>a+b,0)/xs.length;
function validateBars(bars,now=Date.now()){
 if(!Array.isArray(bars)||bars.length<510||bars.length>2000)throw Error('Sunt necesare 510–2000 sesiuni OHLC, nu doar observațiile din raport.');
 for(let i=0;i<bars.length;i++){const b=bars[i];if(!b||![b.t,b.o,b.h,b.l,b.c,b.v].every(finite)||b.t>now||b.o<=0||b.l<=0||b.c<=0||b.v<=0||b.h<Math.max(b.o,b.c)||b.l>Math.min(b.o,b.c)||i&&b.t<=bars[i-1].t)throw Error('Istoric invalid, volum lipsă sau ordine temporală neconfirmată.');if(i&&Math.abs(b.c/bars[i-1].c-1)>.25)throw Error('Salt zilnic peste 25%: verifică ajustările și evenimentele înainte de antrenare.');}
}
function ema(values,n){const out=Array(values.length).fill(null);out[n-1]=mean(values.slice(0,n));for(let i=n;i<values.length;i++)out[i]=values[i]*2/(n+1)+out[i-1]*(1-2/(n+1));return out;}
function dataset(bars,now=Date.now()){
 validateBars(bars,now);const c=bars.map(b=>b.c),e21=ema(c,21),e50=ema(c,50),e200=ema(c,200),atr=Array(c.length).fill(null),rsi=Array(c.length).fill(null);let gain=0,loss=0,tr=0;
 for(let i=1;i<c.length;i++){const change=c[i]-c[i-1],up=Math.max(0,change),down=Math.max(0,-change),range=Math.max(bars[i].h-bars[i].l,Math.abs(bars[i].h-c[i-1]),Math.abs(bars[i].l-c[i-1]));if(i<=14){gain+=up/14;loss+=down/14;tr+=range/14;}else{gain=(gain*13+up)/14;loss=(loss*13+down)/14;tr=(tr*13+range)/14;}if(i>=14){atr[i]=tr;rsi[i]=gain===0&&loss===0?50:loss===0?100:100-100/(1+gain/loss);}}
 const features=i=>{const p=c[i],a=atr[i]/p*100,volume=mean(bars.slice(i-20,i).map(b=>b.v));const x=[5,20,60].map(n=>(p/c[i-n]-1)*100).concat([(p/e21[i]-1)*100,(p/e50[i]-1)*100,(p/e200[i]-1)*100,(e21[i]/e21[i-5]-1)*100,rsi[i],a,bars[i].v/volume]);if(!x.every(finite)||a<=0)throw Error('Indicatorii necesari nu pot fi verificați.');return x;};
 const rows=[];for(let i=199;i<bars.length-HORIZON;i++){const x=features(i),move=(c[i+HORIZON]/c[i]-1)*100/x[8];rows.push({t:bars[i].t,end:bars[i+HORIZON].t,x,y:move<=-1?0:move>=1?2:1});}return {rows,latest:features(bars.length-1)};
}
function split(rows){
 if(!Array.isArray(rows)||rows.length<300)throw Error('Minimum 300 exemple etichetate pentru separarea temporală.');
 for(let i=0;i<rows.length;i++){const r=rows[i];if(!r||!finite(r.t)||!finite(r.end)||r.end<=r.t||i&&r.t<=rows[i-1].t||!Array.isArray(r.x)||r.x.length!==10||!r.x.every(finite)||![0,1,2].includes(r.y))throw Error('Exemple de antrenare invalide.');}
 const a=Math.floor(rows.length*.6),b=Math.floor(rows.length*.8),validationStart=rows[a].t,testStart=rows[b].t,parts={train:rows.slice(0,a).filter(r=>r.end<validationStart),validation:rows.slice(a,b).filter(r=>r.end<testStart),test:rows.slice(b)};
 for(const [key,xs] of Object.entries(parts)){const counts=[0,0,0];xs.forEach(r=>counts[r.y]++);if(xs.length<(key==='train'?150:50)||counts.some(n=>n<(key==='train'?10:5)))throw Error('Istoric insuficient sau clase dezechilibrate în '+key+'. Modelul nu este antrenat.');}
 return parts;
}
function scaler(rows){const means=FEATURES.map((_,j)=>mean(rows.map(r=>r.x[j]))),scales=means.map((m,j)=>Math.max(1e-6,Math.sqrt(mean(rows.map(r=>(r.x[j]-m)**2)))));return {means,scales};}
function normalize(x,s){return x.map((n,i)=>(n-s.means[i])/s.scales[i]);}
function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function network(hidden,seed){const random=rng(seed),matrix=(a,b)=>Array.from({length:a},()=>Array.from({length:b},()=>hidden?(random()-.5)*Math.sqrt(6/(a+b)):0));return {hidden,w1:hidden?matrix(10,hidden):null,b1:hidden?Array(hidden).fill(0):null,w2:matrix(hidden||10,3),b2:[0,0,0]};}
function softmax(z){const top=Math.max(...z),xs=z.map(v=>Math.exp(v-top)),sum=xs.reduce((a,b)=>a+b,0);return xs.map(v=>v/sum);}
function forward(net,x){const h=net.hidden?net.b1.map((b,j)=>Math.tanh(b+x.reduce((s,v,i)=>s+v*net.w1[i][j],0))):x;return {h,p:softmax(net.b2.map((b,k)=>b+h.reduce((s,v,j)=>s+v*net.w2[j][k],0)))};}
function metrics(rows,predict){let loss=0,correct=0,brier=0;const confusion=Array.from({length:3},()=>[0,0,0]);for(const r of rows){const p=predict(r.x);if(p.length!==3||!p.every(finite))throw Error('Rezultat numeric invalid.');const label=p.indexOf(Math.max(...p));loss-=Math.log(Math.max(1e-12,p[r.y]));correct+=label===r.y;confusion[r.y][label]++;brier+=p.reduce((s,v,k)=>s+(v-(r.y===k?1:0))**2,0);}return {n:rows.length,loss:loss/rows.length,accuracy:correct/rows.length,balanced:mean(confusion.map((row,k)=>row[k]/row.reduce((a,b)=>a+b,0))),brier:brier/rows.length,confusion};}
function epoch(net,rows){const h=net.hidden||10,dw2=Array.from({length:h},()=>[0,0,0]),db2=[0,0,0],dw1=net.hidden?Array.from({length:10},()=>Array(h).fill(0)):null,db1=net.hidden?Array(h).fill(0):null;
 for(const r of rows){const f=forward(net,r.x),delta=f.p.map((v,k)=>v-(r.y===k?1:0));for(let k=0;k<3;k++){db2[k]+=delta[k];for(let j=0;j<h;j++)dw2[j][k]+=f.h[j]*delta[k];}if(net.hidden)for(let j=0;j<h;j++){const d=(1-f.h[j]*f.h[j])*delta.reduce((s,v,k)=>s+v*net.w2[j][k],0);db1[j]+=d;for(let i=0;i<10;i++)dw1[i][j]+=r.x[i]*d;}}
 const zeros=xs=>xs.map(v=>Array.isArray(v)?zeros(v):0);if(!net._adam)net._adam={step:0,m:{w2:zeros(net.w2),b2:zeros(net.b2),w1:net.w1?zeros(net.w1):null,b1:net.b1?zeros(net.b1):null},v:{w2:zeros(net.w2),b2:zeros(net.b2),w1:net.w1?zeros(net.w1):null,b1:net.b1?zeros(net.b1):null}};const a=net._adam,step=++a.step,n=rows.length,rate=.015;
 function update(values,grad,m,v,penalty){for(let i=0;i<values.length;i++)if(Array.isArray(values[i]))update(values[i],grad[i],m[i],v[i],penalty);else{const d=grad[i]/n+(penalty ? .01*values[i]/n : 0);m[i]=.9*m[i]+.1*d;v[i]=.999*v[i]+.001*d*d;values[i]-=rate*(m[i]/(1-.9**step))/(Math.sqrt(v[i]/(1-.999**step))+1e-8);}}
 update(net.w2,dw2,a.m.w2,a.v.w2,true);update(net.b2,db2,a.m.b2,a.v.b2,false);if(net.hidden){update(net.w1,dw1,a.m.w1,a.v.w1,true);update(net.b1,db1,a.m.b1,a.v.b1,false);}}
function fit(rows,latest,options={}){
 if(!Array.isArray(latest)||latest.length!==10||!latest.every(finite))throw Error('Indicatorii actuali sunt invalizi.');
 const parts=split(rows),scale=scaler(parts.train),scaled=Object.fromEntries(Object.entries(parts).map(([k,xs])=>[k,xs.map(r=>({...r,x:normalize(r.x,scale)}))])),net=network(12,2122026),linear=network(0,1),count=[1,1,1];parts.train.forEach(r=>count[r.y]++);const constant=count.map(n=>n/(parts.train.length+3)),copy=n=>JSON.parse(JSON.stringify({hidden:n.hidden,w1:n.w1,w2:n.w2,b1:n.b1,b2:n.b2}));let best=copy(net),bestLinear=copy(linear),bestLoss=Infinity,bestLinearLoss=Infinity,bestEpoch=0,stale=0,stopped=false;
 const epochs=options.epochs??180;if(!Number.isInteger(epochs)||epochs<20||epochs>240)throw Error('Număr de epoci invalid.');
 for(let i=1;i<=epochs;i++){if(!stopped)epoch(net,scaled.train);epoch(linear,scaled.train);if(i%5===0){const a=metrics(scaled.validation,x=>forward(net,x).p),b=metrics(scaled.validation,x=>forward(linear,x).p);if(!stopped&&a.loss<bestLoss-1e-5){bestLoss=a.loss;best=copy(net);bestEpoch=i;stale=0;}else stale+=5;if(b.loss<bestLinearLoss){bestLinearLoss=b.loss;bestLinear=copy(linear);}options.progress?.({epoch:i,total:epochs,loss:a.loss});if(stale>=35&&i>=60)stopped=true;}}
 const evaluation=metrics(scaled.test,x=>forward(best,x).p),linearTest=metrics(scaled.test,x=>forward(bestLinear,x).p),constantTest=metrics(scaled.test,()=>constant),validation=metrics(scaled.validation,x=>forward(best,x).p),train=metrics(scaled.train,x=>forward(best,x).p),reference=linearTest.loss<constantTest.loss?linearTest:constantTest,advantage=evaluation.loss<Math.min(linearTest.loss,constantTest.loss)-.02&&evaluation.balanced>=Math.max(linearTest.balanced,constantTest.balanced)+.02;
 const normalized=normalize(latest,scale),maxZ=Math.max(...normalized.map(Math.abs)),support=forward(best,normalized).p;
 return {version:VERSION,horizon:HORIZON,network:best,scale,latest:latest.slice(),support,classIndex:support.indexOf(Math.max(...support)),maxZ,advantage,reviewOnly:true,epochs:bestEpoch,report:{train,validation,test:evaluation,linear:linearTest,constant:constantTest,reference:linearTest.loss<constantTest.loss?'linear':'constant',referenceLoss:reference.loss,periods:Object.fromEntries(Object.entries(parts).map(([k,xs])=>[k,{from:xs[0].t,to:xs[xs.length-1].t,lastLabel:xs[xs.length-1].end,n:xs.length}]))}};
}
function valid(result){
 try{const n=result.network,s=result.scale,r=result.report;
  if(result.version!==VERSION||result.horizon!==HORIZON||result.reviewOnly!==true||n.hidden!==12||n.w1.length!==10||n.w1.some(a=>a.length!==12||!a.every(finite))||n.w2.length!==12||n.w2.some(a=>a.length!==3||!a.every(finite))||n.b1.length!==12||n.b2.length!==3||![...n.b1,...n.b2,...s.means,...s.scales,...result.support,...result.latest].every(finite)||s.means.length!==10||s.scales.length!==10||s.scales.some(v=>v<=0)||result.latest.length!==10||result.support.length!==3||result.support.some(v=>v<0||v>1)||Math.abs(result.support.reduce((a,b)=>a+b,0)-1)>1e-6||!finite(result.maxZ)||typeof result.advantage!=='boolean'||![0,1,2].includes(result.classIndex)||!Number.isInteger(result.epochs)||result.epochs<5||result.epochs>240)return false;
  for(const key of ['train','validation','test','linear','constant']){const m=r[key];if(!Number.isInteger(m.n)||m.n<(key==='train'?150:50)||![m.loss,m.accuracy,m.balanced,m.brier].every(finite)||m.loss<0||m.brier<0||m.brier>2||m.accuracy<0||m.accuracy>1||m.balanced<0||m.balanced>1||m.confusion.length!==3||m.confusion.some(row=>row.length!==3||row.some(v=>!Number.isInteger(v)||v<0)||row.reduce((a,b)=>a+b,0)<5))return false;const matrix=m.confusion,total=matrix.flat().reduce((a,b)=>a+b,0),accuracy=matrix.reduce((sum,row,k)=>sum+row[k],0)/total,balanced=mean(matrix.map((row,k)=>row[k]/row.reduce((a,b)=>a+b,0)));if(total!==m.n||Math.abs(accuracy-m.accuracy)>1e-7||Math.abs(balanced-m.balanced)>1e-7)return false;}
  for(const key of ['train','validation','test']){const p=r.periods[key];if(![p.from,p.to,p.lastLabel].every(finite)||p.from>p.to||p.to>=p.lastLabel||p.n!==r[key].n)return false;}
  if(r.linear.n!==r.test.n||r.constant.n!==r.test.n||!(r.periods.train.lastLabel<r.periods.validation.from&&r.periods.validation.lastLabel<r.periods.test.from))return false;
  const z=normalize(result.latest,s),support=forward(n,z).p;if(support.some((v,k)=>Math.abs(v-result.support[k])>1e-7)||Math.abs(Math.max(...z.map(Math.abs))-result.maxZ)>1e-7||result.classIndex!==support.indexOf(Math.max(...support)))return false;
  return result.advantage===(r.test.loss<Math.min(r.linear.loss,r.constant.loss)-.02&&r.test.balanced>=Math.max(r.linear.balanced,r.constant.balanced)+.02);
 }catch{return false;}
}
function assess(record,{symbol,currency,asOf,demo,now=Date.now()}){if(!record)return {state:'missing',message:'Model neantrenat pentru acest instrument.'};if(record.symbol!==symbol||record.currency!==currency||record.kind!==(demo?'synthetic':'market')||!valid(record.result))return {state:'invalid',message:'Model incompatibil sau ilizibil; nu este utilizat.'};if(!finite(record.trainedAt)||record.trainedAt>now+60000||now-record.trainedAt>30*60000||!asOf||record.asOf!==asOf)return {state:'stale',message:'Model expirat sau analiză EOD lipsă. Reantrenează pe sesiunea verificată.'};if(record.result.maxZ>6)return {state:'drift',message:'Indicatorii actuali ies din domeniul antrenării. Interpretarea este blocată.'};return record.result.advantage?{state:'research',message:'Avantaj în acest test; necesită verificări în alte perioade.'}:{state:'no-edge',message:'Fără avantaj demonstrat față de modelele simple.'};}
function demoBars(seed=0,now=Date.now()){
 const end=new Date(now);end.setUTCHours(14,30,0,0);if(end.getTime()>now)end.setUTCDate(end.getUTCDate()-1);const days=[];for(let d=new Date(end);days.length<1100;d.setUTCDate(d.getUTCDate()-1))if(d.getUTCDay()>0&&d.getUTCDay()<6)days.unshift(d.getTime());let price=100;return days.map((t,i)=>{price*=Math.exp(.004*Math.sin((i+seed*17)/17)+.0015*Math.sin(i/3));return {t,o:price*.999,h:price*1.008,l:price*.992,c:price,v:1000000*(1.3+.25*Math.sin(i/9))};});
}
g.HoldingsNeural={VERSION,HORIZON,FEATURES,CLASSES,dataset,split,scaler,normalize,network,forward,fit,valid,assess,demoBars};
})(typeof window!=='undefined'?window:globalThis);
