(function(g){
'use strict';
const VERSION='holdings-hmm-v1',CONFIG=Object.freeze({states:3,features:3,maxIterations:80,initializations:3,varianceFloor:.05,transitionPrior:.1,persistencePrior:2,minimumTrain:180,confirmation:3,concentration:.65,maxZ:6,advantage:.02,gapDays:7}),FEATURES=['Randament 5 sesiuni','Distanță EMA21','ATR / preț'],DAY=86400000;
const finite=Number.isFinite,copy=x=>JSON.parse(JSON.stringify(x)),sum=a=>a.reduce((s,x)=>s+x,0),mean=a=>sum(a)/a.length,argmax=a=>a.indexOf(Math.max(...a)),close=(a,b)=>finite(a)&&finite(b)&&Math.abs(a-b)<1e-7;
const vector=(a,n=3)=>Array.isArray(a)&&a.length===n&&a.every(finite),prob=a=>vector(a)&&a.every(x=>x>=0&&x<=1)&&close(sum(a),1);
function logsum(xs){const m=Math.max(...xs);return m+Math.log(sum(xs.map(x=>Math.exp(x-m))));}
const logsToProb=xs=>{const z=logsum(xs);return xs.map(x=>Math.exp(x-z));};
function checkRows(rows,minimum=1){if(!Array.isArray(rows)||rows.length<minimum||rows.some((r,i)=>!finite(r.t)||!vector(r.x)||i&&r.t<=rows[i-1].t))throw Error('Observații HMM invalide sau insuficiente.');}
function dataset(bars,now=Date.now()){return g.HoldingsNeural.dataset(bars,now).observations.map(r=>({t:r.t,x:[r.x[0],r.x[3],r.x[8]]}));}
function scale(rows){const means=[0,1,2].map(j=>mean(rows.map(r=>r.x[j]))),scales=means.map((m,j)=>Math.max(1e-4,Math.sqrt(mean(rows.map(r=>(r.x[j]-m)**2)))));return {means,scales};}
const normalize=(x,s)=>x.map((v,j)=>(v-s.means[j])/s.scales[j]);
const scaled=(rows,s)=>rows.map(r=>({t:r.t,x:normalize(r.x,s)}));
function emission(model,x){return model.means.map((mu,k)=>-.5*sum(x.map((v,j)=>Math.log(2*Math.PI*model.variances[k][j])+(v-mu[j])**2/model.variances[k][j])));}
function advance(model,x,previous=null){const e=emission(model,x),prior=previous?model.initial.map((_,j)=>sum(previous.map((p,k)=>p*model.transitions[k][j]))):model.initial,p=prior.map((v,k)=>Math.log(Math.max(1e-300,v))+e[k]),density=logsum(p);return {p:logsToProb(p),density};}
function filter(model,rows,anchor=null){let previous=anchor?.p||null,time=anchor?.t??null,total=0;const steps=[];for(const r of rows){const reset=time!==null&&r.t-time>CONFIG.gapDays*DAY;if(reset)previous=null;const s=advance(model,r.x,previous),switching=sum(s.p.map((p,k)=>p*(1-model.transitions[k][k])));steps.push({t:r.t,x:r.x.slice(),p:s.p,density:s.density,reset,switching});total+=s.density;previous=s.p;time=r.t;}return {steps,p:previous,nll:-total/rows.length};}
function expectation(model,rows){
 const e=rows.map(r=>emission(model,r.x)),alpha=[],beta=Array(rows.length),constants=[],resets=rows.map((r,i)=>i===0||r.t-rows[i-1].t>CONFIG.gapDays*DAY),logA=model.transitions.map(a=>a.map(x=>Math.log(x))),logPi=model.initial.map(Math.log);
 for(let t=0;t<rows.length;t++){const a=e[t].map((v,j)=>v+(resets[t]?logPi[j]:logsum(alpha[t-1].map((p,k)=>p+logA[k][j]))));constants[t]=logsum(a);alpha[t]=a.map(x=>x-constants[t]);}
 beta[rows.length-1]=[0,0,0];for(let t=rows.length-2;t>=0;t--)beta[t]=resets[t+1]?[0,0,0]:[0,1,2].map(k=>logsum([0,1,2].map(j=>logA[k][j]+e[t+1][j]+beta[t+1][j]))-constants[t+1]);
 const gamma=alpha.map((a,t)=>logsToProb(a.map((x,k)=>x+beta[t][k]))),transitions=Array.from({length:3},()=>[0,0,0]);
 for(let t=0;t<rows.length-1;t++){if(resets[t+1])continue;const xi=[0,1,2].flatMap(k=>[0,1,2].map(j=>alpha[t][k]+logA[k][j]+e[t+1][j]+beta[t+1][j])),z=logsum(xi);for(let k=0;k<3;k++)for(let j=0;j<3;j++)transitions[k][j]+=Math.exp(xi[k*3+j]-z);}
 return {gamma,transitions,nll:-sum(constants)/rows.length};
}
function initialize(rows,initialization){const sorted=rows.slice().sort((a,b)=>a.x[0]-b.x[0]||a.t-b.t),fractions=[[.15,.5,.85],[.25,.55,.8],[.1,.4,.9]][initialization];return {initial:[1/3,1/3,1/3],transitions:[0,1,2].map(k=>[0,1,2].map(j=>k===j?.9:.05)),means:fractions.map(f=>sorted[Math.floor(f*(rows.length-1))].x.slice()),variances:Array.from({length:3},()=>[1,1,1])};}
function update(model,rows){const e=expectation(model,rows),counts=[0,1,2].map(k=>sum(e.gamma.map(a=>a[k]))),means=counts.map((n,k)=>[0,1,2].map(j=>sum(rows.map((r,t)=>e.gamma[t][k]*r.x[j]))/Math.max(n,1e-12))),variances=counts.map((n,k)=>[0,1,2].map(j=>Math.max(CONFIG.varianceFloor,sum(rows.map((r,t)=>e.gamma[t][k]*(r.x[j]-means[k][j])**2))/Math.max(n,1e-12)))),transitions=e.transitions.map((a,k)=>{const b=a.map((v,j)=>v+CONFIG.transitionPrior+(k===j?CONFIG.persistencePrior:0));return b.map(v=>v/sum(b));});return {initial:model.initial.slice(),transitions,means,variances};}
function canonical(model){const order=[0,1,2].sort((a,b)=>model.means[a][1]-model.means[b][1]||model.means[a][0]-model.means[b][0]);return {initial:order.map(k=>model.initial[k]),transitions:order.map(k=>order.map(j=>model.transitions[k][j])),means:order.map(k=>model.means[k]),variances:order.map(k=>model.variances[k])};}
function period(rows){return {from:rows[0].t,to:rows.at(-1).t,n:rows.length};}
function label(raw){return raw[0]>.05&&raw[1]>.5?'Ascendent':raw[0]<-.05&&raw[1]<-.5?'Deteriorare':'Consolidare / tranziție';}
function profiles(model,s,counts){return model.means.map((mu,k)=>{const raw=mu.map((x,j)=>x*s.scales[j]+s.means[j]);return {state:k,means:raw,label:label(raw),effective:counts[k],volatility:raw[2]>s.means[2]*1.25?'Ridicată':'Obișnuită',persistence:1/(1-model.transitions[k][k])};});}
function quality(model,counts,trainN){const distances=[[0,1],[0,2],[1,2]].map(([a,b])=>Math.sqrt(mean(model.means[a].map((v,j)=>(v-model.means[b][j])**2)))),separation=Math.min(...distances),represented=counts.every(n=>n>=Math.max(20,trainN*.05));return {represented,separation,informative:represented&&separation>=.5};}
function summarize(steps,initialStable=null){let stable=initialStable,run=null,streak=0;return steps.map(s=>{const state=argmax(s.p),concentrated=s.p[state]>=CONFIG.concentration;if(s.reset){stable=null;run=null;streak=0;}if(!concentrated){run=null;streak=0;}else{streak=run===state?streak+1:1;run=state;}const from=stable;let changed=false;if(streak>=CONFIG.confirmation&&stable!==state){stable=state;changed=from!==null;}return {...s,state,stable,streak,pending:stable!==state||!concentrated,changed,from:changed?from:null};});}
function assess(r){if(!valid(r))return {state:'invalid',message:'Rezultatul HMM nu poate fi verificat.'};if(r.maxZ>CONFIG.maxZ)return {state:'drift',message:'Regim neconcludent · indicatori în afara domeniului de antrenare.'};if(!r.quality.informative)return {state:'weak',message:'Regim neconcludent · stări slab separate sau insuficient reprezentate.'};if(r.current.pending||r.current.streak<CONFIG.confirmation)return {state:'transition',message:'Regim în tranziție · așteaptă trei observații concentrate pentru aceeași stare.'};return {state:'descriptive',message:'Regim estimat stabil în model · nu este un semnal de tranzacționare.'};}
function fitPartitions(parts,options={}){
 for(const k of ['train','validation','test'])checkRows(parts[k],k==='train'?CONFIG.minimumTrain:50);if(parts.train.at(-1).t>=parts.validation[0].t||parts.validation.at(-1).t>=parts.test[0].t)throw Error('Seturile HMM nu sunt separate temporal.');
 const s=scale(parts.train),train=scaled(parts.train,s),validation=scaled(parts.validation,s),test=scaled(parts.test,s);let best=null,loss=Infinity;
 for(let initialization=0;initialization<CONFIG.initializations;initialization++){let model=initialize(train,initialization),stale=0,seedBest=Infinity;for(let iteration=1;iteration<=CONFIG.maxIterations;iteration++){model=update(model,train);if(iteration%5)continue;const last=filter(model,train),score=filter(model,validation,{p:last.p,t:train.at(-1).t}).nll;if(score<loss-1e-5){loss=score;best={model:copy(model),iteration,initialization};}if(score<seedBest-1e-5){seedBest=score;stale=0;}else stale+=5;options.progress?.({algorithm:'hmm',epoch:iteration,total:CONFIG.maxIterations,member:initialization+1,members:CONFIG.initializations,loss:score});if(stale>=20&&iteration>=30)break;}}
 const model=canonical(best.model),expect=expectation(model,train),counts=[0,1,2].map(k=>sum(expect.gamma.map(a=>a[k]))),weights=counts.map(x=>x/train.length),single={initial:[1/3,1/3,1/3],transitions:Array.from({length:3},()=>[1/3,1/3,1/3]),means:Array.from({length:3},()=>[0,0,0]),variances:Array.from({length:3},()=>[0,1,2].map(j=>Math.max(CONFIG.varianceFloor,mean(train.map(r=>r.x[j]**2)))))};
 const all=[...train,...validation,...test],filtered=filter(model,all),start=train.length+validation.length,testSteps=filtered.steps.slice(start),metric={n:test.length,hmm:-mean(testSteps.map(x=>x.density)),independent:-mean(test.map(r=>logsum(emission(model,r.x).map((v,k)=>Math.log(Math.max(1e-300,weights[k]))+v)))),gaussian:filter(single,test).nll};
 const fullTimeline=summarize(testSteps),history=parts.test,anchor={t:filtered.steps[start-1].t,p:filtered.steps[start-1].p,stable:null,run:null,streak:0},baseline={weights,variances:single.variances[0]};
 const result={version:VERSION,config:{...CONFIG},reviewOnly:true,model,baseline,scale:s,selection:{iteration:best.iteration,initialization:best.initialization,validation:period(parts.validation)},profiles:profiles(model,s,counts),quality:quality(model,counts,train.length),latest:parts.test.at(-1).x.slice(),maxZ:Math.max(...test.at(-1).x.map(Math.abs)),history:history.map(r=>({t:r.t,x:r.x.slice()})),anchor,timeline:fullTimeline.slice(-90),current:fullTimeline.at(-1),report:{periods:Object.fromEntries(Object.entries(parts).map(([k,rows])=>[k,period(rows)])),test:metric,advantage:metric.hmm<Math.min(metric.independent,metric.gaussian)-CONFIG.advantage}};
 return result;
}
function split(rows){checkRows(rows,300);const a=Math.floor(rows.length*.6),b=Math.floor(rows.length*.8);return {train:rows.slice(0,a),validation:rows.slice(a,b),test:rows.slice(b)};}
function aggregate(folds){const good=folds.filter(f=>f.status==='evaluated'),n=sum(good.map(f=>f.test.n));return {n,hmm:sum(good.map(f=>f.test.n*f.test.hmm))/n,independent:sum(good.map(f=>f.test.n*f.test.independent))/n,gaussian:sum(good.map(f=>f.test.n*f.test.gaussian))/n,wins:good.filter(f=>f.advantage).length};}
function evaluate(rows,options={}){
 checkRows(rows,300);if(rows.length<600){const r=fitPartitions(split(rows),options);r.walk={status:'insufficient',folds:[],summary:null,consistent:false};return r;}
 const ends=[Math.floor(rows.length*.64),Math.floor(rows.length*.8),rows.length],starts=ends.map(n=>Math.floor(n*.8)),folds=[];let final;
 ends.forEach((end,i)=>{const parts=split(rows.slice(0,end));if(i<2)parts.test=parts.test.filter(r=>r.t<rows[starts[i+1]].t);try{const r=fitPartitions(parts,{...options,progress:p=>options.progress?.({...p,stage:i+1,stages:3})});if(!valid(r))throw Error('Raport HMM neverificabil.');folds.push({id:i+1,status:'evaluated',periods:r.report.periods,test:r.report.test,advantage:r.report.advantage});if(i===2)final=r;}catch(error){if(i===2)throw error;folds.push({id:i+1,status:'blocked',periods:Object.fromEntries(Object.entries(parts).map(([k,rs])=>[k,period(rs)])),error:error.message,advantage:false});}});
 const summary=aggregate(folds);final.walk={status:folds.every(f=>f.status==='evaluated')?'complete':'incomplete',folds,summary,consistent:folds.every(f=>f.status==='evaluated')&&summary.wins===3&&summary.hmm<Math.min(summary.independent,summary.gaussian)-CONFIG.advantage};if(!valid(final))throw Error('Evaluarea HMM nu poate fi verificată.');return final;
}
function validPeriod(p,min){return p&&finite(p.from)&&finite(p.to)&&p.from<p.to&&Number.isInteger(p.n)&&p.n>=min;}
function validMetric(m,n){return m&&Number.isInteger(m.n)&&m.n===n&&['hmm','independent','gaussian'].every(k=>finite(m[k]));}
function equal(a,b){if(typeof a==='number'||typeof b==='number')return close(a,b);if(a===null||b===null||typeof a!=='object'||typeof b!=='object')return a===b;const keys=Object.keys(a);return keys.length===Object.keys(b).length&&keys.every(k=>Object.hasOwn(b,k)&&equal(a[k],b[k]));}
function validReport(report){const p=report?.periods;return p&&['train','validation','test'].every(k=>validPeriod(p[k],k==='train'?CONFIG.minimumTrain:50))&&p.train.to<p.validation.from&&p.validation.to<p.test.from&&validMetric(report.test,p.test.n)&&report.advantage===(report.test.hmm<Math.min(report.test.independent,report.test.gaussian)-CONFIG.advantage);}
function validWalk(w,report){if(w===undefined)return true;if(w.status==='insufficient')return w.folds?.length===0&&w.summary===null&&!w.consistent;if(!['complete','incomplete'].includes(w.status)||w.folds?.length!==3)return false;let previous=-Infinity;for(let i=0;i<3;i++){const f=w.folds[i];if(f.id!==i+1||!['evaluated','blocked'].includes(f.status)||!['train','validation','test'].every(k=>validPeriod(f.periods[k],k==='train'?CONFIG.minimumTrain:50))||f.periods.train.to>=f.periods.validation.from||f.periods.validation.to>=f.periods.test.from||f.periods.test.from<=previous)return false;previous=f.periods.test.to;if(f.status==='evaluated'){if(!validMetric(f.test,f.periods.test.n)||f.advantage!==(f.test.hmm<Math.min(f.test.independent,f.test.gaussian)-CONFIG.advantage))return false;}else if(!f.error||f.advantage!==false)return false;}const s=aggregate(w.folds),complete=w.folds.every(f=>f.status==='evaluated');return equal(s,w.summary)&&w.status===(complete?'complete':'incomplete')&&w.consistent===(complete&&s.wins===3&&s.hmm<Math.min(s.independent,s.gaussian)-CONFIG.advantage)&&equal(w.folds.at(-1).periods,report.periods)&&equal(w.folds.at(-1).test,report.test);}
function replay(r){const steps=filter(r.model,scaled(r.history,r.scale),r.anchor);let stable=r.anchor.stable,run=r.anchor.run,streak=r.anchor.streak;return steps.steps.map(s=>{const state=argmax(s.p),concentrated=s.p[state]>=CONFIG.concentration;if(s.reset){stable=null;run=null;streak=0;}if(!concentrated){run=null;streak=0;}else{streak=run===state?streak+1:1;run=state;}const from=stable;let changed=false;if(streak>=CONFIG.confirmation&&stable!==state){stable=state;changed=from!==null;}return {...s,state,stable,streak,pending:stable!==state||!concentrated,changed,from:changed?from:null};});}
function valid(r){try{
 if(r.version!==VERSION||!equal(r.config,CONFIG)||r.reviewOnly!==true||!prob(r.model.initial)||r.model.initial.some(p=>!close(p,1/3))||r.model.transitions.length!==3||r.model.transitions.some(a=>!prob(a)||a.some(x=>x<=0))||r.model.means.length!==3||r.model.means.some(a=>!vector(a))||r.model.variances.length!==3||r.model.variances.some(a=>!vector(a)||a.some(x=>x<CONFIG.varianceFloor))||!vector(r.scale.means)||!vector(r.scale.scales)||r.scale.scales.some(x=>x<1e-4)||!validReport(r.report)||!validWalk(r.walk,r.report)||!Number.isInteger(r.selection.iteration)||r.selection.iteration<5||r.selection.iteration>80||r.selection.iteration%5||![0,1,2].includes(r.selection.initialization)||!equal(r.selection.validation,r.report.periods.validation)||!vector(r.latest))return false;
 if(!Array.isArray(r.profiles)||r.profiles.length!==3||r.profiles.some((p,k)=>p.state!==k||!finite(p.effective)||p.effective<0)||!close(sum(r.profiles.map(p=>p.effective)),r.report.periods.train.n)||!equal(r.profiles,profiles(r.model,r.scale,r.profiles.map(p=>p.effective)))||!equal(r.quality,quality(r.model,r.profiles.map(p=>p.effective),r.report.periods.train.n)))return false;
 checkRows(r.history);if(r.history.length!==r.report.periods.test.n||r.history[0].t!==r.report.periods.test.from||r.history.at(-1).t!==r.report.periods.test.to||!equal(r.latest,r.history.at(-1).x)||!prob(r.anchor.p)||r.anchor.t!==r.report.periods.validation.to||![null,0,1,2].includes(r.anchor.stable)||![null,0,1,2].includes(r.anchor.run)||!Number.isInteger(r.anchor.streak)||r.anchor.streak!==0||r.anchor.stable!==null||r.anchor.run!==null)return false;
 const timeline=replay(r),rows=scaled(r.history,r.scale);if(!prob(r.baseline.weights)||!vector(r.baseline.variances)||r.baseline.variances.some(v=>v<CONFIG.varianceFloor)||r.baseline.weights.some((w,k)=>!close(w,r.profiles[k].effective/r.report.periods.train.n)))return false;
 const metrics={hmm:-mean(timeline.map(x=>x.density)),independent:-mean(rows.map(x=>logsum(emission(r.model,x.x).map((v,k)=>Math.log(Math.max(1e-300,r.baseline.weights[k]))+v)))),gaussian:-mean(rows.map(x=>-.5*sum(x.x.map((v,j)=>Math.log(2*Math.PI*r.baseline.variances[j])+v*v/r.baseline.variances[j]))))};
 return ['hmm','independent','gaussian'].every(k=>close(metrics[k],r.report.test[k]))&&equal(timeline.slice(-90),r.timeline)&&equal(timeline.at(-1),r.current)&&close(Math.max(...normalize(r.latest,r.scale).map(Math.abs)),r.maxZ);
 }catch{return false;}}
function publicReport(r){if(!valid(r))throw Error('HMM invalid');return {version:r.version,config:r.config,reviewOnly:true,selection:r.selection,profiles:r.profiles,quality:r.quality,report:r.report,walk:r.walk};}
function validPublic(r){try{return r.version===VERSION&&equal(r.config,CONFIG)&&r.reviewOnly===true&&validReport(r.report)&&validWalk(r.walk,r.report)&&equal(r.selection.validation,r.report.periods.validation)&&Number.isInteger(r.selection.iteration)&&r.selection.iteration>=5&&r.selection.iteration<=80&&r.selection.iteration%5===0&&[0,1,2].includes(r.selection.initialization)&&r.quality&&typeof r.quality.represented==='boolean'&&finite(r.quality.separation)&&r.quality.separation>=0&&r.quality.represented===r.profiles.every(p=>p.effective>=Math.max(20,r.report.periods.train.n*.05))&&r.quality.informative===(r.quality.represented&&r.quality.separation>=.5)&&r.profiles.length===3&&r.profiles.every((p,k)=>p.state===k&&vector(p.means)&&finite(p.effective)&&p.effective>=0&&p.label===label(p.means)&&finite(p.persistence)&&p.persistence>=1)&&close(sum(r.profiles.map(p=>p.effective)),r.report.periods.train.n);}catch{return false;}}
g.HoldingsHMM={VERSION,CONFIG,FEATURES,dataset,scale,normalize,emission,advance,filter,expectation,initialize,update,split,fitPartitions,evaluate,valid,assess,publicReport,validPublic};
})(typeof window!=='undefined'?window:globalThis);
