(function(g){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function markup(m){return `<section class="interactive-chart" data-chart="${esc(JSON.stringify({bars:m.bars,timezone:m.timezone,ema21:m.ema21Line,ema50:m.ema50Line,support:m.support,resistance:m.resistance}))}"><div class="chart-toolbar"><b>Istoric EOD</b>${[20,60,90].map(n=>`<button data-window="${n}">${n} sesiuni</button>`).join('')}</div><div class="chart-plot"></div><label>Explorează sesiunea<input class="chart-cursor" type="range" min="0" step="1" aria-label="Sesiune pe grafic"></label><p class="chart-readout" aria-live="polite"></p><p class="meta">Glisează pe grafic sau folosește selectorul. Verde: închidere · albastru: EMA21 · portocaliu: EMA50 · niveluri punctate: suport / rezistență curente.</p></section>`;}
function bind(){for(const host of document.querySelectorAll('[data-chart]')){if(host.dataset.bound)continue;host.dataset.bound='1';let data;try{data=JSON.parse(host.dataset.chart);}catch(_){continue;}const all=data.bars,n=all.length;if(!n)continue;let count=Math.min(60,n),start=n-count,cursor=count-1;const plot=host.querySelector('.chart-plot'),slider=host.querySelector('.chart-cursor'),readout=host.querySelector('.chart-readout'),fmt=x=>Number.isFinite(x)?x.toLocaleString('ro-RO',{maximumFractionDigits:2}):'—';
 const date=b=>data.timezone&&g.DailySeries?g.DailySeries.date(b.t,data.timezone):new Date(b.t).toISOString().slice(0,10),line=(arr,offset)=>Array.from({length:n},(_,i)=>arr[i+offset]??null).slice(start,start+count);
 function draw(){const bars=all.slice(start,start+count),close=bars.map(b=>b.c),a21=line(data.ema21,data.ema21.length-n),a50=line(data.ema50,data.ema50.length-n),values=[...close,...a21,...a50,data.support,data.resistance].filter(Number.isFinite),lo=Math.min(...values),hi=Math.max(...values),span=hi-lo||1,x=i=>42+i/Math.max(1,count-1)*478,y=v=>158-(v-lo)/span*135,path=arr=>{let pen=false;return arr.map((v,i)=>{if(!Number.isFinite(v)){pen=false;return '';}const segment=`${pen?'L':'M'}${x(i)},${y(v)}`;pen=true;return segment;}).join(' ')};cursor=Math.max(0,Math.min(count-1,cursor));const b=bars[cursor];plot.innerHTML=`<svg viewBox="0 0 540 195" class="chart" role="img" aria-label="Grafic închideri ${date(bars[0])} până la ${date(bars.at(-1))}"><text x="2" y="20" fill="currentColor" font-size="12">${esc(fmt(hi))}</text><text x="2" y="160" fill="currentColor" font-size="12">${esc(fmt(lo))}</text>${[data.support,data.resistance].filter(Number.isFinite).map(v=>`<path d="M42 ${y(v)}H520" stroke="currentColor" opacity=".35" stroke-dasharray="4 4"/>`).join('')}<path d="${path(a50)}" fill="none" stroke="var(--amber)" stroke-width="1.7"/><path d="${path(a21)}" fill="none" stroke="var(--blue)" stroke-width="1.7"/><path d="${path(close)}" fill="none" stroke="var(--green)" stroke-width="2.5"/><path d="M${x(cursor)} 20V160" stroke="currentColor" opacity=".5"/><circle cx="${x(cursor)}" cy="${y(b.c)}" r="4" fill="var(--green)"/><text x="42" y="185" fill="currentColor" font-size="12">${date(bars[0])}</text><text x="520" y="185" text-anchor="end" fill="currentColor" font-size="12">${date(bars.at(-1))}</text></svg>`;slider.max=count-1;slider.value=cursor;readout.textContent=date(b)+' · închidere '+fmt(b.c)+' · EMA21 '+fmt(a21[cursor])+' · EMA50 '+fmt(a50[cursor])+' · volum '+fmt(b.v);for(const btn of host.querySelectorAll('[data-window]'))btn.setAttribute('aria-pressed',String(count===Math.min(Number(btn.dataset.window),n)));}
 slider.oninput=()=>{cursor=Number(slider.value);draw();};for(const btn of host.querySelectorAll('[data-window]'))btn.onclick=()=>{count=Math.min(Number(btn.dataset.window),n);start=n-count;cursor=count-1;draw();};
 const point=e=>{const r=plot.getBoundingClientRect();cursor=Math.round(Math.max(0,Math.min(1,((e.clientX-r.left)/r.width*540-42)/478))*(count-1));draw();};plot.onpointerdown=e=>{plot.setPointerCapture(e.pointerId);point(e);};plot.onpointermove=e=>{if(e.buttons)point(e);};draw();}}
g.HoldingsChart={markup,bind};
})(typeof window!=='undefined'?window:globalThis);
