(function(g){'use strict';
const finite=Number.isFinite,LABELS={up:'Trend ascendent',recovery:'Recuperare',base:'Bază posibilă',range:'Consolidare / tranziție',down:'Deteriorare'},DAY=86400000;
function relative(stock,benchmark,now=Date.now()){
 const empty={rs20:null,rs60:null,stock20:null,stock60:null,benchmark20:null,benchmark60:null,asOf:stock?.asOf||null,reason:'Benchmark indisponibil / nealiniat'};
 if(!stock?.bars?.length||!benchmark)return empty;
 try{const b=benchmark.meta?g.DailySeries.read(benchmark,benchmark.meta.symbol,now):{bars:g.HoldingsAnalysis.completed(benchmark,now),timezone:'America/New_York'};if(!b.bars.length)return empty;const key=(x,z)=>g.DailySeries.date(x.t,z||'America/New_York'),left=stock.bars.map(x=>({...x,day:key(x,stock.timezone)})),right=b.bars.map(x=>({...x,day:key(x,b.timezone)}));if(left.at(-1).day!==right.at(-1).day)return empty;const result={...empty,reason:null,benchmarkCurrency:b.currency||benchmark.meta?.currency||null};for(const n of [20,60]){const a=left.slice(-n-1),c=right.slice(-n-1);if(a.length!==n+1||c.length!==n+1||a.some((x,i)=>x.day!==c[i].day||!(x.c>0)||!(c[i].c>0)))continue;const sr=(a.at(-1).c/a[0].c-1)*100,br=(c.at(-1).c/c[0].c-1)*100;result['stock'+n]=sr;result['benchmark'+n]=br;result['rs'+n]=sr-br;}if(result.rs20===null&&result.rs60===null)result.reason='Ferestrele de 20 / 60 observații nu au aceleași date EOD';return result;}catch{return empty;}
}
function candidate(x){if(![x.price,x.ema21,x.ema50,x.slope21,x.slope50].every(finite))return null;if(x.price<x.ema50&&x.ema21<x.ema50&&x.price<x.ema21)return 'down';if(x.price>x.ema50&&x.ema21>x.ema50&&x.slope50>0)return 'up';if(x.price>x.ema21&&x.slope21>0&&x.price<x.ema50)return 'recovery';if(x.price<x.ema50&&x.drawdown<=-15&&Math.abs(x.slope21/x.ema21)*100<=0.3&&x.rsi>=40&&x.rsi<=55)return 'base';return 'range';}
function stabilize(rows){let run=null,count=0,confirmed=null,since=null;return rows.map((x,i)=>{const gap=i&&x.t-rows[i-1].t>7*DAY;if(!x.candidate||gap){run=null;count=0;if(gap){confirmed=null;since=null;}}if(x.candidate){if(run===x.candidate)count++;else{run=x.candidate;count=1;}}let changed=false,from=null;if(count>=3&&confirmed!==run){from=confirmed;confirmed=run;since=x.asOf;changed=!!from;}return {...x,confirmed,since,streak:count,pending:x.candidate!==confirmed,changed,from};});}
function analyze(bars,timezone='America/New_York',market={}){
 if(!Array.isArray(bars)||bars.length<60)return null;const c=bars.map(x=>x.c),high=bars.map(x=>x.h),low=bars.map(x=>x.l),ema21=Array(20).fill(null).concat(g.TI.calcEMA(c,21)),ema50=Array(49).fill(null).concat(g.TI.calcEMA(c,50)),rows=[];
 for(let i=59;i<bars.length;i++){const x={t:bars[i].t,asOf:g.DailySeries.date(bars[i].t,timezone),price:c[i],ema21:ema21[i],ema50:ema50[i],slope21:ema21[i]-ema21[i-5],slope50:ema50[i]-ema50[i-5],rsi:g.TI.calcRSI(c.slice(0,i+1),14),drawdown:(c[i]/Math.max(...high.slice(Math.max(0,i-251),i+1))-1)*100};rows.push({...x,candidate:candidate(x)});}
 const timeline=stabilize(rows).slice(-90),last=timeline.at(-1),prior=timeline.at(-2),n=c.length-1,warnings=[];
 if(c[n]<ema21[n])warnings.push({key:'ema21',text:'Închiderea este sub EMA21',early:true});
 if(high.length>=10&&Math.max(...high.slice(-5))<Math.max(...high.slice(-10,-5)))warnings.push({key:'highs',text:'Maximul ultimelor 5 observații este sub maximul celor 5 precedente',early:true});
 const vols=bars.slice(-21,-1).map(x=>x.v),mean=vols.length===20&&vols.every(v=>finite(v)&&v>0)?vols.reduce((a,b)=>a+b,0)/20:null,rvol=mean&&finite(bars[n].v)?bars[n].v/mean:null;
 if(c[n]<c[n-1]&&rvol>=1.5)warnings.push({key:'selling-volume',text:'Închidere în scădere cu volum relativ ≥1,5×',early:true});
 if(finite(market.rs20)&&market.rs20<0)warnings.push({key:'relative',text:'Randamentul pe 20 observații este sub benchmarkul pieței',early:true});
 const changes=timeline.filter(x=>x.changed),current={...last,label:LABELS[last.confirmed]||'Confirmare insuficientă',candidateLabel:LABELS[last.candidate]||'Neverificat'};
 return {version:1,...current,timeline,changes,warnings,rvol,previousCandidate:prior?.candidate||null,confirmation:3,notice:'Reguli descriptive pe OHLC, confirmate după 3 observații EOD consecutive din serie. Baza posibilă nu dovedește acumulare instituțională. Istoricul este recalculat, nu este un jurnal de alerte live.'};
}
function followup(event,series,splits=[]){if(!finite(event.price)||event.price<=0||event.currency!==series.currency)throw Error('Preț / monedă de alertă incompatibile');const at=series.bars.findIndex(x=>g.DailySeries.date(x.t,series.timezone)===event.asOf);if(at<0)throw Error('Sesiunea alertei lipsește');const start=series.bars[at];if(Math.abs(start.c/event.price-1)>0.001)throw Error('Prețul istoric a fost revizuit: compararea alertei este blocată');return [5,20,60].map(n=>{const b=series.bars[at+n];if(!b)return {sessions:n,status:'Istoric insuficient'};if(splits.some(t=>t>=start.t&&t<=b.t))return {sessions:n,status:'Split în interval · blocat'};return {sessions:n,asOf:g.DailySeries.date(b.t,series.timezone),change:(b.c/event.price-1)*100,status:'Variația prețului · fără dividende / FX'};});}
function exposure(positions,total,currency,model){const sums={},rows=[];let known=0;for(const p of positions){if(!currency||p.currency!==currency||!finite(p.value)||p.value<0||!finite(total)||total<=0){rows.push({ticker:p.ticker,weight:null});continue;}const m=model(p),regime=m?.regime?.confirmed||'unknown',weight=p.value/total*100;sums[regime]=(sums[regime]||0)+weight;known+=weight;rows.push({ticker:p.ticker,weight,regime});}return {sums,known,rows,total:positions.length,covered:rows.filter(x=>x.weight!==null).length};}
g.HoldingsRegime={LABELS,relative,candidate,stabilize,analyze,followup,exposure};
})(typeof window!=='undefined'?window:globalThis);
