(function(g){
'use strict';
const VERSION='holdings-mlp-v3',HORIZON=5,FEATURES=['Randament 5','Randament 20','Randament 60','Distanță EMA21','Distanță EMA50','Distanță EMA200','Pantă EMA21','RSI14','ATR / preț','Volum relativ'],CLASSES=['Declin','Mixt','Avans'];
const SEEDS=[2122026,2122027,2122028],TEMPERATURES=[1,1.5,2,3],L2=.001;
const finite=n=>typeof n==='number'&&Number.isFinite(n),mean=xs=>xs.reduce((a,b)=>a+b,0)/xs.length;
function validateBars(bars,now=Date.now()){
 if(!Array.isArray(bars)||bars.length<510||bars.length>2000)throw Error('Sunt necesare 510–2000 sesiuni OHLC, nu doar observațiile din raport.');
 for(let i=0;i<bars.length;i++){const b=bars[i];if(!b||![b.t,b.o,b.h,b.l,b.c,b.v].every(finite)||b.t>now||b.o<=0||b.l<=0||b.c<=0||b.v<=0||b.h<Math.max(b.o,b.c)||b.l>Math.min(b.o,b.c)||i&&b.t<=bars[i-1].t)throw Error('Istoric invalid, volum lipsă sau ordine temporală neconfirmată.');if(i&&Math.abs(b.c/bars[i-1].c-1)>.25)throw Error('Salt zilnic peste 25%: verifică ajustările și evenimentele înainte de antrenare.');}
}
function ema(values,n){const out=Array(values.length).fill(null);out[n-1]=mean(values.slice(0,n));for(let i=n;i<values.length;i++)out[i]=values[i]*2/(n+1)+out[i-1]*(1-2/(n+1));return out;}
function dataset(bars,now=Date.now()){
 validateBars(bars,now);const c=bars.map(b=>b.c),e21=ema(c,21),e50=ema(c,50),e200=ema(c,200),atr=Array(c.length).fill(null),rsi=Array(c.length).fill(null);let gain=0,loss=0,tr=0;
 for(let i=1;i<c.length;i++){const change=c[i]-c[i-1],up=Math.max(0,change),down=Math.max(0,-change),range=Math.max(bars[i].h-bars[i].l,Math.abs(bars[i].h-c[i-1]),Math.abs(bars[i].l-c[i-1]));if(i<=14){gain+=up/14;loss+=down/14;tr+=range/14;}else{gain=(gain*13+up)/14;loss=(loss*13+down)/14;tr=(tr*13+range)/14;}if(i>=14){atr[i]=tr;rsi[i]=gain===0&&loss===0?50:loss===0?100:100-100/(1+gain/loss);}}
 const features=i=>{const p=c[i],a=atr[i]/p*100,volume=mean(bars.slice(i-20,i).map(b=>b.v));const x=[5,20,60].map(n=>(p/c[i-n]-1)*100).concat([(p/e21[i]-1)*100,(p/e50[i]-1)*100,(p/e200[i]-1)*100,(e21[i]/e21[i-5]-1)*100,rsi[i],a,bars[i].v/volume]);if(!x.every(finite)||a<=0)throw Error('Indicatorii necesari nu pot fi verificați.');return x;};
 const observations=bars.slice(199).map((b,j)=>({t:b.t,x:features(j+199)})),rows=[];for(let i=199;i<bars.length-HORIZON;i++){const x=observations[i-199].x,move=(c[i+HORIZON]/c[i]-1)*100/x[8];rows.push({t:bars[i].t,end:bars[i+HORIZON].t,x,y:move<=-1?0:move>=1?2:1});}return {rows,latest:observations.at(-1).x,observations};
}
function split(rows){
 if(!Array.isArray(rows)||rows.length<300)throw Error('Minimum 300 exemple etichetate pentru separarea temporală.');
 for(let i=0;i<rows.length;i++){const r=rows[i];if(!r||!finite(r.t)||!finite(r.end)||r.end<=r.t||i&&r.t<=rows[i-1].t||!Array.isArray(r.x)||r.x.length!==10||!r.x.every(finite)||![0,1,2].includes(r.y))throw Error('Exemple de antrenare invalide.');}
 const a=Math.floor(rows.length*.6),b=Math.floor(rows.length*.8),validationStart=rows[a].t,testStart=rows[b].t,parts={train:rows.slice(0,a).filter(r=>r.end<validationStart),validation:rows.slice(a,b).filter(r=>r.end<testStart),test:rows.slice(b)};
 checkParts(parts);
 return parts;
}
function checkParts(parts){for(const key of ['train','validation','test']){const xs=parts[key],counts=[0,0,0];if(!Array.isArray(xs))throw Error('Set temporal lipsă.');xs.forEach((r,i)=>{if(!r||!finite(r.t)||!finite(r.end)||r.end<=r.t||i&&(r.t<=xs[i-1].t||r.end<=xs[i-1].end)||!Array.isArray(r.x)||r.x.length!==10||!r.x.every(finite)||![0,1,2].includes(r.y))throw Error('Exemple de antrenare invalide.');counts[r.y]++;});if(xs.length<(key==='train'?150:50)||counts.some(n=>n<(key==='train'?10:5)))throw Error('Istoric insuficient sau clase dezechilibrate în '+key+'. Modelul nu este antrenat.');}if(parts.train.some(r=>r.end>=parts.validation[0].t)||parts.validation.some(r=>r.end>=parts.test[0].t))throw Error('Orizonturile se suprapun între seturi.');}
function scaler(rows){const means=FEATURES.map((_,j)=>mean(rows.map(r=>r.x[j]))),scales=means.map((m,j)=>Math.max(1e-6,Math.sqrt(mean(rows.map(r=>(r.x[j]-m)**2)))));return {means,scales};}
function normalize(x,s){return x.map((n,i)=>(n-s.means[i])/s.scales[i]);}
function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function network(hidden,seed){const random=rng(seed),matrix=(a,b)=>Array.from({length:a},()=>Array.from({length:b},()=>hidden?(random()-.5)*Math.sqrt(6/(a+b)):0));return {hidden,w1:hidden?matrix(10,hidden):null,b1:hidden?Array(hidden).fill(0):null,w2:matrix(hidden||10,3),b2:[0,0,0]};}
function softmax(z){const top=Math.max(...z),xs=z.map(v=>Math.exp(v-top)),sum=xs.reduce((a,b)=>a+b,0);return xs.map(v=>v/sum);}
function forward(net,x){const h=net.hidden?net.b1.map((b,j)=>Math.tanh(b+x.reduce((s,v,i)=>s+v*net.w1[i][j],0))):x;return {h,p:softmax(net.b2.map((b,k)=>b+h.reduce((s,v,j)=>s+v*net.w2[j][k],0)))};}
function metrics(rows,predict){let loss=0,correct=0,brier=0;const confusion=Array.from({length:3},()=>[0,0,0]);for(const r of rows){const p=predict(r.x);if(p.length!==3||!p.every(finite))throw Error('Rezultat numeric invalid.');const label=p.indexOf(Math.max(...p));loss-=Math.log(Math.max(1e-12,p[r.y]));correct+=label===r.y;confusion[r.y][label]++;brier+=p.reduce((s,v,k)=>s+(v-(r.y===k?1:0))**2,0);}return {n:rows.length,loss:loss/rows.length,accuracy:correct/rows.length,balanced:confusion.some(row=>row.reduce((a,b)=>a+b,0)===0)?null:mean(confusion.map((row,k)=>row[k]/row.reduce((a,b)=>a+b,0))),brier:brier/rows.length,confusion};}
function validMetric(m,minimum=50,classMinimum=5){try{if(!Number.isInteger(m.n)||m.n<minimum||![m.loss,m.accuracy,m.brier].every(finite)||m.loss<0||m.brier<0||m.brier>2||m.accuracy<0||m.accuracy>1||m.confusion.length!==3||m.confusion.some(row=>row.length!==3||row.some(v=>!Number.isInteger(v)||v<0)||row.reduce((a,b)=>a+b,0)<classMinimum))return false;const matrix=m.confusion,total=matrix.flat().reduce((a,b)=>a+b,0),accuracy=matrix.reduce((sum,row,k)=>sum+row[k],0)/total,balanced=matrix.some(row=>row.reduce((a,b)=>a+b,0)===0)?null:mean(matrix.map((row,k)=>row[k]/row.reduce((a,b)=>a+b,0)));return total===m.n&&Math.abs(accuracy-m.accuracy)<1e-7&&(balanced===null?m.balanced===null:finite(m.balanced)&&Math.abs(balanced-m.balanced)<1e-7);}catch{return false;}}
function nonOverlap(rows){let end=-Infinity;return rows.filter(r=>{if(r.t<end)return false;end=r.end;return true;});}
function edge(a,b,c){return finite(a.balanced)&&finite(b.balanced)&&finite(c.balanced)&&a.loss<Math.min(b.loss,c.loss)-.02&&a.balanced>=Math.max(b.balanced,c.balanced)+.02;}
function epoch(net,rows){const h=net.hidden||10,dw2=Array.from({length:h},()=>[0,0,0]),db2=[0,0,0],dw1=net.hidden?Array.from({length:10},()=>Array(h).fill(0)):null,db1=net.hidden?Array(h).fill(0):null;
 for(const r of rows){const f=forward(net,r.x),delta=f.p.map((v,k)=>v-(r.y===k?1:0));for(let k=0;k<3;k++){db2[k]+=delta[k];for(let j=0;j<h;j++)dw2[j][k]+=f.h[j]*delta[k];}if(net.hidden)for(let j=0;j<h;j++){const d=(1-f.h[j]*f.h[j])*delta.reduce((s,v,k)=>s+v*net.w2[j][k],0);db1[j]+=d;for(let i=0;i<10;i++)dw1[i][j]+=r.x[i]*d;}}
 const zeros=xs=>xs.map(v=>Array.isArray(v)?zeros(v):0);if(!net._adam)net._adam={step:0,m:{w2:zeros(net.w2),b2:zeros(net.b2),w1:net.w1?zeros(net.w1):null,b1:net.b1?zeros(net.b1):null},v:{w2:zeros(net.w2),b2:zeros(net.b2),w1:net.w1?zeros(net.w1):null,b1:net.b1?zeros(net.b1):null}};const a=net._adam,step=++a.step,n=rows.length,rate=.015;
 function update(values,grad,m,v,penalty){for(let i=0;i<values.length;i++)if(Array.isArray(values[i]))update(values[i],grad[i],m[i],v[i],penalty);else{const d=grad[i]/n+(penalty ? (net.hidden?L2:.01/n)*values[i] : 0);m[i]=.9*m[i]+.1*d;v[i]=.999*v[i]+.001*d*d;values[i]-=rate*(m[i]/(1-.9**step))/(Math.sqrt(v[i]/(1-.999**step))+1e-8);}}
 update(net.w2,dw2,a.m.w2,a.v.w2,true);update(net.b2,db2,a.m.b2,a.v.b2,false);if(net.hidden){update(net.w1,dw1,a.m.w1,a.v.w1,true);update(net.b1,db1,a.m.b1,a.v.b1,false);}}
function fit(rows,latest,options={}){return fitPartitions(split(rows),latest,options);}
function modelPeriod(xs){return {from:xs[0].t,to:xs.at(-1).t,lastLabel:xs.at(-1).end,n:xs.length};}
function validationParts(rows){const cut=Math.floor(rows.length*.6),calibration=rows.slice(cut),earlyStopping=rows.slice(0,cut).filter(r=>r.end<calibration[0].t);if(earlyStopping.length<20)throw Error('Validare insuficientă pentru oprirea antrenării.');return {earlyStopping,calibration};}
function ensemble(committee,x){const ps=committee.map(n=>forward(n,x).p);return [0,1,2].map(k=>mean(ps.map(p=>p[k])));}
function soften(p,temperature){return temperature===1?p.slice():softmax(p.map(v=>Math.log(Math.max(1e-12,v))/temperature));}
function predict(result,x){return soften(ensemble(result.committee,x),result.adjustment.temperature);}
function selectTemperature(rows,committee){const counts=[0,0,0];rows.forEach(r=>counts[r.y]++);const eligible=rows.length>=20&&counts.every(n=>n>=3),candidates=TEMPERATURES.map(temperature=>({temperature,loss:metrics(rows,x=>soften(ensemble(committee,x),temperature)).loss}));let temperature=1;if(eligible)for(const c of candidates)if(c.loss<candidates.find(p=>p.temperature===temperature).loss-1e-8)temperature=c.temperature;return {temperature,eligible,candidates};}
function disagreement(committee,x){const ps=committee.map(n=>forward(n,x).p),votes=[0,0,0];ps.forEach(p=>votes[p.indexOf(Math.max(...p))]++);return {votes,spread:Math.max(...[0,1,2].map(k=>Math.max(...ps.map(p=>p[k]))-Math.min(...ps.map(p=>p[k]))))};}
function fitPartitions(parts,latest,options={}){
 if(!Array.isArray(latest)||latest.length!==10||!latest.every(finite))throw Error('Indicatorii actuali sunt invalizi.');
 checkParts(parts);const scale=scaler(parts.train),scaled=Object.fromEntries(Object.entries(parts).map(([k,xs])=>[k,xs.map(r=>({...r,x:normalize(r.x,scale)}))])),vp=validationParts(scaled.validation),linear=network(0,1),count=[1,1,1];parts.train.forEach(r=>count[r.y]++);const constant=count.map(n=>n/(parts.train.length+3)),copy=n=>JSON.parse(JSON.stringify({hidden:n.hidden,w1:n.w1,w2:n.w2,b1:n.b1,b2:n.b2}));
 const epochs=options.epochs??180;if(!Number.isInteger(epochs)||epochs<20||epochs>240)throw Error('Număr de epoci invalid.');
 const committee=[],memberEpochs=[];let bestLinear=copy(linear),bestLinearLoss=Infinity;
 for(let member=0;member<SEEDS.length;member++){
  const net=network(12,SEEDS[member]);let best=copy(net),bestLoss=Infinity,bestEpoch=0,stale=0,stopped=false;
  for(let i=1;i<=epochs;i++){if(!stopped)epoch(net,scaled.train);if(member===0)epoch(linear,scaled.train);if(i%5===0){const a=metrics(vp.earlyStopping,x=>forward(net,x).p);if(!stopped&&a.loss<bestLoss-1e-5){bestLoss=a.loss;best=copy(net);bestEpoch=i;stale=0;}else stale+=5;if(member===0){const b=metrics(vp.earlyStopping,x=>forward(linear,x).p);if(b.loss<bestLinearLoss){bestLinearLoss=b.loss;bestLinear=copy(linear);}}options.progress?.({epoch:i,total:epochs,member:member+1,members:SEEDS.length,loss:a.loss});if(stale>=35&&i>=60)stopped=true;}}
  committee.push(best);memberEpochs.push(bestEpoch);
 }
 const selected=selectTemperature(vp.calibration,committee),adjustment={method:'purged-validation-temperature-v1',...selected,earlyStopping:modelPeriod(vp.earlyStopping),calibration:modelPeriod(vp.calibration),raw:metrics(vp.calibration,x=>ensemble(committee,x)),adjusted:metrics(vp.calibration,x=>soften(ensemble(committee,x),selected.temperature))},output=x=>soften(ensemble(committee,x),selected.temperature);
 const evaluation=metrics(scaled.test,output),linearTest=metrics(scaled.test,x=>forward(bestLinear,x).p),constantTest=metrics(scaled.test,()=>constant),validation=metrics(scaled.validation,output),train=metrics(scaled.train,output),reference=linearTest.loss<constantTest.loss?linearTest:constantTest;
 const normalized=normalize(latest,scale),maxZ=Math.max(...normalized.map(Math.abs)),support=output(normalized),blocks=nonOverlap(scaled.test),blockPeriod=modelPeriod(blocks);
 return {version:VERSION,horizon:HORIZON,network:committee[0],committee,memberEpochs,regularization:L2,adjustment,disagreement:disagreement(committee,normalized),scale,latest:latest.slice(),support,classIndex:support.indexOf(Math.max(...support)),maxZ,advantage:edge(evaluation,linearTest,constantTest),reviewOnly:true,epochs:memberEpochs[0],report:{train,validation,test:evaluation,rawTest:metrics(scaled.test,x=>ensemble(committee,x)),linear:linearTest,constant:constantTest,reference:linearTest.loss<constantTest.loss?'linear':'constant',referenceLoss:reference.loss,nonOverlap:{test:metrics(blocks,output),linear:metrics(blocks,x=>forward(bestLinear,x).p),constant:metrics(blocks,()=>constant),period:blockPeriod},periods:Object.fromEntries(Object.entries(parts).map(([k,xs])=>[k,modelPeriod(xs)]))}};
}
function validNetwork(n){return n?.hidden===12&&Array.isArray(n.w1)&&n.w1.length===10&&n.w1.every(a=>Array.isArray(a)&&a.length===12&&a.every(finite))&&Array.isArray(n.w2)&&n.w2.length===12&&n.w2.every(a=>Array.isArray(a)&&a.length===3&&a.every(finite))&&Array.isArray(n.b1)&&n.b1.length===12&&n.b1.every(finite)&&Array.isArray(n.b2)&&n.b2.length===3&&n.b2.every(finite);}
function validAdjustment(a,period){try{
 if(a.method!=='purged-validation-temperature-v1'||typeof a.eligible!=='boolean'||!TEMPERATURES.includes(a.temperature)||a.candidates.length!==TEMPERATURES.length||a.candidates.some((c,i)=>c.temperature!==TEMPERATURES[i]||!finite(c.loss)||c.loss<0)||!validMetric(a.raw,20,0)||!validMetric(a.adjusted,20,0))return false;
 for(const key of ['earlyStopping','calibration']){const p=a[key];if(![p.from,p.to,p.lastLabel].every(finite)||p.from>p.to||p.to>=p.lastLabel||!Number.isInteger(p.n)||p.n<20||p.from<period.from||p.to>period.to||p.lastLabel>period.lastLabel)return false;}
 if(a.earlyStopping.from!==period.from||a.calibration.to!==period.to||a.calibration.lastLabel!==period.lastLabel||a.earlyStopping.lastLabel>=a.calibration.from||a.earlyStopping.n+a.calibration.n>period.n||a.raw.n!==a.calibration.n||a.adjusted.n!==a.calibration.n)return false;
 const eligible=a.raw.confusion.every(row=>row.reduce((x,y)=>x+y,0)>=3);if(a.eligible!==eligible)return false;let chosen=1;if(eligible)for(const c of a.candidates)if(c.loss<a.candidates.find(p=>p.temperature===chosen).loss-1e-8)chosen=c.temperature;
 return chosen===a.temperature&&Math.abs(a.raw.loss-a.candidates[0].loss)<1e-7&&Math.abs(a.adjusted.loss-a.candidates.find(p=>p.temperature===chosen).loss)<1e-7&&JSON.stringify(a.raw.confusion)===JSON.stringify(a.adjusted.confusion);
 }catch{return false;}}
function valid(result){
 try{const n=result.network,s=result.scale,r=result.report;
  if(result.version!==VERSION||result.horizon!==HORIZON||result.reviewOnly!==true||n.hidden!==12||n.w1.length!==10||n.w1.some(a=>a.length!==12||!a.every(finite))||n.w2.length!==12||n.w2.some(a=>a.length!==3||!a.every(finite))||n.b1.length!==12||n.b2.length!==3||![...n.b1,...n.b2,...s.means,...s.scales,...result.support,...result.latest].every(finite)||s.means.length!==10||s.scales.length!==10||s.scales.some(v=>v<=0)||result.latest.length!==10||result.support.length!==3||result.support.some(v=>v<0||v>1)||Math.abs(result.support.reduce((a,b)=>a+b,0)-1)>1e-6||!finite(result.maxZ)||typeof result.advantage!=='boolean'||![0,1,2].includes(result.classIndex)||!Number.isInteger(result.epochs)||result.epochs<5||result.epochs>240)return false;
  for(const key of ['train','validation','test','linear','constant'])if(!validMetric(r[key],key==='train'?150:50,key==='train'?10:5))return false;
  for(const key of ['train','validation','test']){const p=r.periods[key];if(![p.from,p.to,p.lastLabel].every(finite)||p.from>p.to||p.to>=p.lastLabel||p.n!==r[key].n)return false;}
  if(r.linear.n!==r.test.n||r.constant.n!==r.test.n||!(r.periods.train.lastLabel<r.periods.validation.from&&r.periods.validation.lastLabel<r.periods.test.from))return false;
  if(!Array.isArray(result.committee)||result.committee.length!==3||!result.committee.every(validNetwork)||JSON.stringify(result.committee[0])!==JSON.stringify(n)||result.regularization!==L2||!Array.isArray(result.memberEpochs)||result.memberEpochs.length!==3||result.memberEpochs.some(v=>!Number.isInteger(v)||v<5||v>240)||result.epochs!==result.memberEpochs[0]||!validAdjustment(result.adjustment,r.periods.validation)||!validMetric(r.rawTest)||r.rawTest.n!==r.test.n)return false;
  const z=normalize(result.latest,s),support=predict(result,z),d=disagreement(result.committee,z);if(JSON.stringify(d.votes)!==JSON.stringify(result.disagreement?.votes)||!finite(result.disagreement?.spread)||Math.abs(d.spread-result.disagreement.spread)>1e-7)return false;if(support.some((v,k)=>Math.abs(v-result.support[k])>1e-7)||Math.abs(Math.max(...z.map(Math.abs))-result.maxZ)>1e-7||result.classIndex!==support.indexOf(Math.max(...support)))return false;
  const block=r.nonOverlap;if(!block||![block.period.from,block.period.to,block.period.lastLabel].every(finite)||['test','linear','constant'].some(k=>!validMetric(block[k],1,0)||block[k].n!==block.period.n)||block.period.n>r.test.n||block.period.from!==r.periods.test.from||block.period.to<block.period.from||block.period.to>r.periods.test.to||block.period.lastLabel>r.periods.test.lastLabel||block.period.to>=block.period.lastLabel)return false;
  if(result.comparison!==undefined&&!g.HoldingsModelComparison?.valid(result))return false;
  if(result.walk!==undefined&&!g.HoldingsNeuralEvaluation?.valid(result.walk,r))return false;
  return result.advantage===edge(r.test,r.linear,r.constant);
 }catch{return false;}
}
function assess(record,{symbol,currency,asOf,demo,now=Date.now()}){if(!record)return {state:'missing',message:'Model neantrenat pentru acest instrument.'};if(record.symbol!==symbol||record.currency!==currency||record.kind!==(demo?'synthetic':'market')||!valid(record.result))return {state:'invalid',message:'Model incompatibil sau ilizibil; nu este utilizat.'};if(!finite(record.trainedAt)||record.trainedAt>now+60000||now-record.trainedAt>30*60000||!asOf||record.asOf!==asOf)return {state:'stale',message:'Model expirat sau analiză EOD lipsă. Reantrenează pe sesiunea verificată.'};if(record.result.maxZ>6)return {state:'drift',message:'Indicatorii actuali ies din domeniul antrenării. Interpretarea este blocată.'};if(Math.max(...record.result.disagreement.votes)<2||record.result.disagreement.spread>.35)return {state:'disagreement',message:'Rețelele se contrazic; interpretarea scorurilor este blocată.'};if(!record.result.advantage)return {state:'no-edge',message:'Fără avantaj demonstrat în testul recent față de modelele simple.'};return record.result.walk?.consistent?{state:'research',message:'Avantaj repetat în 3 ferestre și în orizonturi fără suprapunere. Rămâne experimental.'}:{state:'fragile',message:'Avantaj în testul recent; robustețea pe mai multe perioade nu este confirmată.'};}
function demoBars(seed=0,now=Date.now()){
 const end=new Date(now);end.setUTCHours(14,30,0,0);if(end.getTime()>now)end.setUTCDate(end.getUTCDate()-1);const days=[];for(let d=new Date(end);days.length<1100;d.setUTCDate(d.getUTCDate()-1))if(d.getUTCDay()>0&&d.getUTCDay()<6)days.unshift(d.getTime());let price=100;return days.map((t,i)=>{price*=Math.exp(.004*Math.sin((i+seed*17)/17)+.0015*Math.sin(i/3));return {t,o:price*.999,h:price*1.008,l:price*.992,c:price,v:1000000*(1.3+.25*Math.sin(i/9))};});
}
g.HoldingsNeural={VERSION,HORIZON,FEATURES,CLASSES,dataset,split,checkParts,metrics,scaler,normalize,network,forward,ensemble,soften,predict,validationParts,selectTemperature,disagreement,validAdjustment,fit,fitPartitions,valid,validMetric,nonOverlap,edge,assess,demoBars};
})(typeof window!=='undefined'?window:globalThis);
