/* Read-only chronology; a server receipt timestamps first receipt of a hash, not a trade decision. */
(function(g){'use strict';
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function canonical(x){if(x===null||typeof x!=='object')return JSON.stringify(x);if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';}
async function digest(x){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(x)))),v=>v.toString(16).padStart(2,'0')).join('');}
function timeline(outcome,history,notes={},plans=[]){const r=outcome.record,events=[{id:r.id,kind:'analysis',at:r.createdAt,text:r.verdict.title+' · '+r.source.asOf+' · stop '+r.stop+' / țintă '+r.target+' '+r.currency}];
 for(const p of Array.isArray(plans)?plans:[])if(g.TradePlans?.validate(p).ok&&p.basis?.accountSizing?.scope===r.scope&&p.symbol===r.symbol&&p.currency===r.currency&&p.basis.asOf===r.source.asOf&&p.createdAt>=r.source.checkedAt&&p.createdAt<=r.expiresAt&&(!outcome.entryAt||p.createdAt<outcome.entryAt)&&p.entryLow===r.entryLow&&p.entryHigh===r.entryHigh&&p.stop===r.stop&&p.target===r.target)events.push({id:String(p.id),kind:'plan',at:p.createdAt,text:'Plan de simulare cu aceleași repere · '+p.shares+' unități · risc '+p.risk+' '+p.currency+' · corelat pe cont, simbol, sesiune și niveluri; execuția planului nu este certificată.'});
 const raw=notes[r.scope+'|'+r.ticker]?.history,changes=Array.isArray(raw)?raw.filter(x=>x&&Number.isFinite(Date.parse(x.at))).slice().sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)):[],before=changes.filter(x=>Date.parse(x.at)<=r.createdAt).at(-1);for(const x of [...(before?[before]:[]),...changes.filter(x=>Date.parse(x.at)>r.createdAt&&Date.parse(x.at)<=(outcome.closedAt||Date.now()))])if(Number.isFinite(Date.parse(x.at)))events.push({kind:'thesis',at:Date.parse(x.at),text:'Repere manuale · stop '+(x.stop??'—')+' '+(x.stopCurrency||'')+' / țintă '+(x.targetPrice??'—')+' '+(x.targetCurrency||'')+(x.text?' · '+x.text:'')});
 const ids=new Set([...(outcome.buyIds||[]),...(outcome.sellIds||[])]);if(history?.scope===r.scope)for(const x of history.rows||[])if(ids.has(x.id)&&x.ticker===r.ticker)events.push({id:x.id,kind:'execution',at:Date.parse(x.date),text:x.side+' · '+x.quantity+' × '+x.price+' '+x.priceCurrency+' · costuri '+(Array.isArray(x.taxes)?'raportate':'neverificate')+' · FX '+(Number.isFinite(x.fxRate)?x.fxRate:'neverificat')});
 if(outcome.state==='closed')events.push({kind:'result',at:outcome.closedAt,text:'Rezultat asociat · '+outcome.pnl+' '+outcome.pnlCurrency+' · '+outcome.reason});return events.sort((a,b)=>a.at-b.at||a.kind.localeCompare(b.kind));}
function markup(outcome,history,notes,plans){return '<details class="decision-audit"><summary>Traseul deciziei · analiză, planuri, repere, execuții, rezultat</summary><ol>'+timeline(outcome,history,notes,plans).map(x=>'<li><small>'+esc(new Date(x.at).toLocaleString('ro-RO'))+'</small><p>'+esc(x.text)+'</p></li>').join('')+'</ol><p>Orele analizei și reperelor provin din registrul local; execuțiile provin din broker. Asocierea curentă: '+esc(outcome.state)+'.</p></details>';}
let receipts=[],generation=0,active=null;
function cloud(){return g.parent!==g?g.parent.TTCloud:g.TTCloud;}
async function render(host,records,{simulation=false}={}){if(!host)return;const token=++generation,c=cloud(),state=c?.state();active={host,email:state?.email};const available=!simulation&&state?.connected&&state.ready&&state.error!=='account_mismatch'&&state.audit?.available&&state.audit?.protocol==='tt-audit-v1';host.innerHTML='<h3>Amprentele analizelor · verificare server</h3><p>Prima amprentă acceptată pe server își păstrează ora și nu poate fi înlocuită cu alt conținut. Această oră arată când serverul a primit analiza, fără să certifice că a precedat tranzacția.</p><button data-audit-anchor '+(!available||!records.length?'disabled':'')+'>Fixează amprentele pe server</button> <button data-audit-refresh '+(!available?'disabled':'')+'>Verifică amprentele</button><p data-audit-status role="status">'+(simulation?'DEMO FICTIV · nu trimite date pe server.':available?'Verificare disponibilă pentru '+records.length+' analize ale contului.':'Conectează Google și actualizează serviciul pentru verificarea server.')+'</p><div data-audit-results></div>';
 const status=host.querySelector('[data-audit-status]'),result=host.querySelector('[data-audit-results]');async function check(anchor=false){const owner=c?.state().email,valid=()=>{const s=c?.state();return token===generation&&s?.connected&&s.ready&&s.error!=='account_mismatch'&&s.audit?.available&&s.email===owner;}; if(!available||!valid())return;status.textContent='Verific amprentele…';host.querySelectorAll('button').forEach(b=>b.disabled=true);try{const entries=[];for(const r of records){if(!valid())return;const hash=await digest(r);if(!valid())return;entries.push({id:r.id,digest:hash,kind:'analysis'});}let response;if(anchor){for(let i=0;i<entries.length;i+=50){if(!valid())return;response=await c.anchorAudit(entries.slice(i,i+50));if(!valid())return;}}else{if(!valid())return;response=await c.audit();}if(!valid())return;receipts=response?.receipts||[];const byId=new Map(receipts.map(r=>[r.id,r]));const rows=entries.map(e=>{const receipt=byId.get(e.id);return {id:e.id,state:!receipt?'Local · fără amprentă server':receipt.digest===e.digest?'Conținut identic':'DIFERENȚĂ · originalul server este păstrat',receipt};});status.textContent=rows.filter(x=>x.receipt).length+' / '+rows.length+' analize cu amprentă server.';result.innerHTML='<ul>'+rows.slice(-30).map(x=>'<li>'+esc(x.id)+' · <b>'+esc(x.state)+'</b>'+(x.receipt?' · primit '+esc(new Date(x.receipt.acceptedAt).toLocaleString('ro-RO')):'')+'</li>').join('')+'</ul>';}catch(e){if(!valid())return;status.textContent=e.message==='audit_original_changed'?'Conținut diferit de originalul server. Ambele copii rămân păstrate.':'Verificare indisponibilă: '+e.message;}finally{if(token===generation){const enabled=valid();host.querySelectorAll('button').forEach(b=>b.disabled=!enabled);if(!enabled){status.textContent='Contul sau disponibilitatea serviciului s-a schimbat. Reîncarcă raportul pentru contul curent.';result.innerHTML='';}}}}
 host.querySelector('[data-audit-anchor]').onclick=()=>check(true);host.querySelector('[data-audit-refresh]').onclick=()=>check(false);
}
function invalidate(state){if(!active||state?.connected&&state.email===active.email)return;generation++;active.host.querySelectorAll('button').forEach(b=>b.disabled=true);active.host.querySelector('[data-audit-results]').innerHTML='';active.host.querySelector('[data-audit-status]').textContent='Contul Google s-a schimbat. Reîncarcă raportul pentru contul curent.';active=null;}
g.addEventListener?.('message',e=>{if(g.parent!==g&&e.source===g.parent&&e.origin===g.location.origin&&e.data?.ttCloudState)invalidate(e.data.ttCloudState);});g.addEventListener?.('tt-cloud-state',e=>invalidate(e.detail));
function readNotes(storage){try{const x=JSON.parse(storage.getItem('tt_holdings_theses_v1')||'{}');return x&&typeof x==='object'&&!Array.isArray(x)?x:{};}catch{return {};}}
g.TradeAudit={readNotes,canonical,digest,timeline,markup,render};
})(typeof window!=='undefined'?window:globalThis);
