(function(g){
'use strict';
const escape=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function snapshots(){try{return Object.values(JSON.parse(localStorage.getItem('tt_trading212_portfolio_v1')||'{}')).filter(a=>a.environment==='live');}catch(_){return [];}}
// Only US equity identifiers have an unambiguous mapping to this scanner.
function symbol(ticker){return /^[A-Z0-9.-]+_US_EQ$/.test(ticker||'')?ticker.replace(/_US_EQ$/,''):null;}
function held(sym){return snapshots().flatMap(a=>(a.positions||[]).filter(p=>p.quantity>0&&symbol(p.ticker)===sym).map(p=>({position:p,stale:!Number.isFinite(Date.parse(a.fetchedAt))||Date.now()-Date.parse(a.fetchedAt)>300000,asOf:a.fetchedAt})));}
function badge(sym){const matches=held(sym);return matches.length?'<small style="color:var(--accent,#168b68);font-weight:700">DEȚII DEJA · '+(matches.every(x=>!x.stale)?'snapshot Invest':'snapshot vechi — reverifică')+'</small>':'';}
function concentration(a){const s=a.summary||{},total=s.totalValue,c=s.currency;if(!(total>0)||!c||!Array.isArray(a.positions))return {rows:[],missing:true};return {rows:a.positions.filter(p=>p.quantity>0&&p.currency===c&&typeof p.value==='number'&&Number.isFinite(p.value)).map(p=>({...p,weight:p.value/total*100})).sort((x,y)=>y.weight-x.weight),missing:a.positions.some(p=>p.quantity>0&&(p.currency!==c||typeof p.value!=='number'||!Number.isFinite(p.value)))};}
function renderRisk(){const host=document.getElementById('t212Risk');if(!host)return;const data=snapshots();host.innerHTML=data.length?data.map(a=>{const r=concentration(a),stale=!Number.isFinite(Date.parse(a.fetchedAt))||Date.now()-Date.parse(a.fetchedAt)>300000;return '<p>'+escape(a.fetchedAt)+' · '+(stale?'DATE VECHI':'ultimul snapshot')+'</p>'+(!r.rows.length?'<p>Expunerea nu poate fi calculată din datele disponibile.</p>':r.rows.map(p=>'<p><b>'+escape(p.ticker)+'</b> · '+p.weight.toFixed(1)+'% din valoarea contului'+(p.weight>=20?' · CONCENTRARE RIDICATĂ':'')+'</p>').join(''))+(r.missing?'<p>Acoperire parțială: poziții cu valoare sau monedă lipsă.</p>':'');}).join(''):'Fără snapshot Invest. Conectează Trading 212.';}
function insights(){try{const data=JSON.parse(localStorage.getItem('tt_trading212_fills_v1')||'{"accounts":{}}');return Object.values(data.accounts).filter(a=>a.environment==='live').map(a=>{const fills=a.items||[],sell=fills.filter(x=>x.side==='SELL'),currencies={};for(const f of sell)if(typeof f.realized==='number'&&Number.isFinite(f.realized)&&f.currency){const k=f.currency;currencies[k]=(currencies[k]||0)+f.realized;}return {count:fills.length,buys:fills.filter(x=>x.side==='BUY').length,sells:sell.length,missing:sell.filter(x=>typeof x.realized!=='number').length,currencies,complete:a.complete};});}catch(_){return [];}}
function renderCoach(){const host=document.getElementById('t212Coach');if(!host)return;const reports=insights();host.innerHTML=reports.length?reports.map(r=>'<p><b>'+r.count+' execuții importate</b> · '+r.buys+' BUY · '+r.sells+' SELL · '+(r.complete?'istoric parcurs integral':'import parțial')+'</p><p>P&amp;L realizat raportat pe execuțiile SELL: '+(Object.entries(r.currencies).map(([c,v])=>escape(v.toLocaleString('ro-RO',{maximumFractionDigits:2})+' '+c)).join(' / ')||'neverificat')+'</p>'+(r.missing?'<p>'+r.missing+' execuții SELL fără P&amp;L raportat.</p>':'')+'<p>Execuțiile parțiale nu reprezintă automat trades închise. Win rate și R necesită asocierea cumpărărilor cu vânzările și stopul de la intrare.</p>').join(''):'Conectează Trading 212 pentru analiza execuțiilor reale.';}
g.T212C={snapshots,symbol,held,badge,concentration,insights,renderRisk,renderCoach};
if(typeof document!=='undefined'){renderRisk();renderCoach();g.addEventListener('storage',()=>{renderRisk();renderCoach();});g.setInterval(()=>{renderRisk();renderCoach();},30000);}
})(typeof window!=='undefined'?window:globalThis);
