// Broker executions remain distinct from manually paired trade plans.
(function(g){
'use strict';
const KEY='tt_trading212_fills_v1';
function read(){const raw=localStorage.getItem(KEY);if(!raw)return {accounts:{}};const data=JSON.parse(raw);if(!data.accounts||typeof data.accounts!=='object')throw Error('Jurnal Trading 212 incompatibil.');return data;}
function merge(scope,environment,items,nextCursor,fetchedAt){
 const data=read(),a=data.accounts[scope]||{environment,items:[]},byId=new Map(a.items.map(x=>[x.id,x]));let skipped=0;
 for(const item of items){if(!item.id||!item.ticker||!['BUY','SELL'].includes(item.side)||!(item.quantity>0)||!(item.price>0)||!Number.isFinite(Date.parse(item.date))){skipped++;continue;}byId.set(item.id,{...item});}
 a.items=[...byId.values()].sort((x,y)=>Date.parse(y.date)-Date.parse(x.date));a.environment=environment;a.nextCursor=nextCursor;a.fetchedAt=fetchedAt;a.complete=!nextCursor;data.accounts[scope]=a;localStorage.setItem(KEY,JSON.stringify(data));return {count:a.items.length,skipped,complete:a.complete};
}
function review(a,escape){if(!g.ExecutionReview)return '';const r=g.ExecutionReview.fifo(a.items||[]),totals={};for(const x of r.matches)totals[x.currency]=(totals[x.currency]||0)+x.gross;return `<details><summary>Revizuire FIFO · ${r.matches.length} loturi vândute · ${r.open.length} loturi deschise</summary><p>Asociere informativă în moneda instrumentului. Nu reprezintă calcul fiscal. P&amp;L brut exclude comisioane, taxe și FX; P&amp;L broker este păstrat separat; includerea tuturor costurilor în acest câmp nu este confirmată. Diferența valorilor nete broker alocă proporțional încasarea SELL minus costul BUY în aceeași monedă de cont; nu scade din nou costuri deja incluse. Fără confirmarea convenției API, aceasta este reconciliere informativă, nu P&amp;L fiscal sau net certificat. R este indisponibil fără stopul documentat la intrare.</p><p>P&amp;L brut pe monede: ${escape(Object.entries(totals).map(([c,v])=>v.toFixed(2)+' '+c).join(' / ')||'neverificat')}</p><p>${r.unmatched.length} execuții neasociate / incomplete. Loturile parțiale nu sunt numărate drept trades închise.</p><div style="overflow:auto"><table style="width:100%;min-width:700px"><thead><tr><th>Ticker</th><th>Intrare</th><th>Ieșire</th><th>Cantitate</th><th>Preț intrare → ieșire</th><th>P&amp;L brut</th><th>Diferență valori nete broker · FIFO</th></tr></thead><tbody>${r.matches.map(x=>`<tr><td>${escape(x.ticker)}</td><td>${escape(x.opened)}</td><td>${escape(x.closed)}</td><td>${escape(x.quantity)}</td><td>${escape(x.entry)} → ${escape(x.exit)} ${escape(x.currency)}</td><td>${escape(x.gross.toFixed(2))} ${escape(x.currency)}</td><td>${escape(Number.isFinite(x.cashDifference)?x.cashDifference.toFixed(2)+' '+x.cashCurrency:'Neverificată')}</td></tr>`).join('')}</tbody></table></div></details>`;}
function render(){const host=document.getElementById('t212Journal');if(!host)return;const escape=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));try{const data=read().accounts,all=Object.values(data).sort((a,b)=>(Date.parse(b.fetchedAt)||0)-(Date.parse(a.fetchedAt)||0)),accounts=all.filter((a,i)=>all.findIndex(x=>x.environment===a.environment)===i);host.innerHTML=accounts.length?accounts.map(a=>`<h3>Trading 212 · ${a.environment==='demo'?'DEMO':'INVEST'} · ${a.items.length} execuții</h3><p>${a.complete?'Istoricul disponibil a fost parcurs integral':'Import în curs / parțial'} · ${escape(a.fetchedAt)}</p>${review(a,escape)}<div style="overflow:auto;max-height:520px"><table style="width:100%;min-width:650px"><thead><tr><th>Data</th><th>Ticker</th><th>Operație</th><th>Cantitate</th><th>Preț</th><th>P&amp;L broker</th><th>Valoare netă broker</th><th>Comisioane / FX</th></tr></thead><tbody>${a.items.map(x=>`<tr><td>${escape(x.date)}</td><td>${escape(x.ticker)}</td><td>${escape(x.side)}</td><td>${escape(x.quantity)}</td><td>${escape(x.price)} ${escape(x.priceCurrency)}</td><td>${escape(x.realized)} ${escape(x.currency)}</td><td>${escape(x.amount)} ${escape(x.currency)}</td><td>${escape(Number.isFinite(x.fxRate)?'FX raportat: '+x.fxRate:'FX neverificat')}<br>${escape(Array.isArray(x.taxes)?(x.taxes.length?x.taxes.map(t=>[t.name,t.quantity,t.currency].join(' ')).join(' / '):'Lista costurilor raportate este goală'):'Costuri neverificate · relay fără defalcare')}</td></tr>`).join('')}</tbody></table></div>`).join(''):'Conectează Trading 212 pentru importul automat al execuțiilor.';}catch(e){host.textContent='Jurnalul brokerului nu poate fi citit: '+e.message;}}
const SNAPSHOT_KEY='tt_trading212_portfolio_v1';
function saveSnapshot(scope,environment,summary,positions,fetchedAt){
 const data=JSON.parse(localStorage.getItem(SNAPSHOT_KEY)||'{}');data[scope]={environment,summary,positions,fetchedAt};localStorage.setItem(SNAPSHOT_KEY,JSON.stringify(data));
 if(summary&&Array.isArray(positions)&&Number.isFinite(summary.totalValue)&&summary.currency&&Number.isFinite(Date.parse(fetchedAt))&&Date.parse(fetchedAt)<=Date.now()+60000){const h=JSON.parse(localStorage.getItem('tt_trading212_account_history_v1')||'{}'),xs=h[scope]||[],day=fetchedAt.slice(0,10),entry={at:fetchedAt,total:summary.totalValue,currency:summary.currency};const index=xs.findIndex(x=>x.at.slice(0,10)===day);if(index<0)xs.push(entry);else if(Date.parse(xs[index].at)<Date.parse(fetchedAt))xs[index]=entry;h[scope]=xs.sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)).slice(-500);localStorage.setItem('tt_trading212_account_history_v1',JSON.stringify(h));}

}
function mergeCash(scope,environment,kind,items,nextCursor,fetchedAt){
 if(!['dividends','transactions'].includes(kind)||!Array.isArray(items))throw Error('Istoric monetar incompatibil.');
 const data=JSON.parse(localStorage.getItem('tt_trading212_cash_v1')||'{}'),account=data[scope]||{environment},old=account[kind]||{items:[]},byId=new Map(old.items.map(x=>[String(x.id),x]));let skipped=0;
 for(const x of items){if(!x.id||!Number.isFinite(x.amount)||!x.currency||!Number.isFinite(Date.parse(x.date))||Date.parse(x.date)>Date.now()+60000){skipped++;continue;}byId.set(String(x.id),{...x});}
 account[kind]={items:[...byId.values()].sort((a,b)=>Date.parse(b.date)-Date.parse(a.date)),nextCursor:nextCursor||null,complete:!nextCursor&&skipped===0&&!old.skipped,fetchedAt,skipped:(old.skipped||0)+skipped,error:null};data[scope]=account;localStorage.setItem('tt_trading212_cash_v1',JSON.stringify(data));return account[kind];
}
function cashError(scope,environment,kind,error){const data=JSON.parse(localStorage.getItem('tt_trading212_cash_v1')||'{}'),account=data[scope]||{environment};account[kind]={...(account[kind]||{items:[],complete:false}),error:String(error),errorAt:new Date().toISOString()};data[scope]=account;localStorage.setItem('tt_trading212_cash_v1',JSON.stringify(data));}
function renderPortfolio(){const host=document.getElementById('t212Portfolio');if(!host)return;
 const escape=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const format=(n,c)=>typeof n==='number'&&Number.isFinite(n)?escape(n.toLocaleString('ro-RO',{maximumFractionDigits:4})+' '+(c||'')):'—';
 try{const all=Object.values(JSON.parse(localStorage.getItem(SNAPSHOT_KEY)||'{}')).sort((a,b)=>(Date.parse(b.fetchedAt)||0)-(Date.parse(a.fetchedAt)||0)),accounts=all.filter((a,i)=>all.findIndex(x=>x.environment===a.environment)===i);host.innerHTML=accounts.length?accounts.map(a=>{const s=a.summary||{},c=s.currency,stale=!Number.isFinite(Date.parse(a.fetchedAt))||Date.parse(a.fetchedAt)>Date.now()+60000||Date.now()-Date.parse(a.fetchedAt)>300000;return `<h3>${a.environment==='demo'?'DEMO · bani virtuali':'Trading 212 Invest'}</h3><p>${stale?'DATE NEACTUALIZATE':'Ultimul snapshot importat'} · ${escape(a.fetchedAt)}${!a.summary||!a.positions?' · PARȚIAL':''}</p><p>Valoare cont: <b>${format(s.totalValue,c)}</b> · Disponibil: <b>${format(s.available,c)}</b> · P&amp;L nerealizat: <b>${format(s.unrealized,c)}</b> · P&amp;L realizat: <b>${format(s.realized,c)}</b></p><div style="overflow:auto"><table style="width:100%;min-width:600px"><thead><tr><th>Ticker</th><th>Cantitate</th><th>Preț mediu</th><th>Preț raportat</th><th>Valoare</th><th>P&amp;L</th></tr></thead><tbody>${Array.isArray(a.positions)?a.positions.map(p=>`<tr><td>${escape(p.ticker)}</td><td>${format(p.quantity)}</td><td>${format(p.averagePrice,p.instrumentCurrency)}</td><td>${format(p.currentPrice,p.instrumentCurrency)}</td><td>${format(p.value,p.currency)}</td><td>${format(p.unrealized,p.currency)}</td></tr>`).join(''):'<tr><td colspan="6">Poziții nesincronizate.</td></tr>'}</tbody></table></div>`;}).join(''):'Conectează Trading 212 pentru sincronizarea portofoliului real.';}catch(e){host.textContent='Snapshot indisponibil: '+e.message;}
}
g.T212J={merge,read,render,saveSnapshot,renderPortfolio,mergeCash,cashError};if(typeof document!=='undefined'){render();renderPortfolio();g.addEventListener('storage',()=>{render();renderPortfolio();});g.setInterval(renderPortfolio,30000);}
})(typeof window!=='undefined'?window:globalThis);
