(function(g){
'use strict';
const crypto=g.crypto,DB='tt-invest-connection-v1',STORE='vault';
function validate(p){if(!p||!['live','demo'].includes(p.environment)||typeof p.key!=='string'||typeof p.secret!=='string'||!p.key.length||p.key.length>256||!p.secret.length||p.secret.length>512||p.key.includes(':')||! /^[\x21-\x7e]+$/.test(p.key+p.secret))throw Error('Cheie sau secret incompatibil.');return {key:p.key,secret:p.secret,environment:p.environment};}
function open(){return new Promise((resolve,reject)=>{if(!g.indexedDB)return reject(Error('Stocarea conexiunii nu este disponibilă în acest browser.'));const r=g.indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onerror=()=>reject(Error('Conexiunea salvată nu poate fi accesată.'));r.onsuccess=()=>resolve(r.result);});}
async function operation(mode,fn){const db=await open();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode),request=fn(tx.objectStore(STORE));let result;request.onsuccess=()=>{result=request.result;};tx.oncomplete=()=>resolve(result);tx.onerror=tx.onabort=()=>reject(Error('Conexiunea nu a putut fi salvată sau citită.'));});}finally{db.close();}}
async function save(payload){const clean=validate(payload),key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']),iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(clean)));await operation('readwrite',store=>store.put({key,iv,cipher},'connection'));}
async function read(){const record=await operation('readonly',store=>store.get('connection'));if(!record)return null;const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:record.iv},record.key,record.cipher);return validate(JSON.parse(new TextDecoder().decode(plain)));}
async function clear(){await operation('readwrite',store=>store.delete('connection'));}
function encode(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes)));}
function decode(text){if(typeof text!=='string'||text.length>12000||!/^[A-Za-z0-9+/]*={0,2}$/.test(text))throw Error('Cod de transfer invalid.');return Uint8Array.from(atob(text),c=>c.charCodeAt(0));}
async function derived(password,salt){if(typeof password!=='string'||password.length<12||password.length>200)throw Error('Alege o parolă de transfer de cel puțin 12 caractere.');const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function pack(password){const payload=await read();if(!payload)throw Error('Conectează și salvează contul înainte de transfer.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derived(password,salt),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(payload)));return 'TT212.'+btoa(JSON.stringify({v:1,salt:encode(salt),iv:encode(iv),cipher:encode(cipher)}));}
async function unpack(code,password){if(typeof code!=='string'||code.length>14000||!code.startsWith('TT212.'))throw Error('Cod de transfer invalid.');let packet;try{packet=JSON.parse(new TextDecoder().decode(decode(code.slice(6))));}catch(_){throw Error('Cod de transfer invalid.');}if(packet.v!==1)throw Error('Versiune de transfer incompatibilă.');const salt=decode(packet.salt),iv=decode(packet.iv),cipher=decode(packet.cipher);if(salt.length!==16||iv.length!==12||cipher.length>2500)throw Error('Cod de transfer invalid.');const key=await derived(password,salt);let plain;try{plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,cipher);}catch(_){throw Error('Parola de transfer este incorectă sau codul este deteriorat.');}return validate(JSON.parse(new TextDecoder().decode(plain)));}
g.T212Vault={save,read,clear,pack,unpack,validate};
})(typeof window!=='undefined'?window:globalThis);
