// RFC 8291 aes128gcm + RFC 8292 VAPID, using Web Crypto only.
const E=new TextEncoder(),join=(...xs)=>{const out=new Uint8Array(xs.reduce((s,x)=>s+x.length,0));let i=0;for(const x of xs){out.set(x,i);i+=x.length;}return out;};
export function base64url(value){return btoa(String.fromCharCode(...new Uint8Array(value))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
export function decode64(value){if(typeof value!=='string'||value.length>2000||!/^[A-Za-z0-9_-]+$/.test(value))throw Error('invalid_push');return Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),x=>x.charCodeAt(0));}
export function validSubscription(s){try{const u=new URL(s.endpoint),host=u.hostname,allowed=host==='fcm.googleapis.com'&&/^\/(?:fcm\/send|wp)\//.test(u.pathname)||host==='updates.push.services.mozilla.com'&&/^\/wpush\/v2\//.test(u.pathname)||host==='web.push.apple.com'&&u.pathname.length>1||/^[a-z0-9-]+\.notify\.windows\.com$/.test(host)&&u.pathname==='/w/';return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&!u.hash&&s.endpoint.length<=2000&&allowed&&decode64(s.keys?.p256dh).length===65&&decode64(s.keys.p256dh)[0]===4&&decode64(s.keys?.auth).length===16;}catch{return false;}}
async function hkdf(secret,salt,info,length){const key=await crypto.subtle.importKey('raw',secret,'HKDF',false,['deriveBits']);return new Uint8Array(await crypto.subtle.deriveBits({name:'HKDF',hash:'SHA-256',salt,info},key,length*8));}
export async function encryptPush(subscription,payload){if(!validSubscription(subscription))throw Error('invalid_push');const plain=E.encode(JSON.stringify(payload));if(plain.length>3000)throw Error('push_payload_too_large');const ua=decode64(subscription.keys.p256dh),auth=decode64(subscription.keys.auth),pair=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']),as=new Uint8Array(await crypto.subtle.exportKey('raw',pair.publicKey)),publicKey=await crypto.subtle.importKey('raw',ua,{name:'ECDH',namedCurve:'P-256'},false,[]),shared=new Uint8Array(await crypto.subtle.deriveBits({name:'ECDH',public:publicKey},pair.privateKey,256)),salt=crypto.getRandomValues(new Uint8Array(16)),ikm=await hkdf(shared,auth,join(E.encode('WebPush: info\0'),ua,as),32),cek=await hkdf(ikm,salt,E.encode('Content-Encoding: aes128gcm\0'),16),nonce=await hkdf(ikm,salt,E.encode('Content-Encoding: nonce\0'),12),key=await crypto.subtle.importKey('raw',cek,'AES-GCM',false,['encrypt']),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce},key,join(plain,new Uint8Array([2])))),recordSize=new Uint8Array(4);new DataView(recordSize.buffer).setUint32(0,4096);return join(salt,recordSize,new Uint8Array([65]),as,cipher);}
export async function createPushKeys(){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const privateKey=await crypto.subtle.exportKey('jwk',pair.privateKey),publicKey=await crypto.subtle.exportKey('jwk',pair.publicKey);return {privateKey,publicKey:base64url(join(new Uint8Array([4]),decode64(publicKey.x),decode64(publicKey.y)))};}
export async function sendPush(subscription,payload,keys,upstream=fetch,now=Date.now()){if(!validSubscription(subscription))throw Error('invalid_push');const header=base64url(E.encode(JSON.stringify({typ:'JWT',alg:'ES256'}))),claims=base64url(E.encode(JSON.stringify({aud:new URL(subscription.endpoint).origin,exp:Math.floor(now/1000)+3600,sub:'https://mferent80-source.github.io/premarket_scanner.html/app/'}))),signing=header+'.'+claims,key=await crypto.subtle.importKey('jwk',keys.privateKey,{name:'ECDSA',namedCurve:'P-256'},false,['sign']),signature=base64url(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,E.encode(signing))),body=await encryptPush(subscription,payload),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await upstream(subscription.endpoint,{method:'POST',redirect:'manual',signal:controller.signal,headers:{Authorization:'vapid t='+signing+'.'+signature+', k='+keys.publicKey,'Content-Encoding':'aes128gcm','Content-Type':'application/octet-stream',TTL:'300',Urgency:'normal'},body});return {state:r.status===404||r.status===410?'expired':r.status>=200&&r.status<300?'accepted':'failed',status:r.status,at:now};}catch{return {state:'failed',status:null,at:now};}finally{clearTimeout(timer);}}
