(function(g){
'use strict';
const R=g.HoldingsAccountRisk,S=g.HoldingsStrategy,F=g.HoldingsForecast,V=g.HoldingsStrategyView,memory=new Map(),drafts=new Map(),messages=new Map(),examples=new Map();let context=null;
const real=g.HoldingsForecastStorage.create({getItem:k=>localStorage.getItem(k),setItem:(k,v)=>localStorage.setItem(k,v)},{mergeForKey:k=>R.identity(k)?R.merge:null,onChange:refresh});
const demo={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v),status:()=>({state:'demo',message:'DATE FICTIVE · exemplu izolat de contul tău.'})},storage=()=>context?.demo?demo:real;
const LABELS={perDecisionPct:'Risc suplimentar / valoarea contului',totalStopPct:'Risc total la stop / valoarea contului',instrumentPct:'Concentrare maximă pe instrument'},TITLES={'within-limits':'În limitele tale · estimare',blocked:'Depășește limitele tale',incomplete:'Verificare incompletă','no-position':'Verdictul nu adaugă o poziție'};
function refresh(){g.HoldingsNeuralUI?.refresh();}
function setContext(c){context=c;}
function identity(p){return g.HoldingsStrategyUI.identity(p);}
function account(e){if(context?.demo){const x=examples.get(e.scope);return x?{snapshot:x.snapshot,matches:true,notes:x.notes}: {snapshot:context.snapshot,matches:true,notes:Object.fromEntries(context.positions.map(p=>[p.ticker,context.note?.(p)||{}]))};}const selected=g.T212Snapshot?.read(context?.environment||'live'),matches=!!selected&&selected[0]===e.scope&&context?.scope===e.scope;return {snapshot:matches?selected[1]:null,matches,notes:Object.fromEntries((matches&&Array.isArray(selected[1].positions)?selected[1].positions:[]).map(p=>[p.ticker,context.note?.(p)||{}]))};}
function settings(e,currency){const k=R.settingsKey(e,currency);if(!k)return R.defaults();const raw=storage().getItem(k),s=raw===null?R.defaults():JSON.parse(raw);if(!R.validSettings(s))throw Error('Limite incompatibile; copia existentă este păstrată.');return s;}
async function restore(p,{identity:e=identity(p)}={}){if(!context||context.demo||!F.identity(e))return;const a=account(e),k=R.settingsKey(e,a.snapshot?.summary?.currency);await Promise.all([R.key(e),k].filter(Boolean).map(k=>real.load(k)));}
function input(e){const a=account(e);return R.prepare(a.snapshot,a.notes,settings(e,a.snapshot?.summary?.currency),a.matches);}
function capture(p,decision,{identity:e=identity(p),now=Date.now()}={}){
 if(!context||R.key(identity(p))!==R.key(e))return {ok:false,error:'Contul sau instrumentul s-a schimbat.'};
 try{const st=storage(),before=st.getItem(R.key(e)),d=R.document(before,e,now);if(d.entries.some(r=>r.id===decision.id))return {ok:true,duplicate:true};const entry=R.project(decision,e,input(e),now);if(!entry)throw Error('Verificarea poate fi fixată doar la capturarea unei decizii noi.');const raw=JSON.stringify({version:R.VERSION,entries:[...d.entries,entry]});R.document(raw,e,now);st.setItem(R.key(e),raw);messages.set(R.key(e),'Prima verificare a contului a fost fixată lângă decizie: '+TITLES[entry.result.state]+'.');return {ok:true,saved:true,state:entry.result.state};}
 catch(error){messages.set(R.key(e),'Verificarea contului nu a fost păstrată: '+error.message);return {ok:false,error:error.message};}
}
function current(p,decision){const e=identity(p);try{const a=input(e),entries=R.document(storage().getItem(R.key(e)),e).entries,k=R.settingsKey(e,a.snapshot?.summary?.currency);return {ok:true,identity:e,input:a,entries,result:R.evaluate(a,decision,e),storage:storage().status?.(R.key(e)),limitsStorage:k?storage().status?.(k):null};}catch(error){return {ok:false,identity:e,entries:[],error:error.message};}}
function saveSettings(p,s){const e=identity(p);try{const a=account(e),k=R.settingsKey(e,a.snapshot?.summary?.currency);if(!k)throw Error('Moneda contului lipsește; sincronizează Trading 212.');settings(e,a.snapshot.summary.currency);if(!R.validSettings(s))throw Error('Introdu fiecare limită între 0 și 100%, mai mare decât zero.');storage().setItem(k,JSON.stringify(s));drafts.delete(k);messages.set(R.key(e),'Limite salvate pentru acest cont și această monedă. Verificările păstrate la decizie rămân fixe.');refresh();return {ok:true};}catch(error){messages.set(R.key(e),error.message);refresh();return {ok:false,error:error.message};}}
function simulation(p){if(!context?.demo||!p)return false;const e=identity(p),now=Date.now(),positions=context.positions.map(p=>({ticker:p.ticker,quantity:p.quantity,currentPrice:p.currentPrice,instrumentCurrency:p.instrumentCurrency,currency:'USD',value:p.quantity*p.currentPrice})),invested=positions.reduce((s,p)=>s+p.value,0),snapshot={environment:'synthetic',fetchedAt:new Date(now).toISOString(),summary:{currency:'USD',totalValue:10000,available:10000-invested,reserved:0,invested},positions},notes=Object.fromEntries(positions.map(p=>[p.ticker,{stop:p.currentPrice*.95,stopCurrency:p.instrumentCurrency}]));
 examples.set(e.scope,{snapshot,notes});demo.setItem(R.settingsKey(e,'USD'),JSON.stringify({version:R.SETTINGS,perDecisionPct:1,totalStopPct:5,instrumentPct:30}));
 const asOf=g.DailySeries.date(now-60000,'America/New_York'),price=p.currentPrice,forecast=F.project({model:'verdict',modelVersion:F.VERSIONS.verdict,trainedAt:now,state:'up',source:{t:now-60000,asOf,timezone:'America/New_York',closeMinutes:960,close:price,atrPct:2},estimate:{title:'Verdict inventat pentru verificarea riscului',verdictState:'up',direction:2,sourceFingerprint:'fictional-risk-example',reasons:['Exemplu fictiv, fără predicție reală.'],cards:Object.entries(F.VERSIONS).filter(([id])=>id!=='verdict').map(([id,version])=>({id,version,state:'research',value:'Exemplu fictiv'}))}},e,now),decision=S.project(forecast,e,S.defaults(),now);
 if(!decision)return false;examples.get(e.scope).decision=decision;capture(p,decision,{identity:e,now});messages.set(R.key(e),'EXEMPLU · sold, poziții, stopuri, limite și verdict inventate. Nu sunt datele sau rezultatele contului tău.');refresh();return true;
}
function renderResult(r,{frozen=false}={}){const esc=V.esc,fmt=V.fmt,c=esc(r.currency||'monedă necunoscută'),amount=v=>fmt(v)+' '+c;
 return '<div class="account-risk-result" data-risk-state="'+r.state+'"><h5>'+esc(TITLES[r.state])+'</h5><p class="strategy-meta">'+(frozen?'Snapshot la prima decizie: ':'Snapshot citit acum: ')+esc(r.snapshotAt||'indisponibil')+'</p><div class="strategy-metrics">'+[['Sold disponibil',amount(r.available)],['Risc la stop · acoperire '+r.stopCoverage+'/'+r.positions,amount(r.totalStopRisk)],['Risc suplimentar · cu costuri',amount(r.proposal?.risk)],['Buget suplimentar maxim · estimat',amount(r.capacity?.accountAmount)]].map(([l,v])=>'<div><small>'+esc(l)+'</small><b>'+v+'</b></div>').join('')+'</div>'+(r.totalStopRisk===null&&r.knownStopRisk!==null?'<p class="strategy-meta">Sumă parțială la stopurile calculabile: '+amount(r.knownStopRisk)+'. Riscul total rămâne necunoscut.</p>':'')+(r.proposal?'<p class="strategy-meta">Scenariu 1.000 USD ≈ '+amount(r.proposal.amount)+' · concentrarea ar deveni '+fmt(r.proposal.concentration,1)+'% · preț de referință din snapshot '+fmt(r.proposal.price)+' USD · stop estimativ '+fmt(r.proposal.stop)+' USD. '+(r.capacity?'Bugetul maxim echivalează cu aproximativ '+fmt(r.capacity.quoteAmount)+' USD.':'')+'</p>':'')+'<ul class="account-risk-checks">'+r.checks.map(x=>'<li data-check="'+x.state+'"><b>'+(x.state==='pass'?'În limită':x.state==='fail'?'Depășit':'Necunoscut')+'</b> · '+esc(x.label)+': '+fmt(x.value)+(x.id==='concentration'?'%':' '+c)+' / limită '+fmt(x.limit)+(x.id==='concentration'?'%':' '+c)+'</li>').join('')+'</ul>'+(r.reasons.length?'<ul class="account-risk-reasons">'+r.reasons.map(x=>'<li>'+esc(x)+'</li>').join(''):'')+'</div>';
}
function markup(p,i,decision){
 const e=identity(p),example=context?.demo?examples.get(e.scope):null;if(example?.decision?.forecast.symbol===e.symbol)decision=example.decision;
 const x=current(p,decision),a=account(e),sk=R.settingsKey(e,a.snapshot?.summary?.currency),draft=drafts.get(sk)||x.input?.settings||R.defaults(),esc=V.esc,last=x.entries.at(-1);
 return '<section class="account-risk" id="model-lab-'+i+'-account-risk" tabindex="-1" aria-label="Verificarea riscului contului"><div class="strategy-heading"><div><span class="eyebrow">CONT → LIMITĂ DE RISC'+(context.demo?' · DATE FICTIVE':'')+'</span><h4>Se încadrează alocarea în cont?</h4></div><span class="tag">Estimare · fără ordine</span></div><p class="strategy-meta">Verificăm suplimentarea de 1.000 USD peste poziția existentă. Stopurile de reevaluare sunt introduse de tine, în moneda instrumentului; salvează din nou reperele vechi pentru confirmarea monedei.</p><p role="status" class="strategy-meta">'+esc(messages.get(R.key(e))||'Limitele se aplică acestui cont, în moneda sa. O verificare incompletă nu confirmă încadrarea.')+'</p>'+(!x.ok?'<p class="strategy-status">'+esc(x.error)+'</p>':renderResult(x.result))+(x.limitsStorage?'<p class="strategy-meta" role="status">Limite: '+esc(x.limitsStorage.message)+'</p>':'')+'<details class="strategy-details"><summary>Limitele mele · '+esc(a.snapshot?.summary?.currency||'monedă indisponibilă')+'</summary><p class="strategy-meta">Procente din valoarea totală raportată de broker. Nu există limite recomandate implicit. Limitele sunt comune deținerilor acestui cont și acestei monede.</p><div class="account-risk-fields">'+R.fields.map(field=>'<label for="risk-'+i+'-'+field+'">'+esc(LABELS[field])+' (%)<input id="risk-'+i+'-'+field+'" type="number" min="0.01" max="100" step="any" inputmode="decimal" data-risk-index="'+i+'" data-risk-field="'+field+'" value="'+esc(draft[field]??'')+'" '+(!x.ok||!sk?'disabled':'')+'></label>').join('')+'</div><button data-risk-save="'+i+'" '+(!x.ok||!sk?'disabled':'')+'>Salvează limitele contului</button></details>'+(last?'<details class="strategy-details"><summary>Verificarea păstrată la prima decizie · EOD '+esc(last.decision.forecast.source.asOf)+'</summary><p class="strategy-meta">Limite fixate: suplimentar '+V.fmt(last.input.settings.perDecisionPct)+'% · total la stop '+V.fmt(last.input.settings.totalStopPct)+'% · instrument '+V.fmt(last.input.settings.instrumentPct)+'%. '+esc(x.storage?.message||'')+'</p>'+renderResult(last.result,{frozen:true})+'</details>':'<p class="strategy-meta">Verificările de la captură încep cu următoarele decizii; istoricul vechi nu este completat retrospectiv.</p>')+'<div class="strategy-actions"><button data-risk-export="'+i+'" '+(!last?'disabled':'')+'>Exportă verificările contului</button>'+(context.demo?'<button data-risk-demo="'+i+'">Încarcă exemplul de risc · fictiv</button>':'<a href="../broker/">Reverifică Trading 212</a>')+'</div><p class="strategy-meta">Prețul următoarei deschideri este necunoscut. Recalculează la prețul de intrare; disponibilul poate varia. Sumele rezervate blochează o verificare completă. Risc la stop ≠ pierdere maximă: gapurile, evoluția FX și costurile pozițiilor existente nu sunt incluse. Simularea și verdictul AI rămân neschimbate.</p></section>';
}
function bind(){const position=i=>context?.positions[Number(i)],draft=p=>{const e=identity(p),a=account(e),k=R.settingsKey(e,a.snapshot?.summary?.currency);if(!k)throw Error('Moneda contului lipsește.');if(!drafts.has(k))drafts.set(k,copy(settings(e,a.snapshot.summary.currency)));return drafts.get(k);};
 for(const input of document.querySelectorAll('[data-risk-field]'))input.oninput=()=>{const p=position(input.dataset.riskIndex);if(p)draft(p)[input.dataset.riskField]=input.value===''?null:Number(input.value);};
 for(const b of document.querySelectorAll('[data-risk-save]'))b.onclick=()=>{const p=position(b.dataset.riskSave);if(p)saveSettings(p,draft(p));};
 for(const b of document.querySelectorAll('[data-risk-demo]'))b.onclick=()=>simulation(position(b.dataset.riskDemo));
 for(const b of document.querySelectorAll('[data-risk-export]'))b.onclick=()=>{const p=position(b.dataset.riskExport),x=current(p,null);if(x.ok&&x.entries.length)g.HoldingsNeuralUI.exportReport({symbol:x.identity.symbol,kind:x.identity.kind,asOf:x.entries.at(-1).decision.forecast.source.asOf,result:R.exportReport(x.entries,x.identity)});};
}
function copy(x){return JSON.parse(JSON.stringify(x));}
g.HoldingsAccountRiskUI={setContext,restore,capture,current,saveSettings,simulation,markup,bind};
})(typeof window!=='undefined'?window:globalThis);
