(function(g){
'use strict';
const M=g.HoldingsForecastMonitor,F=g.HoldingsForecast,preferences=new Map(),seeded=new Set();let context=null,generation=0,batch=null,notice='';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),date=t=>Number.isFinite(t)?new Date(t).toLocaleString('ro-RO',{dateStyle:'short',timeStyle:'short'}):'—';
const scope=()=>context.scope+'|'+(context.demo?'synthetic':'market');
function prefs(){if(!preferences.has(scope()))preferences.set(scope(),{model:'quantile',filter:'all',query:'',sort:'priority'});return preferences.get(scope());}
function report(){return M.build(context.positions.map(p=>g.HoldingsForecastUI.snapshot(p)),{scope:context.scope,kind:context.demo?'synthetic':'market',...prefs()});}
function setContext(c){if(!context||context.scope!==c.scope||context.demo!==c.demo){generation++;if(batch)batch.stopped=true;batch=null;notice='';}context=c;render();}
function progress(){if(!batch)return notice||'Verifică toate registrele deținute, inclusiv instrumentele ascunse de filtre. Estimările originale rămân fixe.';const b=batch,counts=b.checked+' surse procesate · '+b.errors+' erori · '+b.skipped+' omise';return (b.active?'Verificare '+b.done+' / '+b.total+' · ':b.stopped?'Verificare oprită · ':'Verificare încheiată · ')+counts+(b.active&&b.stopped?'. Cererea curentă se poate încheia; cererile următoare sunt oprite.':'');}
function render(){
 const host=document.getElementById('forecastMonitor');if(!host||!context)return;
 const r=report(),p=prefs(),names=g.HoldingsForecastUI.NAMES,active=host.contains(document.activeElement)?document.activeElement:null,focused=active?.id,selection=active?.selectionStart,open=host.querySelector('details')?.open;
 const options=(xs,value)=>Object.entries(xs).map(([id,name])=>'<option value="'+id+'" '+(id===value?'selected':'')+'>'+esc(name)+'</option>').join('');
 host.innerHTML='<div class="forecast-monitor-heading"><div><span class="eyebrow">PORTOFOLIU · PREDICȚII VS. REALITATE</span><h3>Monitorizarea modelelor</h3><p>Rezultate pe deținere. Vezi unde lipsesc dovezile și ce merită revizuit.</p></div><span class="tag">'+(context.demo?'SIMULARE':'Local · acest dispozitiv')+'</span></div>'+(context.demo?'<p class="forecast-demo">Date fictive și estimări ilustrative. Acest demo nu măsoară performanța reală a modelelor.</p>':'')+
 '<div class="forecast-monitor-stats">'+[['Dețineri',r.totals.positions],['Cu rezultate · model ales',r.totals.withResults],['De revizuit',r.totals.review],['Cu estimări în așteptare',r.totals.waiting],['Verificare restantă',r.totals.due]].map(([name,value])=>'<div><small>'+name+'</small><b>'+value+'</b></div>').join('')+'</div>'+
 '<div class="forecast-monitor-toolbar"><label>Model<select id="forecastMonitorModel">'+options(names,p.model)+'</select></label><label>Stare<select id="forecastMonitorFilter">'+options({all:'Toate deținerile',review:'De revizuit',due:'Verificare restantă',waiting:'Cu estimări în așteptare',missing:'Fără estimări',ready:'Cu rezultate'},p.filter)+'</select></label><label>Caută ticker<input id="forecastMonitorQuery" type="search" maxlength="100" autocomplete="off" value="'+esc(p.query)+'" placeholder="Ex. AAPL"></label><label>Ordine<select id="forecastMonitorSort">'+options({priority:'Prioritate',ticker:'Ticker A–Z',sample:'Mai multe rezultate'},p.sort)+'</select></label></div>'+
 '<div class="forecast-monitor-actions"><button class="primary" id="forecastMonitorCheck" '+(!r.rows.some(x=>x.hasRegistry)||batch?.active?'disabled':'')+'>'+(context.demo?'Verifică simularea':'Verifică portofoliul')+'</button>'+(batch?.active?'<button id="forecastMonitorStop" '+(batch.stopped?'disabled':'')+'>Oprește verificarea</button>':'')+'<button id="forecastMonitorExport" '+(!r.rows.length?'disabled':'')+'>Exportă raportul</button>'+(context.demo?'<button id="forecastMonitorDemo">Încarcă simularea portofoliului</button>':'')+'</div><p class="forecast-monitor-status meta" role="status" aria-live="polite">'+esc(progress())+'</p>'+(batch?.active?'<progress aria-label="Progres verificare portofoliu" max="'+Math.max(1,batch.total)+'" value="'+batch.done+'"></progress>':'')+
 '<div class="forecast-monitor-list-heading"><b>'+esc(names[r.model])+'</b><small>'+r.visible.length+' / '+r.totals.positions+' dețineri · orizont de 5 sesiuni</small></div><div class="forecast-monitor-list">'+(r.visible.length?r.visible.map(row=>'<article class="forecast-monitor-row" data-state="'+row.state+'"><div class="forecast-monitor-identity"><strong>'+esc(row.symbol||row.ticker)+'</strong><small>'+esc(row.currency||'Monedă neverificată')+'</small><span class="forecast-monitor-badge">'+esc(row.checkState==='checking'?'Se verifică…':row.label)+'</span></div><div class="forecast-monitor-evidence"><b>'+(row.report?row.report.n+' orizonturi separate':'Evaluare blocată')+'</b><p>'+esc(row.report?g.HoldingsForecastUI.overview(row.report):'Nu calculăm rezultate pe date incompatibile.')+'</p><p class="forecast-monitor-reason">'+esc(row.reason)+'</p><small>'+(row.report?row.report.all+' finalizate · '+row.report.pending+' în așteptare · '+row.report.unverifiable+' excluse':'Niciun rezultat nou calculat')+'</small></div><div class="forecast-monitor-meta"><small>Ultima estimare <b>'+esc(row.lastForecast||'—')+'</b></small><small>Verificare registru <b>'+esc(date(row.lastCheck))+'</b></small><small>Analiză EOD actuală <b>'+esc(row.asOf||'Indisponibilă')+'</b></small>'+(row.freshness?.expectedAsOf?'<small'+(row.freshness.needsCheck?' class="forecast-monitor-due"':'')+'>EOD așteptat <b>'+esc(row.freshness.expectedAsOf)+'</b></small><small>EOD verificat <b>'+esc(row.freshness.checkedAsOf||'Neefectuat')+'</b></small>':'')+'<button data-monitor-ledger="'+esc(row.ticker)+'">Vezi registrul →</button></div></article>').join(''):'<p class="empty">'+(r.rows.length?'Nicio deținere nu corespunde filtrelor.':'Conectează Trading 212 sau încarcă demo-ul pentru dețineri. Modelele trebuie calculate înainte să existe estimări de urmărit.')+'</p>')+'</div>'+
 '<details class="forecast-monitor-rules"><summary>Cum interpretăm raportul</summary><p>'+esc(r.limits)+'</p><p>Sub 20 orizonturi separate: eșantion mic. Acoperirea sub 70%, performanța sub reper și deteriorarea între două blocuri de 20 sunt semnale descriptive de revizuire, nu teste statistice sau recomandări de tranzacționare. HMM și Isolation Forest descriu contextul, fără acuratețe predictivă.</p><p>Verificarea automată pornește la deschiderea filei Rapoarte, cel mult o dată pentru sesiunea EOD disponibilă în această vizită. Butonul permite reîncercarea. «Verificare restantă» compară ultima verificare cu EOD-ul așteptat în fusul bursei, inclusiv după redeschiderea aplicației. Weekendul și o sesiune încă neîncheiată nu cer o actualizare nouă. Calendarul complet al sărbătorilor nu este confirmat; sursa poate refuza verificarea într-o zi fără tranzacționare. Cinci sesiuni efective sunt necesare pentru rezultat; estimările în așteptare nu sunt pierderi.</p><p>Raportul include deținerile actuale și istoricul păstrat pe acest dispozitiv. Înregistrările pozițiilor vândute rămân salvate separat. Lipsa unei analize actuale nu transformă rezultatele istorice în estimări noi. Exportul include toate deținerile, indiferent de filtre, fără cantități, sold, chei API sau identificatorul contului.</p></details>';
 if(open!==undefined)host.querySelector('details').open=open;
 for(const [id,key,event] of [['forecastMonitorModel','model','onchange'],['forecastMonitorFilter','filter','onchange'],['forecastMonitorQuery','query','oninput'],['forecastMonitorSort','sort','onchange']])host.querySelector('#'+id)[event]=e=>{prefs()[key]=e.target.value;render();};
 host.querySelector('#forecastMonitorCheck').onclick=()=>context.demo?demo():checkAll(true);
 const stop=host.querySelector('#forecastMonitorStop');if(stop)stop.onclick=cancel;
 host.querySelector('#forecastMonitorExport').onclick=exportReport;
 const seed=host.querySelector('#forecastMonitorDemo');if(seed)seed.onclick=()=>demo();
 for(const b of host.querySelectorAll('[data-monitor-ledger]'))b.onclick=()=>{if(!g.HoldingsLayout.openModelLedger(b.dataset.monitorLedger)){notice='Deținerea nu mai este disponibilă. Reîncarcă raportul.';render();}};
 if(focused){const target=host.querySelector('#'+focused);target?.focus({preventScroll:true});if(Number.isInteger(selection)&&target?.type==='search')target.setSelectionRange(selection,selection);}
}
async function checkAll(manual=false){
 if(!context||context.demo||batch?.active)return;
 const queue=context.positions.map(p=>g.HoldingsForecastUI.snapshot(p)).filter(x=>F.identity(x.identity)&&x.ledger.ok&&x.ledger.entries.length).map(x=>({ticker:x.identity.ticker,key:F.key(x.identity)})),token=generation;
 if(!queue.length)return;
 const b=batch={active:true,stopped:false,total:queue.length,done:0,checked:0,errors:0,skipped:0};render();
 try{for(const target of queue){if(b.stopped||token!==generation||batch!==b)break;const p=context.positions.find(p=>p.ticker===target.ticker);let out={state:'ignored'};
   if(p&&F.key(g.HoldingsForecastUI.snapshot(p).identity)===target.key){try{out=await g.HoldingsForecastUI.check(p,manual)||out;}catch{out={state:'error'};}}
   if(token!==generation||batch!==b)break;b.done++;if(out.state==='checked')b.checked++;else if(['error','blocked'].includes(out.state))b.errors++;else b.skipped++;render();
  }}finally{b.active=false;if(token===generation&&batch===b)render();}
 return {total:b.total,done:b.done,checked:b.checked,errors:b.errors,skipped:b.skipped,stopped:b.stopped};
}
function cancel(){if(batch?.active){batch.stopped=true;render();}}
function exportReport(){if(!context)return;const r=report(),{visible,query,...result}=r;g.HoldingsNeuralUI.exportReport({symbol:'PORTOFOLIU',kind:r.kind,asOf:new Date(r.generatedAt).toISOString().slice(0,10),result});}
function demo({auto=false}={}){if(!context?.demo||!context.positions.length||!context.positions.every(p=>context.model(p)))return false;const key=scope();if(auto&&seeded.has(key))return false;for(const p of context.positions)g.HoldingsForecastUI.simulation(p,{update:false});seeded.add(key);if(auto)prefs().model='neural';notice='Simulare încărcată pentru toate deținerile. Cele 24 de orizonturi per model sunt ilustrative.';render();if(auto)g.HoldingsLayout.showPage('reports');return true;}
if(typeof document!=='undefined')document.addEventListener('click',e=>{if(e.target.closest('[data-workspace-tab="reports"]'))queueMicrotask(()=>{render();void checkAll(false);});});
g.HoldingsForecastMonitorUI={setContext,render,checkAll,cancel,exportReport,demo};
})(typeof window!=='undefined'?window:globalThis);
