(function(g){
'use strict';
const G=g.HoldingsGarch,reports=g.HoldingsModelStorage.create({getItem:k=>localStorage.getItem(k),setItem:(k,v)=>localStorage.setItem(k,v)}),errors=new Map();let context=null,job=null,serial=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString('ro-RO',{maximumFractionDigits:d,minimumFractionDigits:d}):'—',day=t=>new Date(t).toISOString().slice(0,10);
const key=p=>'tt_holdings_garch_v1:'+encodeURIComponent(context.scope)+'|'+encodeURIComponent(p.ticker);
const blocked=()=>!!job||['HoldingsNeuralUI','HoldingsHMMUI','HoldingsIsolationUI','HoldingsQuantileUI'].some(name=>g[name]?.busy());
function read(p){try{return reports.read(key(p),context.demo);}catch{return null;}}
function usable(r,p,m,now=Date.now()){try{return !!r&&r.symbol===context.symbol(p)&&r.currency===m?.currency&&r.asOf===m?.asOf&&r.kind===(context.demo?'synthetic':'market')&&r.result?.current?.t===r.sourceTime&&g.DailySeries.date(r.sourceTime,r.timezone)===r.asOf&&Number.isFinite(r.sourceClose)&&Math.abs(r.sourceClose-m.price)<=1e-6*Math.max(1,m.price)&&Math.abs(r.result.current.close-m.price)<=1e-6*Math.max(1,m.price)&&Number.isFinite(r.trainedAt)&&r.trainedAt<=now&&now-r.trainedAt<=1800000&&G.valid(r.result,now);}catch{return false;}}
function inspect(p){const record=read(p),ok=usable(record,p,context.model(p));return {record,usable:ok,assessment:ok?G.assess(record.result):null,persistence:reports.inspect(key(p),context.demo,ok)};}
function refresh(){g.HoldingsNeuralUI?.refresh();}
function cancel(update=true){if(job){if(update)errors.set(job.key,'Analiză GARCH anulată. Raportul anterior este păstrat.');job.worker?.terminate();clearTimeout(job.timeout);job.resolve({state:'cancelled'});job=null;serial++;}if(update)refresh();}
function setContext(c){if(context&&(context.scope!==c.scope||context.demo!==c.demo))cancel(false);if(job){const p=c.positions.find(p=>p.ticker===job.ticker),m=p?c.model(p):null;if(!p||c.symbol(p)!==job.symbol||m?.currency!==job.currency||m?.asOf!==job.asOf||m?.price!==job.price)cancel(false);}context=c;}
function markup(p,i,inspection=inspect(p)){
 const {record:r,usable:ok,assessment:a}=inspection,result=ok?r.result:null,m=context.model(p),active=job?.ticker===p.ticker,busy=blocked();
 const number=(label,value)=>'<div><small>'+label+'</small><b>'+value+'</b></div>';
 let html=`<section class="garch-card" id="model-lab-${i}-garch" data-garch-host="${i}" tabindex="-1"><div class="hmm-heading"><div><span class="eyebrow">AL ȘASELEA MODEL · VOLATILITATE</span><h4>GARCH(1,1)</h4><p>Amplitudinea estimată a fluctuațiilor la 5 și 20 de sesiuni, comparată cu nivelul istoric al stockului.</p></div><span class="tag">${context.demo?'Date fictive':'Experimental'}</span></div><div class="hmm-controls"><button class="primary" data-garch-train="${i}" ${busy||!m||!context.symbol(p)?'disabled':''}>${r?'Reestimează volatilitatea':'Estimează volatilitatea'}</button>${active?'<button data-garch-cancel>Oprește GARCH</button><progress data-garch-progress max="'+G.CONFIG.iterations+'" value="0"></progress>':''}</div><p class="meta" role="status" aria-live="polite" data-garch-status>${esc(errors.get(key(p))||(active?'Calculez volatilitatea în fundal…':busy?'Aștept finalizarea modelului activ.':!m?'Rulează mai întâi analiza EOD.':r&&!ok?'Raport expirat sau incompatibil. Reestimează pe sesiunea curentă.':'Trei ferestre de test, varianță constantă și EWMA ca repere.'))}</p>`;
 if(ok&&inspection.persistence?.message)html+='<p class="model-storage-note" role="status">'+esc(inspection.persistence?.message)+'</p>';
 if(result){
  html+=`<div class="hmm-verdict ${a.state==='descriptive'?'':'warn'}"><b>${a.state==='drift'?'Estimare ascunsă':a.state==='descriptive'?'Volatilitate · '+esc(G.level(result)):'Volatilitate exploratorie'}</b><p>${esc(a.message)}</p><small>EOD ${esc(r.asOf)} · procente ale randamentului logaritmic · fără direcție de preț</small></div>`;
  if(a.state!=='drift')html+='<div class="garch-metrics">'+result.current.horizons.map(h=>number('Fluctuație cumulată · '+h.horizon+' sesiuni',fmt(h.cumulativePct)+'%')+number('Medie zilnică echivalentă · '+h.horizon+' sesiuni',fmt(h.dailyEquivalentPct)+'% · '+fmt(h.ratio)+'× istoric')).join('')+'</div><p class="meta">Nivel istoric zilnic în antrenare: '+fmt(result.current.usualDailyPct)+'%. Fluctuația cumulată este rădăcina sumei varianțelor condiționale. Nu este pierdere maximă, limită de preț, interval de încredere sau probabilitate de profit.</p>';
  html+='<details class="neural-details"><summary>Testele la 5 și 20 de sesiuni</summary><p class="meta">Avantaj la 5 sesiuni: '+result.walk.wins[5]+' / '+result.folds.length+' ferestre; la 20 sesiuni: '+result.walk.wins[20]+' / '+result.folds.length+'. Scor QLIKE mai mic este mai bun; valorile pot fi negative. Scorurile se compară numai în același orizont.</p><div class="neural-table-wrap"><table><thead><tr><th>Test · EOD</th><th>Orizont · blocuri separate</th><th>GARCH</th><th>Constant</th><th>EWMA</th></tr></thead><tbody>'+result.folds.map(f=>G.HORIZONS.map(h=>{const t=f.metrics.horizons[h];return '<tr><td>'+day(f.periods.test.from)+' → '+day(f.periods.test.to)+'</td><td>'+h+' sesiuni · '+t.n+'</td><td>'+fmt(t.model,3)+'</td><td>'+fmt(t.constant,3)+'</td><td>'+fmt(t.ewma,3)+'</td></tr>';}).join('')).join('')+'</tbody></table></div><p class="meta">Parametrii sunt estimați numai înaintea fiecărui test; starea de volatilitate se actualizează cu observațiile deja cunoscute. Testele nu selectează parametri. Blocurile nu au randamente comune, dar pot rămâne corelate.</p><p class="meta">'+result.folds.map((f,i)=>'F'+(i+1)+': antrenare până la '+day(f.periods.train.to)+' · '+f.periods.train.n+' randamente · '+(f.model.converged?'căutare numerică terminată':'limită de iterații')+(f.model.boundary?' · parametru la limita căutării':'')).join('<br>')+'</p><button data-garch-export="'+i+'">Descarcă raportul GARCH</button></details>';
 }
 return html+'<details class="neural-details"><summary>Metoda GARCH și limitele ei</summary><p>Randamente logaritmice zilnice. Model GARCH(1,1) cu medie fixă din antrenare: varianța următoare = ω + α × șocul anterior² + β × varianța anterioară. Parametri pozitivi, α + β &lt; 0,995, estimați prin cvasi-verosimilitate Gaussiană cu trei porniri fixe. Căutarea este limitată și verificată; nu presupunem distribuție Gaussiană exactă a pieței.</p><p>Repere: varianța istorică constantă și EWMA cu λ = 0,94 fixat înaintea testelor. Interpretarea cere trei ferestre, minimum 20 blocuri separate per orizont în total, avantaj QLIKE de minimum 0,02 față de ambele repere în cel puțin două ferestre și în cea recentă, fără limite numerice atinse. GARCH nu votează direcția; numai o estimare validată poate adăuga prudență la Verdict.</p><p>Ridicată = minimum 1,5× nivelul istoric; foarte ridicată = minimum 2,5×, la orizontul de 5 sesiuni. Acestea sunt praguri descriptive fixe, fără garanții de risc. Știrile, earnings, gapurile, FX și riscul portofoliului se verifică separat. GARCH simetric nu modelează separat șocurile negative.</p><p><a href="../tools/holdings-garch-validation.html" target="_blank" rel="noopener">Verificarea publică și metodologia GARCH</a></p></details><a class="model-back" data-model-jump="summary" href="#model-lab-'+i+'-summary">Sinteză ↑</a></section>';
}
function finish(current,error,result){
 if(job!==current||context.scope!==current.scope||context.demo!==current.demo)return;
 current.worker?.terminate();clearTimeout(current.timeout);job=null;const reportKey=current.key;let persistence=current.demo?'demo':'local';
 if(!error)try{
  if(!G.valid(result)||result.current.t!==current.sourceTime||Math.abs(result.current.close-current.price)>1e-6*Math.max(1,current.price))throw Error('Raport neverificabil sau închidere EOD diferită.');
  const record={symbol:current.symbol,currency:current.currency,asOf:current.asOf,kind:current.demo?'synthetic':'market',sourceTime:current.sourceTime,sourceClose:current.price,sourceFingerprint:current.sourceFingerprint,timezone:current.timezone,closeMinutes:current.closeMinutes,trainedAt:Date.now(),result};
  persistence=reports.save(reportKey,record,current.demo);errors.delete(reportKey);
 }catch(e){error='Raport GARCH respins: '+e.message;}
 if(error)errors.set(reportKey,error);
 else try{g.HoldingsForecastUI?.capture(context.positions.find(p=>p.ticker===current.ticker));}catch{reports.captureFailed(reportKey,current.demo);}
 current.resolve?.({state:error?'error':'ready',error:error||null,persistence:error?null:persistence});refresh();

}
async function train(p,options={}){
 if(!p||blocked())return {state:'error',error:'Un alt model rulează deja.'};const m=context.model(p),symbol=context.symbol(p);if(!m||!symbol)return {state:'error',error:'Este necesară analiza EOD și identitatea instrumentului.'};
 const current=job={id:++serial,key:key(p),scope:context.scope,demo:context.demo,ticker:p.ticker,symbol,currency:m.currency,asOf:m.asOf,price:m.price,managed:!!options.managed};current.completion=new Promise(resolve=>current.resolve=resolve);errors.delete(current.key);refresh();
 try{
  let src=options.source;
  if(!src){if(current.demo){const bars=context.demoBars(p.ticker==='FICTIVB_US_EQ'?2:p.ticker==='FICTIVC_US_EQ'?3:0);src={bars,symbol,currency:m.currency,asOf:m.asOf,kind:'synthetic',timezone:'America/New_York',closeMinutes:960};}else{const raw=await D.fetchStock(symbol,{range:'5y',interval:'1d',ttl:0});src={...DailySeries.read(raw,symbol),symbol,kind:'market'};}}
  if(job!==current)return current.completion;
  if(src.symbol!==symbol||src.currency!==m.currency||src.asOf!==m.asOf||src.kind!==(current.demo?'synthetic':'market')||!Array.isArray(src.bars)||!src.bars.length||!Number.isFinite(m.price)||!Number.isFinite(src.bars.at(-1).c)||Math.abs(src.bars.at(-1).c-m.price)>1e-6*Math.max(1,m.price))throw Error('Istoricul GARCH nu corespunde instrumentului, monedei sau închiderii EOD.');
  Object.assign(current,{sourceTime:src.bars.at(-1).t,sourceFingerprint:src.fingerprint||g.HoldingsVerdict?.fingerprint(src.bars),timezone:src.timezone,closeMinutes:src.closeMinutes});
  if(typeof Worker==='undefined')throw Error('Browserul nu oferă analiză în fundal.');current.worker=new Worker('garch-worker.js?v='+G.VERSION);
  current.worker.onmessage=e=>{if(job!==current||e.data.id!==current.id)return;if(e.data.progress){const p=e.data.progress;options.onProgress?.(p);for(const host of document.querySelectorAll('[data-garch-host]'))if(context.positions[Number(host.dataset.garchHost)]?.ticker===current.ticker){host.querySelector('[data-garch-status]').textContent='GARCH · Fereastra '+p.stage+' / '+p.stages+' · Pornire '+p.member+' / '+p.members+' · Iterația '+p.epoch+' / '+p.total;host.querySelector('[data-garch-progress]').value=p.epoch;}}else finish(current,e.data.error,e.data.result);};
  current.worker.onerror=()=>finish(current,'Workerul GARCH nu a putut finaliza estimarea.');current.timeout=setTimeout(()=>finish(current,'GARCH a depășit 120 secunde; raportul nu este utilizat.'),120000);current.worker.postMessage({id:current.id,bars:src.bars,now:Date.now()});
 }catch(e){finish(current,e.message);}return current.completion;
}
function bind(){for(const b of document.querySelectorAll('[data-garch-train]'))b.onclick=()=>train(context.positions[Number(b.dataset.garchTrain)]);for(const b of document.querySelectorAll('[data-garch-cancel]'))b.onclick=()=>cancel();for(const b of document.querySelectorAll('[data-garch-export]'))b.onclick=()=>{const p=context.positions[Number(b.dataset.garchExport)],r=read(p);if(usable(r,p,context.model(p)))g.HoldingsNeuralUI.exportReport(r);};}
g.HoldingsGarchUI={setContext,inspect,markup,bind,cancel,run:(p,options)=>train(p,{...options,managed:true}),cancelManaged:()=>{if(job?.managed)cancel(false);},busy:()=>!!job};
})(typeof window!=='undefined'?window:globalThis);
