(function(g){
'use strict';
const Q=g.HoldingsKNN,N=g.HoldingsNeural,reports=g.HoldingsModelStorage.create({getItem:k=>localStorage.getItem(k),setItem:(k,v)=>localStorage.setItem(k,v)},{onChange:refresh}),errors=new Map(),demoStarted=new Set();let context=null,job=null,serial=0;
const equal=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=1e-6*Math.max(1,Math.abs(a),Math.abs(b));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString('ro-RO',{minimumFractionDigits:d,maximumFractionDigits:d}):'—',day=t=>new Date(t).toISOString().slice(0,10);
const key=p=>'tt_holdings_knn_v1:'+encodeURIComponent(context.scope)+'|'+encodeURIComponent(p.ticker);
function restore(p){return context&&p?reports.restore(key(p),context.demo):Promise.resolve();}
function read(p){try{return reports.read(key(p),context.demo);}catch{return null;}}
function usable(r,p,m,now=Date.now()){try{return !!r&&Number.isFinite(r.sourceTime)&&r.symbol===context.symbol(p)&&r.currency===m?.currency&&r.asOf===m?.asOf&&r.result?.current?.t===r.sourceTime&&g.DailySeries?.date(r.sourceTime,r.timezone)===r.asOf&&equal(r.sourceClose,m?.price)&&equal(r.result.current.close,m?.price)&&r.kind===(context.demo?'synthetic':'market')&&Number.isFinite(r.trainedAt)&&r.trainedAt<=now&&now-r.trainedAt<=1800000&&Q.valid(r.result);}catch{return false;}}
function cancel(update=true){if(job){if(update)errors.set(job.key,'Estimare anulată. Raportul anterior este păstrat.');job.worker?.terminate();clearTimeout(job.timeout);job.resolve?.({state:'cancelled'});job=null;serial++;}if(update)refresh();}
function setContext(c){if(context&&(context.scope!==c.scope||context.demo!==c.demo))cancel(false);if(job){const p=c.positions.find(p=>p.ticker===job.ticker),m=p?c.model(p):null;if(!p||c.symbol(p)!==job.symbol||m?.currency!==job.currency||m?.asOf!==job.asOf||m?.price!==job.price)cancel(false);}context=c;if(!c.demo)for(const p of c.positions)restore(p);}
function refresh(){g.HoldingsNeuralUI?.refresh();}
function inspect(p){const r=read(p),ok=usable(r,p,context.model(p));return {record:r,usable:ok,assessment:ok?Q.assess(r.result):null,persistence:reports.inspect(key(p),context.demo,ok)};}
function markup(p,i,inspection=inspect(p)){
 const m=context.model(p),{record:r,usable:ok,assessment:a}=inspection,active=job?.ticker===p.ticker;
 let html='<section class="quantile-card" data-knn-host="'+i+'" id="model-lab-'+i+'-knn" tabindex="-1"><div class="hmm-heading"><div><span class="eyebrow">AL ȘAPTELEA MODEL · SITUAȚII SIMILARE</span><h4>KNN · vecini istorici</h4><p>Ce s-a întâmplat în cinci sesiuni după situații cu trend, RSI, ATR și volum similare?</p></div><span class="tag">'+(context.demo?'Date fictive':'Experimental')+'</span></div><div class="hmm-controls"><button class="primary" data-knn-train="'+i+'" '+(busy()||!m||!context.symbol(p)?'disabled':'')+'>'+(r?'Recalculează KNN':'Calculează KNN')+'</button>'+(active?'<button data-knn-cancel>Anulează KNN</button><progress data-knn-progress max="3" value="0"></progress>':'')+'</div><p class="meta" role="status" aria-live="polite" data-knn-status>'+esc(errors.get(key(p))||(active?'Compar vecinii în fundal…':!m?'Rulează mai întâi analiza EOD.':r&&!ok?'Raport expirat sau incompatibil. Recalculează KNN.':'Aceleași date OHLCV ca celelalte modele; calcule locale.'))+'</p>';
 if(ok){const x=r.result,c=x.current,t=x.report.test,b=x.report.constant,day=t=>new Date(t).toISOString().slice(0,10);
  html+='<div class="hmm-verdict '+(a.state==='research'?'':'warn')+'"><b>'+esc(a.state==='drift'?'KNN se abține':N.CLASSES[c.classIndex]+' · '+(a.state==='research'?'experimental':'exploratoriu'))+'</b><p>'+esc(a.message)+'</p><small>EOD '+esc(r.asOf)+' · +5 sesiuni · k = '+x.model.k+'</small></div>';
  if(inspection.persistence?.message)html+='<p class="model-storage-note" role="status">'+esc(inspection.persistence.message)+'</p>';
  if(a.state!=='drift')html+='<p class="meta">Frecvențe ale claselor între vecini, cu ajustare Laplace: '+c.support.map((v,k)=>N.CLASSES[k]+' '+fmt(100*v,1)+'%').join(' · ')+'. Procente necalibrate; nu reprezintă probabilitatea profitului.</p>';
  html+='<div class="hmm-test-grid"><div><small>Loss KNN / frecvențe / momentum</small><b>'+fmt(t.loss,3)+' / '+fmt(b.loss,3)+' / '+fmt(x.report.momentum.loss,3)+'</b></div><div><small>Acuratețe echilibrată · test</small><b>'+fmt(t.balanced*100,1)+'%</b></div><div><small>Ferestre cu avantaj</small><b>'+(x.walk.summary?x.walk.summary.wins+' / 3':'Istoric insuficient')+'</b></div></div><details class="neural-details"><summary>Vecinii istorici și verificarea KNN</summary><p class="meta">'+x.model.memory.length+' exemple de referință cu rezultate pe orizonturi separate. Distanță până la al k-lea vecin '+fmt(c.distance,3)+'; limita domeniului '+fmt(x.selection.distanceLimit,3)+'.</p><div class="neural-table-wrap"><table><thead><tr><th>Origine</th><th>Rezultat încheiat</th><th>Clasă observată</th><th>Distanță</th></tr></thead><tbody>'+c.neighbors.map(n=>'<tr><td>'+day(n.t)+'</td><td>'+day(n.end)+'</td><td>'+esc(N.CLASSES[n.y])+'</td><td>'+fmt(n.distance,3)+'</td></tr>').join('')+'</tbody></table></div><p class="meta">Test recent: '+t.n+' exemple zilnice. Control pe orizonturi separate: '+x.report.nonOverlap.test.n+'. Loss mai mic este mai bun. Exemplele zilnice pot fi corelate.</p><ul>'+Object.entries(x.report.periods).map(([k,v])=>'<li>'+esc({train:'Antrenare',validation:'Validare',test:'Test'}[k])+': '+day(v.from)+' → '+day(v.to)+' · '+v.n+' exemple</li>').join('')+'</ul><p class="meta">k selectat din 5 / 9 / 15 numai pe validare. Trei ferestre: '+esc(x.walk.reason||'evaluate cronologic, cu etichete eliminate la granițe')+'.</p><button data-knn-export="'+i+'">Descarcă raportul KNN</button></details>';
 }
 return html+'<details class="neural-details"><summary>Metoda KNN și limite</summary><p>Zece indicatori normalizați numai pe antrenare. Distanță euclidiană; vecini din antrenare, cu rezultate deja încheiate. Orizonturile vecinilor nu se ating și nu se suprapun. Pragurile claselor: ±1 ATR inițial la +5 sesiuni. Testul nu alege k sau limita distanței.</p><p>Avantajul cere loss mai mic cu 0,02 și acuratețe echilibrată mai mare cu 2 puncte procentuale decât frecvențele și momentum. Verdictul direcțional cere avantaj repetat în trei ferestre și pe minimum 50 orizonturi separate, cu clase reprezentate. KNN neconcludent împiedică direcția cumulată; KNN validat care contrazice celelalte estimări produce conflict. Nu intră în calibrarea probabilistică Neural + Boosting.</p></details><a class="model-back" data-model-jump="summary" href="#model-lab-'+i+'-summary">Sinteză ↑</a></section>';
}
function busy(){return !!job||g.HoldingsNeuralUI?.busy()||g.HoldingsGarchUI?.busy()||g.HoldingsHMMUI?.busy()||g.HoldingsIsolationUI?.busy()||g.HoldingsQuantileUI?.busy();}
function finish(current,error,result){
 if(job!==current||context.scope!==current.scope||context.demo!==current.demo)return;
 current.worker?.terminate();clearTimeout(current.timeout);job=null;const reportKey=current.key;let persistence=current.demo?'demo':'local';
 if(!error)try{
  if(!Q.valid(result)||result.current.t!==current.sourceTime||result.current.close!==current.sourceClose)throw Error('Raport neverificabil sau sesiune diferită.');
  const record={symbol:current.symbol,currency:current.currency,kind:current.demo?'synthetic':'market',asOf:current.asOf,sourceTime:current.sourceTime,sourceFingerprint:current.sourceFingerprint,timezone:current.timezone,sourceClose:current.sourceClose,closeMinutes:current.closeMinutes,trainedAt:Date.now(),result};
  persistence=reports.save(reportKey,record,current.demo);errors.delete(reportKey);
 }catch(e){error='Raport KNN respins: '+e.message;}
 if(error)errors.set(reportKey,error);
 else try{g.HoldingsForecastUI?.capture(context.positions.find(p=>p.ticker===current.ticker));}catch{reports.captureFailed(reportKey,current.demo);}
 current.resolve?.({state:error?'error':'ready',error:error||null,persistence:error?null:persistence});refresh();

}
async function train(p,options={}){
 if(!p||job||g.HoldingsNeuralUI?.busy()||g.HoldingsGarchUI?.busy()||g.HoldingsHMMUI?.busy()||g.HoldingsIsolationUI?.busy()||g.HoldingsQuantileUI?.busy())return;const m=context.model(p),symbol=context.symbol(p);if(!m||!symbol)return;
 const current=job={id:++serial,key:key(p),scope:context.scope,ticker:p.ticker,demo:context.demo,symbol,currency:m.currency,asOf:m.asOf,price:m.price,timezone:'America/New_York',closeMinutes:960,managed:!!options.managed,onProgress:options.onProgress};current.completion=new Promise(resolve=>current.resolve=resolve);errors.delete(current.key);refresh();
 try{let bars;if(options.source){const src=options.source;if(src.symbol!==symbol||src.currency!==m.currency||src.asOf!==m.asOf||src.kind!==(current.demo?'synthetic':'market')||!Array.isArray(src.bars)||!src.bars.length||!Number.isFinite(src.bars.at(-1).c)||Number.isFinite(m.price)&&Math.abs(src.bars.at(-1).c-m.price)>1e-6*Math.max(1,m.price))throw Error('Istoricul comun nu corespunde instrumentului, monedei sau închiderii EOD.');bars=src.bars;current.sourceFingerprint=src.fingerprint;current.timezone=src.timezone;current.closeMinutes=src.closeMinutes;}else if(current.demo)bars=N.demoBars(p.ticker==='FICTIVB_US_EQ'?2:0,Date.parse(m.asOf+'T23:59:00Z'));else{const raw=await D.fetchStock(symbol,{range:'5y',interval:'1d',ttl:0}),source=DailySeries.read(raw,symbol);if(source.asOf!==m.asOf||source.currency!==m.currency)throw Error('Istoricul KNN și analiza EOD nu au aceeași sesiune și monedă.');bars=source.bars;if(Number.isFinite(m.price)&&Math.abs(bars.at(-1).c-m.price)>1e-6*Math.max(1,m.price))throw Error('Prețul EOD diferă de analiza deținerii. Actualizează analiza înaintea estimării.');current.timezone=source.timezone;current.closeMinutes=source.closeMinutes;}
  if(job!==current)return current.completion;current.sourceTime=bars.at(-1)?.t;current.sourceClose=bars.at(-1)?.c;current.sourceFingerprint??=g.HoldingsVerdict?.fingerprint(bars);if(typeof Worker==='undefined')throw Error('Browserul nu oferă analiză în fundal.');current.worker=new Worker('knn-worker.js?v='+Q.VERSION);
  current.worker.onmessage=e=>{if(job!==current||e.data.id!==current.id)return;if(e.data.progress){current.onProgress?.(e.data.progress);const v=e.data.progress;for(const host of document.querySelectorAll('[data-knn-host]'))if(context.positions[Number(host.dataset.knnHost)]?.ticker===current.ticker){host.querySelector('[data-knn-status]').textContent='KNN · Fereastra '+(v.stage||1)+' / '+(v.stages||1)+' · k verificat '+v.epoch+' / '+v.total;const bar=host.querySelector('[data-knn-progress]');if(bar)bar.value=v.epoch;}}else finish(current,e.data.error,e.data.result);};
  current.worker.onerror=()=>finish(current,'Workerul KNN nu a putut finaliza estimarea.');current.timeout=setTimeout(()=>finish(current,'Estimarea a depășit 180 secunde; rezultatul nu este utilizat.'),180000);current.worker.postMessage({id:current.id,bars,now:Date.now()});
 }catch(e){finish(current,e.message);}
return current.completion;}
function demo(p){if(!context?.demo||!p||demoStarted.has(key(p)))return;demoStarted.add(key(p));train(p);}
function bind(){for(const b of document.querySelectorAll('[data-knn-train]'))b.onclick=()=>train(context.positions[Number(b.dataset.knnTrain)]);for(const b of document.querySelectorAll('[data-knn-cancel]'))b.onclick=()=>cancel();for(const b of document.querySelectorAll('[data-knn-export]'))b.onclick=()=>{const p=context.positions[Number(b.dataset.knnExport)],r=read(p);if(usable(r,p,context.model(p)))g.HoldingsNeuralUI.exportReport(r);};}
g.HoldingsKNNUI={setContext,restore,inspect,markup,bind,cancel,demo,run:(p,options)=>train(p,{...options,managed:true}),cancelManaged:()=>{if(job?.managed)cancel(false);},busy:()=>!!job};
})(typeof window!=='undefined'?window:globalThis);
