(function(g){'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>Number.isFinite(v)?v.toLocaleString('ro-RO',{maximumFractionDigits:2}):'—';
const KEY='tt_holdings_layout_v1',TOP=['holdings','regimes','reports','control'],DETAIL=['summary','daily','technical','scenarios','news','neural','plan'];let state={accounts:{}},ctx=null,rows=[],page='holdings',detailsOpen=new Map(),reportOpen=[],rosterExpanded=true;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}');if(saved.accounts&&typeof saved.accounts==='object')state=saved;}catch{}
function choose(list,ticker){return list.some(x=>x.p.ticker===ticker)?ticker:list[0]?.p.ticker||null;}
function prefs(){return state.accounts[ctx?.scope||'']||{};}
function remember(patch){const scope=ctx?.scope||'';state.accounts[scope]={...prefs(),...patch};if(ctx?.demo||!scope)return;try{const accounts=Object.fromEntries(Object.entries(state.accounts).filter(([key])=>key&&key!=='educational-demo'));localStorage.setItem(KEY,JSON.stringify({accounts}));}catch{$('status').textContent='Preferința de afișare nu a putut fi salvată. Datele deținării rămân disponibile.';}}
function disclosure(d,i){return d.querySelector(':scope > summary')?.textContent||d.className||String(i);}
function capture(){for(const card of document.querySelectorAll('.holding[data-ticker]')){const scope=ctx?.scope||'';card.querySelectorAll('details').forEach((d,i)=>detailsOpen.set(scope+'|'+card.dataset.ticker+'|'+disclosure(d,i),d.open));}const host=$('managementReports');if(host)reportOpen=[...host.querySelectorAll(':scope > details')].map(x=>x.open);}
function organize(){const source=$('holdingManagement'),target=$('managementReports');if(!source||!target)return;if(source.hidden){target.replaceChildren();target.hidden=true;return;}const parts=[...source.querySelectorAll(':scope > details')];if(parts.length){const old=[...target.querySelectorAll(':scope > details')].map(x=>x.open);target.replaceChildren(...parts);parts.forEach((x,i)=>x.open=old[i]??reportOpen[i]??false);}target.hidden=!target.children.length;}
function showPage(name,focus=false){page=TOP.includes(name)?name:'holdings';for(const b of document.querySelectorAll('[data-workspace-tab]')){const active=b.dataset.workspaceTab===page;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;}for(const p of document.querySelectorAll('[data-workspace-panel]'))p.hidden=p.dataset.workspacePanel!==page;if(focus)$('workspace-tab-'+page)?.focus();}
function detailTab(card,name){name=DETAIL.includes(name)?name:'summary';for(const b of card.querySelectorAll('[data-holding-tab]')){const active=b.dataset.holdingTab===name;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;}for(const p of card.querySelectorAll('[data-holding-panel]'))p.hidden=p.dataset.holdingPanel!==name;}
function pick(ticker,{scroll=false,verdict=false}={}){if(!ctx)return;capture();const selected=choose(rows,ticker);remember({ticker:selected});showPage('holdings');if(document.body.dataset.holdingsView==='quick')$('holdingDetailView').click();render(ctx,rows);g.HoldingsNeuralUI?.refresh();if(g.matchMedia?.('(max-width: 760px)').matches){rosterExpanded=false;showRoster();}if(scroll)$('selectedAnalysis')?.scrollIntoView({behavior:'smooth',block:'start'});if(verdict&&selected)g.HoldingsVerdictUI?.open(selected);}
function openModelLedger(ticker){
 if(!ctx?.positions.some(p=>p.ticker===ticker))return false;
 if(!rows.some(r=>r.p.ticker===ticker)){const reset=$('holdingReset');if(!reset?.onclick)return false;reset.click();}
 if(!rows.some(r=>r.p.ticker===ticker))return false;
 remember({detailTabs:{...(prefs().detailTabs||{}),[ticker]:'neural'}});pick(ticker,{verdict:false});g.HoldingsNeuralUI?.refresh();
 const card=[...document.querySelectorAll('.holding[data-ticker]')].find(c=>c.dataset.ticker===ticker),ledger=card?.querySelector('.forecast-card');ledger?.focus({preventScroll:true});ledger?.scrollIntoView({behavior:g.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});return true;
}
function showRoster(){const mobile=g.matchMedia?.('(max-width: 760px)').matches,expanded=!mobile||rosterExpanded||document.body.dataset.holdingsView==='quick';$('rosterBody').hidden=!expanded;$('toggleHoldingRoster').setAttribute('aria-expanded',String(expanded));$('toggleHoldingRoster').textContent=expanded?'Ascunde lista':'Schimbă deținerea';$('toggleHoldingRoster').hidden=document.body.dataset.holdingsView==='quick';}
function render(c,list){ctx=c;rows=list;organize();const reviews=Object.fromEntries(c.positions.map(p=>[p.ticker,g.HoldingsReview.assess(p,c.model(p),c.note(p),c.events(p),c.symbol(p),Date.now(),c.snapshot?.fetchedAt)]));renderShortcuts(reviews);const selected=choose(rows,prefs().ticker);remember({ticker:selected});const host=$('holdingQuickList');host.hidden=false;host.innerHTML=rows.length?`<table class="holding-roster-table"><thead><tr><th>Instrument / regim</th><th>Valoare</th><th>P&amp;L</th></tr></thead><tbody>${rows.map(({p,m})=>{const regime=m?.regime?.label||m?.medium||'Analiză lipsă',attention=m?.attention?.length||0,review=reviews[p.ticker];return `<tr class="${selected===p.ticker?'selected':''}"><td><button data-pick-holding="${esc(p.ticker)}" aria-pressed="${selected===p.ticker}" title="${esc(review.reasons.join(' · ')||'Nicio regulă de revizuire declanșată; continuă monitorizarea.')}"><b>${esc(c.symbol(p)||p.ticker)}</b><span>${esc(p.name||p.ticker)}</span><small class="${m?.medium==='Descendent'?'bad':m?.medium==='Ascendent'?'good':'warn'}">${esc(regime)}${attention?' · '+attention+(attention===1?' semnal':' semnale'):''}</small><em class="review-cue ${review.kind}">${review.label}</em></button></td><td><b>${fmt(p.value)}</b><small>${esc(p.currency||'monedă?')}</small></td><td class="${p.unrealized<0?'bad':p.unrealized>0?'good':''}"><b>${fmt(p.unrealized)}</b><small>${esc(p.currency||'monedă?')}</small></td></tr>`;}).join('')}</tbody></table>`:`<div class="empty">${c.positions.length?'Nicio deținere nu corespunde filtrelor.':'Conectează Trading 212 pentru deținerile tale sau deschide demo-ul din Instrumente.'}</div>`;
 for(const b of host.querySelectorAll('[data-pick-holding]'))b.onclick=()=>pick(b.dataset.pickHolding,{scroll:g.matchMedia?.('(max-width: 760px)').matches});
 const chosen=rows.find(x=>x.p.ticker===selected),model=chosen&&c.model(chosen.p);
 if(g.TTDecisionPanel){const ticker=chosen&&c.symbol(chosen.p);g.TTDecisionPanel.set({purpose:'holding',candidate:model?{symbol:ticker,currency:model.currency,sourceDate:model.asOf,sourceTimezone:c.demo?'America/New_York':model.timezone,sourceCloseMinutes:c.demo?960:model.closeMinutes,ts:model.checkedAt,kind:c.demo?'synthetic':'market',trend:model.decisionTrend,price:model.price,atr:model.atr,rs:model.rs20,rvol:model.rvol}:null,modelAction:chosen?()=>g.HoldingsVerdictUI?.open(chosen.p.ticker):null,empty:{title:chosen?'Reanalizează '+(ticker||chosen.p.ticker):c.positions.length?'Nicio deținere pentru filtrele curente':'Deținerile nu sunt încă încărcate',reason:chosen?'Deținerea selectată nu are o serie EOD actuală și verificată. Verifică asocierea simbolului și erorile analizei.':c.positions.length?'Schimbă filtrele pentru a vedea deținerile disponibile.':'Încarcă snapshot-ul Trading 212 pentru a analiza deținerile tale.',next:chosen?'Reanalizează deținerile și verifică simbolul de piață.':c.positions.length?'Resetează filtrele și selectează o deținere.':'Deschide Trading 212 și actualizează contul.'}});}
 $('selectedHoldingLabel').textContent=selected?c.symbol(rows.find(x=>x.p.ticker===selected).p)||selected:'Alege o deținere';$('selectedAnalysis').hidden=!selected||document.body.dataset.holdingsView==='quick';
 for(const card of document.querySelectorAll('.holding[data-ticker]')){const restore=!card.dataset.layoutBound;card.hidden=card.dataset.ticker!==selected;decorate(card,reviews[card.dataset.ticker],selected);const tab=prefs().detailTabs?.[card.dataset.ticker]||'summary';detailTab(card,tab);card.querySelectorAll('details').forEach((d,i)=>{const k=c.scope+'|'+card.dataset.ticker+'|'+disclosure(d,i);if(restore&&detailsOpen.has(k))d.open=detailsOpen.get(k);});card.dataset.layoutBound='1';for(const b of card.querySelectorAll('[data-holding-tab]'))b.onclick=()=>{remember({detailTabs:{...(prefs().detailTabs||{}),[card.dataset.ticker]:b.dataset.holdingTab}});detailTab(card,b.dataset.holdingTab);if(b.dataset.holdingTab==='neural')g.HoldingsNeuralUI?.refresh();};bindKeys(card.querySelector('[role="tablist"]'));}
 showPage(page);showRoster();}
function renderShortcuts(reviews){const host=$('holdingReviewShortcuts');if(!host)return;const review=Object.values(reviews).filter(x=>x.review).length,missing=Object.values(reviews).filter(x=>x.kind==='check').length,state=$('holdingState').value;host.innerHTML=[['all','Toate',ctx.positions.length],['review','De revizuit',review],['missing','Date lipsă',missing]].map(([value,label,count])=>`<button data-review-filter="${value}" aria-label="${label} · ${count} dețineri" aria-pressed="${state===value}">${label}<b>${count}</b></button>`).join('');for(const b of host.querySelectorAll('[data-review-filter]'))b.onclick=()=>{$('holdingState').value=b.dataset.reviewFilter;if(b.dataset.reviewFilter==='review')$('holdingSort').value='review';$('holdingState').dispatchEvent(new Event('change',{bubbles:true}));};}
function decorate(card,review,selected){if(!review)return;const label=card.querySelector('[data-review-label]');if(label){label.textContent=review.label;label.dataset.kind=review.kind;}const note=card.querySelector('[data-review-note]');if(note){note.hidden=!review.reasons.length;const signature=JSON.stringify([review.kind,review.reasons]);if(note.dataset.reviewContent!==signature){note.dataset.reviewContent=signature;note.innerHTML=review.reasons.length?`<div><b>${review.label}</b><span>${esc(review.reasons[0])}</span></div>${review.reasons.length>1?`<details><summary>Toate motivele · ${review.reasons.length}</summary><ul>${review.reasons.map(x=>'<li>'+esc(x)+'</li>').join('')}</ul></details>`:''}`:'';note.dataset.kind=review.kind;}}const index=rows.findIndex(x=>x.p.ticker===selected),order=card.querySelector('[data-holding-order]');if(order)order.textContent=(index+1)+' / '+rows.length;for(const button of card.querySelectorAll('[data-holding-step]')){const delta=Number(button.dataset.holdingStep);button.disabled=index+delta<0||index+delta>=rows.length;button.onclick=()=>step(delta);}const change=card.querySelector('[data-show-holdings]');if(change)change.onclick=showList;}
function step(delta){const index=rows.findIndex(x=>x.p.ticker===prefs().ticker),target=rows[index+delta];if(target)pick(target.p.ticker,{scroll:true});}
function showList(){showPage('holdings');rosterExpanded=true;showRoster();$('holdingFilters')?.scrollIntoView({behavior:'smooth',block:'start'});}
function bindKeys(list){if(!list)return;list.onkeydown=e=>{if(e.altKey||e.ctrlKey||e.metaKey||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key)||!e.target.matches('[role="tab"]'))return;const buttons=[...list.querySelectorAll('[role="tab"]')],at=buttons.indexOf(e.target),index=e.key==='Home'?0:e.key==='End'?buttons.length-1:(at+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;e.preventDefault();buttons[index].click();buttons[index].focus();};}
if(typeof document!=='undefined'){for(const b of document.querySelectorAll('[data-workspace-tab]'))b.onclick=()=>showPage(b.dataset.workspaceTab);bindKeys(document.querySelector('.workspace-tabs'));$('toggleHoldingRoster').onclick=()=>{rosterExpanded=!rosterExpanded;showRoster();};g.addEventListener('resize',showRoster);}
g.HoldingsLayout={render,capture,organize,pick,choose,showPage,step,showList,openModelLedger,selected:()=>prefs().ticker};
})(typeof window!=='undefined'?window:globalThis);
