(function(g){'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>Number.isFinite(v)?v.toLocaleString('ro-RO',{maximumFractionDigits:2}):'—';
const KEY='tt_holdings_layout_v1',TOP=['holdings','regimes','reports','control'],DETAIL=['summary','technical','scenarios','news','plan'];let state={accounts:{}},ctx=null,rows=[],page='holdings',detailsOpen=new Map(),reportOpen=[],rosterExpanded=true;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}');if(saved.accounts&&typeof saved.accounts==='object')state=saved;}catch{}
function choose(list,ticker){return list.some(x=>x.p.ticker===ticker)?ticker:list[0]?.p.ticker||null;}
function prefs(){return state.accounts[ctx?.scope||'']||{};}
function remember(patch){const scope=ctx?.scope||'';state.accounts[scope]={...prefs(),...patch};if(ctx?.demo||!scope)return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch{$('status').textContent='Preferința de afișare nu a putut fi salvată. Datele deținării rămân disponibile.';}}
function capture(){for(const card of document.querySelectorAll('.holding[data-ticker]')){const scope=ctx?.scope||'';card.querySelectorAll('details').forEach((d,i)=>detailsOpen.set(scope+'|'+card.dataset.ticker+'|'+i,d.open));}const host=$('managementReports');if(host)reportOpen=[...host.querySelectorAll(':scope > details')].map(x=>x.open);}
function organize(){const source=$('holdingManagement'),target=$('managementReports');if(!source||!target)return;if(source.hidden){target.replaceChildren();target.hidden=true;return;}const parts=[...source.querySelectorAll(':scope > details')];if(parts.length){const old=[...target.querySelectorAll(':scope > details')].map(x=>x.open);target.replaceChildren(...parts);parts.forEach((x,i)=>x.open=old[i]??reportOpen[i]??false);}target.hidden=!target.children.length;}
function showPage(name,focus=false){page=TOP.includes(name)?name:'holdings';for(const b of document.querySelectorAll('[data-workspace-tab]')){const active=b.dataset.workspaceTab===page;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;}for(const p of document.querySelectorAll('[data-workspace-panel]'))p.hidden=p.dataset.workspacePanel!==page;if(focus)$('workspace-tab-'+page)?.focus();}
function detailTab(card,name){name=DETAIL.includes(name)?name:'summary';for(const b of card.querySelectorAll('[data-holding-tab]')){const active=b.dataset.holdingTab===name;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;}for(const p of card.querySelectorAll('[data-holding-panel]'))p.hidden=p.dataset.holdingPanel!==name;}
function pick(ticker,{scroll=false}={}){if(!ctx)return;const selected=choose(rows,ticker);remember({ticker:selected});showPage('holdings');if(document.body.dataset.holdingsView==='quick')$('holdingDetailView').click();render(ctx,rows);if(g.matchMedia?.('(max-width: 760px)').matches){rosterExpanded=false;showRoster();}if(scroll)$('selectedAnalysis')?.scrollIntoView({behavior:'smooth',block:'start'});}
function showRoster(){const mobile=g.matchMedia?.('(max-width: 760px)').matches,expanded=!mobile||rosterExpanded||document.body.dataset.holdingsView==='quick';$('rosterBody').hidden=!expanded;$('toggleHoldingRoster').setAttribute('aria-expanded',String(expanded));$('toggleHoldingRoster').textContent=expanded?'Ascunde lista':'Schimbă deținerea';}
function render(c,list){ctx=c;rows=list;organize();const selected=choose(rows,prefs().ticker);remember({ticker:selected});const host=$('holdingQuickList');host.hidden=false;host.innerHTML=rows.length?`<table class="holding-roster-table"><thead><tr><th>Instrument / regim</th><th>Valoare</th><th>P&amp;L</th></tr></thead><tbody>${rows.map(({p,m})=>{const regime=m?.regime?.label||m?.medium||'Analiză lipsă',attention=m?.attention?.length||0;return `<tr class="${selected===p.ticker?'selected':''}"><td><button data-pick-holding="${esc(p.ticker)}" aria-pressed="${selected===p.ticker}"><b>${esc(c.symbol(p)||p.ticker)}</b><span>${esc(p.name||p.ticker)}</span><small class="${m?.medium==='Descendent'?'bad':m?.medium==='Ascendent'?'good':'warn'}">${esc(regime)}${attention?' · '+attention+' semnale':''}</small></button></td><td><b>${fmt(p.value)}</b><small>${esc(p.currency||'monedă?')}</small></td><td class="${p.unrealized<0?'bad':p.unrealized>0?'good':''}"><b>${fmt(p.unrealized)}</b><small>${esc(p.currency||'monedă?')}</small></td></tr>`;}).join('')}</tbody></table>`:`<div class="empty">${c.positions.length?'Nicio deținere nu corespunde filtrelor.':'Conectează Trading 212 pentru deținerile tale sau deschide demo-ul din Instrumente.'}</div>`;
 for(const b of host.querySelectorAll('[data-pick-holding]'))b.onclick=()=>pick(b.dataset.pickHolding,{scroll:g.matchMedia?.('(max-width: 760px)').matches});
 $('selectedHoldingLabel').textContent=selected?c.symbol(rows.find(x=>x.p.ticker===selected).p)||selected:'Alege o deținere';$('selectedAnalysis').hidden=!selected||document.body.dataset.holdingsView==='quick';
 for(const card of document.querySelectorAll('.holding[data-ticker]')){card.hidden=card.dataset.ticker!==selected;const tab=prefs().detailTabs?.[card.dataset.ticker]||'summary';detailTab(card,tab);card.querySelectorAll('details').forEach((d,i)=>{const k=c.scope+'|'+card.dataset.ticker+'|'+i;if(detailsOpen.has(k))d.open=detailsOpen.get(k);});for(const b of card.querySelectorAll('[data-holding-tab]'))b.onclick=()=>{remember({detailTabs:{...(prefs().detailTabs||{}),[card.dataset.ticker]:b.dataset.holdingTab}});detailTab(card,b.dataset.holdingTab);};bindKeys(card.querySelector('[role="tablist"]'));}
 showPage(page);showRoster();}
function bindKeys(list){if(!list)return;list.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key)||!e.target.matches('[role="tab"]'))return;const buttons=[...list.querySelectorAll('[role="tab"]')],at=buttons.indexOf(e.target),index=e.key==='Home'?0:e.key==='End'?buttons.length-1:(at+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;e.preventDefault();buttons[index].click();buttons[index].focus();};}
if(typeof document!=='undefined'){for(const b of document.querySelectorAll('[data-workspace-tab]'))b.onclick=()=>showPage(b.dataset.workspaceTab);bindKeys(document.querySelector('.workspace-tabs'));$('toggleHoldingRoster').onclick=()=>{rosterExpanded=!rosterExpanded;showRoster();};g.addEventListener('resize',showRoster);}
g.HoldingsLayout={render,capture,organize,pick,choose,showPage};
})(typeof window!=='undefined'?window:globalThis);
