(function(g){
'use strict';
const A=g.HoldingsAutoLearning,F=g.HoldingsForecast,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let context=null,coordinator=null,generation=0,ticking=false,timer=null;const statuses=new Map();
const apis=()=>({neural:g.HoldingsNeuralUI,hmm:g.HoldingsHMMUI,isolation:g.HoldingsIsolationUI,quantile:g.HoldingsQuantileUI,garch:g.HoldingsGarchUI,knn:g.HoldingsKNNUI});
function identity(p){const m=context.model(p);return {scope:context.scope,ticker:p.ticker,symbol:context.symbol(p),currency:m?.currency||context.reference?.(p)?.currency||p.instrumentCurrency,kind:context.demo?'synthetic':'market'};}
const storage=()=>g.HoldingsForecastUI.autoStorage();
function settings(p){try{const raw=storage().getItem(A.key(identity(p)));return raw?JSON.parse(raw):{version:A.VERSION,enabled:true};}catch{return {version:A.VERSION,enabled:true,phase:'loading'};}}
function current(target,source){const p=context?.positions.find(p=>p.ticker===target.ticker),m=p&&context.model(p);return !!p&&target.generation===generation&&F.key(identity(p))===target.key&&(!source||m?.asOf===source.asOf&&m?.price===source.close);}
function refresh(){g.HoldingsNeuralUI?.refresh();}
function create(){return A.create({
 restore:target=>g.HoldingsForecastUI.restore(context.positions.find(p=>p.ticker===target.ticker)),
 read:target=>settings(context.positions.find(p=>p.ticker===target.ticker)),write:(target,value)=>storage().setItem(A.key(target.identity),JSON.stringify(value)),current,
 load:async(target,isCurrent)=>{const p=context.positions.find(p=>p.ticker===target.ticker);await Promise.all(Object.values(apis()).map(api=>api.restore?.(p)));if(!isCurrent())throw Error('Contextul s-a schimbat.');const source=await context.loadVerdict(p,{isCurrent});if(isCurrent())context.refresh();return source;},
 steps:Object.entries(apis()).map(([id,api])=>({models:id==='neural'?['neural','boosting']:[id],run:(target,source,onProgress)=>api.run(context.positions.find(p=>p.ticker===target.ticker),{source,onProgress}),cancel:()=>api.cancelManaged()})),
 complete:async run=>{const p=context.positions.find(p=>p.ticker===run.target.ticker);g.HoldingsForecastUI.checkSource?.(p,run.source);const snapshots=Object.fromEntries(Object.entries(apis()).map(([id,api])=>[id,api.inspect(p)])),probabilistic=g.HoldingsForecastUI.probabilistic(p,run.source,snapshots),report=g.HoldingsVerdict.build({expected:run.source,snapshots,statuses:run.statuses,probabilistic});g.HoldingsForecastUI.capture(p);if(report.available===g.HoldingsVerdict.IDS.length)g.HoldingsForecastUI.captureVerdict(p,report,run.source);return report;},
 update:run=>{if(current(run.target,run.source)){const signature=run.phase+'|'+Object.entries(run.statuses||{}).map(([k,v])=>k+':'+v.state).join('|'),previous=statuses.get(run.target.key);statuses.set(run.target.key,{phase:run.phase,progress:run.progress,error:run.error,statuses:run.statuses,signature});if(previous?.signature!==signature)refresh();}}
 });}
function stop(){coordinator?.stop();}
function note(p,source){if(!context||!p||!source)return;const s=settings(p),e=identity(p);if(source.symbol!==e.symbol||source.currency!==e.currency||source.kind!==e.kind||s.asOf===source.asOf&&s.fingerprint===source.fingerprint&&s.phase==='done')return;storage().setItem(A.key(e),JSON.stringify({...s,asOf:source.asOf,fingerprint:source.fingerprint,at:Date.now(),phase:'done',error:null}));}
async function tick(force=false,ticker=null){
 if(ticking||!context||document.hidden||context.demo&&!force||g.HoldingsVerdictUI?.busy?.()||Object.values(apis()).some(api=>api.busy()))return;
 ticking=true;const token=generation;try{for(const p of context.positions.slice()){if(!force&&g.matchMedia?.('(max-width: 760px)').matches&&p.ticker!==(g.HoldingsLayout?.selected?.()||context.positions[0]?.ticker))continue;if(ticker&&p.ticker!==ticker)continue;if(!context||document.hidden||token!==generation||g.HoldingsVerdictUI?.busy?.())break;const e=identity(p);if(!F.identity(e))continue;await g.HoldingsForecastUI.restore(p);if(token!==generation||!context.positions.some(x=>x.ticker===p.ticker)||F.key(identity(p))!==F.key(e))break;const m=context.model(p)||context.reference?.(p),s=settings(p);let expected;try{if(m)expected=g.DailySeries.expected(Date.now(),m.timezone||'America/New_York',m.closeMinutes??960);}catch{}
   if(!m||!expected||!force&&(s.enabled===false||s.asOf===expected&&s.phase==='done'||s.phase==='error'&&Date.now()-(s.at||0)<15*60000)){if(!context.demo)await g.HoldingsForecastUI.check?.(p);continue;}
   if(Object.values(apis()).some(api=>api.busy()))break;coordinator??=create();await coordinator.start({ticker:p.ticker,key:F.key(e),identity:e,asOf:expected,generation},{force});
  }}finally{ticking=false;}
}
function setContext(c){if(!context||context.scope!==c.scope||context.demo!==c.demo){generation++;stop();}context=c;if(!timer){timer=setInterval(()=>void tick(),60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)void tick();});}void tick();}
function progressMarkup(l){
 const r=l?.progress;if(!r)return '';const latest=r.latest,split=latest?{fit:latest.fit,test:latest.test}:r.split,names=['Declin','Mixt','Avans'],score=v=>Number.isFinite(v)?v.toLocaleString('ro-RO',{minimumFractionDigits:3,maximumFractionDigits:3}):'—';
 const period=p=>p.from?esc(p.from)+' → '+esc(p.to)+' · rezultate până la '+esc(p.lastOutcome):'Perioadă încă indisponibilă';
 let html='<section class="learning-progress" aria-label="Progres către verdict probabilistic"><h4>Progres către verdict probabilistic</h4><b>'+esc(r.title)+'</b><p>'+r.available+' perechi Neural + Boosting cu rezultat verificat, pe orizonturi separate.</p><label>'+(r.reviewed?'Rezultate noi pentru următoarea evaluare':'Perechi pentru prima evaluare')+' · '+r.current+' / '+r.target+'<progress max="'+r.target+'" value="'+Math.min(r.current,r.target)+'"></progress></label><p>'+esc(r.reason)+'</p>'+(r.remaining?'<p>Mai sunt necesare cel puțin '+r.remaining+(r.remaining===1?' rezultat nou pe orizont separat. ':' rezultate noi pe orizonturi separate. ')+r.pending+' perechi sunt în așteptare.</p>':'')+'<h5>Clasele din '+(latest?'ultima evaluare':'perechile disponibile')+'</h5><div class="learning-table-wrap"><table><caption>Minimum '+r.blockMinimum+' rezultate și '+r.classMinimum+' din fiecare clasă în fiecare bloc</caption><thead><tr><th>Bloc · perioadă</th><th>Rezultate</th>'+names.map(n=>'<th>'+n+'</th>').join('')+'</tr></thead><tbody>'+[['fit','Calibrare'],['test','Test ulterior']].map(([k,name])=>{const p=split[k];return '<tr><th>'+name+'<small>'+period(p)+'</small></th><td>'+p.n+' / '+r.blockMinimum+'</td>'+p.counts.map(n=>'<td'+(n<r.classMinimum?' class="learning-shortage"':'')+'>'+n+' / '+r.classMinimum+'</td>').join('')+'</tr>';}).join('')+'</tbody></table></div>';
 if(latest){const s=latest.scores;html+='<h5>Ultimul test al combinației · '+latest.test.n+' orizonturi</h5><p>'+(latest.promoted?'Candidatul a fost adoptat.':latest.eligible?'Candidatul a trecut reperele inițiale, dar nu toate condițiile pentru înlocuirea versiunii precedente.':'Candidatul nu a trecut toate reperele; direcția nu se activează prin acest test.')+' Evaluat '+esc(new Date(latest.at).toLocaleString('ro-RO'))+'.</p><div class="learning-table-wrap"><table><caption>Aceleași observații de test · scoruri mai mici sunt mai bune</caption><thead><tr><th>Model / reper</th><th>Log loss</th><th>Brier</th></tr></thead><tbody>'+[['candidate','Combinație candidată'],['neural','Neural'],['boosting','Gradient Boosting'],['prior','Frecvențe din calibrare']].map(([id,name])=>'<tr><th>'+name+'</th><td>'+score(s[id].loss)+'</td><td>'+score(s[id].brier)+'</td></tr>').join('')+'</tbody></table></div>';}
 html+='<details><summary>Ce este exclus și cum se activează verdictul</summary><p>'+r.excluded.legacy+' perechi fără probabilități originale · '+r.excluded.incomplete+' incomplete · '+r.excluded.mismatch+' cu surse sau rezultate diferite · '+r.excluded.unverifiable+' neverificabile · '+r.excluded.overlap+' orizonturi suprapuse · '+r.excluded.restored+' perechi restaurate.</p><p>Ultimele 20 rezultate noi sunt rezervate testului. Calibrarea folosește observații încheiate înaintea acelui test. Nu mutăm clasele între perioade. O pereche necesită estimările ambelor modele, păstrate înaintea rezultatului; estimările reconstruite din trecut nu intră aici.</p><p>Pe test cerem îmbunătățiri peste 0,02 pentru Log loss și peste 0,01 pentru Brier față de frecvențele claselor. Combinația nu poate depăși eroarea celei mai bune componente cu mai mult de 0,01. Pentru înlocuirea unei versiuni, comparația se repetă pe aceleași 20 rezultate noi față de versiunea precedentă.</p><p>O versiune validată păstrată nu garantează o direcție acum. Probabilitățile curente, istoricul comun și modelele de context se verifică în Verdict AI. Abținerea rămâne un rezultat valid.</p></details></section>';
 return html;
}
function markup(p,i){if(!context)return '';const e=identity(p),s=settings(p),run=statuses.get(F.key(e)),l=g.HoldingsForecastUI.learning(p),saved=l?.state?.champion,c=saved&&typeof saved.id==='string'&&Array.isArray(saved.fitOrigins)&&Array.isArray(saved.testOrigins)?saved:null,reviews=Array.isArray(l?.state?.reviews)?l.state.reviews.filter(r=>typeof r?.candidate?.id==='string'&&Number.isFinite(r.at)):[],last=l?.progress?.latest,n=s.enabled!==false;
 const status=run?.phase==='running'?'Reantrenare în curs · '+Object.entries(run.statuses||{}).filter(([,v])=>v.state==='ready').length+' / '+g.HoldingsVerdict.IDS.length+' modele':s.phase==='done'?'Ultima reantrenare încheiată · EOD '+s.asOf:s.error||'Se verifică automat o sesiune EOD nouă.';
 return `<section class="holdings-learning" aria-label="Învățare și reantrenare AI"><div class="calibration-heading"><div><span class="eyebrow">MODELE ȘI REZULTATE NOI</span><h3>Învățare în timp</h3></div><span class="tag">${context.demo?'Demo separat':n?'Automat activ':'Automat oprit'}</span></div><p role="status">${esc(status)}</p><div class="hmm-controls"><button data-learning-toggle="${i}" aria-pressed="${n}">${n?'Oprește reantrenarea automată':'Activează reantrenarea automată'}</button><button data-learning-run="${i}">Reantrenează acum</button></div><p>Modelele se reantrenează pe istoricul actualizat. Predicțiile originale și rezultatele observate se păstrează. Reantrenarea automată rulează cât timp această pagină este deschisă; o pagină închisă nu execută calcule. Verificarea predicțiilor păstrate continuă și când reantrenarea este oprită, cel mult o dată pentru fiecare EOD; după o eroare reîncercăm peste 15 minute.</p>${progressMarkup(l)}<b>${c?(l.ok?'Versiune activă: ':'Checkpoint suspendat: ')+esc(c.id):'Combinație probabilistică în colectare'}</b><p>${esc(l?.reason||'Istoricul se încarcă.')}</p>${c?'<p class="meta">Calibrare: '+c.fitOrigins.length+' orizonturi · test separat: '+c.testOrigins.length+'. Adoptată la '+esc(new Date(c.createdAt).toLocaleString('ro-RO'))+'.</p>':''}${last?'<p class="meta">Ultimul candidat: '+esc(last.id)+' · '+(last.promoted?'adoptat':'respins; checkpoint-ul anterior este păstrat')+'.</p>':''}<details><summary>Versiuni și metoda de învățare</summary><p>Neural, Boosting și modelele de context sunt recalibrate prin reantrenare pe datele disponibile. Nu actualizăm ponderile neuronale după fiecare tranzacție. Învățarea combinației folosește numai perechi Neural și Boosting păstrate înaintea rezultatului, pe orizonturi separate. Minimum 20 pentru calibrare și 20 pentru test, cu 4 rezultate din fiecare clasă în fiecare bloc.</p><p>Candidatul trebuie să depășească frecvențele claselor și să păstreze calitatea ambelor componente pe test. Pentru înlocuirea unei versiuni active, cerem un bloc ulterior de 20 rezultate noi și scoruri mai bune decât versiunea anterioară pe exact același bloc. Ponderile și temperatura versiunii active rămân fixe între evaluări.</p>${reviews.length?'<ol>'+reviews.slice(-10).reverse().map(r=>'<li>'+esc(r.candidate.id)+' · '+esc(new Date(r.at).toLocaleDateString('ro-RO'))+' · '+(r.promoted?'adoptat':'respins')+'</li>').join('')+'</ol>':''}</details></section>`;
}
function bind(){for(const b of document.querySelectorAll('[data-learning-toggle]'))b.onclick=async()=>{const p=context.positions[Number(b.dataset.learningToggle)];if(!p)return;await g.HoldingsForecastUI.restore(p);const s=settings(p);storage().setItem(A.key(identity(p)),JSON.stringify({...s,enabled:s.enabled===false}));if(s.enabled!==false)stop();refresh();if(s.enabled===false)void tick();};for(const b of document.querySelectorAll('[data-learning-run]'))b.onclick=()=>{const p=context.positions[Number(b.dataset.learningRun)];if(p)void tick(true,p.ticker);};}
function probabilityEvidenceMarkup(r){
 const e=r?.evidence,number=(v,d=3)=>Number.isFinite(v)?v.toLocaleString('ro-RO',{maximumFractionDigits:d}):'—',period=p=>p?.from?esc(p.from)+' → '+esc(p.to):'perioadă neverificată',simulated=r?.kind==='synthetic';
 const heading=simulated?'<p class="probability-proof-demo">DATE FICTIVE · dovezi simulate, fără performanță reală.</p>':'';
 if(!e||!e.test||!e.scores)return '<section class="probability-proof" aria-label="Dovezile probabilităților">'+heading+'<b>Exploratoriu · fără test activ verificat</b><p>'+number(e?.available??r?.observations,0)+' / minimum '+number(e?.minimum??40,0)+' perechi pe orizonturi separate. Sunt necesare cel puțin 20 rezultate pentru testul ulterior și clase reprezentate suficient. Procentele afișate nu activează o direcție.</p></section>';
 const titles={validated:'Test trecut · estimare eligibilă',abstaining:'Test trecut · clase prea apropiate',suspended:'Direcție suspendată · rezultate ulterioare slabe'},scores=e.scores,n=e.test.n;
 const complete=['candidate','neural','boosting','prior'].every(k=>scores[k]?.n===n&&['loss','brier','accuracy'].every(f=>Number.isFinite(scores[k][f])));
 if(!complete)return '<p class="probability-proof" role="status">Scorurile dovezilor nu pot fi verificate.</p>';
 const deltaLoss=scores.prior.loss-scores.candidate.loss,deltaBrier=scores.prior.brier-scores.candidate.brier,names={candidate:'Combinația activă',neural:'Neural',boosting:'Boosting',prior:'Reper simplu · frecvențe din calibrare'},monitor=e.monitoring;
 let html='<section class="probability-proof" aria-label="Dovezile probabilităților">'+heading+'<div class="probability-proof-heading"><b>'+esc(titles[e.phase]||'Dovezi de verificat')+'</b><span>'+n+' rezultate pe test ulterior</span></div><p>Test: '+period(e.test)+' · rezultate până la '+esc(e.test.lastOutcome||'neverificat')+'.</p><p>Față de reperul simplu: log loss mai mic cu '+number(deltaLoss)+' · Brier mai mic cu '+number(deltaBrier)+'. Scoruri de clasă, fără măsurarea profitului.</p><details><summary>Perioade și scoruri comparabile</summary><p>Calibrare: '+e.fit.n+' rezultate · '+period(e.fit)+'. Parametrii au fost fixați înaintea testului.</p><div class="learning-table-wrap"><table><caption>Aceleași '+n+' rezultate de test · mai mic este mai bun pentru Log loss și Brier</caption><thead><tr><th>Estimare</th><th>Log loss</th><th>Brier</th><th>Clasă corectă</th></tr></thead><tbody>'+Object.entries(names).map(([k,name])=>'<tr><th>'+name+'</th><td>'+number(scores[k].loss)+'</td><td>'+number(scores[k].brier)+'</td><td>'+number(scores[k].accuracy*100,1)+'%</td></tr>').join('')+'</tbody></table></div><p class="meta">Avantaj descriptiv pe acest test, fără confirmare statistică. Estimările originale și rezultatele verificate sunt păstrate; datele restaurate nu activează checkpoint-ul.</p>';
 if(monitor){html+='<p><b>După validare: '+monitor.n+' / '+monitor.required+' rezultate noi</b> · '+period(monitor)+'.</p>';if(monitor.performance&&monitor.reference)html+='<p>Log loss: '+number(monitor.performance.loss)+' / reper '+number(monitor.reference.loss)+' · Brier: '+number(monitor.performance.brier)+' / reper '+number(monitor.reference.brier)+'. '+(monitor.degraded?'Ambele scoruri sunt cel puțin la fel de slabe ca reperul; direcția este suspendată.':'Acest bloc nu declanșează regula de suspendare.')+'</p>';else html+='<p class="meta">Verificarea degradării cere un bloc complet de 20 rezultate noi, observate după adoptarea versiunii.</p>';}
 return html+'</details></section>';
}
function probabilityMarkup(r){const p=r?.probabilities;if(!p)return '';const names=['Declin','Mixt','Avans'],format=n=>(100*n).toLocaleString('ro-RO',{maximumFractionDigits:1,minimumFractionDigits:1});return `<section class="holdings-probability" aria-label="Probabilitățile combinației AI"><div class="calibration-heading"><h3>Probabilități · +5 sesiuni</h3><span class="tag">${r.checkpoint?(r.evidence?.phase==='suspended'?'Validată · direcție suspendată':r.eligible?'Versiune validată':'Validată · abținere'):'Exploratoriu · 50/50'}</span></div><div class="probability-grid">${p.map((v,k)=>'<div><span>'+names[k]+'</span><b>'+format(v)+'%</b><progress max="1" value="'+v+'" aria-label="'+names[k]+'"></progress></div>').join('')}</div>${probabilityEvidenceMarkup(r)}<p>${esc(r.reason)}</p><p class="meta">Avans: cel puțin +1 ATR inițial; Declin: cel mult −1 ATR; Mixt: între praguri. Estimare pentru închiderea de peste 5 sesiuni, fără costuri. Nu reprezintă probabilitatea de profit.</p>${r.validation?'<p class="meta">'+r.validation.fit+' observații de calibrare · '+r.validation.test+' de test. Neural '+format(r.validation.parameters.neuralWeight)+'% · Boosting '+format(1-r.validation.parameters.neuralWeight)+'% · temperatură '+r.validation.parameters.temperature+'. Praguri de decizie fixe: clasa dominantă ≥45% și diferență ≥10 puncte procentuale față de următoarea clasă.</p>':'<p class="meta">'+r.observations+' / minimum 40 perechi cu rezultat verificat. Probabilitățile exploratorii nu activează o direcție.</p>'}</section>`;}
g.HoldingsAutoLearningUI={setContext,markup,probabilityMarkup,probabilityEvidenceMarkup,bind,tick,stop,note,busy:()=>!!coordinator?.busy()};
})(typeof window!=='undefined'?window:globalThis);
