(function(g){
'use strict';
const A=g.HoldingsAutoLearning,F=g.HoldingsForecast,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let context=null,coordinator=null,generation=0,ticking=false,timer=null;const statuses=new Map();
const apis=()=>({neural:g.HoldingsNeuralUI,hmm:g.HoldingsHMMUI,isolation:g.HoldingsIsolationUI,quantile:g.HoldingsQuantileUI,garch:g.HoldingsGarchUI});
function identity(p){const m=context.model(p);return {scope:context.scope,ticker:p.ticker,symbol:context.symbol(p),currency:m?.currency||p.instrumentCurrency,kind:context.demo?'synthetic':'market'};}
const storage=()=>g.HoldingsForecastUI.autoStorage();
function settings(p){try{const raw=storage().getItem(A.key(identity(p)));return raw?JSON.parse(raw):{version:A.VERSION,enabled:true};}catch{return {version:A.VERSION,enabled:true,phase:'loading'};}}
function current(target,source){const p=context?.positions.find(p=>p.ticker===target.ticker),m=p&&context.model(p);return !!p&&target.generation===generation&&F.key(identity(p))===target.key&&(!source||m?.asOf===source.asOf&&m?.price===source.close);}
function refresh(){g.HoldingsNeuralUI?.refresh();}
function create(){return A.create({
 restore:target=>g.HoldingsForecastUI.restore(context.positions.find(p=>p.ticker===target.ticker)),
 read:target=>settings(context.positions.find(p=>p.ticker===target.ticker)),write:(target,value)=>storage().setItem(A.key(target.identity),JSON.stringify(value)),current,
 load:async(target,isCurrent)=>{const p=context.positions.find(p=>p.ticker===target.ticker);await Promise.all(Object.values(apis()).map(api=>api.restore?.(p)));if(!isCurrent())throw Error('Contextul s-a schimbat.');const source=await context.loadVerdict(p,{isCurrent});if(isCurrent())context.refresh();return source;},
 steps:Object.entries(apis()).map(([id,api])=>({models:id==='neural'?['neural','boosting']:[id],run:(target,source,onProgress)=>api.run(context.positions.find(p=>p.ticker===target.ticker),{source,onProgress}),cancel:()=>api.cancelManaged()})),
 complete:async run=>{const p=context.positions.find(p=>p.ticker===run.target.ticker);g.HoldingsForecastUI.checkSource?.(p,run.source);const snapshots=Object.fromEntries(Object.entries(apis()).map(([id,api])=>[id,api.inspect(p)])),probabilistic=g.HoldingsForecastUI.probabilistic(p,run.source,snapshots),report=g.HoldingsVerdict.build({expected:run.source,snapshots,statuses:run.statuses,probabilistic});g.HoldingsForecastUI.capture(p);if(report.available===6)g.HoldingsForecastUI.captureVerdict(p,report,run.source);return report;},
 update:run=>{if(current(run.target,run.source)){statuses.set(run.target.key,{phase:run.phase,progress:run.progress,error:run.error,statuses:run.statuses});refresh();}}
 });}
function stop(){coordinator?.stop();}
function note(p,source){if(!context||!p||!source)return;const s=settings(p),e=identity(p);if(source.symbol!==e.symbol||source.currency!==e.currency||source.kind!==e.kind||s.asOf===source.asOf&&s.fingerprint===source.fingerprint&&s.phase==='done')return;storage().setItem(A.key(e),JSON.stringify({...s,asOf:source.asOf,fingerprint:source.fingerprint,at:Date.now(),phase:'done',error:null}));}
async function tick(force=false,ticker=null){
 if(ticking||!context||document.hidden||context.demo&&!force||g.HoldingsVerdictUI?.busy?.()||Object.values(apis()).some(api=>api.busy()))return;
 ticking=true;try{for(const p of context.positions.slice()){if(ticker&&p.ticker!==ticker)continue;if(!context||document.hidden||g.HoldingsVerdictUI?.busy?.())break;const m=context.model(p),e=identity(p);if(!m||!F.identity(e))continue;await g.HoldingsForecastUI.restore(p);const s=settings(p);let expected;try{expected=g.DailySeries.expected(Date.now(),m.timezone||'America/New_York',m.closeMinutes??960);}catch{continue;}
   if(!force&&(s.enabled===false||s.asOf===expected&&s.phase==='done'||s.phase==='error'&&Date.now()-(s.at||0)<15*60000))continue;
   if(Object.values(apis()).some(api=>api.busy()))break;coordinator??=create();await coordinator.start({ticker:p.ticker,key:F.key(e),identity:e,asOf:expected,generation},{force});
  }}finally{ticking=false;}
}
function setContext(c){if(!context||context.scope!==c.scope||context.demo!==c.demo){generation++;stop();}context=c;if(!timer){timer=setInterval(()=>void tick(),60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)void tick();});}void tick();}
function markup(p,i){if(!context)return '';const e=identity(p),s=settings(p),run=statuses.get(F.key(e)),l=g.HoldingsForecastUI.learning(p),c=l?.state?.champion,reviews=l?.state?.reviews||[],last=reviews.at(-1),n=s.enabled!==false;
 const status=run?.phase==='running'?'Reantrenare în curs · '+Object.entries(run.statuses||{}).filter(([,v])=>v.state==='ready').length+' / 6 modele':s.phase==='done'?'Ultima reantrenare încheiată · EOD '+s.asOf:s.error||'Se verifică automat o sesiune EOD nouă.';
 return `<section class="holdings-learning" aria-label="Învățare și reantrenare AI"><div class="calibration-heading"><div><span class="eyebrow">MODELE ȘI REZULTATE NOI</span><h3>Învățare în timp</h3></div><span class="tag">${context.demo?'Demo separat':n?'Automat activ':'Automat oprit'}</span></div><p role="status">${esc(status)}</p><div class="hmm-controls"><button data-learning-toggle="${i}" aria-pressed="${n}">${n?'Oprește reantrenarea automată':'Activează reantrenarea automată'}</button><button data-learning-run="${i}">Reantrenează acum</button></div><p>Modelele se reantrenează pe istoricul actualizat. Predicțiile originale și rezultatele observate se păstrează. Reantrenarea automată rulează cât timp această pagină este deschisă; o pagină închisă nu execută calcule.</p><b>${c?(l.ok?'Versiune activă: ':'Checkpoint suspendat: ')+esc(c.id):'Combinație probabilistică în colectare'}</b><p>${esc(l?.reason||'Istoricul se încarcă.')}</p>${c?'<p class="meta">Calibrare: '+c.fitOrigins.length+' orizonturi · test separat: '+c.testOrigins.length+'. Adoptată la '+esc(new Date(c.createdAt).toLocaleString('ro-RO'))+'.</p>':''}${last?'<p class="meta">Ultimul candidat: '+esc(last.candidate.id)+' · '+(last.promoted?'adoptat':'respins; checkpoint-ul anterior este păstrat')+'.</p>':''}<details><summary>Versiuni și metoda de învățare</summary><p>Neural, Boosting și modelele de context sunt recalibrate prin reantrenare pe datele disponibile. Nu actualizăm ponderile neuronale după fiecare tranzacție. Învățarea combinației folosește numai perechi Neural și Boosting păstrate înaintea rezultatului, pe orizonturi separate. Minimum 20 pentru calibrare și 20 pentru test, cu 4 rezultate din fiecare clasă în fiecare bloc.</p><p>Candidatul trebuie să depășească frecvențele claselor și să păstreze calitatea ambelor componente pe test. Pentru înlocuirea unei versiuni active, cerem un bloc ulterior de 20 rezultate noi și scoruri mai bune decât versiunea anterioară pe exact același bloc. Ponderile și temperatura versiunii active rămân fixe între evaluări.</p>${reviews.length?'<ol>'+reviews.slice(-10).reverse().map(r=>'<li>'+esc(r.candidate.id)+' · '+esc(new Date(r.at).toLocaleDateString('ro-RO'))+' · '+(r.promoted?'adoptat':'respins')+'</li>').join('')+'</ol>':''}</details></section>`;
}
function bind(){for(const b of document.querySelectorAll('[data-learning-toggle]'))b.onclick=async()=>{const p=context.positions[Number(b.dataset.learningToggle)];if(!p)return;await g.HoldingsForecastUI.restore(p);const s=settings(p);storage().setItem(A.key(identity(p)),JSON.stringify({...s,enabled:s.enabled===false}));if(s.enabled!==false)stop();refresh();if(s.enabled===false)void tick();};for(const b of document.querySelectorAll('[data-learning-run]'))b.onclick=()=>{const p=context.positions[Number(b.dataset.learningRun)];if(p)void tick(true,p.ticker);};}
function probabilityMarkup(r){const p=r?.probabilities;if(!p)return '';const names=['Declin','Mixt','Avans'],format=n=>(100*n).toLocaleString('ro-RO',{maximumFractionDigits:1,minimumFractionDigits:1});return `<section class="holdings-probability" aria-label="Probabilitățile combinației AI"><div class="calibration-heading"><h3>Probabilități · +5 sesiuni</h3><span class="tag">${r.checkpoint?'Versiune validată':'Exploratoriu · 50/50'}</span></div><div class="probability-grid">${p.map((v,k)=>'<div><span>'+names[k]+'</span><b>'+format(v)+'%</b><progress max="1" value="'+v+'" aria-label="'+names[k]+'"></progress></div>').join('')}</div><p>${esc(r.reason)}</p><p class="meta">Avans: cel puțin +1 ATR inițial; Declin: cel mult −1 ATR; Mixt: între praguri. Estimare pentru închiderea de peste 5 sesiuni, fără costuri. Nu reprezintă probabilitatea de profit.</p>${r.validation?'<p class="meta">'+r.validation.fit+' observații de calibrare · '+r.validation.test+' de test. Neural '+format(r.validation.parameters.neuralWeight)+'% · Boosting '+format(1-r.validation.parameters.neuralWeight)+'% · temperatură '+r.validation.parameters.temperature+'. Praguri de decizie fixe: clasa dominantă ≥45% și diferență ≥10 puncte procentuale față de următoarea clasă.</p>':'<p class="meta">'+r.observations+' / minimum 40 perechi cu rezultat verificat. Probabilitățile exploratorii nu activează o direcție.</p>'}</section>`;}
g.HoldingsAutoLearningUI={setContext,markup,probabilityMarkup,bind,tick,stop,note,busy:()=>!!coordinator?.busy()};
})(typeof window!=='undefined'?window:globalThis);
