(function(g){
'use strict';
const N=g.HoldingsNeural,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('ro-RO',{maximumFractionDigits:d,minimumFractionDigits:d}):'—',memory=new Map();let context=null,job=null,serial=0,demoStarted=false,delegated=false;const errors=new Map(),storageKey=(scope,ticker)=>'tt_holdings_neural_v1:'+encodeURIComponent(scope)+'|'+encodeURIComponent(ticker);
function read(p){const key=storageKey(context.scope,p.ticker);try{const raw=context.demo?memory.get(key):localStorage.getItem(key);return raw?JSON.parse(raw):null;}catch{return {invalid:true};}}
function setContext(c){if(context&&(c.scope!==context.scope||c.demo!==context.demo)){cancel(false);document.querySelector('.neural-report')?.close();}context=c;}
function drawing(result){const net=result?.network,inputs=Array.from({length:10},(_,i)=>[60,28+i*13]),hidden=Array.from({length:12},(_,i)=>[320,16+i*13]),outputs=[[580,36],[580,87],[580,138]];let paths='';hidden.forEach(([x,y],j)=>outputs.forEach(([a,b],k)=>{const w=net?.w2[j][k]||0;paths+=`<path d="M${x},${y} C420,${y} 470,${b} ${a},${b}" stroke="${w<0?'#d7978d':'#77c9af'}" stroke-opacity="${net?'.25':'.09'}" stroke-width="${.5+Math.min(1.5,Math.abs(w))}" fill="none"/>`;}));inputs.forEach(([x,y],i)=>[1,4,7,10].forEach(j=>paths+=`<path d="M${x},${y} L320,${hidden[j][1]}" stroke="#789ba9" stroke-opacity=".13" fill="none"/>`));const nodes=points=>points.map(([x,y])=>`<circle cx="${x}" cy="${y}" r="4" fill="#81c8b1"/>`).join('');return `<svg class="neural-network" viewBox="0 0 700 185" role="img" aria-label="Prima rețea din ansamblul de trei: 10 intrări, 12 neuroni ascunși, 3 clase">${paths}${nodes(inputs)}${nodes(hidden)}${nodes(outputs)}${N.CLASSES.map((s,k)=>`<text x="596" y="${outputs[k][1]+4}">${s}</text>`).join('')}<text x="30" y="177">10 indicatori</text><text x="275" y="177">12 neuroni · tanh</text><text x="550" y="177">3 clase · 5 sesiuni</text></svg>`;}
function walkMarkup(w){
 if(!w)return '<p class="meta">Robustețea pe mai multe perioade nu este evaluată. Reantrenează modelul.</p>';
 if(w.status==='insufficient')return `<section class="neural-walk-summary"><b>Robustețe neconfirmată · istoric insuficient</b><p class="meta">${esc(w.reason)}</p></section>`;
 const s=w.summary,b=s.nonOverlap,date=t=>new Date(t).toISOString().slice(0,10),tested=w.folds.filter(f=>f.status==='evaluated').length;
 return `<section class="neural-walk-summary"><div><b>${w.consistent?'Avantaj repetat în cele trei ferestre':'Robustețe neconfirmată'}</b><span class="tag">${s.wins}/3 cu avantaj</span></div><p class="meta">${tested}/3 ferestre evaluate · ${b.test.n} orizonturi fără suprapunere. ${w.status==='incomplete'?esc(w.reason):'Aceleași reguli și hiperparametri în fiecare fereastră.'}</p><details class="neural-details"><summary>Compară cele trei ferestre de test</summary><div class="neural-table-wrap"><table><thead><tr><th>Fereastră · EOD</th><th>Exemple</th><th>Loss rețea</th><th>Loss liniar / frecvențe</th><th>Verdict</th></tr></thead><tbody>${w.folds.map(f=>`<tr><td>${f.id} · ${date(f.periods.test.from)} → ${date(f.periods.test.to)}</td>${f.status==='evaluated'?`<td>${f.metrics.test.n}</td><td>${fmt(f.metrics.test.loss,3)}</td><td>${fmt(f.metrics.linear.loss,3)} / ${fmt(f.metrics.constant.loss,3)}</td><td>${f.advantage?'Avantaj în fereastră':'Fără avantaj'}</td>`:`<td colspan="4">Blocat: ${esc(f.error)}</td>`}</tr>`).join('')}</tbody></table></div><h4>Control cu orizonturi fără suprapunere</h4><p class="meta">Rețea: loss ${fmt(b.test.loss,3)} · acuratețe echilibrată ${Number.isFinite(b.test.balanced)?fmt(b.test.balanced*100,1)+'%':'indisponibilă'}. Repere: loss ${fmt(b.linear.loss,3)} / ${fmt(b.constant.loss,3)}. ${s.blockEnough?s.nonOverlapAdvantage?'Avantaj față de ambele repere.':'Avantajul nu este susținut de acest control.':'Mai puțin de 50 orizonturi sau prea puține exemple într-o clasă.'}</p><p class="meta">Etichetele nu se suprapun între ferestre. Orizonturile fără suprapunere pot rămâne corelate; nu sunt tranzacții independente. Regimurile viitoare și costurile nu sunt verificate de acest test.</p></details></section>`;
}
function diagnostics(r){const a=r.adjustment,d=r.disagreement,date=t=>new Date(t).toISOString().slice(0,10);return `<section class="neural-walk-summary"><div><b>Ansamblu · 3 rețele</b><span class="tag">${Math.max(...d.votes)}/3 voturi pentru aceeași clasă</span></div><p class="meta">Temperatură ${fmt(a.temperature,1)} · diferență maximă între scorurile rețelelor ${fmt(d.spread*100,1)} pp. ${a.eligible?'Ajustarea a fost aleasă pe un interval separat.':'Calibrare insuficientă; scorurile nu sunt ajustate.'}</p><details class="neural-details"><summary>Ajustarea scorurilor și acordul rețelelor</summary><p class="meta">Oprire antrenare: ${date(a.earlyStopping.from)} → ${date(a.earlyStopping.to)} (${a.earlyStopping.n} exemple). Ajustare: ${date(a.calibration.from)} → ${date(a.calibration.to)} (${a.calibration.n} exemple). Etichetele primului interval se încheie înaintea celui de ajustare.</p><p class="meta">Loss pe ajustare: ${fmt(a.raw.loss,3)} → ${fmt(a.adjusted.loss,3)}. Loss pe test: ansamblu brut ${fmt(r.report.rawTest.loss,3)} → ajustat ${fmt(r.report.test.loss,3)}. Efectul pe test poate fi nefavorabil; nu selectăm temperatura după el.</p><p class="meta">Voturi declin / mixt / avans: ${d.votes.join(' / ')}. Dacă fiecare rețea alege altă clasă sau diferența depășește 35 pp, interpretarea este blocată. Acordul rețelelor nu demonstrează corectitudinea estimării.</p></details></section>`;}
function markup(p,i){const m=context.model(p),record=read(p),state=N.assess(record,{symbol:context.symbol(p),currency:m?.currency,asOf:m?.asOf,demo:context.demo}),result=record?.result,usable=N.valid(result)&&!['invalid','stale','missing'].includes(state.state),active=job?.scope===context.scope&&job.ticker===p.ticker,busy=!!job;const error=errors.get(storageKey(context.scope,p.ticker));
 const metrics=usable?`<div class="neural-metrics"><div><small>Exemple de test</small><b>${result.report.test.n}</b></div><div><small>Loss rețea · mai mic e mai bun</small><b>${fmt(result.report.test.loss,3)}</b></div><div><small>Loss liniar / frecvențe</small><b>${fmt(result.report.linear.loss,3)} / ${fmt(result.report.constant.loss,3)}</b></div><div><small>Acuratețe echilibrată · test</small><b>${fmt(result.report.test.balanced*100,1)}%</b></div></div>`:'';
 const scores=usable&&!['drift','disagreement'].includes(state.state)?`<div class="neural-scores">${N.CLASSES.map((s,k)=>`<div><div><span>${s}</span><b>${fmt(result.support[k]*100,1)}%</b></div><div class="neural-meter"><span style="width:${result.support[k]*100}%"></span></div></div>`).join('')}</div><p class="meta">${result.adjustment.eligible?"Scoruri mediate din trei rețele și ajustate pe un interval separat de validare.":"Scoruri mediate din trei rețele; calibrare insuficientă, distribuție neajustată."} Calibrarea pe piață nu este confirmată. Procentele nu reprezintă probabilitatea unui profit sau o recomandare de tranzacționare.</p>`:'';
 const details=usable?`<details class="neural-details"><summary>Verificarea modelului și datele folosite</summary><p>Epoci selectate: ${result.memberEpochs.join(" / ")}. Media a trei rețele cu inițializări fixe, regularizare L2 ${result.regularization}. Ponderile și normalizarea folosesc antrenarea. O primă parte a validării selectează epocile; ultima parte, separată prin eliminarea etichetelor suprapuse, selectează temperatura. Testul nu selectează parametri.</p><div class="neural-table-wrap"><table><thead><tr><th>Interval</th><th>De la</th><th>Până la</th><th>Exemple</th></tr></thead><tbody>${Object.entries(result.report.periods).map(([k,v])=>`<tr><td>${{train:'Antrenare',validation:'Validare',test:'Test'}[k]}</td><td>${new Date(v.from).toISOString().slice(0,10)}</td><td>${new Date(v.to).toISOString().slice(0,10)}</td><td>${v.n}</td></tr>`).join('')}</tbody></table></div><p class="meta">Etichetele de antrenare se încheie înaintea validării; cele de validare, înaintea testului. Exemplele zilnice se suprapun și nu sunt tranzacții independente.</p><div class="neural-inputs">${N.FEATURES.map((s,k)=>`<div><span>${s}</span><b>${fmt(result.latest[k])}${k===7?'':k===9?'×':'%'}</b></div>`).join('')}</div><p class="meta">Distanță maximă față de distribuția antrenării: ${fmt(result.maxZ,1)} deviații standard. Peste 6, interpretarea este blocată.</p><button data-neural-export="${i}">Descarcă raportul modelului</button></details>`:'';
 return `<section class="neural-card"><div class="neural-heading"><div><span class="eyebrow">NEURAL LAB · ${context.demo?'DATE FICTIVE':'CERCETARE LOCALĂ'}</span><h3>Rețea neuronală pentru ${esc(context.symbol(p)||p.ticker)}</h3><p>Mișcarea în următoarele 5 sesiuni: declin, mixt sau avans față de ±1 ATR curent.</p></div><span class="tag">Experimental</span></div>${drawing(usable?result:null)}<div class="neural-verdict ${['no-edge','drift','fragile','disagreement'].includes(state.state)?'warn':''}"><b>${esc(active?'Antrenare în curs…':state.message)}</b><p class="meta">${record?.asOf&&usable?'EOD '+esc(record.asOf)+' · '+esc(record.source)+' · antrenat '+esc(new Date(record.trainedAt).toLocaleString('ro-RO')):'Analiza tehnică și planul tău rămân disponibile în celelalte file.'}</p></div><div class="neural-controls"><button class="primary" data-neural-train="${i}" ${busy||!m||!context.symbol(p)?'disabled':''}>${record?'Reantrenează modelul':'Antrenează pe istoric'}</button>${busy?`<button data-neural-cancel>Anulează${active?'':' antrenarea în curs'}</button>${active?'<progress data-neural-progress max="180" value="0"></progress>':''}`:''}</div><p class="meta" data-neural-status role="status" aria-live="polite">${esc(error||(!m?'Este necesară o analiză EOD actuală.':context.demo?'Demo: 1100 sesiuni fictive. Rezultatele demonstrează mecanismul.':'Solicită până la 5 ani OHLC. Antrenarea și cele trei evaluări rulează pe dispozitivul tău; datele contului nu intră în model.'))}</p>${metrics}${usable?diagnostics(result):""}${usable?walkMarkup(result.walk):''}${scores}${details}<details class="neural-details"><summary>Ce poate și ce nu poate învăța</summary><p>Ansamblu de trei MLP 10 → 12 → 3, antrenate prin backpropagation; desenul arată prima rețea. Indicatori de preț, trend, RSI, ATR și volum; nu include știri, earnings, fundamentale, FX, breadth sau expunerea contului. Eticheta descrie schimbarea închiderii după 5 sesiuni față de închiderea analizată, fără costuri.</p><p>Comparație cu un model liniar și cu frecvențele claselor. Avantajul cere loss cu minimum 0,02 mai mic și acuratețe echilibrată cu minimum 2 puncte procentuale mai bună decât ambele repere. Avantajul repetat cere trei ferestre favorabile și controlul cu orizonturi fără suprapunere. Temperatura din 1 / 1,5 / 2 / 3 este aleasă pe calibrare pentru loss mai mic; aceasta nu dovedește calibrarea pe piață sau profitabilitatea.</p><p>Minimum 510 bare pentru testul recent și minimum 600 exemple etichetate pentru trei ferestre, cu volum verificabil și toate clasele reprezentate. Salturile zilnice peste 25% blochează antrenarea. Reantrenarea pe același istoric nu produce dovezi independente.</p><p><a href="../tools/holdings-neural-validation.html" target="_blank" rel="noopener">Verificarea pe instrumente publice și metodologia</a></p></details></section>`;
}
function card(p,i){return `<div data-neural-host="${i}"></div>`;}
function refresh(){if(!context)return;for(const host of document.querySelectorAll('[data-neural-host]')){if(host.closest('.holding')?.hidden||host.closest('[data-holding-panel]')?.hidden)continue;const i=Number(host.dataset.neuralHost),p=context.positions[i];if(!p)continue;const open=new Set([...host.querySelectorAll('details[open]')].map(d=>d.querySelector('summary')?.textContent)),focused=host.contains(document.activeElement)?document.activeElement?.getAttribute('data-neural-train')!==null?'data-neural-train':document.activeElement?.getAttribute('data-neural-export')!==null?'data-neural-export':null:null;host.innerHTML=markup(p,i);host.querySelectorAll('details').forEach(d=>d.open=open.has(d.querySelector('summary')?.textContent));if(focused)host.querySelector('['+focused+']')?.focus({preventScroll:true});}bind(false,false);}
function cancel(update=true){if(job){if(update)errors.set(storageKey(job.scope,job.ticker),'Antrenare anulată. Modelul anterior, dacă există, este păstrat.');job.worker?.terminate();clearTimeout(job.timeout);job=null;serial++;}if(update)refresh();}
function finish(current,error,result){if(job!==current||context.scope!==current.scope||context.demo!==current.demo)return;current.worker?.terminate();clearTimeout(current.timeout);job=null;const key=storageKey(current.scope,current.ticker);if(error)errors.set(key,error);else try{const record={symbol:current.symbol,currency:current.currency,kind:current.demo?'synthetic':'market',asOf:current.asOf,source:current.demo?'SIMULARE · nu cotații':'Yahoo Finance OHLC · antrenare locală',trainedAt:Date.now(),result};if(!N.valid(result))throw Error('Rezultatul neuronal nu poate fi verificat.');if(current.demo)memory.set(key,JSON.stringify(record));else localStorage.setItem(key,JSON.stringify(record));errors.delete(key);}catch(e){errors.set(key,'Modelul nu a fost salvat: '+e.message);}refresh();}
async function train(p){if(job)return;const m=context.model(p),symbol=context.symbol(p);if(!m||!symbol)return;const current=job={id:++serial,scope:context.scope,ticker:p.ticker,demo:context.demo,symbol,currency:m.currency,asOf:m.asOf};errors.delete(storageKey(current.scope,current.ticker));refresh();
 try{let bars;if(current.demo)bars=N.demoBars(p.ticker==='FICTIVB_US_EQ'?2:0,Date.parse(m.asOf+'T23:59:00Z'));else{const raw=await D.fetchStock(symbol,{range:'5y',interval:'1d',ttl:0});const source=DailySeries.read(raw,symbol);if(source.asOf!==m.asOf||source.currency!==m.currency)throw Error('Istoricul și analiza curentă nu au aceeași sesiune și monedă.');bars=source.bars;}if(job!==current)return;if(typeof Worker==='undefined')throw Error('Browserul nu oferă antrenare în fundal.');current.worker=new Worker('neural-worker.js?v='+N.VERSION);current.worker.onmessage=e=>{if(job!==current||e.data.id!==current.id)return;if(e.data.progress){const p=e.data.progress;for(const host of document.querySelectorAll('[data-neural-host]'))if(context.positions[Number(host.dataset.neuralHost)]?.ticker===current.ticker){if(host.querySelector('[data-neural-status]'))host.querySelector('[data-neural-status]').textContent=(p.stage?'Fereastra '+p.stage+' / '+p.stages+' · ':'')+(p.member?'Rețeaua '+p.member+' / '+p.members+' · ':'')+'Epoca '+p.epoch+' / '+p.total+' · loss validare '+fmt(p.loss,3);const progress=host.querySelector('[data-neural-progress]');if(progress){progress.max=p.total;progress.value=p.epoch;}}}else finish(current,e.data.error,e.data.result);};current.worker.onerror=()=>finish(current,'Workerul nu a putut finaliza antrenarea.');current.timeout=setTimeout(()=>finish(current,'Antrenarea a depășit 300 secunde; rezultatul nu este utilizat.'),300000);current.worker.postMessage({id:current.id,bars,now:Date.now()});}catch(e){finish(current,e.message);}}
function exportReport(record){
 document.querySelector('.neural-report')?.close();
 const json=JSON.stringify(record,null,2),url=URL.createObjectURL(new Blob([json],{type:'application/json'})),dialog=document.createElement('dialog');dialog.className='neural-report';dialog.setAttribute('aria-labelledby','neural-report-title');
 dialog.innerHTML=`<div class="neural-report-heading"><h3 id="neural-report-title">Raport neuronal · ${esc(record.symbol)}</h3><button type="button" data-neural-close>Închide</button></div><p>EOD ${esc(record.asOf)} · ${record.kind==='synthetic'?'DATE FICTIVE':'cercetare locală'}. Conține ponderile modelului și verificările; procentele rămân necalibrate.</p><a class="neural-download" download>Descarcă JSON</a><details><summary>Vezi și copiază raportul JSON</summary><label for="neural-report-json">Raport complet · selectează textul pentru copiere</label><textarea id="neural-report-json" readonly spellcheck="false"></textarea></details>`;
 const link=dialog.querySelector('a');link.href=url;link.download='neural-'+record.symbol.replace(/[^A-Za-z0-9._-]/g,'_')+'-'+record.asOf+'.json';dialog.querySelector('textarea').value=json;dialog.querySelector('[data-neural-close]').onclick=()=>dialog.close();dialog.onclose=()=>{dialog.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);};document.body.appendChild(dialog);dialog.showModal();
}
function bind(auto=true,draw=true){if(!delegated){delegated=true;document.addEventListener('click',e=>{if(e.target.closest('[data-holding-tab="neural"]'))queueMicrotask(refresh);});}if(draw)refresh();for(const button of document.querySelectorAll('[data-neural-train]'))button.onclick=()=>{const p=context.positions[Number(button.dataset.neuralTrain)];if(p)train(p);};for(const button of document.querySelectorAll('[data-neural-cancel]'))button.onclick=()=>cancel();for(const button of document.querySelectorAll('[data-neural-export]'))button.onclick=()=>{const record=read(context.positions[Number(button.dataset.neuralExport)]);if(record&&N.valid(record.result))exportReport(record);};if(auto&&!demoStarted&&context.demo&&new URLSearchParams(location.search).get('neural')==='1'&&context.positions[0]&&context.model(context.positions[0])){demoStarted=true;document.querySelector('.holding[data-ticker] [data-holding-tab="neural"]')?.click();train(context.positions[0]);}}
setInterval(()=>{if(context&&!job)refresh();},60000);
g.HoldingsNeuralUI={setContext,card,bind,cancel};
})(typeof window!=='undefined'?window:globalThis);
