(function(g){
'use strict';
let context=null;const selections=new Map();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=3)=>Number.isFinite(v)?v.toLocaleString('ro-RO',{minimumFractionDigits:d,maximumFractionDigits:d}):'—',pct=v=>Number.isFinite(v)?fmt(v*100,1)+'%':'—';
const apis=()=>({neural:g.HoldingsNeuralUI,hmm:g.HoldingsHMMUI,isolation:g.HoldingsIsolationUI,quantile:g.HoldingsQuantileUI,garch:g.HoldingsGarchUI});
function setContext(c){if(!context||context.scope!==c.scope||context.demo!==c.demo)selections.clear();context=c;}
function selected(p){return selections.get(p.ticker)??2;}
function expected(p){const m=context.model(p),b=m?.bars?.at(-1);if(!b||typeof m.sourceFingerprint!=='string')return null;return {symbol:context.symbol(p),currency:m.currency,asOf:m.asOf,kind:context.demo?'synthetic':'market',t:b.t,close:m.price,timezone:m.timezone||'America/New_York',closeMinutes:m.closeMinutes??960,fingerprint:m.sourceFingerprint};}
function report(p,snapshots){const source=expected(p);snapshots??=Object.fromEntries(Object.entries(apis()).map(([id,api])=>[id,api?.inspect(p)]));return g.HoldingsPerformance.build({expected:source,snapshots,item:g.HoldingsForecastUI.snapshot(p),probabilistic:g.HoldingsForecastUI.probabilistic(p,source,snapshots)});}
const values=xs=>'<dl class="performance-metrics">'+xs.map(m=>'<div><dt>'+esc(m.label)+'</dt><dd>'+fmt(m.value,m.precision)+esc(m.unit)+'</dd></div>').join('')+'</dl>';
function windows(m,zone){const day=t=>g.DailySeries.date(t,zone);return '<details class="performance-windows"><summary>Ferestrele de test și reperele</summary><div class="performance-table-wrap"><table><thead><tr><th>Test · sesiuni EOD</th><th>Exemple / blocuri</th><th>Scor model</th><th>Cel mai bun reper</th></tr></thead><tbody>'+m.windows.map(w=>'<tr><th>'+esc(day(w.from))+' → '+esc(day(w.to))+'</th><td>'+w.n+'</td>'+ (w.status==='evaluated'?'<td>'+fmt(w.score)+(m.id==='isolation'?'%':'')+'</td><td>'+fmt(w.baseline)+'</td>':'<td colspan="2">Blocat: '+esc(w.error)+'</td>')+'</tr>').join('')+'</tbody></table></div><p class="meta">'+(m.id==='isolation'?'Scorul din tabel este rata semnalelor, cu interpretare descriptivă.':m.id==='garch'?'Tabelul rezumă QLIKE la 5 sesiuni; valorile la 20 sesiuni sunt afișate separat.':m.id==='quantile'?'Scorul de interval este în unități ATR.':'Scor mai mic este mai bun pentru model și reperele lui.')+' Etichetele închiderii la +5 sesiuni se pot încheia după ultima origine afișată.</p>'+values(m.control)+'</details>';}
function historyMarkup(r){return '<h4>Testele istorice · recalculare cronologică</h4><p class="meta">'+r.historical.available+' / 6 rapoarte actuale verificate · '+r.historical.complete+' / 6 modele cu trei ferestre evaluate. Ferestrele pot diferi între tipurile de model.</p><div class="performance-grid">'+r.historical.models.map(m=>'<article class="performance-model"><header><h5>'+esc(m.name)+'</h5><span class="tag">'+(m.status==='complete'?'3 ferestre':m.status==='partial'?'Test parțial':m.status==='recent'?'Test recent':'Indisponibil')+'</span></header><b>'+esc(m.judgment)+'</b>'+values(m.metrics)+'<p class="meta">'+esc(m.reason)+'</p>'+(m.windows.length?windows(m,r.timezone):'')+'</article>').join('')+'</div>';}
function prospectiveMarkup(r,classIndex){const p=r.prospective;if(!p.ok)return '<h4>Predicțiile urmărite în timp</h4><p role="status">'+esc(p.reason)+'</p>';
 const rows=p.models.filter(m=>['neural','boosting','verdict'].includes(m.id)),probability=rows.filter(m=>m.probability.n>0);
 let html='<h4>Predicțiile urmărite în timp</h4><p class="meta">'+esc(p.reason)+(p.restoredExcluded?' '+p.restoredExcluded+' estimări restaurate sunt disponibile în registru și excluse din această măsurare.':'')+'</p><div class="performance-table-wrap"><table><thead><tr><th>Model</th><th>Rezultate verificate / separate</th><th>Probabilități evaluate</th><th>Log loss</th><th>Brier</th><th>În așteptare</th></tr></thead><tbody>'+rows.map(m=>'<tr><th>'+esc(m.name)+'</th><td>'+m.all+' / '+m.n+'</td><td>'+m.probability.n+'</td><td>'+fmt(m.probability.loss)+'</td><td>'+fmt(m.probability.brier)+'</td><td>'+m.pending+'</td></tr>').join('')+'</tbody></table></div>';
 html+='<p class="meta">Fiecare model folosește propriile estimări păstrate. Numărul din a doua coloană după „/” este controlul fără suprapunere. Estimările vechi fără probabilități contribuie la direcție, cu probabilități evaluate numai unde au fost păstrate inițial.</p>';
 const v=rows.find(m=>m.id==='verdict');if(v)html+='<p>'+v.directional+' verdicte direcționale verificate · '+v.abstentions+' abțineri · '+(v.probability.validated||0)+' rezultate ale unei combinații validate. Abținerile cu probabilități sunt incluse în Log loss și Brier.</p>';
 if(!probability.length)html+='<p class="performance-empty">Probabilitățile păstrate nu au încă rezultate verificate. Valorile se completează după închiderea orizontului de +5 sesiuni.</p>';
 if(probability.length)html+='<details><summary>Cât de bine corespund probabilitățile cu rezultatele?</summary><p>Clasa selectată se verifică pe probabilitățile originale, grupate în intervale de 20 puncte procentuale. Eșantioanele mici rămân descriptive.</p>'+probability.map(m=>'<h5>'+esc(m.name)+' · '+m.probability.n+' orizonturi</h5><div class="performance-table-wrap"><table><thead><tr><th>Probabilitate înscrisă</th><th>Observații</th><th>Probabilitate medie</th><th>Frecvență observată</th></tr></thead><tbody>'+m.probability.reliability[classIndex].map(b=>'<tr><th>'+Math.round(b.from*100)+'–'+Math.round(b.to*100)+'%</th><td>'+b.n+'</td><td>'+pct(b.predicted)+'</td><td>'+pct(b.observed)+'</td></tr>').join('')+'</tbody></table></div>').join('')+'</details>';
 const others=p.models.filter(m=>!['neural','boosting','verdict'].includes(m.id));
 html+='<details><summary>Rezultatele celorlalte modele urmărite în timp</summary><div class="performance-grid">'+others.map(m=>{const metrics=[metricCount('Orizonturi separate',m.n),metricCount('În așteptare',m.pending),metricCount('Rezultate excluse',m.unverifiable)];if(m.id==='quantile')metrics.push({label:'Acoperire observată',value:Number.isFinite(m.coverage)?m.coverage*100:null,unit:'%',precision:1},{label:'Scor de interval',value:m.score,unit:' ATR',precision:3},{label:'Scor · reper',value:m.baselineScore,unit:' ATR',precision:3});if(m.id==='garch')metrics.push({label:'QLIKE',value:m.score,unit:'',precision:3},{label:'Varianță constantă',value:m.constantScore,unit:'',precision:3},{label:'EWMA',value:m.ewmaScore,unit:'',precision:3});return '<article class="performance-model"><h5>'+esc(m.name)+' · +'+m.horizon+' sesiuni</h5>'+values(metrics)+'<p class="meta">'+esc(m.warning)+'</p></article>';}).join('')+'</div></details>';return html;
}
function metricCount(label,value){return {label,value,unit:'',precision:0};}
function markup(p,i,snapshots){if(!context)return '';const r=report(p,snapshots),busy=g.HoldingsAutoLearningUI?.busy()||g.HoldingsVerdictUI?.busy()||Object.values(apis()).some(api=>api?.busy()),classIndex=selected(p);
 return '<section class="holdings-performance" id="model-lab-'+i+'-performance" tabindex="-1" aria-label="Performanța AI"><div class="performance-heading"><div><span class="eyebrow">DOVEZI PE INSTRUMENT</span><h3>Performanța AI · '+esc(r.symbol||p.ticker)+'</h3></div><span class="tag">'+(context.demo?'DEMO · date fictive':'Date de piață · cercetare')+'</span></div><p>EOD '+esc(r.asOf||'indisponibil')+' · '+esc(r.currency||'—')+'. Scorurile istorice și rezultatele după captură se afișează separat.</p><div class="performance-actions"><button data-performance-run="'+i+'" '+(busy||!context.model(p)?'disabled':'')+'>Recalculează testele istorice</button><button data-performance-check="'+i+'" '+(busy?'disabled':'')+'>Verifică predicțiile păstrate</button><button data-performance-export="'+i+'">Exportă performanța AI</button></div><section class="performance-verdict"><b>'+esc(r.verdict.title)+'</b>'+r.verdict.reasons.map(reason=>'<p>'+esc(reason)+'</p>').join('')+'</section>'+historyMarkup(r)+'<label class="performance-class">Clasa verificată în tabelul probabilităților<select data-performance-class="'+i+'">'+['Declin','Mixt','Avans'].map((name,k)=>'<option value="'+k+'" '+(k===classIndex?'selected':'')+'>'+name+'</option>').join('')+'</select></label>'+prospectiveMarkup(r,classIndex)+'<details class="performance-method"><summary>Cum interpretăm performanța</summary><p>Log loss și Brier penalizează probabilitățile greșite; valori mai mici sunt mai bune. Brier însumează erorile celor trei clase, pe scara 0–2. Acuratețea echilibrată dă aceeași importanță fiecărei clase și rămâne indisponibilă dacă lipsește o clasă.</p><p>Recalcularea rulează toate cele șase modele pe un singur istoric verificat. Parametrii, normalizarea, pragurile și calibrarea fiecărui test folosesc perioadele anterioare. HMM și varianța GARCH se actualizează cronologic, cu observațiile deja cunoscute.</p>'+r.limits.map(limit=>'<p>'+esc(limit)+'</p>').join('')+'</details></section>';
}
function bind(){
 for(const b of document.querySelectorAll('[data-performance-run]'))b.onclick=()=>{const p=context.positions[Number(b.dataset.performanceRun)];if(p)void g.HoldingsAutoLearningUI.tick(true,p.ticker);};
 for(const b of document.querySelectorAll('[data-performance-check]'))b.onclick=()=>{const p=context.positions[Number(b.dataset.performanceCheck)];if(p)void g.HoldingsForecastUI.check(p,true);};
 for(const b of document.querySelectorAll('[data-performance-class]'))b.onchange=()=>{const p=context.positions[Number(b.dataset.performanceClass)],v=Number(b.value);if(p&&[0,1,2].includes(v)){selections.set(p.ticker,v);g.HoldingsNeuralUI.refresh();}};
 for(const b of document.querySelectorAll('[data-performance-export]'))b.onclick=()=>{const p=context.positions[Number(b.dataset.performanceExport)];if(p){const result=report(p);g.HoldingsNeuralUI.exportReport({symbol:result.symbol||p.ticker,currency:result.currency,kind:result.kind,asOf:result.asOf||'indisponibil',result});}};
}
g.HoldingsPerformanceUI={setContext,markup,bind,report};
})(typeof window!=='undefined'?window:globalThis);
