(function(g){
'use strict';
const Q=g.HoldingsQuantile,N=g.HoldingsNeural,memory=new Map(),errors=new Map(),demoStarted=new Set();let context=null,job=null,serial=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString('ro-RO',{minimumFractionDigits:d,maximumFractionDigits:d}):'—',day=t=>new Date(t).toISOString().slice(0,10);
const key=p=>'tt_holdings_quantile_v1:'+encodeURIComponent(context.scope)+'|'+encodeURIComponent(p.ticker);
function read(p){try{const raw=context.demo?memory.get(key(p)):localStorage.getItem(key(p));return raw?JSON.parse(raw):null;}catch{return null;}}
function usable(r,p,m,now=Date.now()){try{return !!r&&Number.isFinite(r.sourceTime)&&r.symbol===context.symbol(p)&&r.currency===m?.currency&&r.asOf===m?.asOf&&r.result?.current?.t===r.sourceTime&&g.DailySeries?.date(r.sourceTime,r.timezone)===r.asOf&&(context.demo||!Number.isFinite(m?.price)||Math.abs(r.result.current.close-m.price)<=1e-6*Math.max(1,m.price))&&r.kind===(context.demo?'synthetic':'market')&&Number.isFinite(r.trainedAt)&&r.trainedAt<=now&&now-r.trainedAt<=1800000&&Q.valid(r.result);}catch{return false;}}
function cancel(update=true){if(job){if(update)errors.set(job.key,'Estimare anulată. Raportul anterior este păstrat.');job.worker?.terminate();clearTimeout(job.timeout);job=null;serial++;}if(update)refresh();}
function setContext(c){if(context&&(context.scope!==c.scope||context.demo!==c.demo))cancel(false);if(job){const p=c.positions.find(p=>p.ticker===job.ticker),m=p?c.model(p):null;if(!p||c.symbol(p)!==job.symbol||m?.currency!==job.currency||m?.asOf!==job.asOf||!c.demo&&m?.price!==job.price)cancel(false);}context=c;}
function refresh(){g.HoldingsNeuralUI?.refresh();}
function inspect(p){const r=read(p),ok=usable(r,p,context.model(p));return {record:r,usable:ok,assessment:ok?Q.assess(r.result):null};}
function chart(c,currency){
 if(!c||![c.close,...(c.prices||[])].every(Number.isFinite)||c.prices?.length!==3||c.prices.some(v=>v<=0)||c.prices[0]>c.prices[1]||c.prices[1]>c.prices[2])return '';
 const values=[c.close,...c.prices],lo=Math.min(...values),hi=Math.max(...values),pad=Math.max((hi-lo)*.25,hi*.003),y=v=>175-(v-lo+pad)/(hi-lo+2*pad)*140;
 return '<figure class="quantile-chart"><svg viewBox="0 0 540 220" role="img" aria-label="Preț EOD '+esc(fmt(c.close)+' '+currency)+'. Interval pentru închiderea peste cinci sesiuni: '+esc(fmt(c.prices[0])+'–'+fmt(c.prices[2])+' '+currency)+', mediană '+esc(fmt(c.prices[1]))+'. Nu este traiectoria prețului."><line x1="60" y1="185" x2="480" y2="185" class="quantile-axis"/><line x1="75" y1="'+y(c.close)+'" x2="425" y2="'+y(c.close)+'" class="quantile-reference"/><circle cx="95" cy="'+y(c.close)+'" r="5" class="quantile-dot"/><text x="68" y="'+(y(c.close)-12)+'">'+fmt(c.close)+'</text><rect x="348" y="'+y(c.prices[2])+'" width="65" height="'+Math.max(1,y(c.prices[0])-y(c.prices[2]))+'" rx="6" class="quantile-band"/><line x1="339" x2="422" y1="'+y(c.prices[1])+'" y2="'+y(c.prices[1])+'" class="quantile-median"/><text x="242" y="'+(y(c.prices[1])+4)+'">'+fmt(c.prices[1])+'</text><text x="430" y="'+(y(c.prices[2])-9)+'">'+fmt(c.prices[2])+'</text><text x="430" y="'+(y(c.prices[0])+17)+'">'+fmt(c.prices[0])+'</text><text x="75" y="210">EOD</text><text x="326" y="210">+5 sesiuni · '+esc(currency)+'</text></svg><figcaption>Interval pentru închiderea la +5 sesiuni. Nu descrie maximele, minimele sau drumul prețului.</figcaption></figure>';
}
function markup(p,i,inspection=inspect(p)){
 const m=context.model(p),{record:r,usable:ok,assessment:a}=inspection,result=ok?r.result:null,active=job?.ticker===p.ticker,busy=!!job||g.HoldingsNeuralUI?.busy()||g.HoldingsHMMUI?.busy()||g.HoldingsIsolationUI?.busy();
 const metric=(label,value)=>'<div><small>'+label+'</small><b>'+value+'</b></div>';
 let html='<section class="quantile-card" data-quantile-host="'+i+'" id="model-lab-'+i+'-quantile" tabindex="-1"><div class="hmm-heading"><div><span class="eyebrow">AL CINCILEA MODEL · INTERVALE</span><h4>Regresie cu cuantile</h4><p>Unde ar putea închide prețul peste cinci sesiuni și cât de larg este intervalul estimat?</p></div><span class="tag">'+(context.demo?'Date fictive':'Experimental')+'</span></div><div class="hmm-controls"><button class="primary" data-quantile-train="'+i+'" '+(busy||!m||!context.symbol(p)?'disabled':'')+'>'+(r?'Reestimează intervalul':'Estimează intervalul')+'</button>'+(active?'<button data-quantile-cancel>Anulează estimarea</button><progress data-quantile-progress max="180" value="0"></progress>':'')+'</div><p class="meta" role="status" aria-live="polite" data-quantile-status>'+esc(errors.get(key(p))||(active?'Calculez intervalele în fundal…':busy?'Aștept finalizarea modelului activ.':!m?'Rulează mai întâi analiza EOD.':r&&!ok?'Raport expirat sau incompatibil. Reestimează pe sesiunea curentă.':'Estimare separată de modelele de direcție, calculată pe dispozitiv.'))+'</p>';
 if(result){const c=result.current,t=result.report.test,b=result.report.baseline;
  html+='<div class="hmm-verdict '+(a.state==='descriptive'?'':'warn')+'"><b>'+esc(a.state==='drift'?'Estimare ascunsă':a.state==='descriptive'?'Interval experimental':'Interval de monitorizat')+'</b><p>'+esc(a.message)+'</p><small>EOD '+esc(r.asOf)+' · închidere la +5 sesiuni · acoperire urmărită 80%</small></div>';
  if(a.state!=='drift')html+=chart(c,r.currency)+'<div class="hmm-test-grid">'+metric('Limită inferioară estimată',fmt(c.prices[0])+' '+esc(r.currency))+metric('Mediană estimată',fmt(c.prices[1])+' '+esc(r.currency))+metric('Limită superioară estimată',fmt(c.prices[2])+' '+esc(r.currency))+'</div><p class="meta">Lățime '+fmt(c.widthPct)+'% din prețul EOD. Acoperirea nominală de 80% nu este probabilitatea unui profit sau o garanție pentru această deținere.</p>';
  html+='<div class="hmm-test-grid">'+metric('Închideri incluse · test recent',t.covered+' / '+t.n+' · '+fmt(t.coverage*100,1)+'%')+metric('Acoperire · orizonturi separate',result.report.nonOverlap.covered+' / '+result.report.nonOverlap.n)+metric('Ferestre cu scor mai bun decât reperul',result.walk.status==='evaluated'?result.walk.wins+' / 3':'Istoric insuficient')+'</div>';
  html+='<details class="neural-details"><summary>Verificarea intervalelor estimate</summary><div class="neural-table-wrap"><table><thead><tr><th>Test recent</th><th>Model</th><th>Cuantile istorice simple</th></tr></thead><tbody><tr><td>Acoperire observată</td><td>'+fmt(t.coverage*100,1)+'%</td><td>'+fmt(b.coverage*100,1)+'%</td></tr><tr><td>Lățime medie · ATR</td><td>'+fmt(t.width)+'</td><td>'+fmt(b.width)+'</td></tr><tr><td>Scor de interval · ATR</td><td>'+fmt(t.score,3)+'</td><td>'+fmt(b.score,3)+'</td></tr><tr><td>Loss pinball mediu · ATR</td><td>'+fmt(t.pinball,3)+'</td><td>'+fmt(b.pinball,3)+'</td></tr></tbody></table></div><p class="meta">Scor mai mic este mai bun: penalizează lățimea și închiderile ratate. O acoperire mare obținută prin intervale foarte largi nu dovedește utilitate.</p><ul class="quantile-periods">'+Object.entries(result.report.periods).map(([k,v])=>'<li>'+({train:'Antrenare',validation:'Validare',reference:'Referință pentru ajustare',test:'Test'}[k])+': '+day(v.from)+' → '+day(v.to)+' · '+v.n+' exemple</li>').join('')+'</ul><p class="meta">Ajustarea limitelor: '+fmt(result.calibration.delta,3)+' ATR din '+result.calibration.rows.length+' orizonturi de referință fără suprapunere. Nici testul, nici prețul viitor nu aleg această ajustare.</p>';
  if(result.walk.status==='evaluated')html+='<div class="neural-table-wrap"><table><thead><tr><th>Fereastră de test</th><th>Incluse</th><th>Scor model / reper</th></tr></thead><tbody>'+result.walk.folds.map(f=>'<tr><td>'+day(f.report.periods.test.from)+' → '+day(f.report.periods.test.to)+'</td><td>'+f.report.test.covered+' / '+f.report.test.n+'</td><td>'+fmt(f.report.test.score,3)+' / '+fmt(f.report.baseline.score,3)+'</td></tr>').join('')+'</tbody></table></div>';else html+='<p class="meta">Trei ferestre indisponibile: '+esc(result.walk.reason)+'</p>';
  html+='<p class="meta">Cuantile brute reordonate în '+t.crossings+' / '+t.n+' exemple de test. Testele zilnice se suprapun în interiorul ferestrei; controlul cu orizonturi separate poate rămâne corelat.</p><button data-quantile-export="'+i+'">Descarcă raportul cuantilelor</button></details>';
 }
 return html+'<details class="neural-details"><summary>Metodă și limite ale cuantilelor</summary><p>Trei regresii liniare cu loss pinball estimează cuantilele 10%, 50% și 90% ale randamentului la cinci sesiuni, exprimat în ATR curent. Normalizarea și coeficienții folosesc numai antrenarea; validarea selectează iterația. Limitele sunt ordonate înaintea ajustării pe o referință separată și apoi evaluate pe test.</p><p>Regimurile financiare nu sunt interschimbabile: ajustarea pe trecut nu oferă o garanție de acoperire în viitor. Nu sunt incluse știri, earnings, FX, costuri sau riscul întregului portofoliu. Datele insuficiente și ieșirea din domeniul învățat sunt semnalate. Acest model nu votează în verdictul Neural / Boosting.</p><p><a href="../tools/holdings-quantile-validation.html" target="_blank" rel="noopener">Verificarea publică și metodologia cuantilelor</a></p></details><a class="model-back" data-model-jump="summary" href="#model-lab-'+i+'-summary">Sinteză ↑</a></section>';
}
function finish(current,error,result){
 if(job!==current||context.scope!==current.scope||context.demo!==current.demo)return;current.worker?.terminate();clearTimeout(current.timeout);job=null;
 if(error)errors.set(current.key,error);else try{if(!Q.valid(result)||result.current.t!==current.sourceTime)throw Error('Raport neverificabil sau sesiune diferită.');const record={symbol:current.symbol,currency:current.currency,kind:current.demo?'synthetic':'market',asOf:current.asOf,sourceTime:current.sourceTime,timezone:current.timezone,trainedAt:Date.now(),result};if(current.demo)memory.set(current.key,JSON.stringify(record));else localStorage.setItem(current.key,JSON.stringify(record));errors.delete(current.key);}catch(e){errors.set(current.key,'Intervalul nu a fost salvat: '+e.message);}refresh();
}
async function train(p){
 if(!p||job||g.HoldingsNeuralUI?.busy()||g.HoldingsHMMUI?.busy()||g.HoldingsIsolationUI?.busy())return;const m=context.model(p),symbol=context.symbol(p);if(!m||!symbol)return;
 const current=job={id:++serial,key:key(p),scope:context.scope,ticker:p.ticker,demo:context.demo,symbol,currency:m.currency,asOf:m.asOf,price:m.price,timezone:'America/New_York'};errors.delete(current.key);refresh();
 try{let bars;if(current.demo)bars=N.demoBars(p.ticker==='FICTIVB_US_EQ'?2:0,Date.parse(m.asOf+'T23:59:00Z'));else{const raw=await D.fetchStock(symbol,{range:'5y',interval:'1d',ttl:0}),source=DailySeries.read(raw,symbol);if(source.asOf!==m.asOf||source.currency!==m.currency)throw Error('Istoricul cuantilelor și analiza EOD nu au aceeași sesiune și monedă.');bars=source.bars;if(Number.isFinite(m.price)&&Math.abs(bars.at(-1).c-m.price)>1e-6*Math.max(1,m.price))throw Error('Prețul EOD diferă de analiza deținerii. Actualizează analiza înaintea estimării.');current.timezone=source.timezone;}
  if(job!==current)return;current.sourceTime=bars.at(-1)?.t;if(typeof Worker==='undefined')throw Error('Browserul nu oferă analiză în fundal.');current.worker=new Worker('quantile-worker.js?v='+Q.VERSION);
  current.worker.onmessage=e=>{if(job!==current||e.data.id!==current.id)return;if(e.data.progress){const v=e.data.progress;for(const host of document.querySelectorAll('[data-quantile-host]'))if(context.positions[Number(host.dataset.quantileHost)]?.ticker===current.ticker){host.querySelector('[data-quantile-status]').textContent='Cuantile · Fereastra '+v.stage+' / '+v.stages+' · Cuantila '+v.member+' / 3 · Iterația '+v.epoch+' / '+v.total;const bar=host.querySelector('[data-quantile-progress]');if(bar)bar.value=v.epoch;}}else finish(current,e.data.error,e.data.result);};
  current.worker.onerror=()=>finish(current,'Workerul cuantilelor nu a putut finaliza estimarea.');current.timeout=setTimeout(()=>finish(current,'Estimarea a depășit 180 secunde; rezultatul nu este utilizat.'),180000);current.worker.postMessage({id:current.id,bars,now:Date.now()});
 }catch(e){finish(current,e.message);}
}
function demo(p){if(!context?.demo||!p||demoStarted.has(key(p)))return;demoStarted.add(key(p));train(p);}
function bind(){for(const b of document.querySelectorAll('[data-quantile-train]'))b.onclick=()=>train(context.positions[Number(b.dataset.quantileTrain)]);for(const b of document.querySelectorAll('[data-quantile-cancel]'))b.onclick=()=>cancel();for(const b of document.querySelectorAll('[data-quantile-export]'))b.onclick=()=>{const p=context.positions[Number(b.dataset.quantileExport)],r=read(p);if(usable(r,p,context.model(p)))g.HoldingsNeuralUI.exportReport(r);};}
g.HoldingsQuantileUI={setContext,inspect,markup,chart,bind,cancel,demo,busy:()=>!!job};
})(typeof window!=='undefined'?window:globalThis);
