(function(g){'use strict';
const $=id=>document.getElementById(id),R=g.HoldingRoster,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),finite=Number.isFinite,fmt=(v,c='',signed=false)=>finite(v)?(signed&&v>0?'+':'')+v.toLocaleString('ro-RO',{maximumFractionDigits:2})+(c?' '+c:''):'Neverificat';
const memory=new Map(),demo=R.create({getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)}),real=R.create({getItem:k=>localStorage.getItem(k),setItem:(k,v)=>localStorage.setItem(k,v)});
let context=null,contextKey=null,visit=null,favorites=[],pair=['',''],message='';
const kind=()=>context.demo?'synthetic':'market',engine=()=>context.demo?demo:real;
const refresh=()=>context&&(context.refreshRoster||context.refresh)();
function project(p,now=Date.now(),overrides={}){const identity=context.rosterIdentity?.(p)||{symbol:context.symbol(p)};return R.entry(p,{...identity,model:context.model(p),note:context.note(p),brokerAt:context.snapshot?.fetchedAt,now,...overrides});}
function setContext(c){const key=JSON.stringify([c.scope,!!c.demo]),changed=contextKey!==key;context=c;contextKey=key;if(changed){pair=[c.positions[0]?.ticker||'',c.positions[1]?.ticker||''];message='';$('holdingFavoritesOnly').checked=false;$('holdingChangesOnly').checked=false;}
 favorites=engine().favorites(c.scope,kind());visit=engine().observe(c.scope,c.positions.map(p=>project(p)),{kind:kind()});
 $('holdingRosterTools').hidden=!c.positions.length;renderVisit();renderSelectors();if($('holdingComparison').open)renderComparison();
}
function filter(rows){if(!context)return rows;const changed=new Set((visit?.rows||[]).filter(r=>r.changed).map(r=>r.ticker));return R.prioritize(rows.filter(r=>(!$('holdingFavoritesOnly').checked||favorites.includes(r.p.ticker))&&(!$('holdingChangesOnly').checked||changed.has(r.p.ticker))),favorites);}
function controls(p){const starred=favorites.includes(p.ticker),symbol=context?.symbol(p)||p.ticker;return '<button class="roster-star" data-roster-favorite="'+esc(p.ticker)+'" aria-label="'+(starred?'Elimină din favorite ':'Adaugă la favorite ')+esc(symbol)+'" aria-pressed="'+starred+'" title="'+(starred?'Elimină din favorite':'Păstrează prima în listă')+'">'+(starred?'★':'☆')+'</button>';}
function badge(p){const r=visit?.rows?.find(x=>x.ticker===p.ticker);return r?.changed?'<span class="roster-change">'+r.lines.length+' '+(r.lines.length===1?'schimbare':'schimbări')+'</span>':'';}
function bindRoster(host){for(const b of host.querySelectorAll('[data-roster-favorite]'))b.onclick=()=>{if(!context.positions.some(p=>p.ticker===b.dataset.rosterFavorite))return;const r=engine().toggle(context.scope,b.dataset.rosterFavorite,kind());message=r.reason||'';favorites=engine().favorites(context.scope,kind());refresh();};}
function renderVisit(){const rows=(visit?.rows||[]).filter(r=>r.changed),from=visit?.from?new Date(visit.from).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'}):null;
 $('holdingChangesCount').textContent=String(rows.length);$('holdingFavoritesLabel').textContent='Doar favorite · '+context.positions.filter(p=>favorites.includes(p.ticker)).length;
 $('holdingChangesLabel').textContent='Schimbate de la ultima vizită · '+rows.length;
 $('holdingVisitStatus').textContent=(context.demo?'DEMO · repere fictive. ':'')+(from?'Reper: '+from+'. ':'')+(message||visit?.reason||'Reper indisponibil.');
 const host=$('holdingVisitRows');g.ViewRefresh.patchList(host,rows,r=>context.scope+'|'+r.ticker,r=>'<article class="visit-change"><button data-open-visit="'+esc(r.ticker)+'">'+esc(r.symbol)+' · deschide analiza</button><ul>'+r.lines.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></article>');
 $('holdingVisitEmpty').textContent=visit?.state==='first'?'La prima vizită nu inventăm un istoric anterior.':visit?.state==='ready'?'Nicio schimbare comparabilă în reperele disponibile.':'Comparația nu este încă verificată.';$('holdingVisitEmpty').hidden=rows.length>0;
 $('holdingVisitSeen').disabled=!context.positions.length||visit?.state==='unavailable';$('holdingVisitDemo').hidden=!context.demo;
 for(const b of host.querySelectorAll('[data-open-visit]'))b.onclick=()=>g.HoldingsLayout.openHolding(b.dataset.openVisit,{scroll:true});
}
function renderSelectors(){for(const [i,id] of ['holdingCompareA','holdingCompareB'].entries()){const select=$(id),markup='<option value="">Alege o deținere</option>'+context.positions.map(p=>'<option value="'+esc(p.ticker)+'">'+esc(context.symbol(p)||p.ticker)+' · '+esc(p.name||p.ticker)+'</option>').join('');if(select.innerHTML!==markup)select.innerHTML=markup;if(!context.positions.some(p=>p.ticker===pair[i]))pair[i]='';select.value=pair[i];}}
function probability(p,m){if(!m||!g.HoldingsForecastUI||!g.HoldingsNeuralUI)return null;try{const n=g.HoldingsNeuralUI.inspect(p),last=m.bars?.at(-1);if(!n.usable||!last||!finite(last.t))return null;const source={symbol:context.symbol(p),currency:m.currency,asOf:m.asOf,t:last.t,kind:kind(),fingerprint:m.sourceFingerprint||g.HoldingsVerdict.fingerprint(m.bars)};return g.HoldingsForecastUI.probabilistic(p,source,{neural:n});}catch{return null;}}
function probabilityText(r){const p=r.probability;if(!p)return 'Modele actuale indisponibile.<small>Deschide Modele AI pentru verificare.</small>';const label=p.evidence?.phase==='suspended'?'Direcție suspendată':p.eligible?'Validată':p.checkpoint?'Validată · abținere':'Exploratorie · fără direcție activă';return ['Declin','Mixt','Avans'].map((n,i)=>'<span class="compare-prob">'+n+' '+fmt(p.probabilities[i]*100,'%')+'</span>').join('')+'<small>'+label+' · '+(p.evidence?.test?.n||0)+' rezultate în testul activ.</small>';}
function renderComparison(){if(!context)return;const host=$('holdingCompareResult'),positions=pair.map(t=>context.positions.find(p=>p.ticker===t));
 if(!positions.every(Boolean)||pair[0]===pair[1]){host.innerHTML='<p>Alege două dețineri diferite, aflate în acest cont.</p>';return;}
 const now=Date.now(),data=positions.map(p=>{const original=context.model(p),m=original&&context.demo?{...original,timezone:original.timezone||'America/New_York',closeMinutes:original.closeMinutes??960}:original;return R.comparison(p,{symbol:context.symbol(p),model:m,note:context.note(p),snapshot:context.snapshot,probability:probability(p,m),kind:kind(),now});});
 const stopNames={missing:'Neverificat',safe:'Peste zona de alertă',near:'Aproape de stop',crossed:'Stop atins'};
 const rows=[['Verdict tehnic',r=>esc(r.pulse.title)],['Trend scurt / mediu / lung',r=>r.model?[r.model.short,r.model.medium,r.model.long].map(esc).join(' / ')+'<small>EOD '+esc(r.model.asOf)+'</small>':'Analiză EOD indisponibilă'],['Probabilități · +5 sesiuni',probabilityText],['Valoare · citire broker',r=>esc(fmt(r.value,r.currency||''))],['P&L nerealizat · broker',r=>'<b class="'+(r.pnl<0?'bad':r.pnl>0?'good':'')+'">'+esc(fmt(r.pnl,r.currency||'',true))+'</b>'],['Pondere în cont',r=>esc(fmt(r.weight,'%'))],['Stop personal',r=>esc(stopNames[r.stop.state])+(r.stop.distance!==null?'<small>'+esc(fmt(r.stop.distance,'%'))+' față de stopul '+esc(fmt(r.stop.level,r.stop.currency||''))+'</small>':'')],['Distanță monetară până la stop',r=>r.stop.state==='crossed'?'Stop atins; distanța de risc nu este estimată.':esc(fmt(r.stopRisk,r.stop.currency||''))+(r.stop.source?'<small>'+esc(r.stop.source)+'</small>':'')],['Volatilitate · ATR14',r=>esc(fmt(r.model?.atrPct,'%'))],['Forță relativă · RS20',r=>esc(fmt(r.model?.rs20,'pp',true))+'<small>Benchmark: '+esc(r.model?.marketBenchmark||'neverificat')+'</small>']];
 host.innerHTML=(context.demo?'<p class="meta">DEMO · comparație pe poziții și prețuri fictive.</p>':'')+'<p class="meta">Citire broker: '+esc(context.snapshot?.fetchedAt?new Date(context.snapshot.fetchedAt).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'}):'neverificată')+'. '+(data.every(r=>r.brokerFresh)?'':'Citirea este veche; sincronizează înainte de reevaluare. ')+'Sumele rămân în moneda fiecărei poziții; ponderile cer moneda contului.</p><table class="holding-compare-table" role="table"><caption>Comparația deținerilor selectate</caption><thead><tr><th scope="col">Reper</th>'+data.map(r=>'<th scope="col">'+esc(r.symbol)+'<small>'+esc(r.name)+'</small></th>').join('')+'</tr></thead><tbody>'+rows.map(([name,fn])=>'<tr><th scope="row">'+name+'</th>'+data.map(r=>'<td>'+fn(r)+'</td>').join('')+'</tr>').join('')+'</tbody></table><p class="meta">Probabilitățile descriu clasele de mișcare a închiderii peste 5 sesiuni, fără costuri; nu sunt probabilități de profit. Distanța până la stop este matematică, în moneda instrumentului, fără FX, gap sau costuri.</p><div class="compare-open">'+data.map(r=>'<button data-open-compare="'+esc(r.ticker)+'">Analiza '+esc(r.symbol)+'</button>').join('')+'</div>';
 for(const b of host.querySelectorAll('[data-open-compare]'))b.onclick=()=>g.HoldingsLayout.openHolding(b.dataset.openCompare,{scroll:true});
}
for(const id of ['holdingFavoritesOnly','holdingChangesOnly'])$(id).onchange=()=>refresh();
for(const [i,id] of ['holdingCompareA','holdingCompareB'].entries())$(id).onchange=()=>{pair[i]=$(id).value;renderComparison();};
$('holdingComparison').addEventListener('toggle',()=>{if($('holdingComparison').open)renderComparison();});$('holdingCompareRefresh').onclick=renderComparison;
$('holdingVisitSeen').onclick=()=>{const r=engine().acknowledge(context.scope,kind());message=r.reason||'';$('holdingChangesOnly').checked=false;refresh();};
$('holdingVisitDemo').onclick=()=>{if(!context?.demo)return;const now=Date.now(),priorAt=now-86400000,old=context.positions.map(p=>{const prior=context.previous?.(p),m=context.model(p);return project({...p,unrealized:p.unrealized-12},priorAt,{model:prior&&m?{...prior,symbol:context.symbol(p),currency:m.currency}:m,brokerAt:new Date(priorAt).toISOString()});});engine().simulate(context.scope,{version:1,at:priorAt,entries:old});refresh();};
g.HoldingsRosterUI={setContext,filter,controls,badge,bindRoster,renderComparison};
})(typeof window!=='undefined'?window:globalThis);
