(function(g){
'use strict';
const S=g.HoldingsStrategy,V=g.HoldingsStrategyView,F=g.HoldingsForecast,memory=new Map(),messages=new Map(),drafts=new Map();let context=null;
const legacy={getItem:k=>localStorage.getItem(k),setItem:(k,v)=>localStorage.setItem(k,v)},real=g.HoldingsForecastStorage.create(legacy,{mergeForKey:S.mergeForKey,onChange:refresh}),demo={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v),commit:changes=>{for(const c of changes)memory.set(c.key,c.value);},status:()=>({state:'demo',message:'DATE FICTIVE · exemple izolate, fără salvare în cont.'})};
const storage=()=>context?.demo?demo:real;
function identity(p){const m=context?.model(p);return {scope:context?.scope,ticker:p?.ticker,symbol:context?.symbol(p),currency:m?.currency||context?.reference?.(p)?.currency||p?.instrumentCurrency,kind:context?.demo?'synthetic':'market'};}
function matches(p,e){return !!context&&F.identity(e)&&S.key(identity(p))===S.key(e);}
function refresh(){g.HoldingsNeuralUI?.refresh();}
function setContext(c){context=c;}
async function restore(p,{identity:e=identity(p)}={}){if(!context||context.demo||!F.identity(e))return;await Promise.all([S.key(e),S.settingsKey(e),S.DIRECTORY].map(k=>real.load(k)));}
function settings(e){const raw=storage().getItem(S.settingsKey(e)),s=raw===null?S.defaults():JSON.parse(raw);if(!S.validSettings(s))throw Error('Setări incompatibile; copia existentă rămâne păstrată.');return s;}
function read(e){return S.document(storage().getItem(S.key(e)),e);}
function snapshot(p){const e=identity(p);try{if(!F.identity(e))throw Error('Identitatea instrumentului nu este completă.');return {ok:true,identity:e,entries:read(e).entries,settings:settings(e),storage:storage().status?.(S.key(e)),settingsStorage:storage().status?.(S.settingsKey(e))};}catch(error){return {ok:false,identity:e,entries:[],error:error.message};}}
function capture(p,forecast,{identity:e=identity(p),now=Date.now()}={}){
 if(!matches(p,e))return {ok:false,error:'Contextul contului s-a schimbat.'};
 try{const st=storage(),d=read(e),s=settings(e),trial=S.project(forecast,e,s,now);if(!trial){const reason=s.enabled?'Simularea cere o estimare nouă, păstrată la timp, pentru o listare USD cu sesiune regulată New York.':'Urmărirea strategiei este oprită pentru deciziile noi.';messages.set(S.key(e),reason);return {ok:true,saved:false,disabled:!s.enabled,reason};}if(d.entries.some(r=>r.id===trial.id))return {ok:true,duplicate:true};
  const before=st.getItem(S.key(e)),directoryBefore=st.getItem(S.DIRECTORY),clean=Object.fromEntries(['scope','ticker','symbol','currency','kind'].map(k=>[k,e[k]]));
  const entries=[...d.entries,trial],raw=JSON.stringify({version:S.VERSION,entries});S.document(raw,e,now);const next=S.directoryMerge(directoryBefore,JSON.stringify({version:S.VERSION,identities:[clean]}));
  st.commit([{key:S.key(e),before,value:raw},{key:S.DIRECTORY,before:directoryBefore,value:next}]);messages.set(S.key(e),'Decizia nouă și costurile au fost fixate. Aștept următoarea deschidere și 5 sesiuni încheiate.');return {ok:true,saved:true};
 }catch(error){messages.set(S.key(e),'Simularea nu a fost păstrată: '+error.message);return {ok:false,error:error.message};}
}
function checkSource(p,source,{identity:e=identity(p),forecasts=[],now=Date.now()}={}){
 if(!matches(p,e))return {ok:false,error:'Context schimbat.'};
 try{const d=read(e);if(!d.entries.length)return {ok:true};const originals=new Map(forecasts.map(r=>[r.id,r])),entries=d.entries.map(r=>S.verify(r,e,source,originals.get(r.forecast.id),now));if(entries.some(r=>!S.validEntry(r,e,now)))throw Error('Rezultat incompatibil.');storage().setItem(S.key(e),JSON.stringify({version:S.VERSION,entries}));return {ok:true};}
 catch(error){messages.set(S.key(e),'Verificarea simulării este indisponibilă: '+error.message);return {ok:false,error:error.message};}
}
function saveSettings(p,input){const e=identity(p);try{read(e);settings(e);if(!S.validSettings(input))throw Error('Introdu procente între 0 și 5 pentru fiecare cost.');storage().setItem(S.settingsKey(e),JSON.stringify(input));drafts.delete(S.key(e));messages.set(S.key(e),'Setările se aplică numai deciziilor viitoare. Registrele existente rămân fixe.');refresh();return {ok:true};}catch(error){messages.set(S.key(e),error.message);refresh();return {ok:false,error:error.message};}}
function simulation(p){if(!context?.demo)return false;const e=identity(p),entries=g.HoldingsStrategyDemo.build(e);demo.setItem(S.key(e),JSON.stringify({version:S.VERSION,entries}));messages.set(S.key(e),'EXEMPLU · 12 verdicte inventate și prețuri fictive. Nu sunt rezultate ale modelelor antrenate.');refresh();return true;}
function markup(p,i){
 const x=snapshot(p),e=x.identity,k=S.key(e),draft=drafts.get(k)||x.settings||S.defaults(),esc=V.esc;
 return '<section class="ai-strategy" id="model-lab-'+i+'-strategy" tabindex="-1" aria-label="Strategie AI simulată"><div class="strategy-heading"><div><span class="eyebrow">VERDICT AI → SIMULARE · '+(context.demo?'DATE FICTIVE':'DUPĂ CAPTURĂ')+'</span><h4>Strategie AI · rezultatul net</h4></div><span class="tag">Simulare · fără ordine</span></div>'+V.rules()+'<p class="strategy-status" role="status" aria-live="polite">'+esc(x.error||messages.get(k)||'Se capturează automat doar verdictele finale noi, cu 6/6 modele verificate, inclusiv abținerile. O analiză prea târzie pentru EOD nu pornește o tranzacție.')+'</p>'+(x.storage?'<p class="strategy-meta" role="status">'+esc(x.storage.message)+(x.storage.state==='pending'?' Nu este încă confirmată salvarea permanentă.':'')+'</p>':'')+'<details class="strategy-details"><summary>Urmărire '+(draft.enabled?'activă':'oprită')+' · costuri pentru deciziile viitoare</summary><label class="strategy-toggle"><input type="checkbox" data-strategy-enabled="'+i+'" '+(draft.enabled?'checked':'')+' '+(!x.ok?'disabled':'')+'> Urmărește verdictele noi</label><div class="strategy-costs">'+Object.entries(V.LABELS).map(([field,label])=>'<label for="strategy-'+i+'-'+field+'">'+esc(label)+' (%)<input id="strategy-'+i+'-'+field+'" type="number" min="0" max="5" step="0.01" inputmode="decimal" data-strategy-index="'+i+'" data-strategy-cost="'+field+'" value="'+esc(draft.costs[field])+'" '+(!x.ok?'disabled':'')+'></label>').join('')+'</div><p class="strategy-meta">Ipoteze implicite: spread 0,10%, slippage 0,05% pe sens, comision și FX 0%. Verifică estimările tale; nu sunt tarife confirmate ale brokerului. Salvarea costurilor creează un scenariu separat pentru viitor. Oprirea capturii păstrează și verifică deciziile deja luate.</p><button data-strategy-save="'+i+'" '+(!x.ok?'disabled':'')+'>Salvează pentru viitor</button></details>'+(x.ok?V.results(x.entries,e):'')+'<div class="strategy-actions"><button data-strategy-check="'+i+'" '+(!x.ok||context.demo?'disabled':'')+'>Verifică sesiunile noi</button><button data-strategy-export="'+i+'" '+(!x.ok||!x.entries.length?'disabled':'')+'>Exportă simularea</button>'+(context.demo?'<button data-strategy-demo="'+i+'">Încarcă exemplul · date fictive</button>':'')+'<a href="../shadow-book/#aiStrategyShadow">Vezi registrul în Shadow Book</a></div>'+V.limits()+'<a class="model-back" data-model-jump="summary" href="#model-lab-'+i+'-summary">Sinteză ↑</a></section>';
}
function bind(){
 const position=i=>context?.positions[Number(i)],draft=p=>{const e=identity(p),k=S.key(e);if(!drafts.has(k))drafts.set(k,JSON.parse(JSON.stringify(settings(e))));return drafts.get(k);};
 for(const input of document.querySelectorAll('[data-strategy-cost]'))input.oninput=()=>{const p=position(input.dataset.strategyIndex);if(p)draft(p).costs[input.dataset.strategyCost]=input.value===''?null:Number(input.value);};
 for(const input of document.querySelectorAll('[data-strategy-enabled]'))input.onchange=()=>{const p=position(input.dataset.strategyEnabled);if(p)draft(p).enabled=input.checked;};
 for(const b of document.querySelectorAll('[data-strategy-save]'))b.onclick=()=>{const p=position(b.dataset.strategySave);if(!p)return;const s=draft(p),old=settings(identity(p)),changed=Object.keys(S.DEFAULT_COSTS).some(k=>s.costs[k]!==old.costs[k]);saveSettings(p,{...s,costBasis:changed?'user-estimate':old.costBasis});};
 for(const b of document.querySelectorAll('[data-strategy-check]'))b.onclick=()=>{const p=position(b.dataset.strategyCheck);if(p)void g.HoldingsForecastUI.check(p,true);};
 for(const b of document.querySelectorAll('[data-strategy-demo]'))b.onclick=()=>simulation(position(b.dataset.strategyDemo));
 for(const b of document.querySelectorAll('[data-strategy-export]'))b.onclick=()=>{const p=position(b.dataset.strategyExport),x=snapshot(p);if(x.ok)g.HoldingsNeuralUI.exportReport({symbol:x.identity.symbol,kind:x.identity.kind,asOf:x.entries.at(-1)?.forecast.source.asOf||'fara-date',result:S.exportReport(x.entries,x.identity)});};
}
g.HoldingsStrategyUI={setContext,restore,identity,snapshot,capture,checkSource,saveSettings,simulation,markup,bind};
})(typeof window!=='undefined'?window:globalThis);
