(function(g){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString('ro-RO',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const REASONS={horizon:'Închidere sesiunea 5',abstention:'Fără poziție',stop:'Stop',target:'Țintă','gap-stop':'Gap sub stop','both-stop-first':'Stop și țintă · stop primul'};
const LABELS={spreadPct:'Spread complet',slippagePct:'Slippage / sens',commissionPct:'Comision / sens',fxPct:'Conversie FX / sens'};
function rules(){return '<p class="strategy-rules"><b>Regulă fixă:</b> verdict final pozitiv → următoarea deschidere; stop la 1 ATR inițial, țintă la 2 ATR, ieșire în maximum 5 sesiuni. Verdict mixt, negativ sau neconcludent → fără poziție.</p><p class="strategy-meta">Scenariu de 1.000 unități ale monedei de cotare per intrare, cu unități fracționare, fără compunere. Nu folosește soldul sau cantitatea deținerii. SUA și listări europene suportate, cu rezultate separate pe instrument și monedă. GBP și GBX rămân unități distincte.</p>';}
function results(entries,e){
 const r=g.HoldingsStrategy.report(entries,e);if(!r.ok)return '<p class="strategy-status">'+esc(r.reason)+'</p>';
 if(!r.decisions)return '<p class="strategy-empty">Încă nu există decizii urmărite. Registrul începe cu următorul verdict nou, păstrat la timp pentru sesiunea EOD; rezultatele vechi nu sunt transformate în tranzacții.</p>';
 const unit=esc(e.currency),amount=(x,k)=>x?.[k]??x?.[k.replace(/USD$/,'')];
 const lastCheck=Math.max(...entries.map(r=>r.verification.checkedAt||0));
 const panels=r.policies.map(x=>{const m=x.metrics,p=x.policy;return '<article class="strategy-policy"><h5>Costuri '+esc(p.id)+' · '+(p.costBasis==='research-assumptions'?'ipoteze de cercetare':'estimarea ta')+'</h5><p class="strategy-meta">'+Object.entries(p.costs).map(([k,v])=>esc(LABELS[k])+': '+fmt(v)+'%').join(' · ')+'</p><div class="strategy-metrics">'+[['Rezultat net',amount(m,'netUSD')],['Costuri estimate',amount(m,'costUSD')],['Reper pasiv net',amount(m,'passiveNetUSD')],['Diferență față de reper',amount(m,'advantageUSD')]].map(([name,value])=>'<div><small>'+name+'</small><b>'+fmt(value)+' '+unit+'</b></div>').join('')+'</div><p class="strategy-meta">'+x.decisions+' decizii · '+x.separate+' orizonturi separate · '+x.trades+' poziții simulate · '+x.abstentions+' fără poziție · '+x.pending+' în așteptare · '+x.unverifiable+' neverificabile · '+x.overlap+' suprapuse excluse · '+x.ambiguous+' bare cu stop și țintă.</p>'+(m?'<p class="strategy-meta">'+esc(x.from)+' → '+esc(x.to)+' · brut '+fmt(amount(m,'grossUSD'))+' '+unit+' · medie netă / poziție '+fmt(amount(m,'averageTradeUSD'))+' '+unit+' · poziții net pozitive '+fmt(m.winRate===null?null:m.winRate*100,1)+'% · scădere maximă a curbei rezultatelor '+fmt(amount(m,'maxDrawdownUSD'))+' '+unit+'.</p>':'')+'</article>';}).join('');
 const selected=new Set();for(const policy of r.policies){let end=-Infinity;for(const row of entries.filter(r=>r.policy.id===policy.policy.id&&r.verification.state==='resolved').sort((a,b)=>a.forecast.source.t-b.forecast.source.t))if(row.forecast.source.t>end){selected.add(row.id);end=row.outcome.result.horizonEnd;}}
 const rows=entries.slice().sort((a,b)=>b.forecast.source.t-a.forecast.source.t).slice(0,12);
 return (lastCheck?'<p class="strategy-meta">Ultima verificare: '+esc(new Date(lastCheck).toLocaleString('ro-RO'))+'.</p>':'')+panels+'<details class="strategy-details"><summary>Decizii și execuții păstrate · '+entries.length+'</summary><div class="strategy-table-wrap"><table><thead><tr><th>Origine / verdict</th><th>Intrare / stop / țintă</th><th>Ieșire / costuri</th><th>Net / verificare</th></tr></thead><tbody>'+rows.map(x=>{const o=x.outcome?.result,valid=x.verification.state==='resolved';return '<tr><td><b>'+esc(x.forecast.source.asOf)+'</b><small>'+esc(x.forecast.estimate.title)+'</small><small>'+esc(x.policy.id)+'</small></td><td>'+(o&&o.trade?fmt(o.entry)+' / '+fmt(o.stop)+' / '+fmt(o.target)+'<small>'+esc(o.entryAsOf)+'</small>':o?'Fără poziție':'Aștept următoarea deschidere')+'</td><td>'+(o?esc(REASONS[o.exitReason])+(o.trade?' · '+fmt(o.exit):'')+'<small>Costuri '+fmt(amount(o,'costUSD'))+' '+unit+' · orizont '+esc(o.horizonAsOf)+'</small>':'—')+'</td><td>'+(o?fmt(amount(o,'netUSD'))+' '+unit+'':'—')+'<small>'+(valid?(selected.has(x.id)?'În agregatele principale':'Suprapus · exclus'):x.verification.state==='pending'?'În așteptare':'Exclus · neverificabil')+'</small><small>'+esc(x.verification.reason)+'</small></td></tr>';}).join('')+'</tbody></table></div><p class="strategy-meta">Ultimele '+rows.length+' decizii. Exportul conține întregul registru.</p></details>';
}
function limits(){return '<details class="strategy-details"><summary>Execuție, costuri și limite</summary><p>Toate regulile, verdictul și scenariul de costuri se fixează la captură. Modificările costurilor se aplică numai deciziilor viitoare; scenariile diferite au rapoarte separate. Nu alegem retrospectiv parametrii după profit.</p><p>ATR-ul absolut este cel de la origine; stopul și ținta pornesc de la deschiderea următoare. Gap sub stop: ieșire la deschidere. Gap peste țintă: ieșire conservatoare la țintă. Dacă ambele niveluri sunt atinse în aceeași bară, folosim stopul primul și semnalăm ambiguitatea.</p><p>Cost pe fiecare sens = jumătate din spreadul complet + slippage + comision + FX. Procentele sunt aplicate valorii intrării și ieșirii. Valorile implicite sunt ipoteze neconfirmate, nu tarifele brokerului. Modelul nu include comisioane fixe/minime, taxe, dividende, finanțare sau execuție intraday.</p><p>Reperul cumpără același instrument la aceeași deschidere și vinde la închiderea sesiunii 5, cu aceleași costuri; fiecare interval pornește de la 1.000 unități ale monedei instrumentului. Este un reper pe ferestre separate, nu randamentul deținerii pe întreaga perioadă. Abținerile au rezultat zero în strategie și păstrează reperul. Așteptăm toate cele 5 sesiuni chiar dacă stopul sau ținta au fost atinse mai devreme.</p><p>Seriile revizuite sau incompatibile sunt excluse și păstrează rezultatul original. Totalurile folosesc numai orizonturi separate, pe instrument și scenariu; scăderea maximă descrie curba sumelor simulate, nu riscul portofoliului. Datele OHLC pot omite sesiuni sau ajustări mici. Aceste rezultate sunt o simulare prospectivă și nu confirmă profitabilitatea pe bani reali.</p></details>';}
g.HoldingsStrategyView={esc,fmt,LABELS,rules,results,limits};
})(typeof window!=='undefined'?window:globalThis);
