(function(g){
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>Number.isFinite(n)?n.toLocaleString('ro-RO',{maximumFractionDigits:2}):'—';let context=null,reviews={},reviewBusy=false,formDrafts={},demoAlerts=[];
function capture(){if(!context)return;context.positions.forEach((p,i)=>{const find=k=>document.querySelector('[data-'+k+'="'+i+'"]');if(!find('up'))return;formDrafts[context.scope+'|'+p.ticker]={up:find('up').checked,rs:find('rs').checked,floor:find('floor').value,fundamental:find('fundamental').value,ex:find('ex').value,pay:find('pay').value,source:find('source').value};});}
function fills(){if(context.demo){const p=context.positions[0];return p?[{id:'demo-sell',ticker:p.ticker,side:'SELL',price:100,quantity:2,priceCurrency:'USD',date:new Date(Date.now()-100*86400000).toISOString()}]:[];}try{return JSON.parse(localStorage.getItem('tt_trading212_fills_v1')||'{}').accounts?.[context.scope]?.items||[];}catch(_){return [];}}
function mapped(){const models={},notes={},events={};for(const p of context.positions){models[p.ticker]=context.model(p);notes[p.ticker]=context.note(p);events[p.ticker]=context.events(p);}return {models,notes,events};}
function render(ctx){context=ctx;const W=g.HoldingsWorkspace,{models,notes,events}=mapped(),s=ctx.snapshot,age=Date.now()-Date.parse(s?.fetchedAt),fresh=Number.isFinite(age)&&age>=-60000&&age<=300000,currency=s?.summary?.currency,total=s?.summary?.totalValue;
 $('workbench').hidden=!ctx.positions.length&&!fills().some(f=>f.side==='SELL');const ranked=W.attention(ctx.positions,models,notes,events,total,currency,ctx.symbol,fresh,Date.now(),s?.fetchedAt),calendar=W.calendar(ctx.positions,notes,events,ctx.symbol);
 renderAlerts(ranked,models);
 $('attentionDesk').innerHTML=`<h2>Ce necesită atenție azi</h2><p class="meta">Ordine după reguli de revizuire, nu recomandări de vânzare. ${ctx.demo?'SIMULARE.':''}</p>${ranked.map(r=>`<button class="attention-row" data-focus="${esc(r.ticker)}"><b>${esc(r.ticker)}</b><span>Prioritate ${r.priority}/100</span><small>${r.reasons.map(esc).join(' · ')}</small></button>`).join('')||'<p>Fără dețineri pentru prioritizare.</p>'}`;
 g.PortfolioScenariosUI.render(ctx);
 $('portfolioCalendar').innerHTML=`<h2>Calendarul portofoliului · 90 zile</h2><p class="meta">Provider și repere manuale separate. Ex-dividend și plata dividendului necesită sursă introdusă de tine; lipsa unui eveniment nu confirmă absența lui.</p>${calendar.map(e=>`<p class="${e.days<=7?'warn':''}"><b>${esc(e.date)} · ${esc(e.ticker)}</b> · ${esc(e.type)} · ${esc(e.status)} · ${esc(e.source)}${e.url?` · <a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">Sursă ↗</a>`:''}</p>`).join('')||'<p>Niciun eveniment utilizabil în interval.</p>'}`;
 $('reviewSales').onclick=reviewSales;renderSales();
}
function renderAlerts(ranked,models){const host=$('alertHistory');try{const A=g.HoldingsAlerts,records=context.demo?A.reconcile(demoAlerts,context.scope,ranked,models):A.reconcile(A.load(),context.scope,ranked,models);if(context.demo)demoAlerts=records;else A.save(records);const rows=records.filter(r=>r.scope===context.scope).sort((a,b)=>b.firstAt-a.firstAt),unread=rows.filter(r=>!r.seenAt).length;host.innerHTML=`<h2>Alerte de revizuire · ${unread} necitite</h2><p class="meta">${context.demo?'DEMO · istoric temporar':'Istoric păstrat pe acest dispozitiv'} · aceeași condiție activă produce o singură alertă. O reapariție după rezolvare creează un episod nou. Fără notificări în afara aplicației.</p><details><summary>Istoric · ${rows.length} episoade</summary>${rows.slice(0,100).map(r=>`<article class="news-item"><b>${esc(r.ticker)}</b> · ${r.active?'activă':'rezolvată'} · ${r.seenAt?'citită':'nouă'}<p>${esc(r.reason)}</p><small>${esc(new Date(r.firstAt).toLocaleString('ro-RO'))}${r.asOf?' · EOD '+esc(r.asOf):''}</small>${!r.seenAt?`<button data-alert="${esc(r.id)}">Marchează citită</button>`:''}</article>`).join('')||'<p>Nicio alertă înregistrată.</p>'}${rows.length>100?'<p>Se afișează ultimele 100; istoricul anterior este păstrat.</p>':''}</details>`;for(const b of host.querySelectorAll('[data-alert]'))b.onclick=()=>{if(context.demo){demoAlerts=A.seen(demoAlerts,b.dataset.alert);renderAlerts(ranked,models);host.querySelector('details').open=true;return;}try{A.save(A.seen(A.load(),b.dataset.alert));renderAlerts(ranked,models);host.querySelector('details').open=true;}catch(_){b.textContent='Salvare nereușită';}};}catch(_){host.textContent='Istoricul alertelor nu a putut fi salvat. Verifică spațiul disponibil și permisiunile de stocare.';}}
function card(p,i){const draft=formDrafts[context.scope+'|'+p.ticker]||{},n=context.note(p),t=HoldingsWorkspace.thesis(n,context.model(p)),cal=n.calendar||[],ex=cal.find(x=>x.type==='Ex-dividend')||{},pay=cal.find(x=>x.type==='Plată dividend')||{};return `<details class="notes"><summary>Teza inițială vs evoluția reală</summary><p><b>Motiv păstrat la prima salvare:</b> ${esc(t.initial||'Nedocumentat')}</p><p><b>Teza curentă:</b> ${esc(t.current||'Nedocumentată')}</p>${t.rows.map(r=>`<p class="${r.state==='slăbită'?'warn':''}">${esc(r.label)} · ${esc(r.state)}</p>`).join('')||'<p>Nu ai definit condiții măsurabile.</p>'}<p>Fundamental · ${esc(t.fundamental)} (revizuire manuală)</p><label><input type="checkbox" data-up="${i}" ${(draft.up??n.criteria?.uptrend)?'checked':''}> Cere trend mediu ascendent</label><label><input type="checkbox" data-rs="${i}" ${(draft.rs??n.criteria?.relative)?'checked':''}> Cere RS20 pozitiv</label><label>Închidere minimă · moneda seriei<input type="number" min="0" step="any" data-floor="${i}" value="${esc(draft.floor??n.criteria?.minimumClose??'')}"></label><label>Revizuire fundamentală<select data-fundamental="${i}">${['nerevizuită','susținută','slăbită'].map(x=>`<option ${(draft.fundamental??t.fundamental)===x?'selected':''}>${x}</option>`).join('')}</select></label><h3>Repere de dividend · introduse manual</h3><label>Ex-dividend<input type="date" data-ex="${i}" value="${esc(draft.ex??ex.date??'')}"></label><label>Plată dividend<input type="date" data-pay="${i}" value="${esc(draft.pay??pay.date??'')}"></label><label>Link sursă HTTPS · Investor Relations<input type="url" data-source="${i}" value="${esc(draft.source??ex.url??pay.url??'')}" placeholder="https://..."></label><button data-work-save="${i}">Salvează condițiile și calendarul</button><span data-work-status="${i}" class="meta"></span></details><details class="notes"><summary>Cronologia tickerului</summary><div data-timeline="${i}"></div></details>`;}
function bind(){for(const b of document.querySelectorAll('[data-focus]'))b.onclick=()=>{const target=[...document.querySelectorAll('.holding[data-ticker]')].find(el=>el.dataset.ticker===b.dataset.focus);target?.scrollIntoView({behavior:'smooth',block:'start'});};for(const b of document.querySelectorAll('[data-work-save]'))b.onclick=()=>{const i=Number(b.dataset.workSave),p=context.positions[i],find=k=>document.querySelector('[data-'+k+'="'+i+'"]'),url=find('source').value.trim(),ex=find('ex').value,pay=find('pay').value;if(url&&!HoldingsEvents.safeURL(url)||[ex,pay].some(d=>d&&!HoldingsEvents.validDate(d))){document.querySelector('[data-work-status="'+i+'"]').textContent='Dată sau URL invalid.';return;}const old=context.note(p),patch={criteria:{symbol:context.symbol(p),currency:context.model(p)?.currency||'NEVERIFICAT',uptrend:find('up').checked,relative:find('rs').checked,minimumClose:find('floor').value},fundamental:find('fundamental').value,calendar:[...(Array.isArray(old.calendar)?old.calendar:[]).filter(x=>!['Ex-dividend','Plată dividend'].includes(x.type)),...(ex?[{type:'Ex-dividend',date:ex,url,source:'Introdus de tine'}]:[]),...(pay?[{type:'Plată dividend',date:pay,url,source:'Introdus de tine'}]:[])]};try{delete formDrafts[context.scope+'|'+p.ticker];context.save(p,patch);document.querySelector('[data-work-status="'+i+'"]').textContent=context.demo?'Demo · nu se salvează în cont':'Condiții salvate local.';render(context);timelineFor(p,i);}catch(_){document.querySelector('[data-work-status="'+i+'"]').textContent='Salvarea nu a reușit.';}};context.positions.forEach(timelineFor);}
function timelineFor(p,i){const e=context.events(p),rows=HoldingsWorkspace.timeline(p.ticker,fills(),context.history(p),context.note(p),e);const host=document.querySelector('[data-timeline="'+i+'"]');if(host)host.innerHTML=rows.map(r=>`<p><small>${esc(r.asOf||new Date(r.date).toLocaleString('ro-RO'))} · ${esc(r.type)}</small><br>${r.url?`<a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.text)}</a>`:esc(r.text)}</p>`).join('')||'<p>Istoric încă nedocumentat. Observațiile sunt acumulate de la folosirea acestei funcții; istoricul anterior nu este reconstruit.</p>';}
function sales(){return fills().filter(f=>f.side==='SELL'&&f.id).sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));}
function renderSales(){const rows=sales();$('reviewSales').disabled=reviewBusy;$('salesStatus').textContent=reviewBusy?'Verific istoricul și evenimentele de split…':rows.length+' execuții SELL importate · calcul la cerere';$('salesResults').innerHTML=rows.map(f=>{const r=reviews[context.scope+'|'+f.id];return `<article class="news-item"><b>${esc(f.ticker)}</b> · ${esc(f.date)} · ${fmt(f.quantity)} vândute la ${fmt(f.price)} ${esc(f.priceCurrency)}${r?.rows?r.rows.map(x=>`<p>${x.sessions} observații EOD după ziua vânzării · ${x.change===undefined?esc(x.status):fmt(x.change)+'% · '+esc(x.asOf)+' · '+fmt(x.price)+' '+esc(f.priceCurrency)}</p>`).join(''):`<p>${esc(r?.error||'Neanalizat')}</p>`}</article>`;}).join('')||'<p>Nicio execuție SELL importată pentru acest cont.</p>';}
async function reviewSales(){if(reviewBusy)return;reviewBusy=true;const c=context,scope=c.scope,list=sales(),histories={};renderSales();let index=0;async function worker(){while(index<list.length){const f=list[index++],key=scope+'|'+f.id,sym=c.symbol({ticker:f.ticker});try{if(!sym)throw Error('Asociere simbol exact necesară.');if(!histories[sym])histories[sym]=c.demo?Promise.resolve({series:{bars:c.demoBars(),timezone:'America/New_York',currency:'USD'},splits:[]}):HoldingsWorkspace.saleHistory(sym);const h=await histories[sym];reviews[key]={rows:HoldingsWorkspace.afterSale(f,h.series,h.splits)};}catch(e){reviews[key]={error:e.message};}if(context.scope===scope)renderSales();}}try{await Promise.all([worker(),worker()]);}finally{reviewBusy=false;renderSales();}}
g.HoldingsWorkbench={render,card,bind,capture};
})(typeof window!=='undefined'?window:globalThis);
