import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {KEYS,mergeRecord,validateValue} from '../lib/cloud-sync-model.mjs';
const source=readFileSync(new URL('../app/cloud-sync.js',import.meta.url),'utf8').replace(/^import .*;\n/,'');
async function setup({local={},remote={},baseline={},vault=null,enabled=true,onPut}={}){
 const storage=new Map(Object.entries(local)),privateStore=new Map([['session',{token:'token',subject:'123',email:'me@example.test'}],['baseline:123',baseline]]),calls=[];let currentVault=vault;const records=structuredClone(remote),window={addEventListener(){},dispatchEvent(){},T212Vault:{read:async()=>currentVault,save:async v=>{currentVault=v;},clear:async()=>{currentVault=null;}},TTCloudStore:{get:async k=>structuredClone(privateStore.get(k)||null),put:async(k,v)=>{privateStore.set(k,structuredClone(v));},remove:async k=>{privateStore.delete(k);}}};
 const c={KEYS,mergeRecord,validateValue,window,localStorage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)},document:{hidden:false,addEventListener(){},querySelectorAll:()=>[],getElementById:()=>null},navigator:{onLine:true},location:{origin:'https://mferent80-source.github.io',href:'https://mferent80-source.github.io/app/'},URL,Date,AbortController,CustomEvent:class{},StorageEvent:class{},setTimeout,clearTimeout,setInterval:()=>{},fetch:async(url,opts)=>{calls.push({url,opts});let data;if(url==='cloud-sync-config.json')data={enabled,endpoint:'https://premarket-scanner-html.mferent80.workers.dev'};else if(url.endsWith('/status'))data={enabled:true,clientId:'test.apps.googleusercontent.com'};else if(url.endsWith('/session'))data={subject:'123'};else if(url.endsWith('/records'))data={records:structuredClone(records)};else if(url.endsWith('/record')){const b=JSON.parse(opts.body);if(onPut)onPut(storage,b);assert.equal(b.revision,records[b.key]?.revision||0);records[b.key]={revision:b.revision+1,value:b.value,updated:10};data={revision:b.revision+1,updated:10};}else throw Error(url);return {ok:true,json:async()=>data};}};
 vm.createContext(c);vm.runInContext(source,c);for(let i=0;i<15;i++)await new Promise(r=>setImmediate(r));return {api:window.TTCloud,storage,privateStore,records,calls,vault:()=>currentVault};
}
test('first phone receives cloud data without pushing empty replacement',async()=>{const s=await setup({remote:{tt_journal_v1:{revision:3,updated:9,value:[{id:'trade'}]}}});assert.equal(JSON.parse(s.storage.get('tt_journal_v1'))[0].id,'trade');assert.equal(s.calls.filter(c=>c.opts?.method==='PUT').length,0);assert.equal(s.api.state().connected,true);});
test('offline mode config disabled does not transmit saved credentials',async()=>{const s=await setup({enabled:false,vault:{key:'key',secret:'secret',environment:'live'}});assert.equal(s.calls.length,1);assert.equal(s.api.state().ready,false);assert.equal(s.api.state().error,'cloud_not_configured');});
test('remote tombstone cannot be republished by an old local credential',async()=>{const s=await setup({vault:{key:'key',secret:'secret',environment:'live'},remote:{cloud_credentials:{revision:2,value:null,updated:9}}});assert.equal(s.calls.filter(c=>c.opts?.method==='PUT').length,0);assert.equal(s.records.cloud_credentials.value,null);});
test('edit made during network write is kept locally for next sync',async()=>{let fired=false;const s=await setup({local:{tt_journal_v1:JSON.stringify([{id:'a'}])},onPut:(storage,b)=>{if(b.key==='tt_journal_v1'&&!fired){fired=true;storage.set('tt_journal_v1',JSON.stringify([{id:'a'},{id:'b'}]));}}});assert.equal(JSON.parse(s.storage.get('tt_journal_v1')).length,2);await s.api.sync();assert.equal(s.records.tt_journal_v1.value.length,2);});
test('same trade conflict is held without any PUT or local overwrite',async()=>{const old=[{id:'a',note:'old'}],local=[{id:'a',note:'PC'}],remote=[{id:'a',note:'phone'}];const s=await setup({local:{tt_journal_v1:JSON.stringify(local)},remote:{tt_journal_v1:{revision:2,value:remote,updated:9}},baseline:{tt_journal_v1:{revision:1,value:old}}});assert.ok(s.api.state().conflicts.includes('tt_journal_v1'));assert.equal(s.calls.filter(c=>c.opts?.method==='PUT').length,0);assert.equal(JSON.parse(s.storage.get('tt_journal_v1'))[0].note,'PC');});
test('different Google owner cannot upload this devices local journal',async()=>{const s=await setup({local:{tt_cloud_owner:'different',tt_journal_v1:'[{"id":"private"}]'}});assert.equal(s.api.state().error,'account_mismatch');assert.equal(s.calls.filter(c=>c.url.endsWith('/records')).length,0);});
