import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import {mergeRecord,validateValue} from '../lib/cloud-sync-model.mjs';import {seal,unseal,verifyGoogle,handleCloud} from './cloud-sync-worker.mjs';
const enc=v=>Buffer.from(typeof v==='string'?v:JSON.stringify(v)).toString('base64url');
test('three-way additions, edits, and deletions survive across devices',()=>{const b=[{id:1,note:'before'},{id:2,note:'delete'}],l=[{id:1,note:'edited'},{id:3,note:'new'}],r=[...b,{id:4,note:'phone'}];const m=mergeRecord('tt_journal_v1',b,l,r);assert.deepEqual(m.conflicts,[]);assert.deepEqual(m.value.map(x=>x.id).sort(),[1,3,4]);assert.equal(m.value.find(x=>x.id===1).note,'edited');});
test('same trade edited differently is explicit conflict',()=>{const m=mergeRecord('tt_journal_v1',[{id:1,note:'old'}],[{id:1,note:'PC'}],[{id:1,note:'phone'}]);assert.equal(m.conflicts.length,1);});
test('empty fresh phone imports existing journal',()=>{const m=mergeRecord('tt_journal_v1',undefined,undefined,[{id:'a'}]);assert.deepEqual(m,{value:[{id:'a'}],conflicts:[]});});
test('independent watchlist changes reconcile without reintroducing removed symbols',()=>{assert.deepEqual(mergeRecord('wl_stocks',['AAPL','MSFT'],['AAPL','NVDA'],['AAPL','MSFT','TSM']).value.sort(),['AAPL','NVDA','TSM']);});
test('broker snapshots select latest source timestamp',()=>{const local={a:{fetchedAt:'2026-10-01',positions:[1]}},remote={a:{fetchedAt:'2026-10-02',positions:[2]}};assert.deepEqual(mergeRecord('tt_trading212_portfolio_v1',undefined,local,remote).value,remote);});
test('broker execution lists union IDs and metadata does not cause permanent conflicts',()=>{const l={accounts:{a:{fetchedAt:'2026-10-01',complete:true,items:[{id:1,date:'2026-09-30'}]}}},r={accounts:{a:{fetchedAt:'2026-10-02',complete:false,items:[{id:2,date:'2026-10-01'}]}}};const m=mergeRecord('tt_trading212_fills_v1',undefined,l,r);assert.equal(m.value.accounts.a.items.length,2);assert.equal(m.value.accounts.a.complete,true);assert.equal(m.conflicts.length,0);});
test('credential edits are atomic and cannot mix key and secret from different devices',()=>{const m=mergeRecord('cloud_credentials',{key:'old',secret:'old'},{key:'PC',secret:'old'},{key:'old',secret:'phone'});assert.equal(m.conflicts.length,1);});
test('unknown keys, oversized data and prototype properties are rejected',()=>{assert.throws(()=>validateValue('finnhub_api_key','secret'));assert.throws(()=>validateValue('tt_holdings_theses_v1',JSON.parse('{"__proto__":{}}')));assert.throws(()=>validateValue('tt_journal_v1',[{text:'a'.repeat(1000001)}]));});
test('encrypted records authenticate subject, key and revision',async()=>{const key=Buffer.alloc(32,42).toString('base64url'),p=await seal({secret:'sensitive'},key,'u|cloud_credentials|1');assert.ok(!p.includes('sensitive'));assert.deepEqual(await unseal(p,key,'u|cloud_credentials|1'),{secret:'sensitive'});await assert.rejects(unseal(p,key,'other|cloud_credentials|1'));await assert.rejects(unseal(p,key,'u|cloud_credentials|2'));});
test('Google tokens need valid signature, audience, nonce and unexpired claims',async()=>{const kp=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const jwk=await crypto.subtle.exportKey('jwk',kp.publicKey);Object.assign(jwk,{kid:'test',alg:'RS256'});const now=Date.now(),claims={aud:'client',iss:'https://accounts.google.com',sub:'12345',email:'example@gmail.com',email_verified:true,nonce:'nonce',iat:Math.floor(now/1000),exp:Math.floor(now/1000)+3600};async function token(p){const parts=enc({alg:'RS256',kid:'test'})+'.'+enc(p),signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',kp.privateKey,new TextEncoder().encode(parts));return parts+'.'+Buffer.from(signature).toString('base64url');}const fetcher=async()=>Response.json({keys:[jwk]}),good=await token(claims);assert.equal((await verifyGoogle(good,'client','nonce',fetcher,now)).subject,'12345');await assert.rejects(verifyGoogle(good,'wrong','nonce',fetcher,now));await assert.rejects(verifyGoogle(good,'client','wrong',fetcher,now));await assert.rejects(verifyGoogle(await token({...claims,exp:0}),'client','nonce',fetcher,now));await assert.rejects(verifyGoogle(good.slice(0,-10)+'aaaaaaaaaa','client','nonce',fetcher,now));});
test('unconfigured cloud advertises disabled and does not accept credentials',async()=>{const origin='https://mferent80-source.github.io';const status=await handleCloud(new Request('https://worker/api/cloud/status',{headers:{Origin:origin}}),{});assert.equal((await status.json()).enabled,false);const auth=await handleCloud(new Request('https://worker/api/cloud/auth',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:'{}'}),{});assert.equal(auth.status,503);});
test('foreign origin blocked before any database or Google request',async()=>{const r=await handleCloud(new Request('https://worker/api/cloud/records',{headers:{Origin:'https://evil.example'}}),{},()=>{throw Error('must not fetch');});assert.equal(r.status,403);assert.equal(r.headers.get('Access-Control-Allow-Origin'),null);});
function database(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('./cloud-sync-schema.sql',import.meta.url),'utf8'));return {sqlite,prepare(sql){return {bind(...args){return {async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}};}};}};}
const ORIGIN='https://mferent80-source.github.io';
function request(path,method='GET',token='',data){return new Request('https://worker/api/cloud/'+path,{method,headers:{Origin:ORIGIN,...(token?{Authorization:'Bearer '+token}:{}),...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});}
test('D1 revisions are atomic; users cannot read each other, sessions revoke',async()=>{const db=database(),env={CLOUD_DB:db,GOOGLE_CLIENT_ID:'test.apps.googleusercontent.com',CLOUD_ENCRYPTION_KEY:Buffer.alloc(32,3).toString('base64url')};const a=Buffer.alloc(32,1).toString('base64url'),b=Buffer.alloc(32,2).toString('base64url');for(const [token,subject] of [[a,'111'],[b,'222']])db.sqlite.prepare('INSERT INTO cloud_sessions VALUES(?,?,?,?)').run(createHash('sha256').update(token).digest('base64url'),subject,'owner@gmail.com',Math.floor(Date.now()/1000)+3600);
 const write=await handleCloud(request('record','PUT',a,{key:'tt_holdings_theses_v1',value:{AAPL:{text:'private'}},revision:0}),env);assert.equal(write.status,200);assert.equal((await write.json()).revision,1);
 const collision=await handleCloud(request('record','PUT',a,{key:'tt_holdings_theses_v1',value:{},revision:0}),env);assert.equal(collision.status,409);
 const own=await handleCloud(request('records','GET',a),env);assert.equal((await own.json()).records.tt_holdings_theses_v1.value.AAPL.text,'private');const other=await handleCloud(request('records','GET',b),env);assert.deepEqual((await other.json()).records,{});
 assert.ok(!db.sqlite.prepare('SELECT packet FROM cloud_records').get().packet.includes('private'));
 const unauthorized=await handleCloud(request('records'),env);assert.equal(unauthorized.status,401);
 await handleCloud(request('session','DELETE',a),env);assert.equal((await handleCloud(request('records','GET',a),env)).status,401);db.sqlite.close();});
test('challenge requires bounded JSON and authentication requests are throttled',async()=>{const db=database(),env={CLOUD_DB:db,GOOGLE_CLIENT_ID:'test.apps.googleusercontent.com',CLOUD_ENCRYPTION_KEY:Buffer.alloc(32,3).toString('base64url')};const first=await handleCloud(request('challenge','POST','',{}),env);assert.equal(first.status,200);assert.equal((await first.json()).nonce.length,43);for(let i=0;i<19;i++)await handleCloud(request('challenge','POST','',{}),env);assert.equal((await handleCloud(request('challenge','POST','',{}),env)).status,429);db.sqlite.close();});
test('near-limit journals encrypt/decrypt without overflowing the JavaScript argument stack',async()=>{const key=Buffer.alloc(32,42).toString('base64url'),value=[{id:1,text:'x'.repeat(900000)}];validateValue('tt_journal_v1',value);const packet=await seal(value,key,'u|tt_journal_v1|1');assert.equal((await unseal(packet,key,'u|tt_journal_v1|1'))[0].text.length,900000);});
