import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const NOW=Date.parse('2026-10-08T15:00:00Z'),ids=['neural','boosting','hmm','isolation','quantile','garch','knn'];
function model(extra={}){return {symbol:'TEST',currency:'USD',asOf:'2026-10-07',kind:'market',historyKey:'ohlcv60:12345678',generatedAt:NOW,direction:2,state:'aligned',title:'Seven models',available:7,total:7,cards:ids.map(id=>({id,name:id,available:true,eligible:true,direction:2,state:'eligible'})),...extra};}
function boot(memory=new Map(),fail=false){const events={},c={structuredClone,Date:class extends Date{static now(){return NOW;}},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>{if(fail)throw Error('quota');memory.set(k,v);},removeItem:k=>memory.delete(k)},CustomEvent:class{constructor(type){this.type=type;}},addEventListener:(n,f)=>events[n]=f,dispatchEvent:e=>events[e.type]?.(e)};c.window=c;vm.createContext(c);for(const f of ['lib/decision-verdict.js','lib/decision-bridge.js'])vm.runInContext(readFileSync(f,'utf8'),c);return {B:c.TTDecisionBridge,c,events,memory};}
test('seven-model summaries including KNN survive a frame switch and preserve exact source identity',()=>{const a=boot(),m=model();assert.equal(a.B.save(m),true);const b=boot(a.memory),r=b.B.find(m);assert.equal(r.cards.find(c=>c.id==='knn').direction,2);assert.equal(b.B.find({...m,historyKey:'ohlcv60:87654321'}),null);assert.equal(b.B.find({...m,currency:'EUR'}),null);});
test('stale, future and partial model summaries cannot be reused in another decision',()=>{const b=boot();for(const m of [model({generatedAt:NOW-1800001}),model({generatedAt:NOW+1}),model({available:6}),model({cards:model().cards.slice(0,6)})])assert.equal(b.B.save(m),false);});
test('model cache stores only public evidence fields and strips unexpected fields again on restore',()=>{const b=boot(),m=model({apiKey:'SECRET',positions:['PRIVATE']});m.cards[0].notes='PRIVATE';assert.equal(b.B.save(m),true);assert.doesNotMatch(b.memory.get(b.B.KEY),/SECRET|PRIVATE/);const raw=JSON.parse(b.memory.get(b.B.KEY)),key=Object.keys(raw)[0];raw[key].apiKey='SECRET';b.memory.set(b.B.KEY,JSON.stringify(raw));assert.doesNotMatch(JSON.stringify(boot(b.memory).B.find(m)),/SECRET/);});
test('a failed cache write leaves the current computed report usable without inventing persistence',()=>{const b=boot(new Map(),true),m=model();assert.equal(b.B.save(m),true);assert.equal(b.B.find(m).available,7);assert.equal(b.memory.has(b.B.KEY),false);});
test('public class probabilities survive a frame switch while private calibration registers are stripped',()=>{
 const b=boot(),m=model({probabilistic:{version:'holdings-learning-v1',horizon:5,probabilities:[.1,.2,.7],classIndex:2,eligible:true,checkpoint:'ensemble-1234abcd',validation:{scope:'PRIVATE',balance:'SECRET'}}});m.cards[0].probabilities=[.1,.2,.7];m.cards.at(-1).neighborSupport=[.2,.2,.6];
 assert.equal(b.B.save(m),true);const found=boot(b.memory).B.find(m);assert.equal(found.probabilistic.eligible,true);assert.deepEqual(Array.from(found.probabilistic.probabilities),[.1,.2,.7]);assert.deepEqual(Array.from(found.cards.at(-1).neighborSupport),[.2,.2,.6]);assert.doesNotMatch(JSON.stringify(found),/PRIVATE|SECRET|validation/);
 m.probabilistic.probabilities=[.9,.9,.9];assert.equal(b.B.save(m),true);assert.equal(b.B.find(m).probabilistic,null);
});
