import test from 'node:test';
import assert from 'node:assert/strict';
import {core,fixture,plain} from './holdings-learning-fixtures.mjs';
const NOW=Date.parse('2026-10-08T12:00:00Z');
function setup(){return core(['lib/holdings-forecast-storage.js','lib/holdings-forecast-monitor.js','lib/decision-validation.js']);}
function market(c,n=40,options={}){const item=plain(fixture(c,n,options));item.identity.kind='market';for(const r of item.ledger.entries){r.kind='market';r.verification.checkedAt=NOW;r.outcome.checkedAt=NOW;r.outcome.retrievedAt=NOW;}return item;}
test('Desk reads seven original models and verdict with separate GARCH horizons, never global accuracy',()=>{const c=setup(),item=market(c),F=c.HoldingsForecast;for(const r of item.ledger.entries.filter(r=>r.model==='neural'))item.ledger.entries.push({...plain(r),model:'knn',modelVersion:F.VERSIONS.knn,id:'knn|'+r.source.asOf});const before=JSON.stringify(item),v=c.TTDecisionValidation.build(item,{now:NOW});assert.equal(v.ok,true);assert.equal(v.rows.length,9);assert.deepEqual(Array.from(v.rows.filter(r=>r.model==='garch'),r=>r.horizon),[5,20]);assert.equal(v.rows.find(r=>r.model==='knn').report.n,40);assert.equal(v.rows.find(r=>r.model==='knn').canSupport,true);assert.equal(v.accuracy,undefined);assert.equal(JSON.stringify(item),before);});
test('restored forecasts are visible as exclusions and cannot authenticate prospective advantage',()=>{const c=setup(),item=market(c);item.ledger.entries.forEach(r=>{r.restoredAt=NOW;});const v=c.TTDecisionValidation.build(item,{now:NOW});assert.equal(v.restored,80);assert.equal(v.rows.find(r=>r.model==='neural').report.n,0);assert.equal(v.rows.find(r=>r.model==='neural').restored,40);assert.ok(v.rows.every(r=>!r.canSupport));});
test('missing observed classes and synthetic or stale histories cannot support a verdict',()=>{const c=setup(),item=market(c,40,{onlyClass:2});const v=c.TTDecisionValidation.build(item,{now:NOW}),row=v.rows.find(r=>r.model==='neural');assert.equal(row.state,'limited');assert.equal(row.canSupport,false);assert.match(row.reason,/clasă/);const synthetic=c.TTDecisionValidation.build(fixture(c),{now:NOW});assert.equal(synthetic.simulation,true);assert.ok(synthetic.rows.every(r=>!r.canSupport));item.ledger.entries.forEach(r=>{r.verification.checkedAt=r.outcome.t+8*3600000;});assert.ok(c.TTDecisionValidation.build(item,{now:NOW}).rows.every(r=>!r.canSupport));});
test('overlapping forecasts reduce the sample and baseline failures require review',()=>{const c=setup(),item=market(c,40,{step:1});assert.ok(c.TTDecisionValidation.build(item,{now:NOW}).rows.find(r=>r.model==='neural').report.n<20);const bad=market(c);for(const r of bad.ledger.entries){r.estimate.classIndex=1;r.estimate.probabilities=[.01,.98,.01];}const row=c.TTDecisionValidation.build(bad,{now:NOW}).rows.find(r=>r.model==='neural');assert.equal(row.report.flags.noEdge,true);assert.equal(row.state,'review');assert.equal(row.canSupport,false);});
test('wrong listing, duplicate IDs and malformed originals fail without rewriting the ledger',()=>{const c=setup(),item=market(c),before=JSON.stringify(item);for(const change of [x=>x.identity.currency='EUR',x=>x.ledger.entries.push(x.ledger.entries[0]),x=>x.ledger.entries[0].privateBalance=999]){const altered=plain(item);change(altered);assert.equal(c.TTDecisionValidation.build(altered,{now:NOW}).ok,false);}assert.equal(JSON.stringify(item),before);});
test('verification reads durable and local originals together and persists actual outcomes without deleting estimates',async()=>{const c=setup(),F=c.HoldingsForecast,item=market(c,1),e=item.identity,r=item.ledger.entries[0],pending={...plain(r),outcome:null,verification:{state:'pending',checkedAt:null,sessions:0,reason:'Aștept sesiuni.'}},second=item.ledger.entries[1],k=F.key(e),map=new Map([[k,JSON.stringify({version:F.VERSION,entries:[pending]})]]),disk=new Map([[k,JSON.stringify({version:F.VERSION,entries:[second]})]]);const reader=c.TTDecisionValidation.createReader({storage:{getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)},durable:{get:async k=>disk.get(k)||null,write:async changes=>{for(const x of changes)disk.set(x.key,c.HoldingsForecastStorage.merge(disk.get(x.key),x.value,x.key));return new Map(disk);}}});const read=await reader.read(e);assert.equal(read.ledger.entries.length,2);const bars=[{t:r.source.t,o:100,h:101,l:99,c:100,v:10000},...r.outcome.path.map(x=>({t:x.t,o:x.c,h:x.c+1,l:x.c-1,c:x.c,v:10000})),{t:Date.parse('2026-10-07T13:30:00Z'),o:100,h:101,l:99,c:100,v:10000}];const checked=await reader.check(e,{symbol:e.symbol,currency:e.currency,timezone:r.source.timezone,closeMinutes:960,asOf:'2026-10-07',bars,retrievedAt:NOW},{now:NOW});assert.equal(checked.ledger.entries.length,2);const resolved=checked.ledger.entries.find(x=>x.model==='neural');assert.equal(resolved.verification.state,'resolved');assert.deepEqual(plain(resolved.estimate),plain(pending.estimate));assert.equal(resolved.capturedAt,pending.capturedAt);assert.equal(resolved.outcome.close,r.outcome.close);});
test('unavailable durable storage and corrupt local registers remain explicit failures',async()=>{const c=setup(),item=market(c,1),reader=c.TTDecisionValidation.createReader({storage:{getItem:()=>'{broken'},durable:null});await assert.rejects(reader.read(item.identity),/ilizibil/);const broken=c.TTDecisionValidation.createReader({storage:{getItem:()=>null},durable:{get:async()=>{throw Error('IndexedDB indisponibil');}}});await assert.rejects(broken.read(item.identity),/IndexedDB/);});
test('shared verdict readers wait for the original register and reject another active account',async()=>{const c=setup(),item=market(c,1),F=c.HoldingsForecast,e=item.identity;let active=e.scope;const raw=JSON.stringify({version:F.VERSION,entries:item.ledger.entries});c.localStorage={getItem:k=>k===F.key(e)?raw:null};c.HoldingsForecastStorage.indexedStore=()=>null;c.T212Snapshot={read:()=>[active,{}]};const candidate={symbol:e.symbol,currency:e.currency,kind:'market'};assert.equal(c.TTDecisionValidation.peekCandidate(candidate,active),null);const v=await c.TTDecisionValidation.getCandidate(candidate,active);assert.equal(v.ok,true);assert.equal(v.identity.scope,e.scope);assert.equal(v.total,2);assert.equal(await c.TTDecisionValidation.getCandidate(candidate,'foreign'),null);active='foreign';assert.equal(c.TTDecisionValidation.peekCandidate(candidate,e.scope),null);assert.equal(c.TTDecisionValidation.peekCandidate({...candidate,kind:'synthetic'},active),null);});
test('a selected-account switch while the shared register loads cannot return previous account evidence',async()=>{const c=setup(),item=market(c,1),e=item.identity;let active=e.scope,resolve;c.localStorage={getItem:()=>null};c.HoldingsForecastStorage.indexedStore=()=>({get:()=>new Promise(r=>resolve=r)});c.T212Snapshot={read:()=>[active,{}]};const pending=c.TTDecisionValidation.getCandidate({symbol:e.symbol,currency:'USD'},active);active='next';resolve(JSON.stringify({version:c.HoldingsForecast.VERSION,entries:item.ledger.entries}));assert.equal(await pending,null);});
