import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
const html=readFileSync('desk/index.html','utf8'),body=html.match(/function buildPlan\(rows,choice,capitalValue\)\{[\s\S]*?(?=\n  async function savePlan)/)[0];
function build({region='US',actionable=true,inResults=true,usable=true}={}){const selected={symbol:'TEST',mode:'momentum',region,currency:region==='US'?'USD':'EUR',actionable,state:'ARMED',ts:Date.now(),entryLow:100,entryHigh:100,stop:95,target:110,score:80},context={selected,data:{analyses:[]},breadthData:null,window:{DailySeries:{usable:()=>usable}},DailySeries:{usable:()=>usable},decisionItems:()=>inResults?[selected]:[],$:()=>({value:10000}),allowedRisk:()=>0.5,TradePlans:{create:()=>({currency:'USD'}),exposure:()=>({value:0,risk:0})},plans:[],ticketSizing:()=>({ok:true}),gov:()=>({budgetLeftUsd:200,maxLossWeekUsd:300,weekPnl:0}),Date,Number,Math};vm.createContext(context);vm.runInContext(body,context);return context.buildPlan();}
test('plan requires actionable selection still present in current verified results',()=>{assert.equal(build({actionable:false}),null);assert.equal(build({inResults:false}),null);assert.equal(build({usable:false}),null);assert.ok(build());});
test('EU currency cannot be sized from a USD capital budget',()=>{assert.equal(build({region:'EU'}),null);assert.equal(build().currency,'USD');});
test('queued save keeps the symbol and capital the user submitted',async()=>{
 const a={symbol:'A',mode:'momentum',currency:'USD',actionable:true,state:'ARMED',ts:Date.now()},b={...a,symbol:'B'},nodes={ticketSave:{},ticketCapital:{value:'10000'},ticketVerdict:{}};let release,captured;
 const context={selected:a,plans:[],data:{analyses:[]},breadthData:null,queueError:'',window:{DailySeries:{usable:()=>true}},DailySeries:{usable:()=>true},decisionItems:()=>[a,b],$:k=>nodes[k],ticketSizing:()=>({ok:true}),gov:()=>({budgetLeftUsd:200,maxLossWeekUsd:300,weekPnl:0}),allowedRisk:()=>.5,renderQueue(){},renderPerformance(){},renderStrategyBreakdown(){},Number,Date,Math,TradePlans:{exposure:()=>({value:0,risk:0}),create:(candidate,capital)=>{captured={symbol:candidate.symbol,capital};return {...captured,mode:'momentum'};},mutate:(storage,fn)=>new Promise(resolve=>{release=()=>resolve(fn([]));})},localStorage:{},planStorage:{}};
 vm.createContext(context);vm.runInContext(body+'\n'+html.match(/async function savePlan\(\)\{[\s\S]*?(?=\n  function renderPerformance)/)[0],context);
 const pending=context.savePlan();context.selected=b;nodes.ticketCapital.value='2000';release();await pending;assert.deepEqual(captured,{symbol:'A',capital:10000});assert.equal(nodes.ticketCapital.disabled,false);
});
test('flat prices do not falsely produce overbought RSI100',()=>{const c={};vm.createContext(c);vm.runInContext(readFileSync('lib/indicators.js','utf8'),c);assert.equal(c.TI.calcRSI(Array(40).fill(100),14),50);});

test('daily context is not labelled live or a calibrated probability and Governor coverage is explicit',()=>{
 assert.doesNotMatch(html,/DATE LIVE DIN SUITĂ|<span>ÎNCREDERE<\/span>/);assert.match(html,/SCOR CONTEXT/);assert.match(html,/nu este probabilitatea unui profit/);assert.match(html,/conf\?conf\+'\/100'/);assert.match(html,/Execuțiile și pozițiile Trading 212 nu sunt reconciliate automat/);
});
