import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const NOW=Date.parse('2026-10-08T12:00:00Z'),c={Date,Intl};vm.createContext(c);for(const p of ['lib/daily-series.js','lib/decision-verdict.js','lib/desk-alerts.js'])vm.runInContext(readFileSync(p,'utf8'),c);const A=c.TTDeskAlerts,plain=x=>JSON.parse(JSON.stringify(x));
function sample(){return {scope:'a',now:NOW,snapshot:{fetchedAt:new Date(NOW-1000).toISOString(),positions:[{ticker:'TEST_US_EQ',quantity:2,instrumentCurrency:'USD'}]},capital:{scope:'a',snapshotAt:new Date(NOW-1000).toISOString(),equity:1000,limits:{instrumentPct:20},rows:[{ticker:'TEST_US_EQ',price:94,stop:95,breached:true,quoteCurrency:'USD',weight:30}]}};}
test('a documented stop breach and concentration identify prices, thresholds and next actions',()=>{const r=A.build(sample());assert.equal(r.rows[0].id,'stop:TEST_US_EQ');assert.equal(r.rows[0].severity,'critical');assert.match(r.rows[0].reason,/94 ≤ stop 95 USD/);assert.match(r.rows[0].next,/nu confirmă execuția/);assert.match(r.rows.find(x=>x.id.startsWith('concentration')).reason,/30%.*20%/);});
test('stale and future snapshots never present current stop or concentration alerts',()=>{for(const t of [NOW-300001,NOW+1]){const s=sample();s.snapshot.fetchedAt=new Date(t).toISOString();const r=A.build(s);assert.ok(r.rows.some(x=>x.id==='account-source'));assert.ok(!r.rows.some(x=>x.id.startsWith('stop:')||x.id.startsWith('concentration:')));}});
test('foreign account capital, absent quote currencies and missing limits cannot fabricate risk observations',()=>{const s=sample();s.capital.scope='b';assert.ok(!A.build(s).rows.some(x=>x.id.startsWith('stop:')));s.capital.scope='a';s.capital.rows[0].quoteCurrency=null;s.capital.limits=null;assert.ok(!A.build(s).rows.some(x=>x.id.startsWith('stop:')||x.id.startsWith('concentration:')));});
test('trend deterioration is recomputed from a current, matching EOD series and disappears on recovery',()=>{const s=sample(),bars=Array.from({length:240},(_,i)=>({t:i+1,c:150-i*.1,o:150-i*.1,h:151-i*.1,l:149-i*.1,v:10000}));s.analyses={'a|TEST_US_EQ':{symbol:'TEST',currency:'USD',fetchedAt:NOW,model:{bars,price:bars.at(-1).c,asOf:'2026-10-07',timezone:'America/New_York',closeMinutes:960}}};assert.ok(A.build(s).rows.some(x=>x.id==='trend-down:TEST_US_EQ'));s.analyses['a|TEST_US_EQ'].symbol='OTHER';assert.ok(A.build(s).rows.some(x=>x.id==='trend-source:TEST_US_EQ'));assert.ok(!A.build(s).rows.some(x=>x.id==='trend-down:TEST_US_EQ'));s.analyses['a|TEST_US_EQ'].symbol='TEST';for(const b of bars)b.c=100+b.t*.05;s.analyses['a|TEST_US_EQ'].model.price=bars.at(-1).c;assert.ok(!A.build(s).rows.some(x=>x.id==='trend-down:TEST_US_EQ'));});
test('model evidence is account scoped and recently read; unknown histories cannot grant reassurance',()=>{const s=sample();s.validation={ok:true,identity:{scope:'a',symbol:'TEST',ticker:'TEST_US_EQ'},readAt:NOW,rows:[{model:'knn',horizon:5,state:'review',reason:'Fără avantaj față de reper.'}]};assert.ok(A.build(s).rows.some(x=>x.id.includes(':knn:5')));for(const altered of [{readAt:NOW-60001},{simulation:true},{identity:{scope:'b'}}]){s.validation={...s.validation,...altered};assert.ok(!A.build(s).rows.some(x=>x.id.startsWith('model:')));}});
test('alerts have stable IDs, clear on updated facts and explicitly expose incomplete sources',()=>{const s=sample(),before=plain(A.build(s));assert.deepEqual(plain(A.build(s)),before);s.capital.rows[0].price=100;s.capital.rows[0].breached=false;s.capital.rows[0].weight=10;assert.ok(!A.build(s).rows.some(x=>x.id.startsWith('stop:')||x.id.startsWith('concentration:')));s.snapshot.positions=null;assert.ok(A.build(s).rows.some(x=>x.id==='positions-incomplete'));assert.equal(A.build().rows[0].id,'account');});
