import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const now=Date.parse('2026-10-04T17:00:00Z'),plain=x=>JSON.parse(JSON.stringify(x));
function setup({demo=false}={}){
 const controls=new Map(),events={},document={activeElement:null,getElementById:k=>k==='forecastMonitor'?host:null,addEventListener:(name,f)=>events[name]=f};
 let html='',exported=null,opened=null,seeds=0,checks=[],resolveCheck;
 const control=id=>{if(!controls.has(id))controls.set(id,{id,focus(){document.activeElement=this;},setSelectionRange(a){this.selectionStart=a;}});return controls.get(id);};
 const host={contains:el=>!!el&&controls.get(el.id)===el,querySelector:q=>q==='details'?control('details'):q.startsWith('#')&&html.includes('id="'+q.slice(1)+'"')?control(q.slice(1)):null,querySelectorAll:()=>[]};Object.defineProperty(host,'innerHTML',{get:()=>html,set:v=>{html=v;}});
 const sandbox={document,queueMicrotask,Date:class extends Date{static now(){return now;}},HoldingsLayout:{openModelLedger:t=>{opened=t;return true;},showPage(){}},HoldingsNeuralUI:{exportReport:r=>exported=r}};vm.createContext(sandbox);for(const path of ['lib/daily-series.js','lib/holdings-forecast.js','lib/holdings-forecast-monitor.js'])vm.runInContext(readFileSync(path,'utf8'),sandbox);const F=sandbox.HoldingsForecast;
 let ctx={scope:'private-account',demo,positions:[{ticker:'AAA_US_EQ',quantity:99,apiKey:'SECRET'},{ticker:'BBB_US_EQ',quantity:10}],symbol:p=>p.ticker.split('_')[0],model:()=>({currency:'USD',asOf:'2026-10-02'})};
 function snapshot(p){const identity={scope:ctx.scope,ticker:p.ticker,symbol:ctx.symbol(p),currency:'USD',kind:ctx.demo?'synthetic':'market'},t=Date.parse('2026-09-25T13:30:00Z'),capture=t+7*3600000;
  const entry=F.project({model:'quantile',modelVersion:F.VERSIONS.quantile,trainedAt:capture-60000,state:'research',source:{t,asOf:'2026-09-25',timezone:'America/New_York',closeMinutes:960,close:100,atrPct:2},estimate:{prices:[98,100,103],baselinePrices:[96,100,104]}},identity,capture);
  return {identity,asOf:'2026-10-02',ledger:{ok:true,entries:[entry]},check:null};
 }
 sandbox.HoldingsForecastUI={snapshot,NAMES:{neural:'Neural · MLP',boosting:'Gradient Boosting',quantile:'Regresie cu cuantile',hmm:'HMM',isolation:'Isolation Forest'},overview:()=> 'Date pe model',simulation:()=>{seeds++;},check:(p,manual)=>{checks.push({ticker:p.ticker,manual});return new Promise(resolve=>resolveCheck=resolve);}};
 vm.runInContext(readFileSync('holdings/forecast-monitor.js','utf8'),sandbox);const ui=sandbox.HoldingsForecastMonitorUI;ui.setContext(ctx);
 return {ui,ctx,host,controls,events,sandbox,checks,change:c=>{ctx=c;ui.setContext(c);},resolve:state=>resolveCheck({state}),exported:()=>exported,seeds:()=>seeds,opened:()=>opened};
}
test('all portfolio registries are checked sequentially even when search hides other positions',async()=>{const s=setup(),input=s.controls.get('forecastMonitorQuery');input.oninput({target:{value:'AAA'}});assert.match(s.host.innerHTML,/1 \/ 2 dețineri/);const pending=s.ui.checkAll(true);assert.equal(s.checks.length,1);s.resolve('checked');await new Promise(setImmediate);assert.equal(s.checks.length,2);s.resolve('error');const result=await pending;assert.deepEqual(plain(result),{total:2,done:2,checked:1,errors:1,skipped:0,stopped:false});assert.ok(s.checks.every(x=>x.manual));assert.match(s.host.innerHTML,/1 erori/);});
test('cancel stops following requests while allowing the active one to finish',async()=>{const s=setup(),pending=s.ui.checkAll(true);s.ui.cancel();assert.match(s.host.innerHTML,/cererile următoare sunt oprite/);s.resolve('checked');const result=await pending;assert.equal(s.checks.length,1);assert.equal(result.done,1);assert.equal(result.stopped,true);assert.match(s.host.innerHTML,/Verificare oprită/);});
test('account switches stop an old queue and do not publish its progress into the new account',async()=>{const s=setup(),pending=s.ui.checkAll(true);s.change({...s.ctx,scope:'other'});s.resolve('checked');await pending;assert.equal(s.checks.length,1);assert.doesNotMatch(s.host.innerHTML,/surse procesate/);assert.match(s.host.innerHTML,/Verifică toate registrele/);});
test('removed and renamed instruments are omitted rather than fetched under a stale identity',async()=>{for(const change of [c=>({...c,positions:[c.positions[0]]}),c=>({...c,symbol:p=>p.ticker.startsWith('BBB')?'CHANGED':'AAA'})]){const s=setup(),pending=s.ui.checkAll(true);s.change(change(s.ctx));s.resolve('checked');const result=await pending;assert.equal(s.checks.length,1);assert.equal(result.skipped,1);}});
test('duplicate batch activation makes no overlapping requests and busy single-holding checks are counted as omitted',async()=>{const s=setup(),pending=s.ui.checkAll();await s.ui.checkAll(true);assert.equal(s.checks.length,1);s.resolve('busy');await new Promise(setImmediate);assert.equal(s.checks.length,2);s.resolve('checked');const result=await pending;assert.equal(result.skipped,1);assert.equal(result.checked,1);assert.equal(s.checks[0].manual,false);});
test('export includes all positions despite active display filters, without account identifiers or brokerage amounts',()=>{const s=setup();s.controls.get('forecastMonitorQuery').oninput({target:{value:'AAA'}});s.controls.get('forecastMonitorExport').onclick();const r=s.exported();assert.equal(r.result.version,'holdings-forecast-monitor-v1');assert.equal(r.result.rows.length,2);assert.equal(r.result.visible,undefined);assert.equal(r.symbol,'PORTOFOLIU');assert.ok(!/private-account|SECRET|apiKey|quantity|w1/.test(JSON.stringify(r)));});
test('model filter changes state through the actual control and is separated by account',()=>{const s=setup();s.controls.get('forecastMonitorModel').onchange({target:{value:'hmm'}});assert.match(s.host.innerHTML,/value="hmm" selected/);assert.match(s.host.innerHTML,/Fără estimări/);s.change({...s.ctx,scope:'other'});assert.match(s.host.innerHTML,/value="quantile" selected/);s.change(s.ctx);assert.match(s.host.innerHTML,/value="hmm" selected/);});
test('demo operates only on synthetic examples and does not call market verification',async()=>{const s=setup({demo:true});assert.equal(s.ui.demo({auto:true}),true);assert.equal(s.seeds(),2);assert.equal(s.ui.demo({auto:true}),false);await s.ui.checkAll(true);assert.equal(s.checks.length,0);assert.match(s.host.innerHTML,/estimări ilustrative/);const real=setup();assert.equal(real.ui.demo(),false);assert.equal(real.seeds(),0);});
test('typing and report refresh retain focus and caret in the search control',()=>{const s=setup(),input=s.controls.get('forecastMonitorQuery');input.focus();input.type='search';input.selectionStart=2;input.oninput({target:{value:'AA'}});assert.equal(s.sandbox.document.activeElement,input);assert.equal(input.selectionStart,2);});
test('reports navigation requests automatic checks rather than unbounded manual retries',async()=>{const s=setup();s.events.click({target:{closest:q=>q==='[data-workspace-tab="reports"]'?{}:null}});await new Promise(setImmediate);assert.equal(s.checks.length,1);assert.equal(s.checks[0].manual,false);s.resolve('ignored');await new Promise(setImmediate);s.resolve('ignored');await new Promise(setImmediate);});
