import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const ctx={Intl,Date};vm.createContext(ctx);vm.runInContext(readFileSync('lib/indicators.js','utf8'),ctx);vm.runInContext(readFileSync('lib/holdings-analysis.js','utf8'),ctx);const A=ctx.HoldingsAnalysis;
const now=Date.parse('2026-10-03T12:00:00Z');
function bars(n=260,end='2026-10-02'){const days=[];for(const d=new Date(end+'T13:30:00Z');days.length<n;d.setUTCDate(d.getUTCDate()-1))if(d.getUTCDay()>0&&d.getUTCDay()<6)days.unshift(d.getTime());return days.map((t,i)=>({t,o:70+i*.2,c:70+i*.2+.1,h:70+i*.2+1,l:70+i*.2-1,v:1000}));}
test('aligned uptrend returns indicators and explicit conditional price levels',()=>{const b=bars(),r=A.analyze(b,b,now);assert.equal(r.asOf,'2026-10-02');assert.equal(r.short,'Ascendent');assert.equal(r.medium,'Ascendent');assert.equal(r.long,'Ascendent');assert.ok(r.ema21>r.ema50&&r.ema50>r.ema200);assert.equal(r.rs20,0);assert.equal(r.rvol,1);assert.ok(r.resistance>=r.price);assert.ok(r.support<r.price);assert.ok(r.upTarget>r.resistance);assert.ok(r.downTarget<r.support);assert.equal('probability' in r,false);});
test('no benchmark or zero volume remains unverified, never substitutes neutral values',()=>{const b=bars().map(x=>({...x,v:0})),r=A.analyze(b,null,now);assert.equal(r.rs20,null);assert.equal(r.rvol,null);assert.ok(r.attention.some(x=>x.includes('nu poate fi verificat')));});
test('stale history and corrupted candles block scenario generation',()=>{assert.throws(()=>A.analyze(bars(260,'2026-09-30'),null,now),/STALE/);const b=bars();b[b.length-1].h=1;assert.throws(()=>A.analyze(b,null,now),/invalidă/);});
test('partial daily bar is excluded before the New York session closes',()=>{const b=bars(),r=A.analyze(b,null,Date.parse('2026-10-02T15:00:00Z'));assert.equal(r.asOf,'2026-10-01');assert.equal(r.price,b[b.length-2].c);});
test('weekend and Monday pre-close use Friday while completed Monday uses Monday',()=>{assert.equal(A.expectedDate(now),'2026-10-02');assert.equal(A.expectedDate(Date.parse('2026-10-05T17:00:00Z')),'2026-10-02');assert.equal(A.expectedDate(Date.parse('2026-10-05T22:00:00Z')),'2026-10-05');});
test('insufficient long history does not fabricate EMA200 or a long-term trend',()=>{const r=A.analyze(bars(80),null,now);assert.equal(r.ema200,null);assert.equal(r.long,'Istoric insuficient');assert.throws(()=>A.analyze(bars(50),null,now),/60/);});
