import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function setup(){const c={Intl,Date};vm.createContext(c);for(const f of ['lib/daily-series.js','lib/holdings-pulse.js','lib/holding-evolution.js','lib/trading212-portfolio.js'])vm.runInContext(readFileSync(f,'utf8'),c);return c;}
const at='2026-10-08T18:00:00Z',now=Date.parse(at),p={ticker:'A_US_EQ',quantity:10,currentPrice:102,averagePrice:110,unrealized:-80,currency:'EUR',instrumentCurrency:'USD'},m={asOf:'2026-10-07',currency:'USD',symbol:'A',price:101,ema21:95,ema50:90,short:'Ascendent',medium:'Ascendent',long:'Ascendent',rvol:1.4,rsi:60,rs20:2,support:85,resistance:110,timezone:'America/New_York',closeMinutes:960},e={scope:'a',ticker:p.ticker,symbol:'A',currency:'USD',kind:'market',benchmark:'SPY',sectorBenchmark:null},n={stop:90,stopCurrency:'USD',stopAlertPct:3};
const daily={state:'ready',stale:false,to:at,from:'2026-10-07T18:00:00Z',fromDay:'2026-10-07',pnlDelta:10,pnlCurrency:'EUR',reason:'Comparabil'};
const storage=()=>{const data=new Map();return {data,getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};};
test('shrinking losses use comparable broker P&L, while a weak EOD trend remains explicitly separate',()=>{const E=setup().HoldingEvolution,r=E.joint(p,m,daily,{at,now});assert.equal(r.state,'recovery');assert.equal(r.delta,10);assert.match(r.note,/coincide/);const weak=E.joint(p,{...m,medium:'Descendent'},daily,{at,now});assert.equal(weak.state,'recovery');assert.match(weak.note,/nu confirmă/);assert.equal(r.pnl,-80);});
test('positive broker P&L does not disguise short-term or medium-term deterioration',()=>{const E=setup().HoldingEvolution,r=E.joint({...p,unrealized:50},{...m,short:'Descendent'},daily,{at,now});assert.equal(r.state,'weakening');assert.match(r.note,/nu confirmă continuarea/);assert.equal(E.joint({...p,unrealized:50},m,{...daily,pnlDelta:-10},{at,now}).state,'gain-shrinking');});
test('FX disagreement, changed position quantities and missing P&L never manufacture a recovery',()=>{const E=setup().HoldingEvolution;for(const d of [{...daily,pnlCurrency:'USD'},{...daily,state:'changed',reason:'Cantitate schimbată'},{...daily,pnlDelta:null},{...daily,to:'2026-10-08T17:00:00Z'}])assert.notEqual(E.joint(p,m,d,{at,now}).state,'recovery');assert.equal(E.joint({...p,unrealized:null},m,daily,{at,now}).state,'unknown');assert.match(E.joint(p,m,{...daily,state:'changed',reason:'Cantitate schimbată'},{at,now}).money,/Cantitate schimbată/);});
test('stale and future snapshots block current monetary labels; missing technical data stay unknown',()=>{const E=setup().HoldingEvolution;for(const stamp of ['2026-10-08T17:00:00Z','2026-10-08T18:01:01Z',null])assert.equal(E.joint(p,m,daily,{at:stamp,now}).state,'unknown');assert.equal(E.joint(p,null,daily,{at,now}).technical,false);assert.equal(E.joint(p,{...m,currency:'EUR'},daily,{at,now}).technical,false);});
test('broker technical resolution verifies the account-selected cache, exact benchmarks, session and denomination',()=>{const E=setup().HoldingEvolution,entry={symbol:'A',benchmark:'SPY',sectorBenchmark:null,currency:'USD',model:m,fetchedAt:now};assert.equal(E.resolve(p,entry,{symbol:'A',benchmark:'SPY',now}).medium,'Ascendent');for(const patch of [{symbol:'OTHER'},{benchmark:null},{sectorBenchmark:'XLK'},{currency:'EUR'},{error:'failed'},{fetchedAt:now+60001},{model:{...m,asOf:'2026-10-06'}},{model:{...m,timezone:null}}])assert.equal(E.resolve(p,{...entry,...patch},{symbol:'A',benchmark:'SPY',now}),null);assert.equal(E.resolve({...p,instrumentCurrency:'GBp'},{...entry,currency:'GBX'},{symbol:'A',benchmark:'SPY',now}).currency,'GBX');});
test('observed verdict changes persist once, retain their previous evaluation across repaints and isolate identities',()=>{const c=setup(),E=c.HoldingEvolution,S=storage(),first=c.HoldingsPulse.build(p,m,n,{at,now});assert.equal(E.observe(S,e,p,m,n,first,{at,now}).state,'first');const down={...m,price:88,ema21:89,short:'Descendent',medium:'Descendent',rvol:.8,rs20:-2};let r=E.observe(S,e,p,down,n,c.HoldingsPulse.build(p,down,n,{at,now}),{at,now:now+1000});assert.equal(r.changed,true);assert.match(r.rows.join(' '),/Trend mediu: Ascendent → Descendent/);assert.match(r.rows.join(' '),/EMA50/);assert.match(r.rows.join(' '),/Confirmarea volumului/);const saved=S.getItem(E.key(e));r=E.observe(S,e,p,down,n,c.HoldingsPulse.build(p,down,n,{at,now}),{at,now:now+2000});assert.equal(r.changed,true);assert.equal(S.getItem(E.key(e)),saved);for(const patch of [{scope:'b'},{symbol:'B'},{currency:'EUR'},{benchmark:'QQQ'},{sectorBenchmark:'XLK'},{kind:'synthetic'}])assert.notEqual(E.key({...e,...patch}),E.key(e));});
test('personal stop changes explain the rule rather than inventing a new market session',()=>{const c=setup(),E=c.HoldingEvolution,S=storage();E.observe(S,e,p,m,n,c.HoldingsPulse.build(p,m,n,{at,now}),{at,now});const changed={...n,stop:101},r=E.observe(S,e,p,m,changed,c.HoldingsPulse.build(p,m,changed,{at,now}),{at,now:now+1000});assert.equal(r.changed,true);assert.match(r.rows.join(' '),/Planul personal s-a schimbat/);assert.match(r.rows.join(' '),/aproape de stop/);assert.match(E.changeMarkup(r),/Aceeași sesiune EOD/);});
test('ordinary broker quote updates without a rule change do not rewrite the historical comparison',()=>{const c=setup(),E=c.HoldingEvolution,S=storage();E.observe(S,e,p,m,n,c.HoldingsPulse.build(p,m,n,{at,now}),{at,now});const original=S.getItem(E.key(e)),newp={...p,currentPrice:103};E.observe(S,e,newp,m,n,c.HoldingsPulse.build(newp,m,n,{at,now}),{at,now:now+1000});assert.equal(S.getItem(E.key(e)),original);});
test('corrupt, future, older and unwritable histories are preserved without fabricated before/after conclusions',()=>{const c=setup(),E=c.HoldingEvolution,S=storage(),pulse=c.HoldingsPulse.build(p,m,n,{at,now}),k=E.key(e);S.setItem(k,'bad-json');assert.equal(E.observe(S,e,p,m,n,pulse,{at,now}).state,'unavailable');assert.equal(S.getItem(k),'bad-json');S.data.delete(k);E.observe(S,e,p,m,n,pulse,{at,now});const old=S.getItem(k);assert.equal(E.observe(S,e,p,{...m,asOf:'2026-10-06'},n,pulse,{at,now:now+1000}).state,'unavailable');assert.equal(E.observe(S,e,p,m,n,pulse,{at,now:now-1}).state,'unavailable');assert.equal(S.getItem(k),old);assert.equal(E.observe({getItem:()=>null,setItem(){throw Error('quota');}},e,p,m,n,pulse,{at,now}).state,'unavailable');});
test('joint evolution filters compose with currency and outcome filters without changing the total P&L',()=>{const c=setup(),P=c.T212Portfolio,report=P.build([p,{...p,ticker:'B',unrealized:20}],{currency:'EUR',totalValue:1000}),evolution={A_US_EQ:{state:'recovery'},B:{state:'weakening'}};assert.equal(P.select(report,{currency:'EUR',evolutionFilter:'recovery',evolution})[0].ticker,p.ticker);assert.equal(P.select(report,{currency:'EUR',filter:'gain',evolutionFilter:'recovery',evolution}).length,0);assert.equal(report.groups[0].total,-60);assert.match(P.positionsMarkup(report,{currency:'EUR',evolution:{A_US_EQ:c.HoldingEvolution.joint(p,m,daily,{at,now})}}).html,/Bani și direcție tehnică/);});
test('verdict comparisons and monetary labels escape untrusted display text',()=>{const E=setup().HoldingEvolution;assert.doesNotMatch(E.jointMarkup({state:'unknown',label:'<img>',money:'<script>',trend:'<svg>'}),/<img>|<script>|<svg>/);assert.match(E.changeMarkup({changed:false,state:'first',reason:'<img>',rows:[]}),/&lt;img&gt;/);});
