import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const c={};vm.createContext(c);for(const p of ['lib/holdings-neural.js','lib/holdings-hmm.js'])vm.runInContext(readFileSync(p,'utf8'),c);const R=c.HoldingsHMM,N=c.HoldingsNeural,plain=x=>JSON.parse(JSON.stringify(x)),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`),day=86400000;
const model={initial:[1/3,1/3,1/3],transitions:[[.8,.1,.1],[.15,.7,.15],[.1,.1,.8]],means:[[-1,-1,0],[0,0,0],[1,1,0]],variances:[[1,1,1],[1,1,1],[1,1,1]]},short=[{t:0,x:[-.8,-.7,0]},{t:day,x:[.1,.2,.1]},{t:2*day,x:[.9,.8,-.1]}];
function enumerate(m,rows){const weights=[];for(let a=0;a<3;a++)for(let b=0;b<3;b++)for(let d=0;d<3;d++){const states=[a,b,d];let p=m.initial[a];rows.forEach((r,t)=>{p*=Math.exp(R.emission(m,r.x)[states[t]]);if(t)p*=m.transitions[states[t-1]][states[t]];});weights.push({states,p});}return weights;}
const rows=Array.from({length:620},(_,i)=>{const state=Math.floor(i/35)%3,jitter=.06*Math.sin(i*1.73);return {t:i*day,x:[[-1.5,0,1.5][state]+jitter,[-3,0,3][state]+jitter,[2.7,1.8,1.1][state]+jitter]};}),parts=R.split(rows);let result;
test('forward likelihood and training smoothing agree with enumeration of all hidden paths',()=>{const paths=enumerate(model,short),total=paths.reduce((s,x)=>s+x.p,0),e=R.expectation(model,short),f=R.filter(model,short);near(e.nll,-Math.log(total)/3);near(f.nll,e.nll);short.forEach((_,t)=>[0,1,2].forEach(k=>near(e.gamma[t][k],paths.filter(x=>x.states[t]===k).reduce((s,x)=>s+x.p,0)/total)));[0,1,2].forEach(k=>[0,1,2].forEach(j=>near(e.transitions[k][j],paths.reduce((s,x)=>s+x.p*([0,1].filter(t=>x.states[t]===k&&x.states[t+1]===j).length),0)/total)));});
test('causal features include the newest observations and never change when future bars are appended',()=>{const now=Date.parse('2026-10-04T08:00:00Z'),bars=N.demoBars(0,now),prefix=R.dataset(bars.slice(0,1050),now),all=R.dataset(bars,now);assert.deepEqual(plain(all.slice(0,prefix.length)),plain(prefix));assert.equal(all.at(-1).t,bars.at(-1).t);assert.equal(all.length,bars.length-199);});
test('forward regime probabilities do not use later observations',()=>{const a=R.filter(model,short),b=R.filter(model,[...short,{t:3*day,x:[-100,90,40]}]);assert.deepEqual(plain(a.steps),plain(b.steps.slice(0,3)));});
test('learned states outperform a single Gaussian on known synthetic regimes',()=>{result=R.fitPartitions(parts);assert.ok(R.valid(result));assert.equal(result.quality.informative,true);assert.deepEqual(plain(result.profiles.map(x=>x.label)),['Deteriorare','Consolidare / tranziție','Ascendent']);assert.ok(result.report.test.hmm<result.report.test.gaussian-.5);assert.ok(result.current.p[result.current.state]>.9);assert.equal(result.history.length,result.report.test.n);});
test('held-out indicator changes cannot choose scale, parameters or model selection',()=>{const altered={...parts,test:parts.test.map(r=>({...r,x:r.x.map(x=>x+25)}))},other=R.fitPartitions(altered);for(const k of ['scale','model','selection','profiles','quality','baseline'])assert.deepEqual(plain(other[k]),plain(result[k]));assert.notEqual(other.report.test.hmm,result.report.test.hmm);assert.equal(R.assess(other).state,'drift');});
test('serialized posteriors, transitions, baselines and recent scores must match the parameters',()=>{assert.ok(R.valid(plain(result)));for(const change of [x=>x.current.p=[1,0,0],x=>x.timeline.at(-1).state=1,x=>x.model.transitions[0][0]=1,x=>x.profiles[0].label='Ascendent',x=>x.report.test.hmm-=1,x=>x.baseline.weights=[1,0,0],x=>x.selection.validation.to=x.report.periods.test.to,x=>x.anchor.stable=2]){const altered=plain(result);change(altered);assert.equal(R.valid(altered),false);}});
test('a gap resets the filter instead of bridging missing sessions',()=>{const f=R.filter(model,[short[0],{...short[2],t:10*day}]);assert.equal(f.steps[1].reset,true);assert.deepEqual(plain(f.steps[1].p),plain(R.advance(model,short[2].x).p));});
test('collapsed or weakly represented states remain inconclusive',()=>{const constant=Array.from({length:320},(_,i)=>({t:i*day,x:[.1,1.1,2]})),r=R.evaluate(constant);assert.ok(R.valid(r));assert.equal(R.assess(r).state,'weak');assert.equal(r.walk.status,'insufficient');assert.ok(r.profiles.every(x=>x.label==='Ascendent'));});
test('three test intervals are disjoint and their summary cannot be invented',()=>{const r=R.evaluate(rows);assert.ok(R.valid(r));assert.equal(r.walk.status,'complete');assert.equal(r.walk.folds.length,3);r.walk.folds.forEach((f,i)=>{if(i)assert.ok(f.periods.test.from>r.walk.folds[i-1].periods.test.to);assert.ok(f.periods.train.to<f.periods.validation.from);assert.ok(f.periods.validation.to<f.periods.test.from);});const p=R.publicReport(r);assert.ok(R.validPublic(p));for(const change of [x=>x.walk.summary.wins=0,x=>x.quality.informative=!x.quality.informative,x=>x.report.test.hmm-=.5,x=>x.walk.folds[1].periods.test.from=x.walk.folds[0].periods.test.to]){const altered=plain(p);change(altered);assert.equal(R.validPublic(altered),false);}});
test('invalid observations and future or malformed OHLC are rejected',()=>{assert.throws(()=>R.fitPartitions({...parts,test:parts.test.map((r,i)=>i? r:{...r,x:[NaN,1,2]})}));const now=Date.parse('2026-10-04T08:00:00Z'),bars=N.demoBars(0,now);bars.at(-1).t=now+day;assert.throws(()=>R.dataset(bars,now));});
