import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const core={};vm.createContext(core);for(const name of ['daily-series','holdings-neural','holdings-garch','holdings-forecast','holdings-forecast-monitor'])vm.runInContext(readFileSync('lib/'+name+'.js','utf8'),core);
const F=core.HoldingsForecast,plain=x=>JSON.parse(JSON.stringify(x)),now=Date.parse('2026-10-04T17:00:00Z'),capture=Date.parse('2026-09-01T21:00:00Z'),e={scope:'private',ticker:'TEST_US_EQ',symbol:'TEST',currency:'USD',kind:'market'};
const bars=[];for(let day=Date.parse('2026-09-01T13:30:00Z');day<=Date.parse('2026-10-02T13:30:00Z');day+=86400000){if([0,6].includes(new Date(day).getUTCDay()))continue;const c=100*Math.exp(.02*bars.length);bars.push({t:day,o:c,h:c*1.01,l:c*.99,c,v:10000});}
const source={symbol:'TEST',currency:'USD',timezone:'America/New_York',closeMinutes:960,asOf:'2026-10-02',retrievedAt:now,bars};
const base={trainedAt:capture-60000,state:'limited',source:{t:bars[0].t,asOf:'2026-09-01',timezone:'America/New_York',closeMinutes:960,close:100,atrPct:2}};
const garch=(horizon=5)=>({...base,model:'garch',modelVersion:F.VERSIONS.garch,horizon,estimate:{mu:.5,predictedVariance:10,constantVariance:15,ewmaVariance:20}});
const verdict=(direction=2)=>({...base,model:'verdict',modelVersion:F.VERSIONS.verdict,state:direction===null?'weak':direction===2?'up':direction===0?'down':'mixed',estimate:{title:direction===null?'Neconcludent':'Înclinare experimentală',verdictState:direction===null?'weak':direction===2?'up':direction===0?'down':'mixed',direction,sourceFingerprint:'ohlcv-v1:fixture',reasons:['Motive înghețate.'],cards:['neural','boosting','hmm','isolation','quantile','garch'].map(id=>({id,version:F.VERSIONS[id],state:'limited',value:'Rezultat'}))}});
const saved=(input=garch())=>F.project(input,e,capture),resolved=input=>F.verify(saved(input),source,now);
function store(){const data=new Map();return {data,api:F.createStore({getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)})};}
test('GARCH keeps distinct immutable first estimates at 5 and 20 sessions on one EOD',()=>{const s=store();for(const h of [5,20])assert.equal(s.api.save(garch(h),e,capture).saved,true);const changed=garch(20);changed.estimate.predictedVariance=999;assert.equal(s.api.save(changed,e,capture+1000).duplicate,true);const rows=s.api.read(e).entries;assert.equal(rows.length,2);assert.notEqual(rows[0].id,rows[1].id);assert.equal(rows[1].estimate.predictedVariance,10);assert.ok(rows.every(r=>F.validEntry(r,e,now)));});
test('20-session forecasts remain pending at 5 and 19 observations and resolve exactly at 20',()=>{for(const n of [5,19,20]){const xs=bars.slice(0,n+1),end=xs.at(-1),checked=end.t+8*3600000,r=F.verify(saved(garch(20)),{...source,bars:xs,asOf:core.DailySeries.date(end.t,source.timezone),retrievedAt:checked},checked);assert.equal(r.verification.sessions,n);assert.equal(r.verification.state,n===20?'resolved':'pending');assert.equal(F.metric(r)===null,n<20);assert.ok(F.validEntry(r,e,now));if(n===20){assert.equal(r.outcome.t,bars[20].t);assert.equal(r.outcome.path.length,20);}}});
test('GARCH uses the frozen mean and every log return, with QLIKE against frozen variance benchmarks',()=>{for(const h of [5,20]){const r=resolved(garch(h)),m=F.metric(r),actual=h*(2-.5)**2;assert.ok(Math.abs(m.observedVariance-actual)<1e-10);assert.ok(Math.abs(m.observedPct-Math.sqrt(actual))<1e-10);for(const [key,v] of [['score',10],['constantScore',15],['ewmaScore',20]])assert.ok(Math.abs(m[key]-(Math.log(v)+actual/v))<1e-10);assert.equal(m.correct,undefined);assert.equal(m.actualClass,undefined);assert.ok(F.validEntry(r,e,now));}});
test('a later query does not move either GARCH target or its observed proxy',()=>{for(const h of [5,20]){const a=resolved(garch(h)),end=bars[h],checked=end.t+8*3600000,b=F.verify(saved(garch(h)),{...source,bars:bars.slice(0,h+1),asOf:core.DailySeries.date(end.t,source.timezone),retrievedAt:checked},checked);assert.equal(a.outcome.t,b.outcome.t);assert.equal(F.metric(a).observedVariance,F.metric(b).observedVariance);}});
test('revisions inside a completed volatility path exclude the result while preserving its forecast and original path',()=>{const a=resolved(garch(20)),xs=plain(bars);xs[10].c+=.1;const b=F.verify(a,{...source,bars:xs},now+1000);assert.equal(b.verification.state,'unverifiable');assert.deepEqual(plain(a.estimate),plain(b.estimate));assert.deepEqual(plain(a.outcome),plain(b.outcome));assert.equal(F.aggregate([b],'garch',20).n,0);});
test('invalid horizons, nonpositive variances and incompatible verdict directions fail closed',()=>{for(const h of [undefined,0,10,21,'20'])assert.equal(saved({...garch(),horizon:h}),null);for(const change of [x=>x.estimate.predictedVariance=0,x=>x.estimate.ewmaVariance=NaN,x=>x.estimate.mu=Infinity]){const x=garch();change(x);assert.equal(saved(x),null);}const x=verdict();x.estimate.verdictState='weak';assert.equal(saved(x),null);x.estimate.direction=null;x.estimate.cards.pop();assert.equal(saved(x),null);});
test('verdict title, reasons and per-model summaries remain fixed after reanalysis',()=>{const s=store();assert.equal(s.api.save(verdict(),e,capture).saved,true);const x=verdict(0);x.estimate.reasons=['New result'];assert.equal(s.api.save(x,e,capture+1000).duplicate,true);const row=s.api.read(e).entries[0];assert.equal(row.estimate.direction,2);assert.equal(row.estimate.reasons[0],'Motive înghețate.');assert.equal(row.estimate.cards.length,6);});
test('non-directional verdicts are observed abstentions without invented correct or incorrect predictions',()=>{const r=resolved(verdict(null)),m=F.metric(r),a=F.aggregate([r],'verdict');assert.equal(m.correct,null);assert.equal(a.directional,0);assert.equal(a.abstentions,1);assert.equal(a.accuracy,null);assert.equal(F.report([r]).find(x=>x.model==='verdict').flags.enough,false);});
test('frozen combined direction is evaluated by the initial ATR thresholds after five sessions',()=>{const r=resolved(verdict()),m=F.metric(r);assert.equal(m.actualClass,2);assert.equal(m.correct,true);assert.equal(F.aggregate([r],'verdict').accuracy,1);});
test('new record projections drop brokerage, parameters and unknown card fields, and persisted unknown fields are refused',()=>{for(const make of [garch,verdict]){const x=make();x.quantity=999;x.apiKey='SECRET';x.estimate.weights='SECRET';if(x.model==='verdict')x.estimate.cards[0].apiKey='SECRET';const r=saved(x);assert.ok(!/SECRET|quantity|weights|apiKey|private/.test(JSON.stringify(r)));assert.ok(F.validEntry(r,e,now));r.estimate.apiKey='SECRET';assert.equal(F.validEntry(r,e,now),false);}});
test('existing v1 forecasts remain readable and byte-identical when new types are appended',()=>{const s=store(),old=saved({...base,model:'neural',modelVersion:F.VERSIONS.neural,estimate:{classIndex:2,baselineClass:1}});s.data.set(F.key(e),JSON.stringify({version:'holdings-forecast-v1',entries:[old]}));const before=JSON.stringify(old);assert.equal(s.api.save(garch(20),e,capture).saved,true);assert.equal(s.api.save(verdict(),e,capture).saved,true);const rows=s.api.read(e).entries;assert.equal(JSON.stringify(rows[0]),before);assert.equal(rows[0].id,'neural|2026-09-01');assert.equal(rows.length,3);});
test('horizon and nested-card tampering cannot promote invalid records to valid completion',()=>{const r=plain(resolved(garch(20)));r.horizon=5;assert.equal(F.validEntry(r,e,now),false);const v=plain(resolved(verdict()));v.estimate.cards[0].apiKey='SECRET';assert.equal(F.validEntry(v,e,now),false);});
test('both new types retain account, currency, ticker and simulation isolation',()=>{const s=store();s.api.save(garch(20),e,capture);s.api.save(verdict(),e,capture);for(const [k,v] of Object.entries({scope:'other',currency:'EUR',ticker:'ALT',kind:'synthetic'}))assert.equal(s.api.read({...e,[k]:v}).entries.length,0);});
function history({n=24,spacing=21,model='garch',horizon=20,abstain=0,poor=false}={}){
 const xs=core.HoldingsNeural.demoBars(0,now),identity={...e,kind:'synthetic'},entries=[];
 for(let i=0;i<n;i++){
  const at=xs.length-900+i*spacing,b=xs[at],captured=b.t+7*3600000,src={t:b.t,asOf:core.DailySeries.date(b.t,'America/New_York'),timezone:'America/New_York',closeMinutes:960,close:b.c,atrPct:2};
  const input=model==='garch'?garch(horizon):verdict(i<abstain?null:2);input.source=src;input.trainedAt=captured-60000;
  if(model==='garch'&&poor)input.estimate.predictedVariance=100000;
  const row=F.verify(F.project(input,identity,captured),{symbol:identity.symbol,currency:identity.currency,timezone:src.timezone,bars:xs.slice(at,at+horizon+1),retrievedAt:now},now);
  assert.ok(F.validEntry(row,identity,now));entries.push(row);
 }
 return {identity,asOf:'2026-10-02',ledger:{ok:true,entries}};
}
test('portfolio GARCH counts, scores and pending results stay isolated by horizon',()=>{
 const x=history({poor:true}),short=history({n:7,horizon:5});x.ledger.entries.push(...short.ledger.entries);
 for(const [h,n,enough] of [[5,7,false],[20,24,true]]){const r=core.HoldingsForecastMonitor.build([x],{scope:e.scope,kind:'synthetic',model:'garch',horizon:h,now}),row=r.rows[0];assert.equal(row.horizon,h);assert.equal(row.report.n,n);assert.equal(row.report.flags.enough,enough);assert.equal(row.report.accuracy,undefined);assert.equal(row.report.flags.noEdge,h===20);assert.equal(row.state,h===20?'review':'limited');}
 x.ledger.entries.filter(r=>r.horizon===20).forEach(r=>{r.outcome=null;r.verification={state:'pending',checkedAt:null,sessions:0,reason:'Aștept 20 sesiuni.'};});
 const r=core.HoldingsForecastMonitor.build([x],{scope:e.scope,kind:'synthetic',model:'garch',horizon:20,now});assert.equal(r.rows[0].report.n,0);assert.equal(r.rows[0].report.pending,24);assert.equal(r.rows[0].state,'waiting');assert.match(r.rows[0].reason,/20 sesiuni/);
});
test('twenty-session overlapping paths cannot inflate independent observation counts',()=>{const x=history({spacing:6});const r=F.report(x.ledger.entries).find(r=>r.model==='garch'&&r.horizon===20);assert.equal(r.all,24);assert.equal(r.n,6);assert.equal(r.flags.enough,false);});
test('verdict evidence thresholds require twenty evaluated directions regardless of abstention totals',()=>{for(const [abstain,enough] of [[6,false],[4,true],[24,false]]){const x=history({model:'verdict',horizon:5,abstain}),r=F.report(x.ledger.entries).find(r=>r.model==='verdict');assert.equal(r.n,24);assert.equal(r.directional,24-abstain);assert.equal(r.abstentions,abstain);assert.equal(r.flags.enough,enough);if(abstain===24)assert.equal(r.accuracy,null);}});
test('real fitted GARCH forecasts feed the ledger with identical observed proxies and losses at both horizons',()=>{
 const xs=core.HoldingsNeural.demoBars(0,now),at=xs.length-30,b=xs[at],captured=b.t+7*3600000,G=core.HoldingsGarch,result=G.evaluate(G.dataset(xs.slice(0,at+1),captured),{now:captured});assert.ok(G.valid(result,captured));
 const mu=result.folds.at(-1).model.mu,identity={...e,kind:'synthetic'};
 for(const h of result.current.horizons){const input={...garch(h.horizon),trainedAt:captured,source:{...base.source,t:b.t,asOf:core.DailySeries.date(b.t,'America/New_York'),close:b.c},estimate:{mu,predictedVariance:h.cumulativePct**2,constantVariance:h.constantPct**2,ewmaVariance:h.ewmaPct**2}},row=F.verify(F.project(input,identity,captured),{symbol:e.symbol,currency:e.currency,timezone:input.source.timezone,bars:xs.slice(at,at+h.horizon+1),retrievedAt:now},now),m=F.metric(row);
  let previous=b.c,observed=0;for(const next of xs.slice(at+1,at+h.horizon+1)){observed+=(100*Math.log(next.c/previous)-mu)**2;previous=next.c;}
  assert.ok(F.validEntry(row,identity,now));assert.equal(m.observedVariance,observed);assert.equal(m.score,G.qlike(observed,h.cumulativePct**2));assert.equal(m.constantScore,G.qlike(observed,h.constantPct**2));assert.equal(m.ewmaScore,G.qlike(observed,h.ewmaPct**2));
 }
});
