import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const c={Date};vm.createContext(c);vm.runInContext(readFileSync('lib/holdings-notes.js','utf8'),c);const N=c.HoldingsNotes;
test('notes keep original thesis and entire history',()=>{const h=Array.from({length:150},(_,i)=>({at:i}));const n=N.change({text:'original',history:h},{text:'revised'});assert.equal(n.initialText,'original');assert.equal(n.history.length,151);});
test('invalid review dates, negative stops and oversized plans are rejected',()=>{for(const patch of [{stop:-1},{stop:'broken'},{plan:{hold:'a',reduce:'b',invalidate:'c',review:'2026-02-30'}},{plan:{hold:'a'.repeat(2001),reduce:'',invalidate:''}}])assert.throws(()=>N.change({},patch));});
test('a damaged register cannot be overwritten with an empty fallback',()=>{let raw='{bad',write=false;assert.throws(()=>N.save({getItem:()=>raw,setItem:()=>{write=true;}},'scope|A',{text:'new'},{}));assert.equal(write,false);});
test('saving one holding preserves another account and detects concurrent edit',()=>{let raw=JSON.stringify({'other|B':{text:'keep'},'scope|A':{text:'current'}});const store={getItem:()=>raw,setItem:(k,v)=>{raw=v;}};assert.throws(()=>N.save(store,'scope|A',{text:'new'},{text:'old'}));N.save(store,'scope|A',{text:'new'},{text:'current'});assert.equal(JSON.parse(raw)['other|B'].text,'keep');});
test('quota failure leaves persisted and original note unchanged',()=>{const old={text:'old'},raw=JSON.stringify({'s|A':old});assert.throws(()=>N.save({getItem:()=>raw,setItem(){throw Error('quota');}},'s|A',{text:'new'},old));assert.equal(old.text,'old');assert.equal(JSON.parse(raw)['s|A'].text,'old');});

test('manual targets require a positive price and known denomination, and retain their audit history',()=>{for(const patch of [{targetPrice:0,targetCurrency:'USD'},{targetPrice:-1,targetCurrency:'USD'},{targetPrice:'broken',targetCurrency:'USD'},{targetPrice:Infinity,targetCurrency:'USD'},{targetPrice:[],targetCurrency:'USD'},{targetPrice:100},{targetPrice:100,targetCurrency:'invalid'}])assert.throws(()=>N.change({},patch));const n=N.change({text:'original',history:[{at:'old'}]},{targetPrice:'95',targetCurrency:'USD'});assert.equal(n.targetPrice,'95');assert.equal(n.initialText,'original');assert.equal(n.history.length,2);assert.equal(n.history[1].targetPrice,'95');assert.equal(n.history[1].targetCurrency,'USD');const cleared=N.change(n,{targetPrice:'',targetCurrency:'USD'});assert.equal(cleared.targetPrice,'');assert.equal(cleared.history[1].targetPrice,'95');});
