import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function setup(){const c={Intl,Date};vm.createContext(c);for(const f of ['lib/holding-scenarios.js','lib/holding-reduction.js'])vm.runInContext(readFileSync(f,'utf8'),c);return c.HoldingReduction;}
const p={ticker:'A',quantity:10,currentPrice:86,averagePrice:99,instrumentCurrency:'USD',currency:'USD',unrealized:-130},n={stop:85,stopCurrency:'USD'},at='2026-10-08T18:00:00Z',options={at,now:Date.parse(at),accountCurrency:'USD',available:1000};
test('a 25 percent reduction scales quantity, gross proceeds, cost-based result and remaining stop distance',()=>{const R=setup(),r=R.build(p,n,null,{...options,percent:25});assert.equal(r.removed,2.5);assert.equal(r.remaining,7.5);assert.equal(r.proceeds,215);assert.equal(r.soldPricePnl,-32.5);assert.equal(r.remainingValue,645);assert.equal(r.initialStopRisk,10);assert.equal(r.remainingStopRisk,7.5);assert.equal(r.projectedAvailable,1215);});
test('a hypothetical exit above cost can have a positive price result without asserting a net broker profit',()=>{const r=setup().build(p,n,null,{...options,percent:50,price:105});assert.equal(r.proceeds,525);assert.equal(r.soldPricePnl,30);assert.equal(r.remainingValue,525);assert.equal(r.remainingStopRisk,100);assert.equal(r.brokerRealized,undefined);});
test('zero and complete mathematical reductions retain valid zero values and leave the source position untouched',()=>{const R=setup(),before=JSON.stringify(p),zero=R.build(p,n,null,{...options,percent:0}),all=R.build(p,n,null,{...options,percent:100});assert.equal(zero.proceeds,0);assert.equal(zero.soldPricePnl,0);assert.equal(zero.remaining,10);assert.equal(all.remaining,0);assert.equal(all.remainingStopRisk,0);assert.equal(all.remainingValue,0);assert.equal(JSON.stringify(p),before);});
test('fractional quantities and percentages are kept in the arithmetic and readable in the UI',()=>{const R=setup(),position={...p,quantity:.5},r=R.build(position,n,null,{...options,percent:25});assert.equal(r.removed,.125);assert.equal(r.remaining,.375);assert.match(R.markup(position,n,null,{...options,scope:'a'}),/0,125 unități · rămân 0,375 unități/);});
test('different currencies and pence versus pounds never invent account cash or converted proceeds',()=>{const R=setup(),r=R.build({...p,currency:'EUR'},n,null,{...options,accountCurrency:'EUR'});assert.equal(r.proceeds,215);assert.equal(r.projectedAvailable,null);assert.match(r.accountReason,/Monede diferite/);const pence=R.build({...p,instrumentCurrency:'GBp'},{stop:85,stopCurrency:'GBX'},null,{...options,accountCurrency:'GBP'});assert.equal(pence.proceeds,215);assert.equal(pence.projectedAvailable,null);});
test('old broker or EOD references remain dated and cannot extrapolate available account cash',()=>{const R=setup();assert.equal(R.build(p,n,null,{...options,at:'2026-10-08T17:00:00Z'}).projectedAvailable,null);const r=R.build({...p,currentPrice:null},n,{price:90,currency:'USD',asOf:'2026-10-07'},{...options});assert.equal(r.proceeds,225);assert.equal(r.projectedAvailable,null);assert.equal(r.reference.kind,'eod');});
test('invalid fractions, hypothetical prices, quantities and missing averages cannot become fabricated results',()=>{const R=setup();for(const percent of [-1,101,'',null,true,Infinity])assert.ok(R.build(p,n,null,{...options,percent}).reason);for(const price of [0,-1,'',null,true,Infinity])assert.ok(R.build(p,n,null,{...options,price}).reason);assert.ok(R.build({...p,quantity:null},n,null,options).reason);const missing=R.build({...p,averagePrice:null},n,null,options);assert.equal(missing.soldPricePnl,null);assert.equal(missing.proceeds,215);});
test('a stop at or above the simulated price does not manufacture a positive remaining risk',()=>{const r=setup().build(p,n,null,{...options,price:84});assert.equal(r.remainingStopRisk,null);assert.match(r.stopReason,/la\/sub stop/);});
test('overflow is rejected and missing available cash stays unknown rather than starting from zero',()=>{const R=setup();assert.ok(R.build({...p,quantity:1e308},n,null,options).reason);assert.equal(R.build(p,n,null,{...options,available:null}).projectedAvailable,null);assert.equal(R.build(p,n,null,{...options,available:0}).projectedAvailable,215);});
test('native disclosure controls are explicitly simulated and labels cannot inject HTML',()=>{const R=setup(),html=R.markup({...p,ticker:'<img>'},n,null,{...options,scope:'a',simulated:true});assert.match(html,/DATE FICTIVE/);assert.match(html,/aria-label="Procent de redus"/);assert.match(html,/Nicio tranzacție/);assert.doesNotMatch(html,/<img>/);});
test('editing the hypothetical exit keeps the input and disclosure intact and retains drafts only for the selected account',()=>{const R=setup(),html=R.markup(p,n,null,{...options,scope:'a'}),key=JSON.stringify(['a','A','USD']),price={value:'99',matches:q=>q==='[data-reduction-price]'},percent={value:'25'},result={innerHTML:''},buttons=[25,50].map(v=>({dataset:{reductionPreset:String(v)},setAttribute(k,v){this[k]=v}})),host={innerHTML:html,open:true,dataset:{holdingReduction:key},querySelector:q=>q==='[data-reduction-result]'?result:q==='[data-reduction-price]'?price:percent,querySelectorAll:()=>buttons,contains:()=>true};R.bind({querySelectorAll:()=>[host]});host.oninput({target:price});assert.equal(host.innerHTML,html);assert.equal(host.open,true);assert.equal(price.value,'99');assert.match(result.innerHTML,/247,5 USD/);assert.match(R.markup({...p,currentPrice:88},n,null,{...options,scope:'a'}),/value="99"/);assert.doesNotMatch(R.markup(p,n,null,{...options,scope:'b'}),/value="99"/);host.onclick({target:{closest:()=>buttons[1]}});assert.equal(percent.value,'50');assert.equal(price.value,'99');assert.equal(host.open,true);});
