import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function setup(){const writes=new Map(),workers=[],button={dataset:{isolationTrain:'0'}};let resolveFetch,neuralBusy=false,hmmBusy=false;const s={HoldingsIsolation:{VERSION:'holdings-isolation-v1',valid:()=>true,assess:()=>({state:'ordinary',message:'În tipar.'}),FEATURES:[],demoBars:()=>[{t:10,o:1,h:2,l:1,c:1,v:1}]},HoldingsNeural:{demoBars:()=>[{t:10,o:1,h:2,l:1,c:1,v:1}]},HoldingsNeuralUI:{refresh(){},busy:()=>neuralBusy},HoldingsHMMUI:{busy:()=>hmmBusy},document:{querySelectorAll:q=>q==='[data-isolation-train]'?[button]:[]},localStorage:{getItem:k=>writes.get(k)||null,setItem:(k,v)=>writes.set(k,v)},D:{fetchStock:()=>new Promise(resolve=>resolveFetch=resolve)},DailySeries:{read:()=>({bars:[{t:10}],asOf:'2026-10-02',currency:'USD',timezone:'America/New_York'}),date:()=> '2026-10-02'},setTimeout:()=>1,clearTimeout(){},Worker:class{constructor(){workers.push(this);}postMessage(payload){this.payload=payload;}terminate(){this.terminated=true;}}};vm.createContext(s);vm.runInContext(readFileSync('lib/holdings-model-storage.js','utf8'),s);vm.runInContext(readFileSync('holdings/isolation.js','utf8'),s);const context=(scope,demo=true)=>({scope,demo,positions:[{ticker:'TEST_US_EQ',quantity:42,averagePrice:99}],symbol:()=> 'TEST',model:()=>({asOf:'2026-10-02',currency:'USD'})});s.HoldingsIsolationUI.setContext(context('account-a'));s.HoldingsIsolationUI.bind();return {ui:s.HoldingsIsolationUI,workers,writes,button,context,resolve:()=>resolveFetch([]),neuralBusy:()=>neuralBusy=true,hmmBusy:()=>hmmBusy=true};}
test('Isolation Forest worker receives no portfolio, balance or credentials',()=>{const s=setup();s.button.onclick();assert.deepEqual(Object.keys(s.workers[0].payload).sort(),['bars','id','now']);});
test('account changes terminate Isolation Forest jobs and discard delayed messages',()=>{const s=setup();s.button.onclick();const w=s.workers[0];s.ui.setContext(s.context('account-b'));assert.equal(w.terminated,true);w.onmessage({data:{id:w.payload.id,result:{current:{t:10}}}});assert.equal(s.writes.size,0);});
test('a cancelled history request cannot start a worker in another account',async()=>{const s=setup();s.ui.setContext(s.context('a',false));s.button.onclick();s.ui.setContext(s.context('b',false));s.resolve();await new Promise(r=>setImmediate(r));assert.equal(s.workers.length,0);});
test('Isolation Forest cancellation and neural mutual exclusion leave no orphan workers',()=>{const s=setup();s.button.onclick();s.ui.cancel();assert.equal(s.workers[0].terminated,true);assert.equal(s.ui.busy(),false);s.neuralBusy();s.button.onclick();assert.equal(s.workers.length,1);});
test('demo results stay in memory while real results require the source session',async()=>{const s=setup();s.button.onclick();let w=s.workers[0];w.onmessage({data:{id:w.payload.id,result:{current:{t:10}}}});assert.equal(s.writes.size,0);s.ui.setContext(s.context('real',false));s.button.onclick();s.resolve();await new Promise(r=>setImmediate(r));w=s.workers.at(-1);w.onmessage({data:{id:w.payload.id,result:{current:{t:11}}}});assert.equal(s.writes.size,0);});

test('a new EOD session in the same account cancels a pending Isolation Forest job',()=>{const s=setup();s.button.onclick();const context=s.context('account-a');context.model=()=>({asOf:'2026-10-03',currency:'USD'});s.ui.setContext(context);assert.equal(s.workers[0].terminated,true);assert.equal(s.ui.busy(),false);});
test('a blocked storage write stays visible as temporary retention rather than saved history',async()=>{const s=setup();s.ui.setContext(s.context('real',false));s.button.onclick();s.resolve();await new Promise(r=>setImmediate(r));s.writes.set=()=>{throw Error('Storage blocked');};const w=s.workers[0];w.onmessage({data:{id:w.payload.id,result:{current:{t:10}}}});const snapshot=s.ui.inspect(s.context('real',false).positions[0]);assert.equal(s.writes.size,0);assert.equal(snapshot.usable,true);assert.equal(snapshot.record.retention,'session');assert.match(snapshot.persistence.message,/disponibil doar în această sesiune.*refuzat salvarea permanentă/);});

test('Isolation Forest does not start during an HMM job',()=>{const s=setup();s.hmmBusy();s.button.onclick();assert.equal(s.workers.length,0);});

test('a verified Forest remains ready when persistent browser storage is full',async()=>{
 const s=setup();s.ui.setContext(s.context('real',false));const pending=s.ui.run(s.context('real',false).positions[0]);s.resolve();await new Promise(r=>setImmediate(r));
 const quota=Object.assign(new Error('Quota exceeded'),{name:'QuotaExceededError'});s.writes.set=()=>{throw quota;};
 const worker=s.workers[0];worker.onmessage({data:{id:worker.payload.id,result:{current:{t:10}}}});
 const result=await pending;assert.equal(result.state,'ready');assert.equal(result.persistence,'session');assert.equal(s.writes.size,0);
});
test('temporary Forest reports remain isolated by account and disappear on a fresh page',async()=>{const s=setup(),position=s.context('a',false).positions[0];s.ui.setContext(s.context('a',false));const pending=s.ui.run(position);s.resolve();await new Promise(r=>setImmediate(r));s.writes.set=()=>{throw Error('Blocked');};const worker=s.workers[0];worker.onmessage({data:{id:worker.payload.id,result:{current:{t:10}}}});assert.equal((await pending).state,'ready');assert.equal(s.ui.inspect(position).usable,true);s.ui.setContext(s.context('b',false));assert.equal(s.ui.inspect(position).usable,false);s.ui.setContext(s.context('a',false));assert.equal(s.ui.inspect(position).usable,true);const fresh=setup();fresh.ui.setContext(fresh.context('a',false));assert.equal(fresh.ui.inspect(position).usable,false);});
test('an invalid worker result remains an error even when storage is full',async()=>{const s=setup();s.ui.setContext(s.context('real',false));const pending=s.ui.run(s.context('real',false).positions[0]);s.resolve();await new Promise(r=>setImmediate(r));s.writes.set=()=>{throw Error('Blocked');};const worker=s.workers[0];worker.onmessage({data:{id:worker.payload.id,result:{current:{t:11}}}});assert.equal((await pending).state,'error');assert.equal(s.ui.inspect(s.context('real',false).positions[0]).usable,false);});

test('temporary retention preserves the saved report and clears after a successful retry',async()=>{
 const s=setup(),position=s.context('real',false).positions[0],key='tt_holdings_isolation_v1:real|TEST_US_EQ';s.ui.setContext(s.context('real',false));
 const previous=JSON.stringify({symbol:'TEST',currency:'USD',kind:'market',asOf:'2026-10-02',sourceTime:10,timezone:'America/New_York',trainedAt:Date.now(),result:{current:{t:10},marker:'previous'}});s.writes.set(key,previous);const save=s.writes.set.bind(s.writes);s.writes.set=()=>{throw Error('Blocked');};
 const run=async marker=>{const pending=s.ui.run(position);s.resolve();await new Promise(r=>setImmediate(r));const w=s.workers.at(-1);w.onmessage({data:{id:w.payload.id,result:{current:{t:10},marker}}});return pending;};
 assert.equal((await run('temporary')).state,'ready');assert.equal(s.writes.get(key),previous);assert.equal(s.ui.inspect(position).record.result.marker,'temporary');
 s.writes.set=save;assert.equal((await run('retry')).state,'ready');const snapshot=s.ui.inspect(position);assert.equal(snapshot.record.result.marker,'retry');assert.equal(snapshot.persistence.state,'local');assert.equal(snapshot.persistence.message,null);assert.equal(JSON.parse(s.writes.get(key)).result.marker,'retry');
});
