import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const ctx={};vm.createContext(ctx);vm.runInContext(readFileSync('lib/holdings-neural.js','utf8'),ctx);const N=ctx.HoldingsNeural,now=Date.parse('2026-10-04T05:30:00Z');
const plain=x=>JSON.parse(JSON.stringify(x));
function xorRows(){const patterns=[[-1,-1,2],[1,1,2],[-1,1,0],[1,-1,0],[0,0,1]];return Array.from({length:900},(_,i)=>{const p=patterns[i%5];return {t:i*86400000,end:(i+5)*86400000,x:[p[0],p[1],0,0,0,0,0,50,2,1],y:p[2]};});}
let fitted;
test('feature engineering does not look into future OHLC bars',()=>{const bars=plain(N.demoBars(0,now)),a=N.dataset(bars,now),changed=bars.map((b,i)=>i<950?b:{...b,o:b.o*1.01,h:b.h*1.01,l:b.l*1.01,c:b.c*1.01,v:b.v*1.2}),b=N.dataset(changed,now);assert.deepEqual(plain(a.rows.find(r=>r.t===bars[940].t).x),plain(b.rows.find(r=>r.t===bars[940].t).x));assert.equal(a.rows.at(-1).end,bars.at(-1).t);assert.equal(a.rows.length,bars.length-199-5);});
test('labels use the future five-session move divided by current Wilder ATR percent',()=>{const bars=plain(N.demoBars(0,now)),data=N.dataset(bars,now),row=data.rows[70],i=bars.findIndex(b=>b.t===row.t),move=(bars[i+5].c/bars[i].c-1)*100/row.x[8];assert.equal(row.y,move<=-1?0:move>=1?2:1);});
test('chronological splitting purges overlapping target horizons at both boundaries',()=>{const p=N.split(xorRows());assert.ok(p.train.at(-1).end<p.validation[0].t);assert.ok(p.validation.at(-1).end<p.test[0].t);assert.ok(p.train.length<540);assert.ok(p.validation.length<180);assert.equal(p.test.length,180);});
test('feature normalisation is fitted on training only',()=>{const rows=xorRows(),p=N.split(rows),a=N.scaler(p.train);const changed=rows.map((r,i)=>i<540?r:{...r,x:r.x.map(v=>v+10000)}),b=N.scaler(N.split(changed).train);assert.deepEqual(plain(a),plain(b));});
test('invalid bars, missing volume, future timestamps, splits and insufficient classes are blocked',()=>{const bars=plain(N.demoBars(0,now));assert.throws(()=>N.dataset(bars.slice(-260),now),/510/);for(const patch of [{v:0},{c:-1},{t:now+1000}]){const b=bars.map(x=>({...x}));Object.assign(b[500],patch);assert.throws(()=>N.dataset(b,now));}const b=bars.map(x=>({...x}));for(const k of ['o','h','l','c'])b[500][k]*=2;assert.throws(()=>N.dataset(b,now),/25%/);assert.throws(()=>N.split(xorRows().map(r=>({...r,y:1}))),/clase/);assert.throws(()=>N.fit(xorRows(),[NaN]),/Indicatorii/);});
test('the hidden-layer network learns a nonlinear relationship beyond a linear baseline',()=>{const rows=xorRows();fitted=N.fit(rows,rows.at(-1).x,{epochs:240});assert.ok(N.valid(fitted));assert.ok(fitted.report.test.loss<fitted.report.linear.loss-.1);assert.ok(fitted.report.test.balanced>.9);assert.equal(fitted.advantage,true);assert.equal(fitted.reviewOnly,true);assert.equal(fitted.network.hidden,12);assert.equal(fitted.network.w1.length,10);assert.ok(Math.abs(fitted.support.reduce((a,b)=>a+b,0)-1)<1e-10);});
test('serialization preserves predictions and tampered network shapes are rejected',()=>{const copy=plain(fitted);assert.equal(N.valid(copy),true);assert.deepEqual(plain(N.forward(copy.network,N.normalize(copy.latest,copy.scale)).p),plain(copy.support));copy.network.w1[0].pop();assert.equal(N.valid(copy),false);});
test('model records cannot cross symbols, currency, demo, sessions or training expiry',()=>{const record={symbol:'TEST',currency:'USD',kind:'market',trainedAt:now,asOf:'2026-10-02',result:plain(fitted)},opts={symbol:'TEST',currency:'USD',demo:false,asOf:'2026-10-02',now};assert.equal(N.assess(record,opts).state,'fragile');for(const patch of [{symbol:'OTHER'},{currency:'EUR'},{demo:true}])assert.equal(N.assess(record,{...opts,...patch}).state,'invalid');assert.equal(N.assess(record,{...opts,asOf:'2026-10-01'}).state,'stale');assert.equal(N.assess(record,{...opts,now:now+31*60000}).state,'stale');});
test('no advantage and out-of-distribution inputs cannot produce an accepted model',()=>{const result=plain(fitted),record={symbol:'TEST',currency:'USD',kind:'market',trainedAt:now,asOf:'2026-10-02',result},opts={symbol:'TEST',currency:'USD',demo:false,asOf:'2026-10-02',now};result.advantage=false;result.report.linear=plain(result.report.test);assert.equal(N.assess(record,opts).state,'no-edge');result.latest[0]=result.scale.means[0]+7*result.scale.scales[0];result.maxZ=7;result.support=plain(N.forward(result.network,N.normalize(result.latest,result.scale)).p);result.classIndex=result.support.indexOf(Math.max(...result.support));assert.equal(N.assess(record,opts).state,'drift');});
test('demo training is deterministic and personal financial fields are not sent to the worker',()=>{assert.deepEqual(plain(N.demoBars(2,now)),plain(N.demoBars(2,now)));const ui=readFileSync('holdings/neural.js','utf8');assert.match(ui,/postMessage\(\{id:current.id,bars,now:Date.now\(\)\}\)/);assert.doesNotMatch(ui,/quantity|averagePrice|apiKey|authorization|Governor|Journal\.add/);assert.match(ui,/if\(current.demo\)memory.set/);});

test('a cached percentage or advantage cannot contradict the actual weights and test report',()=>{const r=plain(fitted);r.support=[.1,.8,.1];assert.equal(N.valid(r),false);const a=plain(fitted);a.advantage=!a.advantage;assert.equal(N.valid(a),false);const b=plain(fitted);b.report.test.balanced=.1;assert.equal(N.valid(b),false);});
