import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const core={};vm.createContext(core);vm.runInContext(readFileSync('lib/holdings-model-runner.js','utf8'),core);const defer=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};},tick=()=>new Promise(setImmediate);
test('one history load, sequential four workers, five results and duplicate-open deduplication',async()=>{const wait=defer(),calls=[];let loads=0,inflight=0,max=0;const steps=[['neural','boosting'],['hmm'],['isolation'],['quantile']].map(models=>({models,async run(){calls.push(models[0]);inflight++;max=Math.max(max,inflight);await tick();inflight--;return {state:'ready'};},cancel(){}}));const runner=core.HoldingsModelRunner.create({load:async()=>{loads++;await wait.promise;return {t:1};},steps,current:()=>true,reusable:()=>false,update(){}});const a=runner.start({key:'A'}),b=runner.start({key:'A'});wait.resolve();const [x,y]=await Promise.all([a,b]);assert.equal(loads,1);assert.equal(max,1);assert.deepEqual(calls,['neural','hmm','isolation','quantile']);assert.equal(Object.keys(x.statuses).length,5);assert.equal(x.state,y.state);assert.equal(runner.busy(),false);});
test('recent results are reused and force reanalysis executes every worker',async()=>{let count=0;const runner=core.HoldingsModelRunner.create({load:async()=>({}),steps:[{models:['neural','boosting'],run:async()=>{count++;return {state:'ready'};},cancel(){}}],current:()=>true,reusable:()=>true,update(){}});assert.equal((await runner.start({key:'A'})).statuses.neural.state,'cached');await runner.start({key:'A'},{force:true});assert.equal(count,1);});
test('one failure remains explicit and independent models still execute',async()=>{const runner=core.HoldingsModelRunner.create({load:async()=>({}),steps:[{models:['hmm'],run:async()=>{throw Error('failed');},cancel(){}},{models:['quantile'],run:async()=>({state:'ready'}),cancel(){}}],current:()=>true,reusable:()=>false,update(){}});const r=await runner.start({key:'A'});assert.equal(r.statuses.hmm.state,'error');assert.equal(r.statuses.quantile.state,'ready');});
test('cancelled history and instrument switches never start stale workers',async()=>{const wait=defer();let called=0;const runner=core.HoldingsModelRunner.create({load:async()=>wait.promise,steps:[{models:['hmm'],run:async()=>{called++;},cancel(){}}],current:()=>true,reusable:()=>false,update(){}});const pending=runner.start({key:'A'});runner.stop();wait.resolve({});assert.equal((await pending).state,'cancelled');assert.equal(called,0);assert.equal(runner.busy(),false);});
test('cancel settles current worker and prevents later steps or updates',async()=>{const wait=defer();let later=0,cancelled=0,updates=0;const runner=core.HoldingsModelRunner.create({load:async()=>({}),steps:[{models:['hmm'],run:()=>wait.promise,cancel(){cancelled++;wait.resolve({state:'cancelled'});}},{models:['quantile'],run:async()=>{later++;},cancel(){}}],current:()=>true,reusable:()=>false,update(){updates++;}});const pending=runner.start({key:'A'});await tick();runner.stop();const before=updates;assert.equal((await pending).state,'cancelled');assert.equal(cancelled,1);assert.equal(later,0);assert.equal(updates,before);});
test('changed source identity stops sequence and replacement ignores delayed completion',async()=>{const wait=defer();let identity='A',later=0;const runner=core.HoldingsModelRunner.create({load:async target=>({symbol:target.key}),steps:[{models:['hmm'],run:target=>target.key==='A'?wait.promise:Promise.resolve({state:'ready'}),cancel(){wait.resolve({state:'cancelled'});}},{models:['quantile'],run:async()=>{later++;return {state:'ready'};},cancel(){}}],current:target=>target.key===identity,reusable:()=>false,update(){}});const a=runner.start({key:'A'});await tick();identity='B';const b=runner.start({key:'B'});assert.equal((await a).state,'cancelled');assert.equal((await b).state,'done');assert.equal(later,1);});
test('history failure is explicit and starts no workers',async()=>{let count=0;const runner=core.HoldingsModelRunner.create({load:async()=>{throw Error('Wrong currency');},steps:[{models:['hmm'],run:()=>count++,cancel(){}}],current:()=>true,reusable:()=>false,update(){}});const r=await runner.start({key:'A'});assert.equal(r.state,'error');assert.match(r.error,/currency/);assert.equal(count,0);});

test('invalidated context during a worker releases the runner after completion',async()=>{const wait=defer();let valid=true;const runner=core.HoldingsModelRunner.create({load:async()=>({}),steps:[{models:['hmm'],run:()=>wait.promise,cancel(){}}],current:()=>valid,reusable:()=>false,update(){}});const pending=runner.start({key:'A'});await tick();valid=false;wait.resolve({state:'ready'});assert.equal((await pending).state,'cancelled');assert.equal(runner.busy(),false);});
