import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function setup(){const writes=new Map(),workers=[],button={dataset:{neuralTrain:'0'}},core={};vm.createContext(core);vm.runInContext(readFileSync('lib/holdings-neural.js','utf8'),core);let resolveFetch;
 const sandbox={HoldingsNeural:core.HoldingsNeural,document:{querySelectorAll:q=>q==='[data-neural-train]'?[button]:[],querySelector:()=>null,addEventListener(){}},location:{search:''},URLSearchParams,localStorage:{getItem:k=>writes.get(k)||null,setItem:(k,v)=>writes.set(k,v)},D:{fetchStock:()=>new Promise(resolve=>resolveFetch=resolve)},DailySeries:{read:()=>({bars:[],asOf:'2026-10-02',currency:'USD'})},setTimeout:()=>1,setInterval:()=>1,queueMicrotask,clearTimeout(){},Worker:class{constructor(){this.terminated=false;workers.push(this);}postMessage(payload){this.payload=payload;}terminate(){this.terminated=true;}}};vm.createContext(sandbox);vm.runInContext(readFileSync('holdings/neural.js','utf8'),sandbox);const context=(scope,demo=true)=>({scope,demo,positions:[{ticker:'TEST_US_EQ',quantity:99,averagePrice:25}],symbol:()=> 'TEST',model:()=>({currency:'USD',asOf:'2026-10-02'})});sandbox.HoldingsNeuralUI.setContext(context('account-a'));sandbox.HoldingsNeuralUI.bind();return {ui:sandbox.HoldingsNeuralUI,workers,writes,button,context,resolve:()=>resolveFetch([])};
}
test('worker gets only historical bars, time and a temporary job id',()=>{const s=setup();s.button.onclick();assert.equal(s.workers.length,1);assert.deepEqual(Object.keys(s.workers[0].payload).sort(),['bars','id','now']);assert.ok(s.workers[0].payload.bars.length>=510);});
test('changing account terminates the worker and ignores delayed results',()=>{const s=setup();s.button.onclick();const worker=s.workers[0];s.ui.setContext(s.context('account-b'));assert.equal(worker.terminated,true);worker.onmessage({data:{id:worker.payload.id,result:{invalid:true}}});assert.equal(s.writes.size,0);});
test('cancelled downloads cannot start training after the account changes',async()=>{const s=setup();s.ui.setContext(s.context('account-a',false));s.ui.bind();s.button.onclick();s.ui.setContext(s.context('account-b',false));s.resolve();await new Promise(resolve=>setImmediate(resolve));assert.equal(s.workers.length,0);assert.equal(s.writes.size,0);});
test('explicit cancellation frees the worker and does not write a model',()=>{const s=setup();s.button.onclick();s.ui.cancel();assert.equal(s.workers[0].terminated,true);assert.equal(s.writes.size,0);s.button.onclick();assert.equal(s.workers.length,2);});
test('changes to EOD, currency, symbol or the positions in the same account cancel Neural jobs',()=>{
 for(const change of ['eod','currency','symbol','removed']){const s=setup();s.button.onclick();const w=s.workers[0],c=s.context('account-a');if(change==='eod')c.model=()=>({currency:'USD',asOf:'2026-10-03'});if(change==='currency')c.model=()=>({currency:'EUR',asOf:'2026-10-02'});if(change==='symbol')c.symbol=()=> 'OTHER';if(change==='removed')c.positions=[];s.ui.setContext(c);assert.equal(w.terminated,true,change);assert.equal(s.ui.busy(),false);w.onmessage({data:{id:w.payload.id,result:{invalid:true}}});assert.equal(s.writes.size,0);}
});
test('a revised real EOD close cancels pending Neural training before a result is saved',async()=>{
 const s=setup(),c=s.context('account-a',false);c.model=()=>({currency:'USD',asOf:'2026-10-02',price:100});s.ui.setContext(c);s.button.onclick();s.resolve();await new Promise(setImmediate);assert.equal(s.workers.length,1);
 const next={...c,model:()=>({currency:'USD',asOf:'2026-10-02',price:101})};s.ui.setContext(next);assert.equal(s.workers[0].terminated,true);assert.equal(s.ui.busy(),false);assert.equal(s.writes.size,0);
});
