import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const now=Date.parse('2026-10-04T17:00:00Z'),t=Date.parse('2026-10-02T13:30:00Z'),plain=x=>JSON.parse(JSON.stringify(x));
function setup({demo=false,corrupt=false}={}){
 let clock=now;const writes=new Map(),buttons={},core={Date:class extends Date{static now(){return clock;}}};vm.createContext(core);for(const path of ['lib/daily-series.js','lib/holdings-neural.js','lib/holdings-forecast.js','lib/holdings-forecast-backup.js'])vm.runInContext(readFileSync(path,'utf8'),core);
 let exports=null,refreshes=0,fetches=0,resolveFetch,rejectFetch;
 const bar={t,o:100,h:102,l:99,c:100,v:10000},p={ticker:'TEST_US_EQ',instrumentCurrency:'USD',apiKey:'SECRET',quantity:999};
 const record={symbol:'TEST',currency:'USD',kind:demo?'synthetic':'market',asOf:'2026-10-02',sourceTime:t,sourceClose:100,timezone:'America/New_York',closeMinutes:960,trainedAt:now-1000};
 const neural={usable:true,assessment:{state:'no-edge'},comparison:{state:'no-edge'},record:{...record,result:{version:'holdings-mlp-v3',latest:[0,0,0,0,0,0,0,50,2,1],classIndex:2,report:{train:{confusion:[[2,3,5],[6,7,9],[1,2,4]]}},comparison:{boosting:{version:'holdings-gbt-v1',classIndex:0}}}}};
 const quantile={usable:true,assessment:{state:'no-edge'},record:{...record,result:{version:'holdings-quantile-v1',current:{t,close:100,atrPct:2,x:[],prices:[98,101,104]},baseline:{},baselineCalibration:{delta:0}}}};
 const hmm={usable:true,assessment:{state:'transition'},record:{...record,result:{version:'holdings-hmm-v1',current:{state:0},latest:[1,1,2],profiles:[{state:0,label:'Ascendent',means:[1,1,2]}]}}};
 const isolation={usable:true,assessment:{state:'ordinary'},record:{...record,result:{version:'holdings-isolation-v1',current:{score:.4,votes:0},threshold:.6}}};
 const sandbox={...core,Date:core.Date,HoldingsNeuralUI:{inspect:()=>neural,refresh:()=>refreshes++,exportReport:r=>exports=r},HoldingsQuantile:{predict:()=>[-2,0,2]},HoldingsQuantileUI:{inspect:()=>quantile},HoldingsHMMUI:{inspect:()=>hmm},HoldingsIsolationUI:{inspect:()=>isolation},DailySeries:{...core.DailySeries,read:()=>({bars:[bar],timezone:'America/New_York',closeMinutes:960,asOf:'2026-10-02',currency:'USD'})},localStorage:{getItem:k=>writes.get(k),setItem:(k,v)=>writes.set(k,v)},D:{fetchStock:(symbol,options)=>{fetches++;assert.equal(symbol,'TEST');assert.deepEqual(plain(options),{range:'5y',interval:'1d',ttl:0});return new Promise((resolve,reject)=>{resolveFetch=resolve;rejectFetch=reject;});}},document:{querySelectorAll:q=>buttons[q]||[]}};
 vm.createContext(sandbox);vm.runInContext(readFileSync('holdings/forecast.js','utf8'),sandbox);const ui=sandbox.HoldingsForecastUI,c={scope:'a',demo,positions:[p],symbol:()=> 'TEST',model:()=>({currency:'USD',asOf:'2026-10-02',price:100,atrPct:2,bars:[bar],closeMinutes:960})},e={scope:'a',ticker:p.ticker,symbol:'TEST',currency:'USD',kind:demo?'synthetic':'market'};ui.setContext(c);
 if(corrupt)writes.set(core.HoldingsForecast.key(e),'{broken');
 function button(attr){const b={dataset:{[attr.replace(/-([a-z])/g,(_,s)=>s.toUpperCase())]:'0'}};buttons['[data-'+attr+']']=[b];ui.bind();return b;}
 return {ui,c,p,e,writes,core,sandbox,neural,quantile,hmm,isolation,button,setNow:t=>clock=t,exports:()=>exports,refreshes:()=>refreshes,fetches:()=>fetches,resolve:()=>resolveFetch?.([]),reject:()=>rejectFetch?.(Error('offline'))};
}
test('successful model inspections produce five separate first forecasts without account fields',()=>{const s=setup();s.ui.capture(s.p);const d=s.core.HoldingsForecast.createStore({getItem:k=>s.writes.get(k)}).read(s.e);assert.equal(d.ok,true);assert.equal(d.entries.length,5);assert.ok(!/SECRET|apiKey|quantity/.test(JSON.stringify(d)));assert.equal(d.entries.find(r=>r.model==='neural').estimate.baselineClass,1);});
test('reanalyzing the same EOD cannot replace the original direction or interval',()=>{const s=setup();s.ui.capture(s.p);s.neural.record.result.classIndex=0;s.quantile.record.result.current.prices=[95,100,108];s.ui.capture(s.p);const d=JSON.parse(s.writes.get(s.core.HoldingsForecast.key(s.e)));assert.equal(d.entries.length,5);assert.equal(d.entries.find(r=>r.model==='neural').estimate.classIndex,2);assert.deepEqual(d.entries.find(r=>r.model==='quantile').estimate.prices,[98,101,104]);});
test('drifted forecasts remain absent from the performance registry',()=>{const s=setup();s.neural.assessment.state='drift';s.quantile.assessment.state='drift';s.ui.capture(s.p);const d=JSON.parse(s.writes.get(s.core.HoldingsForecast.key(s.e)));assert.deepEqual(d.entries.map(r=>r.model),['hmm','isolation']);});
test('legacy Neural results lacking verified close metadata are not backfilled',()=>{const s=setup();delete s.neural.record.sourceTime;s.ui.capture(s.p);const d=JSON.parse(s.writes.get(s.core.HoldingsForecast.key(s.e)));assert.ok(!d.entries.some(r=>r.model==='neural'||r.model==='boosting'));});
test('save controls rebuild the current account identity at click time',()=>{const s=setup(),b=s.button('forecast-save');s.ui.setContext({...s.c,scope:'b'});b.onclick();assert.equal(s.writes.has(s.core.HoldingsForecast.key(s.e)),false);assert.equal(s.writes.has(s.core.HoldingsForecast.key({...s.e,scope:'b'})),true);});
test('demo storage never writes to localStorage and synthetic examples are explicitly illustrative',()=>{const s=setup({demo:true});s.ui.capture(s.p);s.ui.simulation(s.p);assert.equal(s.writes.size,0);const html=s.ui.markup(s.p,0);assert.match(html,/estimările.*ilustrative/);assert.match(html,/24 orizonturi separate/);assert.match(html,/Regresie cu cuantile/);});
test('simulation does not duplicate observations when loaded again',()=>{const s=setup({demo:true});s.ui.simulation(s.p);const a=s.ui.markup(s.p,0);s.ui.simulation(s.p);const b=s.ui.markup(s.p,0);assert.match(a,/Registrul estimărilor · 192/);assert.match(b,/Registrul estimărilor · 192/);});
test('private account data and fitted weights never enter exported registry',()=>{const s=setup();s.ui.capture(s.p);s.button('forecast-export').onclick();const r=s.exports();assert.equal(r.result.version,'holdings-forecast-v1');assert.equal(r.result.entries.length,5);assert.ok(!/SECRET|apiKey|quantity|committee|w1/.test(JSON.stringify(r)));});
test('corrupt registry survives save and export actions without fabricated results',()=>{const s=setup({corrupt:true});s.ui.capture(s.p);s.button('forecast-export').onclick();assert.equal(s.exports(),null);assert.equal(s.writes.get(s.core.HoldingsForecast.key(s.e)),'{broken');assert.match(s.ui.markup(s.p,0),/Registru ilizibil/);});
test('selected model filter changes the ledger rows through actual control handlers',()=>{const s=setup({demo:true});s.ui.simulation(s.p);const b=s.button('forecast-model');b.value='hmm';b.onchange();const html=s.ui.markup(s.p,0);assert.match(html,/value="hmm" selected/);assert.match(html,/observație de preț/);});
test('an account change during public fetch cannot write the prior or next account',async()=>{const s=setup();s.ui.capture(s.p);const before=s.writes.get(s.core.HoldingsForecast.key(s.e)),pending=s.ui.check(s.p,true);s.ui.setContext({...s.c,scope:'b'});s.resolve();await pending;assert.equal(s.writes.get(s.core.HoldingsForecast.key(s.e)),before);assert.equal(s.writes.has(s.core.HoldingsForecast.key({...s.e,scope:'b'})),false);});
test('one automatic attempt per expected EOD works even with a stale analysis; manual retry remains possible',async()=>{const s=setup();s.ui.capture(s.p);s.setNow(Date.parse('2026-10-05T21:00:00Z'));let pending=s.ui.check(s.p);assert.equal(s.fetches(),1);s.resolve();await pending;await s.ui.check(s.p);assert.equal(s.fetches(),1);pending=s.ui.check(s.p,true);assert.equal(s.fetches(),2);s.resolve();await pending;s.setNow(Date.parse('2026-10-06T21:00:00Z'));pending=s.ui.check(s.p);assert.equal(s.fetches(),3);s.resolve();await pending;});
test('model completion hooks record snapshots and the module loads before Neural UI',()=>{for(const file of ['neural','hmm','isolation','quantile','garch'])assert.match(readFileSync('holdings/'+file+'.js','utf8'),/HoldingsForecastUI\?\.capture/);const html=readFileSync('holdings/index.html','utf8');assert.ok(html.indexOf('src="forecast.js')<html.indexOf('src="neural.js'));});

test('listing currency never falls back to the account wallet currency',()=>{const s=setup();s.c.model=()=>null;delete s.p.instrumentCurrency;s.p.currency='EUR';const snapshot=s.ui.snapshot(s.p);assert.equal(snapshot.identity.currency,undefined);assert.equal(snapshot.ledger.ok,false);assert.equal(s.writes.size,0);});
test('portfolio snapshot reports an unsuccessful verification without deleting saved forecasts',async()=>{const s=setup();s.ui.capture(s.p);const before=s.ui.snapshot(s.p).ledger.entries.length,pending=s.ui.check(s.p,true);assert.equal(s.ui.snapshot(s.p).check.state,'checking');s.reject();const result=await pending;assert.equal(result.state,'error');const snapshot=s.ui.snapshot(s.p);assert.equal(snapshot.ledger.entries.length,before);assert.ok(snapshot.ledger.entries.every(r=>r.verification.state==='pending'));assert.equal(snapshot.check.state,'error');});
test('automatic checks can update saved forecasts without a current model analysis',async()=>{const s=setup();s.ui.capture(s.p);s.c.model=()=>null;s.setNow(Date.parse('2026-10-05T21:00:00Z'));const pending=s.ui.check(s.p);assert.equal(s.fetches(),1);s.resolve();await pending;assert.equal(s.ui.snapshot(s.p).ledger.entries.length,5);});
test('an unfinished session and a current saved EOD do not trigger needless automatic requests',async()=>{const s=setup();s.ui.capture(s.p);await s.ui.check(s.p);s.setNow(Date.parse('2026-10-05T20:14:00Z'));await s.ui.check(s.p);assert.equal(s.fetches(),0);});

test('GARCH captures both horizons and preserves frozen benchmarks after reanalysis',()=>{
 const s=setup(),garch={usable:true,assessment:{state:'limited'},record:{...s.isolation.record,result:{version:'holdings-garch-v1',folds:[{model:{mu:.05,apiKey:'SECRET'}}],current:{horizons:[{horizon:5,cumulativePct:2,constantPct:3,ewmaPct:4},{horizon:20,cumulativePct:4,constantPct:6,ewmaPct:8}]}}}};s.sandbox.HoldingsGarchUI={inspect:()=>garch};s.ui.capture(s.p);let rows=s.ui.snapshot(s.p).ledger.entries.filter(r=>r.model==='garch');assert.equal(rows.length,2);assert.deepEqual(plain(rows.map(r=>r.horizon)),[5,20]);assert.equal(rows[0].estimate.predictedVariance,4);assert.equal(rows[1].estimate.constantVariance,36);assert.ok(!/SECRET|apiKey|folds/.test(JSON.stringify(rows)));garch.record.result.current.horizons[0].cumulativePct=99;s.ui.capture(s.p);rows=s.ui.snapshot(s.p).ledger.entries.filter(r=>r.model==='garch');assert.equal(rows[0].estimate.predictedVariance,4);garch.assessment.state='drift';s.ui.setContext({...s.c,scope:'b'});s.ui.capture(s.p);assert.ok(!s.ui.snapshot(s.p).ledger.entries.some(r=>r.model==='garch'));
});
function completeVerdict(s){const shared={symbol:'TEST',currency:'USD',kind:s.e.kind,asOf:'2026-10-02',t,close:100,timezone:'America/New_York',closeMinutes:960,fingerprint:'ohlcv-v1:test'},report={version:'holdings-verdict-v2',symbol:'TEST',currency:'USD',kind:s.e.kind,asOf:shared.asOf,available:6,total:6,generatedAt:now,state:'weak',title:'Dovezi insuficiente',direction:null,reasons:['Explicație păstrată.'],cards:['neural','boosting','hmm','isolation','quantile','garch'].map(id=>({id,version:s.core.HoldingsForecast.VERSIONS[id],state:'limited',value:'Neconcludent',available:true,quantity:999}))};return {shared,report};}
test('the first complete verdict is saved with its reasons and six summaries without portfolio fields',()=>{const s=setup(),v=completeVerdict(s),out=s.ui.captureVerdict(s.p,v.report,v.shared);assert.equal(out.saved,true);v.report.title='Reanalizat';v.report.reasons=['Alt motiv'];assert.equal(s.ui.captureVerdict(s.p,v.report,v.shared).duplicate,true);const rows=s.ui.snapshot(s.p).ledger.entries;assert.equal(rows.length,1);assert.equal(rows[0].estimate.title,'Dovezi insuficiente');assert.equal(rows[0].estimate.cards.length,6);assert.ok(!/quantity|SECRET|apiKey/.test(JSON.stringify(rows)));const b=s.button('forecast-model');b.value='verdict';b.onchange();assert.match(s.ui.markup(s.p,0),/Verdict și motive păstrate/);assert.match(s.ui.markup(s.p,0),/Explicație păstrată/);});
test('incomplete, stale, mismatched and unavailable-card verdicts never enter the registry',()=>{for(const change of [v=>v.report.available=5,v=>v.report.cards[0].available=false,v=>v.shared.close=101,v=>v.shared.symbol='OTHER',v=>v.report.kind='synthetic',v=>v.report.generatedAt=now-1800001]){const s=setup(),v=completeVerdict(s);change(v);assert.equal(s.ui.captureVerdict(s.p,v.report,v.shared).ok,false);assert.equal(s.writes.size,0);}});
test('simulation covers both volatility horizons and abstentions with usable model filters',()=>{const s=setup({demo:true});s.ui.simulation(s.p);const rows=s.ui.snapshot(s.p).ledger.entries;assert.equal(rows.filter(r=>r.model==='garch'&&r.horizon===20).length,24);assert.equal(rows.filter(r=>r.model==='verdict').length,24);assert.ok(rows.every(r=>s.core.HoldingsForecast.validEntry(r,s.e,now)));const b=s.button('forecast-model');b.value='garch';b.onchange();let html=s.ui.markup(s.p,0);assert.match(html,/QLIKE/);assert.match(html,/20 sesiuni/);assert.doesNotMatch(html,/undefined|NaN/);b.value='verdict';b.onchange();html=s.ui.markup(s.p,0);assert.match(html,/18 verdicturi direcționale · 6 abțineri/);assert.match(html,/exemplu fictiv/);assert.equal(s.writes.size,0);});
test('a registry write failure cannot fabricate a saved combined verdict',()=>{const s=setup(),v=completeVerdict(s);s.sandbox.localStorage.setItem=()=>{throw Error('Quota full');};assert.equal(s.ui.captureVerdict(s.p,v.report,v.shared).ok,false);assert.equal(s.ui.snapshot(s.p).ledger.entries.length,0);});
