import test from 'node:test';import assert from 'node:assert/strict';
import {core,e,fixture,plain} from './holdings-learning-fixtures.mjs';
const c=core(['lib/holdings-forecast-storage.js']),S=c.HoldingsForecastStorage,F=c.HoldingsForecast,k=F.key(e),serialize=entries=>JSON.stringify({version:F.VERSION,entries}),tick=()=>new Promise(r=>setImmediate(r));
function setup(local=new Map(),saved=new Map()){const durable={get:async k=>saved.get(k)??null,write:async changes=>{const staged=new Map();for(const a of changes){const before=saved.get(a.key)??null;if(before!==a.before&&!a.merge)throw Error('Conflict');staged.set(a.key,before!==a.before?S.merge(before,a.value,a.key):a.value);}for(const [k,v]of staged)saved.set(k,v);return staged;}};const storage={getItem:k=>local.get(k)??null,setItem:(k,v)=>local.set(k,v)},adapter=S.create(storage,{durable});return {adapter,storage,durable,local,saved};}
test('migration retains every legacy forecast and leaves its old copy byte-for-byte intact',async()=>{const raw=serialize(fixture(c).ledger.entries),s=setup(new Map([[k,raw]]));assert.throws(()=>s.adapter.getItem(k),/încarcă/);await s.adapter.load(k);await s.adapter.settled();assert.equal(s.local.get(k),raw);assert.equal(s.saved.get(k),raw);assert.equal(s.adapter.getItem(k),raw);assert.equal(s.adapter.status(k).state,'indexeddb');});
test('full localStorage does not prevent durable writes or recovery in a new page',async()=>{const s=setup();s.storage.setItem=()=>{throw Error('Quota exceeded');};await s.adapter.load(k);const raw=serialize(fixture(c,1).ledger.entries);s.adapter.setItem(k,raw);assert.equal(s.adapter.status(k).state,'pending');await s.adapter.settled();const reloaded=S.create(s.storage,{durable:s.durable});await reloaded.load(k);assert.equal(reloaded.getItem(k),raw);assert.equal(reloaded.status(k).state,'indexeddb');});
test('union migration preserves the permanent first estimate and admits other dates',async()=>{const rows=fixture(c,2).ledger.entries,old=serialize(rows.slice(0,2)),changed=plain(rows);changed[0].estimate.probabilities=[.01,.98,.01];changed[0].estimate.classIndex=1;const s=setup(new Map([[k,serialize(changed)]]),new Map([[k,old]]));await s.adapter.load(k);await s.adapter.settled();const result=JSON.parse(s.saved.get(k)).entries;assert.equal(result.length,4);assert.deepEqual(result[0],plain(rows[1]));assert.deepEqual(result.find(r=>r.id===rows[0].id).estimate,plain(rows[0].estimate));});
test('two delayed pages merge independent origins instead of erasing an earlier write',async()=>{const rows=fixture(c,2).ledger.entries,s=setup(),b=S.create(s.storage,{durable:s.durable});await Promise.all([s.adapter.load(k),b.load(k)]);s.adapter.setItem(k,serialize(rows.slice(0,2)));await s.adapter.settled();b.setItem(k,serialize(rows.slice(2)));await b.settled();assert.equal(JSON.parse(s.saved.get(k)).entries.length,4);assert.equal(JSON.parse(b.getItem(k)).entries.length,4);});
test('a failed durable write remains available for export but is clearly marked as session-only',async()=>{const s=setup();await s.adapter.load(k);s.durable.write=async()=>{throw Error('Aborted');};const raw=serialize(fixture(c,1).ledger.entries);s.adapter.setItem(k,raw);await s.adapter.settled();assert.equal(s.saved.has(k),false);assert.equal(s.adapter.getItem(k),raw);assert.equal(s.adapter.status(k).state,'session');assert.match(s.adapter.status(k).message,/Exportă/);});
test('invalid saved copies are not overwritten by migration',async()=>{const raw=serialize(fixture(c,1).ledger.entries),s=setup(new Map([[k,raw]]),new Map([[k,'{broken']]));await s.adapter.load(k);await s.adapter.settled();assert.equal(s.saved.get(k),'{broken');assert.equal(s.local.get(k),raw);assert.equal(s.adapter.status(k).state,'session');});
test('atomic backup and ledger writes detect concurrent changes before either mutation',async()=>{const s=setup(),archive='archive-key';await Promise.all([s.adapter.load(k),s.adapter.load(archive)]);s.saved.set(archive,'concurrent');s.adapter.commit([{key:archive,value:'new archive',before:null},{key:k,value:serialize(fixture(c,1).ledger.entries),before:null}]);await s.adapter.settled();assert.equal(s.saved.get(archive),'concurrent');assert.equal(s.saved.has(k),false);assert.equal(s.adapter.status(k).state,'session');});
test('the expanded protocol can preserve more than five hundred observations',()=>{const item=fixture(c,260,{step:1}),raw=serialize(item.ledger.entries),result=S.merge(null,raw,k);assert.equal(JSON.parse(result).entries.length,520);assert.equal(F.MAX,20000);assert.ok(F.MAX_BYTES>raw.length);});
function browser(){const records=new Map(),transactions=[];const db={objectStoreNames:{contains:()=>true},close(){},transaction(name,mode){assert.equal(name,'history');const tx={reads:[],staged:[],objectStore(){return {get(key){const r={result:records.get(key)};tx.reads.push(r);return r;},put(value,key){tx.staged.push([key,value]);}};},abort(){tx.onabort?.();},requests(){for(const r of tx.reads)r.onsuccess();},commit(){for(const [k,v]of tx.staged)records.set(k,v);tx.oncomplete();}};transactions.push(tx);return tx;}};return {records,transactions,factory:{open(){const r={result:db};queueMicrotask(()=>r.onsuccess());return r;}}};}
test('request success is never mistaken for committed history, and abort keeps both previous values',async()=>{const b=browser(),db=S.indexedStore(b.factory);b.records.set('a','old');const pending=db.write([{key:'a',value:'new',before:'old'},{key:'b',value:'new',before:null}]);let done=false;pending.then(()=>done=true,()=>done=true);await tick();const tx=b.transactions[0];tx.requests();await tick();assert.equal(done,false);assert.equal(b.records.get('a'),'old');assert.equal(b.records.has('b'),false);tx.abort();await assert.rejects(pending,/anulată/);assert.equal(b.records.get('a'),'old');assert.equal(b.records.has('b'),false);});
test('an atomic transaction confirms all values only after completion',async()=>{const b=browser(),db=S.indexedStore(b.factory),p=db.write([{key:'a',value:'one',before:null},{key:'b',value:'two',before:null}]);await tick();const tx=b.transactions[0];tx.requests();tx.commit();const result=await p;assert.equal(result.get('a'),'one');assert.equal(b.records.get('b'),'two');});
