import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const tick=()=>new Promise(r=>setImmediate(r));const c={};vm.createContext(c);vm.runInContext(readFileSync('lib/holdings-auto-learning.js','utf8'),c);const A=c.HoldingsAutoLearning;
function setup(){let clock=10000000,state=null,valid=true,loads=0,trained=0,completed=0,release;const source={asOf:'2026-10-05',fingerprint:'same'},target={asOf:source.asOf,key:'instrument'},updates=[];const s={restore:async()=>{},read:()=>state,write:(_,x)=>state=x,current:()=>valid,load:async()=>{loads++;return source;},steps:[{models:['neural','boosting'],run:async()=>{trained++;return {state:'ready'};},cancel(){}}],complete:async()=>{completed++;return 'report';},update:r=>updates.push(r.phase),now:()=>clock};return {coordinator:A.create(s),s,target,source,updates,get state(){return state;},set state(x){state=x;},loads:()=>loads,trained:()=>trained,completed:()=>completed,setClock:x=>clock=x,invalidate:()=>valid=false};}
test('new EOD runs existing models and records one completed training session',async()=>{const s=setup(),out=await s.coordinator.start(s.target);assert.equal(out.state,'done');assert.equal(s.trained(),1);assert.equal(s.completed(),1);assert.equal(s.state.asOf,'2026-10-05');assert.equal(s.state.phase,'done');assert.equal(s.state.version,A.VERSION);});
test('a completed EOD is reused without repeating training or source fetch',async()=>{const s=setup();await s.coordinator.start(s.target);assert.equal((await s.coordinator.start(s.target)).state,'cached');assert.equal(s.loads(),1);assert.equal(s.trained(),1);});
test('a new EOD starts a new run and a manual request can repeat the same EOD',async()=>{const s=setup();await s.coordinator.start(s.target);s.source.asOf='2026-10-06';s.target.asOf=s.source.asOf;await s.coordinator.start(s.target);assert.equal(s.trained(),2);await s.coordinator.start(s.target,{force:true});assert.equal(s.trained(),3);});
test('disabled automatic training makes no request but manual training keeps it disabled',async()=>{const s=setup();s.state={version:A.VERSION,enabled:false};assert.equal((await s.coordinator.start(s.target)).state,'disabled');assert.equal(s.loads(),0);await s.coordinator.start(s.target,{force:true});assert.equal(s.trained(),1);assert.equal(s.state.enabled,false);});
test('context change during history loading cancels before any training or write',async()=>{const s=setup();let release;s.s.load=()=>new Promise(r=>release=r);s.coordinator=A.create(s.s);const p=s.coordinator.start(s.target);await tick();s.invalidate();release(s.source);assert.equal((await p).state,'cancelled');assert.equal(s.trained(),0);assert.equal(s.state,null);});
test('cancellation terminates the active step and never saves a completed session',async()=>{const s=setup();let release,cancelled=0;s.s.steps[0].run=()=>new Promise(r=>release=r);s.s.steps[0].cancel=()=>{cancelled++;release({state:'cancelled'});};const p=s.coordinator.start(s.target);await tick();s.coordinator.stop();assert.equal((await p).state,'cancelled');assert.equal(cancelled,1);assert.equal(s.completed(),0);assert.equal(s.state.phase,'running');});
test('an unavailable worker leaves a failed session and an automatic retry is throttled',async()=>{const s=setup();s.s.steps[0].run=async()=>({state:'error',error:'worker unavailable'});assert.equal((await s.coordinator.start(s.target)).state,'error');assert.equal(s.state.phase,'error');assert.equal((await s.coordinator.start(s.target)).state,'cached');s.setClock(10000000+15*60000);assert.equal((await s.coordinator.start(s.target)).state,'error');});
test('a second start cannot overlap an active history fetch',async()=>{const s=setup();let release;s.s.load=()=>new Promise(r=>release=r);s.coordinator=A.create(s.s);const pending=s.coordinator.start(s.target);await tick();assert.equal((await s.coordinator.start(s.target)).state,'busy');release(s.source);await pending;assert.equal(s.trained(),1);});
