import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const core={};vm.createContext(core);for(const path of ['lib/daily-series.js','lib/holdings-forecast.js'])vm.runInContext(readFileSync(path,'utf8'),core);const F=core.HoldingsForecast,plain=x=>JSON.parse(JSON.stringify(x));
const captured=Date.parse('2026-09-25T21:00:00Z'),now=Date.parse('2026-10-04T17:00:00Z'),e={scope:'a',ticker:'TEST_US_EQ',symbol:'TEST',currency:'USD',kind:'market'};
const dates=['2026-09-25','2026-09-28','2026-09-29','2026-09-30','2026-10-01','2026-10-02'];
function bars(){return dates.map((d,i)=>({t:Date.parse(d+'T13:30:00Z'),o:100+i,h:102+i,l:99+i,c:100+i,v:10000}));}
function input(model='neural'){return {model,modelVersion:F.VERSIONS[model],trainedAt:captured-60000,state:'no-edge',source:{t:bars()[0].t,asOf:dates[0],timezone:'America/New_York',closeMinutes:960,close:100,atrPct:2},estimate:model==='quantile'?{prices:[98,102,106],baselinePrices:[96,100,104]}:model==='hmm'?{state:0,label:'Ascendent',means:[1,1,2]}:model==='isolation'?{label:'anomaly',score:.7,threshold:.6,votes:3}:{classIndex:2,baselineClass:1}};}
function forecast(model='neural'){return F.project(input(model),e,captured);}
function source(xs=bars()){return {symbol:'TEST',currency:'USD',timezone:'America/New_York',closeMinutes:960,asOf:dates.at(-1),retrievedAt:now,bars:xs};}
function setup(){const writes=new Map(),storage={getItem:k=>writes.get(k)||null,setItem:(k,v)=>writes.set(k,v)};return {writes,store:F.createStore(storage)};}
test('snapshots contain only the immutable forecast protocol, source and simple estimates',()=>{const i=input();i.apiKey='SECRET';i.quantity=99;i.estimate.apiKey='SECRET';const r=forecast();assert.ok(F.validEntry(r,e,now));const saved=F.project(i,e,captured);assert.ok(!/SECRET|quantity|apiKey|scope/.test(JSON.stringify(saved)));});
test('new class forecasts freeze probability vectors while legacy estimates remain valid and unchanged',()=>{
 const old=forecast(),before=JSON.stringify(old),i=input();i.estimate.probabilities=[.1,.2,.7];const r=F.project(i,e,captured);assert.deepEqual(plain(r.estimate.probabilities),[.1,.2,.7]);assert.ok(F.validEntry(r,e,now));i.estimate.probabilities[2]=.1;assert.equal(r.estimate.probabilities[2],.7);assert.ok(F.validEntry(old,e,now));assert.equal(Object.hasOwn(old.estimate,'probabilities'),false);assert.equal(JSON.stringify(old),before);
});
test('invalid, missing-mass and class-inconsistent probability vectors fail closed',()=>{
 for(const probabilities of [[.1,.2,.6],[.1,.2,NaN],[-.1,.3,.8],[.8,.1,.1],[.1,.2,.7,0],null]){const i=input();i.estimate.probabilities=probabilities;assert.equal(F.project(i,e,captured),null);const r=forecast();r.estimate.probabilities=probabilities;assert.equal(F.validEntry(r,e,now),false);}
});
test('later probabilities never overwrite the first class-only forecast of the same session',()=>{
 const {store,writes}=setup();store.save(input(),e,captured);const before=writes.get(F.key(e)),i=input();i.estimate.probabilities=[.1,.2,.7];assert.equal(store.save(i,e,captured+1000).duplicate,true);assert.equal(writes.get(F.key(e)),before);assert.equal(store.read(e).entries[0].estimate.probabilities,undefined);
});
test('forecasts recorded after the next local weekday begins are refused',()=>{assert.equal(F.project(input(),e,Date.parse('2026-09-28T04:01:00Z')),null);assert.equal(F.timely(input().source,Date.parse('2026-09-27T17:00:00Z')),true);});
test('unfinished market session cannot be captured even if its date matches',()=>{const i=input();i.trainedAt=Date.parse('2026-09-25T14:00:00Z');assert.equal(F.project(i,e,i.trainedAt),null);});
test('old training, future training and a mismatched model version fail closed',()=>{for(const change of [i=>i.trainedAt=captured-1800001,i=>i.trainedAt=captured+1,i=>i.modelVersion='other',i=>i.source.asOf='2026-09-24',i=>i.estimate.classIndex=9]){const i=input();change(i);assert.equal(F.project(i,e,captured),null);}});
test('first forecast survives repeated training and the original captured timestamp stays fixed',()=>{const {store}=setup();store.save(input(),e,captured);const i=input();i.estimate.classIndex=0;i.trainedAt+=1000;const out=store.save(i,e,captured+1000);assert.equal(out.duplicate,true);assert.equal(out.entries.length,1);assert.equal(out.entries[0].estimate.classIndex,2);assert.equal(out.entries[0].capturedAt,captured);});
test('each model has its own forecast on the same EOD',()=>{const {store}=setup();for(const m of ['neural','boosting','quantile','hmm','isolation'])assert.equal(store.save(input(m),e,captured).saved,true);assert.equal(store.read(e).entries.length,5);});
test('account, ticker, listing, currency and simulation have separate stores',()=>{const {store}=setup();store.save(input(),e,captured);for(const [k,v] of Object.entries({scope:'b',ticker:'ALT_US_EQ',symbol:'ALT',currency:'EUR',kind:'synthetic'}))assert.equal(store.read({...e,[k]:v}).entries.length,0);});
test('five actual sessions resolve Friday through next Friday without counting a weekend',()=>{const r=F.verify(forecast(),source(),now);assert.equal(r.verification.state,'resolved');assert.equal(r.outcome.asOf,'2026-10-02');assert.equal(r.outcome.close,105);assert.equal(r.outcome.path.length,5);assert.equal(F.metric(r).actualClass,2);assert.equal(F.metric(r).correct,true);});
test('fewer sessions remain pending and are never counted as misses',()=>{const r=F.verify({...forecast(),kind:'synthetic'},source(bars().slice(0,5)),now);assert.equal(r.verification.state,'pending');assert.equal(r.verification.sessions,4);assert.equal(F.metric(r),null);assert.equal(F.report([r])[0].n,0);});
test('a later query resolves at the fifth session, not the most recent close',()=>{const xs=bars();xs.push({...xs.at(-1),t:Date.parse('2026-10-05T13:30:00Z'),c:109,h:110});const later=Date.parse('2026-10-05T21:00:00Z');const r=F.verify(forecast(),{...source(xs),asOf:'2026-10-05',retrievedAt:later},later);assert.equal(r.outcome.close,105);assert.equal(r.outcome.asOf,'2026-10-02');});
test('currency, symbol and timezone mismatches cannot produce scored outcomes',()=>{for(const [key,value] of Object.entries({currency:'EUR',symbol:'ALT',timezone:'Europe/London'})){const r=F.verify(forecast(),{...source(),[key]:value},now);assert.equal(r.verification.state,'unverifiable');assert.equal(r.outcome,null);}});
test('stale retrieval and stale EOD cannot produce scored outcomes',()=>{for(const s of [{...source(),retrievedAt:now-300001},{...source(),asOf:'2026-10-01'},{...source(),closeMinutes:1020}])assert.equal(F.verify(forecast(),s,now).verification.state,'unverifiable');});
test('a revised origin price is excluded without rewriting the saved forecast',()=>{const xs=bars();xs[0].c=100.1;const original=forecast(),r=F.verify(original,source(xs),now);assert.equal(r.verification.state,'unverifiable');assert.equal(r.source.close,100);assert.deepEqual(plain(original),plain(forecast()));});
test('corporate action sized jump and large missing-series gap block evaluation',()=>{for(const mutate of [xs=>{xs[3].c=150;xs[3].h=151;},xs=>{xs.splice(1,1);xs.at(-1).t+=14*86400000;}]){const xs=bars();mutate(xs);assert.equal(F.verify(forecast(),source(xs),now).verification.state,'unverifiable');}});
test('duplicate session, future bar, absent origin and nonfinite OHLC are blocked',()=>{for(const mutate of [xs=>xs.splice(2,0,xs[1]),xs=>xs[2].c=NaN,xs=>xs.shift(),xs=>xs.at(-1).t=now+1]){const xs=bars();mutate(xs);assert.equal(F.verify(forecast(),source(xs),now).verification.state,'unverifiable');}});
test('resolved close stays immutable and source revisions exclude it from later reports',()=>{const first=F.verify(forecast(),source(),now),xs=bars();xs.at(-1).c=105.1;const second=F.verify(first,source(xs),now+1000);assert.equal(second.outcome.close,105);assert.equal(second.verification.state,'unverifiable');assert.equal(F.aggregate([second],'neural').n,0);assert.deepEqual(plain(first.estimate),plain(second.estimate));});
test('a transient missing source leaves the original completed result recoverable',()=>{const first=F.verify(forecast(),source(),now),bad=F.verify(first,{...source(),bars:[]},now+1000),again=F.verify(bad,source(),now+2000);assert.equal(bad.outcome.close,105);assert.equal(again.verification.state,'resolved');assert.equal(again.outcome.checkedAt,now);});
test('quantile outcomes use inclusive frozen bounds and median error in initial ATR',()=>{const r=F.verify(forecast('quantile'),source(),now),m=F.metric(r);assert.equal(m.covered,true);assert.ok(Math.abs(m.mae-1.5)<1e-8);assert.equal(m.baseline.covered,false);assert.ok(Math.abs(m.score-4)<1e-8);assert.ok(Math.abs(m.baseline.score-9)<1e-8);});
test('direction thresholds classify exactly minus/plus one ATR in the same protocol',()=>{for(const [close,expected] of [[98,0],[100,1],[102,2]]){const r=plain(F.verify(forecast(),source(),now));r.outcome.close=close;r.outcome.path.at(-1).c=close;assert.equal(F.metric(r).actualClass,expected);}});
test('descriptive HMM and Isolation never acquire fake accuracy fields',()=>{for(const model of ['hmm','isolation']){const r=F.verify(forecast(model),source(),now),a=F.aggregate([r],model);assert.equal(a.descriptive,true);assert.equal(F.metric(r).descriptive,true);assert.equal(a.accuracy,undefined);assert.equal(a.coverage,undefined);}});
test('touching and overlapping horizons cannot inflate the primary sample count',()=>{const a=F.verify(forecast(),source(),now),b=plain(a);b.source.t=a.outcome.t;const c=plain(a);c.source.t=a.outcome.t+86400000;c.outcome.t+=7*86400000;assert.equal(F.separate([a,b,c]).length,2);assert.equal(F.aggregate([a,b,c],'neural').n,2);assert.equal(F.aggregate([a,b,c],'neural').all,3);});
test('balanced accuracy is absent when an actual class has no observations',()=>{const r=F.verify(forecast(),source(),now),m=F.aggregate([r],'neural');assert.equal(m.accuracy,1);assert.equal(m.baselineAccuracy,0);assert.equal(m.balanced,null);});
test('malformed and future ledger entries preserve original local data and block writes',()=>{for(const raw of ['{broken',JSON.stringify({version:F.VERSION,entries:[{bad:true}]})]){const {store,writes}=setup();writes.set(F.key(e),raw);assert.equal(store.save(input(),e,captured).ok,false);assert.equal(writes.get(F.key(e)),raw);}const r=plain(forecast());r.capturedAt=now+1;assert.equal(F.validEntry(r,e,now),false);});
test('unknown private fields in persisted records are rejected, not included in exports',()=>{const r=plain(forecast());r.apiKey='SECRET';assert.equal(F.validEntry(r,e,now),false);delete r.apiKey;r.estimate.quantity=99;assert.equal(F.validEntry(r,e,now),false);});
test('outcome and verification tampering cannot turn unverified data into valid completion',()=>{const r=plain(forecast());r.verification.state='resolved';assert.equal(F.validEntry(r,e,now),false);const resolved=plain(F.verify(forecast(),source(),now));resolved.outcome.path.pop();assert.equal(F.validEntry(resolved,e,now),false);});
test('storage failures return a usable error instead of claiming a save',()=>{const store=F.createStore({getItem:()=>null,setItem(){throw Error('quota');}});const out=store.save(input(),e,captured);assert.equal(out.ok,false);assert.match(out.error,/refuzat salvarea registrului/);assert.equal(out.saved,undefined);});
test('completed outcomes persist across store instances and retain the exact forecast',()=>{const {store,writes}=setup();store.save(input('quantile'),e,captured);const out=store.check(e,source(),now);assert.equal(out.ok,true);const reloaded=F.createStore({getItem:k=>writes.get(k)}).read(e);assert.equal(reloaded.ok,true);assert.equal(reloaded.entries[0].outcome.close,105);assert.deepEqual(plain(reloaded.entries[0].estimate),plain(input('quantile').estimate));});
test('small samples are explicitly insufficient and pending/excluded denominators are separate',()=>{const good=F.verify(forecast(),source(),now),pending=forecast(),bad=F.verify(forecast(),{},now);const report=F.report([good,pending,bad])[0];assert.equal(report.n,1);assert.equal(report.pending,1);assert.equal(report.unverifiable,1);assert.match(report.warning,/Mai puțin de 20/);});
test('coverage degradation flags are descriptive and based on separated completed forecasts',()=>{const r=F.verify(forecast('quantile'),source(),now),rows=Array.from({length:20},(_,i)=>{const x=plain(r);x.source.t=i*10*86400000;x.outcome.t=x.source.t+5*86400000;x.estimate.prices=[90,91,92];return x;});const report=F.report(rows).find(x=>x.model==='quantile');assert.equal(report.n,20);assert.equal(report.coverage,0);assert.match(report.warning,/sub 70%/);});

test('quota and access errors preserve the ledger and do not expose account storage keys',()=>{
 for(const error of [Object.assign(new Error('PRIVATE account key'),{name:'QuotaExceededError'}),new Error('PRIVATE access error')]){
  const {writes,store}=setup();store.save(input(),e,captured);const old=writes.get(F.key(e)),blocked=F.createStore({getItem:k=>writes.get(k)||null,setItem(){throw error;}});
  const out=blocked.save(input('hmm'),e,captured);assert.equal(out.ok,false);assert.equal(writes.get(F.key(e)),old);assert.match(out.error,/existente sunt păstrate/);assert.doesNotMatch(out.error,/PRIVATE/);
 }
});
