import test from 'node:test';import assert from 'node:assert/strict';
import {core,e,dates,fixture,plain} from './holdings-learning-fixtures.mjs';
const c=core(),L=c.HoldingsLearning,C=c.HoldingsCalibration,now=Date.parse('2026-10-05T18:00:00Z');
function predict(state,item,options={}){return L.predict(state,item,{neural:[.01,.01,.98],boosting:[.01,.01,.98],source:{symbol:e.symbol,currency:e.currency,kind:e.kind,asOf:'2026-10-02',t:Date.parse('2026-10-02T13:30:00Z'),fingerprint:'same-history'},now,...options});}
test('first checkpoint is selected only on earlier calibration and must beat a prior on the later test',()=>{const item=fixture(c),out=L.update(null,item,now);assert.equal(out.ok,true);assert.equal(out.changed,true);assert.ok(out.state.champion);const p=predict(out.state,item);assert.equal(p.eligible,true);assert.equal(p.validation.test,20);assert.equal(p.validation.fit,20);assert.equal(p.classIndex,2);assert.ok(p.probabilities.every(x=>x>0&&x<1));assert.ok(p.validation.parameters.temperature>1);assert.equal(p.symbol,e.symbol);assert.equal(out.state.reviews[0].promoted,true);});
test('less than 40 independent observations and absent classes never acquire an active checkpoint',()=>{for(const item of [fixture(c,39),fixture(c,40,{onlyClass:1})]){const out=L.update(null,item,now);assert.equal(out.state.champion,null);const p=predict(out.state,item);assert.equal(p.eligible,false);assert.equal(p.checkpoint,null);assert.deepEqual(plain(p.probabilities),[.01,.01,.98]);}});
test('held-out outcomes cannot influence selected weights, temperature or fit loss',()=>{const rows=L.sample(fixture(c),now),a=L.evaluate(rows.slice(0,20),rows.slice(20)),changed=plain(rows.slice(20));changed.forEach(r=>r.actualClass=(r.actualClass+1)%3);const b=L.evaluate(rows.slice(0,20),changed);assert.deepEqual(plain(a.parameters),plain(b.parameters));assert.equal(a.fitLoss,b.fitLoss);assert.notEqual(a.scores.candidate.loss,b.scores.candidate.loss);});
test('a saved checkpoint cannot be activated at or before its last evaluation outcome',()=>{const item=fixture(c),out=L.update(null,item,now),end=out.state.champion.reviewEnd;const p=predict(out.state,item,{source:{symbol:e.symbol,currency:e.currency,kind:e.kind,asOf:'old',t:end,fingerprint:'same-history'}});assert.equal(p.eligible,false);assert.equal(p.checkpoint,null);});
test('repaints and repeated analysis of the same ledger do not generate versions',()=>{const item=fixture(c),a=L.update(null,item,now),b=L.update(a.state,item,now+1000);assert.equal(b.changed,false);assert.deepEqual(plain(b.state),plain(a.state));});
test('a challenger requires twenty genuinely new origins and is compared with the old version on the same block',()=>{const item=fixture(c),adopted=dates[239]+9*3600000,a=L.update(null,item,adopted),b=L.update(a.state,fixture(c,59),now);assert.equal(b.changed,false);const d=L.update(a.state,fixture(c,60),now);assert.equal(d.changed,true);assert.equal(d.state.reviews.length,2);assert.equal(d.state.reviews[1].promoted,false);assert.ok(d.state.reviews[1].incumbent);assert.equal(d.state.reviews[1].incumbent.n,20);assert.equal(d.state.champion.id,a.state.champion.id);});
test('changing frozen probabilities, prices or saved parameters suspends the checkpoint',()=>{for(const change of [item=>item.ledger.entries[0].estimate.probabilities=[.1,.85,.05],item=>item.ledger.entries[0].outcome.path[0].c+=.1]){const item=fixture(c),state=L.update(null,item,now).state;change(item);assert.equal(predict(state,item).eligible,false);assert.equal(L.update(state,item,now).ok,false);}const item=fixture(c),state=plain(L.update(null,item,now).state);state.champion.parameters.temperature=1;assert.equal(predict(state,item).eligible,false);});
test('identity, data-kind, absent reports and source errors cannot activate a probability verdict',()=>{const item=fixture(c),state=L.update(null,item,now).state;for(const options of [{neural:null},{boosting:[.2,.2,.2]},{source:{symbol:'OTHER',currency:e.currency,kind:e.kind}},{source:{symbol:e.symbol,currency:e.currency,kind:'market'}}])assert.equal(predict(state,item,options).eligible,false);item.check={state:'error'};assert.equal(predict(state,item).eligible,false);});
test('close class probabilities abstain even with a verified checkpoint',()=>{const item=fixture(c),state=L.update(null,item,now).state,p=predict(state,item,{neural:[.34,.33,.33],boosting:[.34,.33,.33]});assert.equal(p.eligible,false);assert.ok(p.checkpoint);assert.match(p.reason,/nu separă/);});
test('twenty poor future results suspend direction while preserving the checkpoint and every observation',()=>{const old=fixture(c),adopted=dates[239]+9*3600000,state=L.update(null,old,adopted).state,item=fixture(c,60,{wrong:true}),before=JSON.stringify(item),p=predict(state,item);assert.equal(p.eligible,false);assert.match(p.reason,/degradat/);assert.equal(JSON.stringify(item),before);assert.equal(state.champion.id,p.checkpoint);});
test('original probability and calibration protocols remain separate reports',()=>{const item=fixture(c),r=C.build(item,{scope:e.scope,kind:e.kind,now}),state=L.update(null,item,now).state;assert.equal(r.reviewOnly,true);assert.equal(r.direction,undefined);assert.equal(predict(state,item).version,'holdings-learning-v1');assert.equal(r.version,'holdings-calibration-v1');});
test('restored historical estimates remain inspectable but cannot create an operational checkpoint',()=>{const item=fixture(c);item.ledger.entries.forEach(r=>r.restoredAt=now);assert.ok(item.ledger.entries.every(r=>c.HoldingsForecast.validEntry(r,e,now)));assert.equal(C.build(item,{scope:e.scope,kind:e.kind,now}).available,40);const out=L.update(null,item,now);assert.equal(out.state.champion,null);assert.equal(predict(out.state,item).observations,0);});
test('verdict probabilities are frozen, exportable and scored even when the direction abstains',()=>{const F=c.HoldingsForecast,t=Date.parse('2026-10-02T13:30:00Z'),capturedAt=t+8*3600000,input={model:'verdict',modelVersion:F.VERSIONS.verdict,trainedAt:capturedAt-1000,state:'weak',source:{t,asOf:'2026-10-02',timezone:'America/New_York',closeMinutes:960,close:100,atrPct:1},estimate:{title:'Probabilități exploratorii',verdictState:'weak',direction:null,sourceFingerprint:'shared',reasons:['Colectare.'],cards:['neural','boosting','hmm','isolation','quantile','garch','knn'].map(id=>({id,version:F.VERSIONS[id],state:'limited',value:'Estimare'})),probabilistic:{version:L.VERSION,probabilities:[.1,.2,.7],classIndex:2,checkpoint:null,eligible:false}}};const frozen=F.project(input,e,capturedAt);assert.ok(frozen);input.estimate.probabilistic.probabilities[2]=.5;assert.equal(frozen.estimate.probabilistic.probabilities[2],.7);const days=['2026-10-02','2026-10-05','2026-10-06','2026-10-07','2026-10-08','2026-10-09'],checkedAt=Date.parse('2026-10-09T21:00:00Z'),bars=days.map((d,i)=>{const p=100+i*.4;return {t:Date.parse(d+'T13:30:00Z'),o:p,h:p+1,l:p-1,c:p,v:10000};}),r=F.verify(frozen,{symbol:e.symbol,currency:e.currency,timezone:'America/New_York',retrievedAt:checkedAt,bars},checkedAt),m=F.metric(r);assert.ok(F.validEntry(r,e,checkedAt));assert.equal(m.directional,false);assert.ok(Math.abs(m.loss+Math.log(.7))<1e-10);assert.ok(Math.abs(m.brier-.14)<1e-10);const a=F.aggregate([r],'verdict');assert.equal(a.probabilityN,1);assert.equal(a.validatedN,0);assert.equal(a.directional,0);});
