import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {core,e,fixture,plain} from './holdings-strategy-fixtures.mjs';
function setup({demo=false,durable=null,quota=false,local=new Map()}={}){
 let clock=Date.parse('2026-09-18T21:00:00Z'),fetched=0,pendingResolve,model,exported;const controls={},adapters=[],c=core(['lib/holdings-forecast-storage.js','lib/holdings-strategy-demo.js','holdings/strategy-view.js'],{Date:class extends Date{static now(){return clock;}},localStorage:{getItem:k=>local.get(k)??null,setItem:(k,v)=>{if(quota)throw Error('Quota exceeded');local.set(k,v);}},document:{querySelectorAll:q=>controls[q]||[]},HoldingsNeuralUI:{refresh(){},exportReport:r=>exported=r},D:{fetchStock:async()=>{fetched++;return new Promise(resolve=>pendingResolve=resolve);}}});
 if(durable){const create=c.HoldingsForecastStorage.create;c.HoldingsForecastStorage.create=(legacy,options)=>{const adapter=create(legacy,{...options,durable});adapters.push(adapter);return adapter;};}
 for(const path of ['holdings/strategy.js','holdings/forecast.js'])vm.runInContext(readFileSync(path,'utf8'),c);
 const identity={...e,kind:demo?'synthetic':'market'},x=fixture(c,{identity}),p={ticker:e.ticker,instrumentCurrency:'USD',currency:'EUR',quantity:999,apiKey:'secret'},ctx={scope:e.scope,demo,positions:[p],symbol:()=>e.symbol,model:()=>model};model={asOf:x.original.source.asOf,price:100,atrPct:2,currency:'USD',bars:[x.bars[0]]};c.HoldingsForecastUI.setContext(ctx);
 const verdict=(a=x)=>({shared:{symbol:e.symbol,currency:'USD',kind:identity.kind,...a.original.source,fingerprint:'test-fingerprint'},report:{version:c.HoldingsForecast.VERSIONS.verdict,symbol:e.symbol,currency:'USD',kind:identity.kind,asOf:a.original.source.asOf,generatedAt:clock,available:6,total:6,state:a.input.state,...a.input.estimate,cards:a.input.estimate.cards.map(r=>({...r,available:true,quantity:999}))}});
 const capture=(a=x)=>{const v=verdict(a);return c.HoldingsForecastUI.captureVerdict(p,v.report,v.shared);};
 function button(attr){const b={dataset:{[attr.replace(/-([a-z])/g,(_,s)=>s.toUpperCase())]:'0'}};controls['[data-'+attr+']']=[b];c.HoldingsStrategyUI.bind();return b;}
 return {c,x,p,ctx,identity,local,controls,adapters,capture,verdict,button,setNow:t=>clock=t,setModel:a=>{model={asOf:a.original.source.asOf,price:100,atrPct:2,currency:'USD',bars:[a.bars[0]]};},resolve:()=>pendingResolve?.([]),fetches:()=>fetched,exported:()=>exported,restore:()=>c.HoldingsForecastUI.restore(p)};
}
test('only a newly saved complete final verdict captures a trial; reanalysis preserves both originals',async()=>{const s=setup();await s.restore();const out=s.capture();assert.equal(out.saved,true);assert.equal(out.strategy.saved,true);assert.equal(s.c.HoldingsStrategyUI.snapshot(s.p).entries.length,1);const raw=s.local.get(s.c.HoldingsStrategy.key(s.identity));assert.equal(s.capture().duplicate,true);assert.equal(s.local.get(s.c.HoldingsStrategy.key(s.identity)),raw);assert.doesNotMatch(raw,/secret|apiKey|quantity/);const next=fixture(s.c,{identity:s.identity,day:'2026-09-21'});s.setNow(next.capturedAt);s.setModel(next);assert.equal(s.capture(next).strategy.saved,true);assert.equal(s.c.HoldingsStrategyUI.snapshot(s.p).entries.length,2);assert.equal(s.c.HoldingsStrategy.directory(s.local.get(s.c.HoldingsStrategy.DIRECTORY)).identities.length,1);});
test('cost controls preserve drafts across refresh and changes freeze only future decisions',async()=>{const s=setup();await s.restore();s.capture();const S=s.c.HoldingsStrategy,input={dataset:{strategyIndex:'0',strategyCost:'slippagePct'},value:'0.25'};s.controls['[data-strategy-cost]']=[input];s.c.HoldingsStrategyUI.bind();input.oninput();assert.match(s.c.HoldingsStrategyUI.markup(s.p,0),/data-strategy-cost="slippagePct" value="0.25"/);s.button('strategy-save').onclick();assert.equal(s.c.HoldingsStrategyUI.snapshot(s.p).settings.costs.slippagePct,.25);assert.equal(s.c.HoldingsStrategyUI.snapshot(s.p).entries[0].policy.costs.slippagePct,.05);const next=fixture(s.c,{identity:s.identity,day:'2026-09-21'});s.setNow(next.capturedAt);s.setModel(next);s.capture(next);const rows=s.c.HoldingsStrategyUI.snapshot(s.p).entries;assert.equal(rows[1].policy.costs.slippagePct,.25);assert.notEqual(rows[0].policy.id,rows[1].policy.id);input.value='';input.oninput();s.button('strategy-save').onclick();assert.equal(s.c.HoldingsStrategyUI.snapshot(s.p).settings.costs.slippagePct,.25);assert.match(s.c.HoldingsStrategyUI.markup(s.p,0),/între 0 și 5/);assert.equal(S.report(rows,s.identity).policies.length,2);});
test('disabled tracking leaves old decisions verifiable and prevents a later verdict from adding a trade',async()=>{const s=setup();await s.restore();s.capture();s.c.HoldingsStrategyUI.saveSettings(s.p,{...s.c.HoldingsStrategy.defaults(),enabled:false});const next=fixture(s.c,{identity:s.identity,day:'2026-09-21'});s.setNow(next.capturedAt);s.setModel(next);assert.equal(s.capture(next).strategy.disabled,true);assert.equal(s.c.HoldingsStrategyUI.snapshot(s.p).entries.length,1);s.setNow(s.x.now);s.c.HoldingsForecastUI.checkSource(s.p,s.x.source);assert.equal(s.c.HoldingsStrategyUI.snapshot(s.p).entries[0].verification.state,'resolved');});
test('the shared source and manual check resolve the trial without another price request',async()=>{const s=setup();await s.restore();s.capture();s.setNow(s.x.now);s.c.DailySeries.read=()=>s.x.source;const pending=s.c.HoldingsForecastUI.check(s.p,true);await new Promise(r=>setImmediate(r));assert.equal(s.fetches(),1);s.resolve();assert.equal((await pending).state,'checked');const x=s.c.HoldingsStrategyUI.snapshot(s.p);assert.equal(x.entries[0].verification.state,'resolved');assert.ok(Math.abs(x.entries[0].outcome.result.netUSD-7.99)<1e-9);assert.equal(s.fetches(),1);});
test('an account change during verification cannot overwrite either account strategy',async()=>{const s=setup();await s.restore();s.capture();s.setNow(s.x.now);s.c.DailySeries.read=()=>s.x.source;const S=s.c.HoldingsStrategy,before=s.local.get(S.key(s.identity)),pending=s.c.HoldingsForecastUI.check(s.p,true);await new Promise(r=>setImmediate(r));s.c.HoldingsForecastUI.setContext({...s.ctx,scope:'other-account'});s.resolve();assert.equal((await pending).state,'ignored');assert.equal(s.local.get(S.key(s.identity)),before);assert.equal(s.local.has(S.key({...s.identity,scope:'other-account'})),false);assert.equal(s.c.HoldingsStrategyUI.capture(s.p,s.x.original,{identity:s.identity,now:s.x.capturedAt}).ok,false);});
test('late and incomplete verdicts cannot backfill the strategy and corrupt settings survive untouched',async()=>{const s=setup();await s.restore();let v=s.verdict();v.report.available=5;assert.equal(s.c.HoldingsForecastUI.captureVerdict(s.p,v.report,v.shared).ok,false);assert.equal(s.c.HoldingsStrategyUI.snapshot(s.p).entries.length,0);s.setNow(Date.parse('2026-09-21T12:00:00Z'));assert.equal(s.capture().ok,false);assert.equal(s.c.HoldingsStrategyUI.snapshot(s.p).entries.length,0);s.setNow(s.x.capturedAt);const k=s.c.HoldingsStrategy.settingsKey(s.identity);s.local.set(k,'{broken');const out=s.capture();assert.equal(out.saved,true);assert.equal(out.strategy.ok,false);assert.equal(s.local.get(k),'{broken');assert.equal(s.c.HoldingsStrategyUI.snapshot(s.p).ok,false);});
test('the demo control and export use actual calculations without writing account data',()=>{const s=setup({demo:true});s.button('strategy-demo').onclick();const rows=s.c.HoldingsStrategyUI.snapshot(s.p).entries;assert.equal(rows.length,12);assert.equal(s.local.size,0);assert.match(s.c.HoldingsStrategyUI.markup(s.p,0),/12 verdicte inventate/);s.button('strategy-export').onclick();const out=s.exported();assert.equal(out.result.reviewOnly,true);assert.equal(out.kind,'synthetic');assert.doesNotMatch(JSON.stringify(out),/private-account|scope|secret|quantity|apiKey/);s.c.HoldingsForecastUI.setContext({...s.ctx,demo:false});s.button('strategy-demo').onclick();assert.equal(s.local.size,0);assert.equal(s.c.HoldingsStrategyUI.snapshot(s.p).entries.length,0);});
function persistence(){const saved=new Map();return {saved,get:async k=>saved.get(k)??null,write:async changes=>{const staged=new Map();for(const change of changes){let value=change.value,before=saved.get(change.key)??null;if(typeof change.merge==='function')value=change.merge(before,value,change.key);else if(before!==change.before){if(!change.merge)throw Error('Conflict');throw Error('Unexpected forecast merge');}staged.set(change.key,value);}for(const [k,v] of staged)saved.set(k,v);return staged;}};}
test('full localStorage still preserves the trial and directory durably, recoverable from a new page',async()=>{const db=persistence(),s=setup({durable:db,quota:true});await s.restore();assert.equal(s.capture().strategy.saved,true);for(const a of s.adapters)await a.settled();const S=s.c.HoldingsStrategy;assert.equal(JSON.parse(db.saved.get(S.key(s.identity))).entries.length,1);assert.equal(S.directory(db.saved.get(S.DIRECTORY)).identities.length,1);assert.equal(s.local.size,0);const next=setup({durable:db,quota:true});await next.restore();assert.equal(next.c.HoldingsStrategyUI.snapshot(next.p).entries.length,1);assert.equal(next.c.HoldingsStrategyUI.snapshot(next.p).storage.state,'indexeddb');});
test('an aborted durable transaction remains exportable and explicitly session-only',async()=>{const db=persistence(),s=setup({durable:db});await s.restore();db.write=async()=>{throw Error('Aborted');};assert.equal(s.capture().strategy.saved,true);for(const a of s.adapters)await a.settled();assert.equal(db.saved.size,0);assert.equal(s.c.HoldingsStrategyUI.snapshot(s.p).storage.state,'session');s.button('strategy-export').onclick();assert.equal(s.exported().result.entries.length,1);assert.match(s.c.HoldingsStrategyUI.markup(s.p,0),/doar în această sesiune/);});
test('both pages load strategy dependencies before their UI and expose a named navigation target',()=>{const html=readFileSync('holdings/index.html','utf8'),shadow=readFileSync('shadow-book/index.html','utf8');assert.ok(html.indexOf('src="../lib/holdings-strategy.js')<html.indexOf('src="strategy.js'));assert.ok(html.indexOf('src="strategy.js')<html.indexOf('src="forecast.js'));assert.match(readFileSync('holdings/model-summary.js','utf8'),/\['strategy','Strategie simulată'\]/);assert.match(shadow,/id="aiStrategyShadow"/);assert.ok(shadow.indexOf('src="../holdings/strategy-view.js')<shadow.indexOf('src="ai-strategy.js'));});
