import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function setup(){const writes=new Map(),workers=[],button={dataset:{hmmTrain:'0'}};let resolveFetch,neuralBusy=false;const s={HoldingsHMM:{VERSION:'holdings-hmm-v1',valid:()=>true},HoldingsNeural:{demoBars:()=>[{t:10,o:1,h:2,l:1,c:1,v:1}]},HoldingsNeuralUI:{refresh(){},busy:()=>neuralBusy},document:{querySelectorAll:q=>q==='[data-hmm-train]'?[button]:[]},localStorage:{getItem:k=>writes.get(k)||null,setItem:(k,v)=>writes.set(k,v)},D:{fetchStock:()=>new Promise(resolve=>resolveFetch=resolve)},DailySeries:{read:()=>({bars:[{t:10}],asOf:'2026-10-02',currency:'USD',timezone:'America/New_York'}),date:()=> '2026-10-02'},setTimeout:()=>1,clearTimeout(){},Worker:class{constructor(){workers.push(this);}postMessage(payload){this.payload=payload;}terminate(){this.terminated=true;}}};vm.createContext(s);vm.runInContext(readFileSync('holdings/hmm.js','utf8'),s);const context=(scope,demo=true)=>({scope,demo,positions:[{ticker:'TEST_US_EQ',quantity:42,averagePrice:99}],symbol:()=> 'TEST',model:()=>({asOf:'2026-10-02',currency:'USD'})});s.HoldingsHMMUI.setContext(context('account-a'));s.HoldingsHMMUI.bind();return {ui:s.HoldingsHMMUI,workers,writes,button,context,resolve:()=>resolveFetch([]),neuralBusy:()=>neuralBusy=true};}
test('HMM worker receives no portfolio, balance or credentials',()=>{const s=setup();s.button.onclick();assert.deepEqual(Object.keys(s.workers[0].payload).sort(),['bars','id','now']);});
test('account changes terminate HMM jobs and discard delayed messages',()=>{const s=setup();s.button.onclick();const w=s.workers[0];s.ui.setContext(s.context('account-b'));assert.equal(w.terminated,true);w.onmessage({data:{id:w.payload.id,result:{current:{t:10}}}});assert.equal(s.writes.size,0);});
test('a cancelled history request cannot start a worker in another account',async()=>{const s=setup();s.ui.setContext(s.context('a',false));s.button.onclick();s.ui.setContext(s.context('b',false));s.resolve();await new Promise(r=>setImmediate(r));assert.equal(s.workers.length,0);});
test('HMM cancellation and neural mutual exclusion leave no orphan workers',()=>{const s=setup();s.button.onclick();s.ui.cancel();assert.equal(s.workers[0].terminated,true);assert.equal(s.ui.busy(),false);s.neuralBusy();s.button.onclick();assert.equal(s.workers.length,1);});
test('demo results stay in memory while real results require the source session',async()=>{const s=setup();s.button.onclick();let w=s.workers[0];w.onmessage({data:{id:w.payload.id,result:{current:{t:10}}}});assert.equal(s.writes.size,0);s.ui.setContext(s.context('real',false));s.button.onclick();s.resolve();await new Promise(r=>setImmediate(r));w=s.workers.at(-1);w.onmessage({data:{id:w.payload.id,result:{current:{t:11}}}});assert.equal(s.writes.size,0);});

test('a new EOD session in the same account cancels a pending HMM job',()=>{const s=setup();s.button.onclick();const context=s.context('account-a');context.model=()=>({asOf:'2026-10-03',currency:'USD'});s.ui.setContext(context);assert.equal(s.workers[0].terminated,true);assert.equal(s.ui.busy(),false);});
test('a storage error is visible and never claims that the model was saved',async()=>{const s=setup();s.ui.setContext(s.context('real',false));s.button.onclick();s.resolve();await new Promise(r=>setImmediate(r));s.writes.set=()=>{throw Error('Spațiu plin');};const w=s.workers[0];w.onmessage({data:{id:w.payload.id,result:{current:{t:10}}}});assert.equal(s.writes.size,0);assert.match(s.ui.markup(s.context('real',false).positions[0],0),/nu a fost salvat.*Spațiu plin/);});
