import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';

const at='2026-10-08T18:00:00Z',now=Date.parse(at);
const p={ticker:'A_US_EQ',name:'Company A',quantity:10,currentPrice:102,averagePrice:110,unrealized:-80,value:1020,currency:'EUR',instrumentCurrency:'USD'};
const m={symbol:'A',currency:'USD',asOf:'2026-10-07',price:101,ema21:95,ema50:90,short:'Ascendent',medium:'Ascendent',long:'Ascendent',rsi:60,rvol:1.4,rs20:2,support:85,resistance:110,sourceFingerprint:'verified-bars',timezone:'America/New_York',closeMinutes:960};
const note={stop:90,stopCurrency:'USD',stopAlertPct:3},snapshot={fetchedAt:at,summary:{currency:'EUR',totalValue:2040}};
const memory=()=>{const data=new Map();let writes=0;return {data,get writes(){return writes;},getItem:k=>data.get(k)||null,setItem(k,v){writes++;data.set(k,v);}};};
function setup(){const c={Intl,Date};vm.createContext(c);for(const f of ['lib/daily-series.js','lib/holdings-pulse.js','lib/holding-evolution.js','lib/holding-roster.js'])vm.runInContext(readFileSync(f,'utf8'),c);return c;}
function project(R,position=p,options={}){return R.entry(position,{symbol:'A',model:m,note,brokerAt:at,benchmark:'SPY',now,...options});}
const copy=x=>JSON.parse(JSON.stringify(x));

test('favorites stay scoped to the verified account and environment',()=>{const R=setup().HoldingRoster,S=memory(),E=R.create(S);assert.equal(E.toggle('a',p.ticker,'market',now).ok,true);assert.deepEqual([...E.favorites('a','market',now)],[p.ticker]);assert.equal(E.favorites('b','market',now).length,0);assert.equal(E.favorites('a','synthetic',now).length,0);assert.equal(E.toggle('',p.ticker,'market',now).ok,false);assert.equal(R.create(S).favorites('a','market',now)[0],p.ticker);E.toggle('a',p.ticker,'market',now);assert.equal(E.favorites('a','market',now).length,0);});
test('favorite priority preserves the chosen sort within each group without mutating the input',()=>{const R=setup().HoldingRoster,rows=['C','B','A','D'].map(t=>({p:{ticker:t}}));assert.deepEqual(R.prioritize(rows,['A','C']).map(x=>x.p.ticker),['C','A','B','D']);assert.deepEqual(rows.map(x=>x.p.ticker),['C','B','A','D']);});
test('first visit has no invented baseline; later visits compare against a frozen previous visit',()=>{const R=setup().HoldingRoster,S=memory(),E=R.create(S),a=project(R);assert.equal(E.observe('a',[a],{now}).state,'first');const second=R.create(S),b=project(R,{...p,unrealized:-60},{now:now+1000});let r=second.observe('a',[b],{now:now+1000});assert.equal(r.rows[0].changed,true);assert.match(r.rows[0].lines.join(' '),/-80 → -60 EUR.*\+20/);r=second.observe('a',[project(R,{...p,unrealized:-50},{now:now+2000})],{now:now+2000});assert.match(r.rows[0].lines.join(' '),/-80 → -50 EUR.*\+30/);assert.equal(r.from,now);});
test('acknowledging changes establishes an explicit new baseline',()=>{const R=setup().HoldingRoster,S=memory();R.create(S).observe('a',[project(R)],{now});const E=R.create(S),b=project(R,{...p,unrealized:-60});E.observe('a',[b],{now});assert.equal(E.acknowledge('a','market',now).ok,true);assert.equal(E.observe('a',[b],{now}).rows[0].changed,false);assert.equal(R.create(S).observe('a',[b],{now}).rows[0].changed,false);});
test('identical repaints do not continuously write new observation timestamps',()=>{const R=setup().HoldingRoster,S=memory(),E=R.create(S);E.observe('a',[project(R)],{now});const writes=S.writes;E.observe('a',[project(R,p,{now:now+1000})],{now:now+1000});assert.equal(S.writes,writes);const saved=S.getItem(R.scopeKey('a'));assert.equal(E.observe('a',[],{now}).state,'unavailable');assert.equal(S.getItem(R.scopeKey('a')),saved);});
test('bad JSON and malformed or future projections are preserved without overwrite',()=>{const R=setup().HoldingRoster;const base={version:1,favorites:[],snapshot:{version:1,at:now,entries:[project(R)]}};const variants=['bad-json',JSON.stringify({...base,snapshot:{...base.snapshot,at:now+60001}})];for(const patch of [{code:'fake'},{short:'Invented'},{stop:{state:'safe'}},{asOf:'2026-02-30'},{price:null}]){const bad=copy(base);Object.assign(bad.snapshot.entries[0].technical,patch);variants.push(JSON.stringify(bad));}for(const raw of variants){const S=memory(),k=R.scopeKey('a');S.data.set(k,raw);const E=R.create(S);assert.equal(E.observe('a',[project(R)],{now}).state,'unavailable');assert.equal(E.toggle('a',p.ticker,'market',now).ok,false);assert.equal(S.getItem(k),raw);}});
test('source identity changes never generate before/after conclusions',()=>{const R=setup().HoldingRoster,a=project(R);for(const opts of [{symbol:'OTHER'},{benchmark:'QQQ'},{sectorBenchmark:'XLK'}]){const b=project(R,{...p,unrealized:40},opts);assert.equal(R.changes(a,b,{now}).state,'incompatible');}assert.equal(R.changes(a,project(R,{...p,currency:'USD'}),{now}).state,'incompatible');});
test('position quantity and cost changes suppress monetary deltas; unknown quantities stay unknown',()=>{const R=setup().HoldingRoster,a=project(R);for(const patch of [{quantity:11},{averagePrice:111},{quantity:null},{averagePrice:null}]){const r=R.changes(a,project(R,{...p,...patch,unrealized:40}),{now});assert.match(r.lines.join(' '),/nu este comparabilă/);assert.doesNotMatch(r.lines.join(' '),/P&L broker/);}for(const patch of [{quantity:null},{averagePrice:null}])assert.doesNotMatch(R.changes(project(R,{...p,...patch}),project(R,{...p,...patch,unrealized:40}),{now}).lines.join(' '),/P&L broker/);});
test('stale, missing, future or regressed broker snapshots cannot generate a monetary delta',()=>{const R=setup().HoldingRoster,a=project(R);for(const stamp of [null,'2026-10-08T17:00:00Z','2026-10-08T18:01:01Z','2026-10-08T17:59:59Z'])assert.doesNotMatch(R.changes(a,project(R,{...p,unrealized:40},{brokerAt:stamp}),{now}).lines.join(' '),/P&L broker/);});
test('technical changes remain explainable even on the same EOD; older analyses cannot pretend to be new',()=>{const R=setup().HoldingRoster,a=project(R),b=project(R,p,{model:{...m,price:88,medium:'Descendent',short:'Descendent'}}),r=R.changes(a,b,{now});assert.equal(r.changed,true);assert.match(r.lines.join(' '),/Trend mediu: Ascendent → Descendent/);assert.equal(R.changes(a,project(R,p,{model:{...m,asOf:'2026-10-06'}}),{now}).state,'older');assert.match(R.changes(a,project(R,p,{model:null}),{now}).lines.join(' '),/indisponibilă sau expirată/);});
test('new holdings appear as observed additions to an existing baseline',()=>{const R=setup().HoldingRoster,S=memory();R.create(S).observe('a',[project(R)],{now});const r=R.create(S).observe('a',[project(R),project(R,{...p,ticker:'B'})],{now});assert.equal(r.rows[1].newPosition,true);assert.equal(r.rows[1].changed,true);});
test('storage quota errors keep usable in-memory state with a persistent visible reason',()=>{const R=setup().HoldingRoster,E=R.create({getItem:()=>null,setItem(){throw Error('quota');}});assert.equal(E.toggle('a',p.ticker,'market',now).ok,false);assert.equal(E.favorites('a','market',now)[0],p.ticker);E.observe('a',[project(R)],{now});assert.match(E.observe('a',[project(R,p,{now:now+1000})],{now:now+1000}).reason,/nu a putut păstra/);});
test('synthetic prior visits cannot replace the real baseline',()=>{const R=setup().HoldingRoster,S=memory(),E=R.create(S);E.observe('a',[project(R)],{now});const saved=S.getItem(R.scopeKey('a'));assert.equal(E.simulate('a',{version:1,at:now,entries:[project(R,{...p,unrealized:-100})]},{now}),true);assert.equal(E.observe('a',[project(R)],{kind:'synthetic',now}).rows[0].changed,true);assert.equal(E.observe('a',[project(R)],{now}).state,'first');assert.equal(S.getItem(R.scopeKey('a')),saved);});
test('comparison computes monetary distance in instrument currency and weight only in account currency',()=>{const R=setup().HoldingRoster,r=R.comparison(p,{symbol:'A',model:m,note,snapshot,now});assert.equal(r.stopRisk,120);assert.equal(r.stop.currency,'USD');assert.equal(r.weight,50);assert.equal(r.pnl,-80);assert.equal(r.currency,'EUR');assert.equal(R.comparison({...p,currency:'USD'},{symbol:'A',model:m,note,snapshot,now}).weight,null);});
test('crossed, unknown and overflowing stop distances remain unknown instead of zero',()=>{const R=setup().HoldingRoster;for(const patch of [{currentPrice:89},{quantity:null},{quantity:1e308}])assert.equal(R.comparison({...p,...patch},{symbol:'A',model:m,note,snapshot,now}).stopRisk,null);assert.equal(R.comparison(p,{symbol:'A',model:m,note:{...note,stopCurrency:'EUR'},snapshot,now}).stopRisk,null);assert.equal(R.comparison(p,{symbol:'A',model:null,note,snapshot:{...snapshot,fetchedAt:'2026-10-08T17:00:00Z'},now}).stopRisk,null);});
test('comparison rejects wrong symbols, denominations, stale EOD, future dates and invalid prices',()=>{const R=setup().HoldingRoster;for(const patch of [{symbol:'OTHER'},{currency:'EUR'},{asOf:'2026-10-06'},{asOf:'2026-10-09'},{asOf:'2026-02-30'},{price:0},{checkedAt:now+60001}])assert.equal(R.comparison(p,{symbol:'A',model:{...m,...patch},snapshot,now}).model,null);const r=R.comparison({...p,instrumentCurrency:'GBp'},{symbol:'A',model:{...m,currency:'GBX'},note:{...note,stopCurrency:'GBp'},snapshot,now});assert.equal(r.model.currency,'GBX');assert.equal(r.stopRisk,120);});
test('probabilities require the same symbol, EOD, denomination, horizon, environment and source fingerprint',()=>{const R=setup().HoldingRoster,prob={symbol:'A',asOf:m.asOf,currency:'USD',sourceFingerprint:m.sourceFingerprint,kind:'market',horizon:5,probabilities:[.2,.3,.5],eligible:false};const compare=probability=>R.comparison(p,{symbol:'A',model:m,note,snapshot,probability,now});assert.equal(compare(prob).probability.eligible,false);for(const patch of [{symbol:'B'},{asOf:'2026-10-06'},{currency:'EUR'},{sourceFingerprint:'old'},{kind:'synthetic'},{horizon:1},{probabilities:[.2,.3,.6]},{probabilities:[null,.3,.7]}])assert.equal(compare({...prob,...patch}).probability,null);});

function uiSetup(){const c=setup(),S=memory(),ids={};for(const id of ['holdingFavoritesOnly','holdingChangesOnly','holdingRosterTools','holdingComparison','holdingChangesCount','holdingFavoritesLabel','holdingChangesLabel','holdingVisitStatus','holdingVisitRows','holdingVisitEmpty','holdingVisitSeen','holdingVisitDemo','holdingCompareA','holdingCompareB','holdingCompareRefresh','holdingCompareResult'])ids[id]={checked:false,hidden:false,open:false,innerHTML:'',value:'',addEventListener(){},querySelectorAll:()=>[]};c.Date=class extends Date{static now(){return now;}};c.document={getElementById:id=>ids[id]};c.localStorage=S;c.ViewRefresh={patchList(host,rows,key,html){host.innerHTML=rows.map(html).join('');}};let refreshes=0;const ctx={scope:'a',demo:false,positions:[p,{...p,ticker:'B',name:'Company B'}],snapshot,symbol:p=>p.ticker==='B'?'B':'A',model:p=>({...m,symbol:p.ticker==='B'?'B':'A'}),note:()=>note,refresh(){refreshes++;},refreshRoster(){refreshes++;c.HoldingsRosterUI.setContext(ctx);}};vm.runInContext(readFileSync('holdings/roster.js','utf8'),c);c.HoldingsRosterUI.setContext(ctx);return {c,ids,S,ctx,get refreshes(){return refreshes;}};}
test('UI star toggles only favorites and keeps precise accessible identity',()=>{const f=uiSetup(),button={dataset:{rosterFavorite:'B'}},UI=f.c.HoldingsRosterUI;UI.bindRoster({querySelectorAll:()=>[button]});button.onclick();assert.equal(f.refreshes,1);assert.match(UI.controls(f.ctx.positions[1]),/aria-pressed="true"/);assert.match(UI.controls(f.ctx.positions[1]),/Elimină din favorite B/);assert.equal(UI.filter(f.ctx.positions.map(p=>({p})))[0].p.ticker,'B');f.ids.holdingFavoritesOnly.checked=true;assert.equal(UI.filter(f.ctx.positions.map(p=>({p}))).length,1);});
test('comparison preserves two explicit selections and rejects the same position',()=>{const f=uiSetup();f.c.HoldingsRosterUI.renderComparison();assert.match(f.ids.holdingCompareResult.innerHTML,/120 USD/);assert.match(f.ids.holdingCompareResult.innerHTML,/50 %/);assert.match(f.ids.holdingCompareResult.innerHTML,/Modele actuale indisponibile/);f.ids.holdingCompareB.value=p.ticker;f.ids.holdingCompareB.onchange();assert.match(f.ids.holdingCompareResult.innerHTML,/două dețineri diferite/);assert.doesNotMatch(f.ids.holdingCompareResult.innerHTML,/<table/);});
test('account switches reset pair and filters; removed selections stay blank rather than switching silently',()=>{const f=uiSetup();f.ids.holdingFavoritesOnly.checked=true;f.ctx.scope='b';f.ctx.positions=[f.ctx.positions[1]];f.c.HoldingsRosterUI.setContext(f.ctx);assert.equal(f.ids.holdingFavoritesOnly.checked,false);assert.equal(f.ids.holdingCompareB.value,'');f.c.HoldingsRosterUI.renderComparison();assert.match(f.ids.holdingCompareResult.innerHTML,/două dețineri diferite/);});
test('demo favorites and simulated visits never write into persistent real preferences',()=>{const f=uiSetup(),saved=copy([...f.S.data]);f.ctx.demo=true;f.ctx.scope='educational-demo';f.c.HoldingsRosterUI.setContext(f.ctx);assert.equal(f.ids.holdingVisitDemo.hidden,false);f.ids.holdingVisitDemo.onclick();assert.equal(f.ids.holdingChangesCount.textContent,'2');assert.match(f.ids.holdingVisitRows.innerHTML,/P&amp;L broker/);assert.deepEqual(copy([...f.S.data]),saved);f.ids.holdingVisitSeen.onclick();assert.equal(f.ids.holdingChangesCount.textContent,'0');});
test('company names and ticker text are escaped in the comparison controls and reports',()=>{const f=uiSetup();f.ctx.positions[1]={...f.ctx.positions[1],name:'<img src=x>'};f.c.HoldingsRosterUI.setContext(f.ctx);f.c.HoldingsRosterUI.renderComparison();assert.doesNotMatch(f.ids.holdingCompareResult.innerHTML,/<img/);assert.match(f.ids.holdingCompareResult.innerHTML,/&lt;img/);});
