import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const c={Date,URL,setTimeout,clearTimeout};vm.createContext(c);for(const f of ['lib/daily-series.js','lib/holdings-events.js','lib/holdings-workspace.js'])vm.runInContext(readFileSync(f,'utf8'),c);const W=c.HoldingsWorkspace,now=Date.parse('2026-10-03T12:00Z');
test('attention ranks broken conditions and missing data with explicit reasons',()=>{const p=[{ticker:'A',value:250,currency:'USD'},{ticker:'B',value:50,currency:'USD'}],r=W.attention(p,{A:{price:90,medium:'Descendent'},B:null},{A:{stop:95}}, {},1000,'USD',x=>x.ticker,true,now);assert.equal(r[0].ticker,'A');assert.equal(r[0].priority,100);assert.ok(r[1].reasons[0].includes('expirată'));});
test('thesis never infers fundamentals from chart or turns missing RS into positive',()=>{const r=W.thesis({text:'Motiv',criteria:{uptrend:true,relative:true,minimumClose:100}}, {medium:'Ascendent',price:90,rs20:null});assert.equal(r.fundamental,'nerevizuită');assert.deepEqual(Array.from(r.rows,x=>x.state),['susținută','neverificată','slăbită']);});
test('stress isolates currency, sectors and uncovered positions',()=>{const p=[{ticker:'A',value:100,currency:'USD'},{ticker:'B',value:200,currency:'EUR'},{ticker:'C',value:null,currency:'USD'}];let r=W.stress(p,{A:{sector:'Tech'}},'USD',10);assert.equal(r.loss,10);assert.equal(r.covered,1);assert.equal(r.total,3);assert.equal(W.stress(p,{},null,10).loss,null);assert.equal(W.stress(p,{A:{sector:'Tech'}},'USD',10,'Energy').loss,null);assert.throws(()=>W.stress(p,{},'USD',101));});
test('calendar preserves conflicting manual/provider dates and discards stale provider',()=>{const p=[{ticker:'A'}],notes={A:{earnings:'2026-10-05',calendar:[{type:'Ex-dividend',date:'2026-10-10',url:'javascript:alert(1)'}]}},events={A:{symbol:'A',fetchedAt:now,earnings:{date:'2026-10-06',status:'ESTIMARE',source:'Provider'}}};let r=W.calendar(p,notes,events,x=>x.ticker,now);assert.equal(r.length,3);assert.equal(r[2].url,null);r=W.calendar(p,notes,{A:{...events.A,fetchedAt:now-3600000}},x=>x.ticker,now);assert.equal(r.length,2);});
test('timeline dedupes broker fills and retains dated thesis/model observations',()=>{const fill={id:'1',ticker:'A',date:'2026-10-01',side:'BUY',quantity:2,price:10,priceCurrency:'USD'};const r=W.timeline('A',[fill,fill],[{asOf:'2026-10-02',price:11,medium:'Ascendent'}],{history:[{at:'2026-10-03',text:'Teza'}]},null);assert.equal(r.length,3);assert.equal(r[0].type,'Teză / repere salvate');});
function series(){const bars=[];for(let d=new Date('2026-05-01T14:30Z');bars.length<90;d.setUTCDate(d.getUTCDate()+1))if(d.getUTCDay()>0&&d.getUTCDay()<6)bars.push({t:d.getTime(),c:100+bars.length});return {bars,timezone:'America/New_York',currency:'USD'};}
test('post-sale uses complete observations strictly after sale day, checks split and history',()=>{const s=series(),f={side:'SELL',price:100,priceCurrency:'USD',date:'2026-05-01T18:00Z'};let r=W.afterSale(f,s);assert.equal(r[0].price,105);assert.ok(Math.abs(r[0].change-5)<1e-8);r=W.afterSale(f,s,[s.bars[10].t]);assert.ok(r[1].status.includes('Split'));assert.equal(r[0].price,105);assert.throws(()=>W.afterSale({...f,date:'2025-01-01'},s),/Istoric/);assert.throws(()=>W.afterSale({...f,priceCurrency:'EUR'},s),/Monede/);r=W.afterSale({...f,date:new Date(s.bars.at(-1).t).toISOString()},s);assert.equal(r[0].change,undefined);});
