import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {core,e,fixture,plain} from './holdings-strategy-fixtures.mjs';
function setup({demo=false,local=new Map(),durable=null,quota=false}={}){
 let clock=Date.parse('2026-09-18T21:00:00Z'),selected,exported;const controls={},adapters=[],identity={...e,kind:demo?'synthetic':'market'},c=core(['lib/holdings-account-risk.js','lib/holdings-forecast-storage.js','holdings/strategy-view.js'],{Date:class extends Date{static now(){return clock;}},localStorage:{getItem:k=>local.get(k)??null,setItem:(k,v)=>{if(quota)throw Error('Quota exceeded');local.set(k,v);}},T212Snapshot:{read:()=>selected},document:{querySelectorAll:q=>controls[q]||[]},HoldingsNeuralUI:{refresh(){},exportReport:r=>exported=r}});
 if(durable){const create=c.HoldingsForecastStorage.create;c.HoldingsForecastStorage.create=(legacy,options)=>{const a=create(legacy,{...options,durable});adapters.push(a);return a;};}
 for(const file of ['holdings/account-risk.js','holdings/strategy.js','holdings/forecast.js'])vm.runInContext(readFileSync(file,'utf8'),c);
 const x=fixture(c,{identity}),p={ticker:e.ticker,quantity:10,currentPrice:100,instrumentCurrency:'USD',currency:'USD',value:1000},snapshot={environment:demo?'synthetic':'live',fetchedAt:new Date(clock).toISOString(),summary:{currency:'USD',totalValue:10000,available:9000,reserved:0,invested:1000},positions:[p]},notes={[p.ticker]:{stop:95,stopCurrency:'USD'}},ctx={scope:e.scope,demo,positions:[p],snapshot,symbol:()=>e.symbol,model:()=>({currency:'USD',asOf:x.original.source.asOf,price:100,atrPct:2,bars:[x.bars[0]]}),note:p=>notes[p.ticker]||{}};selected=[e.scope,snapshot];c.HoldingsForecastUI.setContext(ctx);
 const R=c.HoldingsAccountRisk,UI=c.HoldingsAccountRiskUI,S=c.HoldingsStrategy,limits={version:R.SETTINGS,perDecisionPct:1,totalStopPct:5,instrumentPct:30};
 function capture(a=x){return c.HoldingsForecastUI.captureVerdict(p,{version:c.HoldingsForecast.VERSIONS.verdict,symbol:e.symbol,currency:'USD',kind:identity.kind,asOf:a.original.source.asOf,generatedAt:clock,available:7,total:7,state:a.input.state,...a.input.estimate,cards:a.input.estimate.cards.map(r=>({...r,available:true}))},{symbol:e.symbol,currency:'USD',kind:identity.kind,...a.original.source,fingerprint:'test-fingerprint'});}
 function button(attr){const b={dataset:{[attr.replace(/-([a-z])/g,(_,s)=>s.toUpperCase())]:'0'}};controls['[data-'+attr+']']=[b];UI.bind();return b;}
 return {c,R,UI,S,x,p,ctx,snapshot,notes,identity,local,controls,adapters,limits,capture,button,restore:()=>c.HoldingsForecastUI.restore(p),select:a=>selected=a,setNow:t=>clock=t,exported:()=>exported};
}
test('a newly saved final verdict freezes a separate account check without altering the strategy',async()=>{const a=setup();await a.restore();a.UI.saveSettings(a.p,a.limits);const out=a.capture();assert.equal(out.strategy.saved,true);assert.equal(out.strategy.risk.saved,true);assert.equal(out.strategy.risk.state,'within-limits');const r=a.UI.current(a.p,a.x.trial);assert.equal(r.entries.length,1);assert.equal(r.entries[0].input.snapshot.summary.available,9000);const strategy=a.c.HoldingsStrategyUI.snapshot(a.p).entries[0];assert.deepEqual(plain(strategy),plain(a.x.trial));a.snapshot.summary.available=0;assert.equal(a.capture().duplicate,true);assert.equal(a.UI.current(a.p,strategy).entries[0].input.snapshot.summary.available,9000);assert.equal(a.UI.current(a.p,strategy).result.state,'blocked');});
test('existing strategy history is not backfilled by opening the new panel or recalculating settings',async()=>{const a=setup();await a.restore();a.local.set(a.S.key(a.identity),JSON.stringify({version:a.S.VERSION,entries:[a.x.trial]}));a.UI.markup(a.p,0,a.x.trial);a.UI.saveSettings(a.p,a.limits);assert.equal(a.UI.current(a.p,a.x.trial).entries.length,0);assert.equal(a.c.HoldingsStrategyUI.capture(a.p,a.x.original).duplicate,true);assert.equal(a.UI.current(a.p,a.x.trial).entries.length,0);});
test('settings use account and wallet currency while risk identity uses instrument currency',async()=>{const a=setup();await a.restore();a.UI.saveSettings(a.p,a.limits);a.capture();const original=a.local.get(a.R.key(a.identity));a.snapshot.summary.currency='EUR';a.snapshot.summary.invested=900;a.snapshot.summary.available=9100;a.snapshot.positions[0].currency='EUR';a.snapshot.positions[0].value=900;assert.equal(a.UI.current(a.p,a.x.trial).input.settings.perDecisionPct,null);a.UI.saveSettings(a.p,{...a.limits,perDecisionPct:.3});assert.equal(JSON.parse(a.local.get(a.R.settingsKey(a.identity,'USD'))).perDecisionPct,1);assert.equal(JSON.parse(a.local.get(a.R.settingsKey(a.identity,'EUR'))).perDecisionPct,.3);assert.equal(a.local.get(a.R.key(a.identity)),original);assert.equal(a.UI.current(a.p,a.x.trial).identity.currency,'USD');});
test('active account changes never read the archived snapshot or permit a mismatched capture',async()=>{const a=setup();await a.restore();a.UI.saveSettings(a.p,a.limits);a.select(['another',{...a.snapshot,positions:null}]);const out=a.capture();assert.equal(out.strategy.risk.state,'incomplete');const frozen=a.UI.current(a.p,a.x.trial).entries[0];assert.equal(frozen.input.accountMatches,false);assert.equal(frozen.input.snapshot,null);assert.equal(frozen.result.totalStopRisk,null);a.c.HoldingsForecastUI.setContext({...a.ctx,scope:'another'});assert.equal(a.UI.capture(a.p,a.x.trial,{identity:a.identity}).ok,false);assert.equal(a.local.has(a.R.key({...a.identity,scope:'another'})),false);});
test('unconfirmed historical stops remain unknown until the user saves their currency explicitly',async()=>{const a=setup();delete a.notes[e.ticker].stopCurrency;await a.restore();a.UI.saveSettings(a.p,a.limits);const out=a.capture();assert.equal(out.strategy.risk.state,'incomplete');a.notes[e.ticker].stopCurrency='USD';const now=a.UI.current(a.p,a.x.trial);assert.equal(now.result.state,'within-limits');assert.equal(now.entries[0].result.state,'incomplete');});
test('numeric drafts survive UI refresh and invalid saves preserve the existing limits',async()=>{const a=setup();await a.restore();a.UI.saveSettings(a.p,a.limits);const input={dataset:{riskIndex:'0',riskField:'perDecisionPct'},value:'.5'};a.controls['[data-risk-field]']=[input];a.UI.bind();input.oninput();assert.match(a.UI.markup(a.p,0,a.x.trial),/data-risk-field="perDecisionPct" value="0.5"/);a.button('risk-save').onclick();assert.equal(a.UI.current(a.p,a.x.trial).input.settings.perDecisionPct,.5);input.value='-1';input.oninput();a.button('risk-save').onclick();assert.equal(a.UI.current(a.p,a.x.trial).input.settings.perDecisionPct,.5);assert.match(a.UI.markup(a.p,0,a.x.trial),/mai mare decât zero/);});
test('corrupt risk histories and settings are preserved with actionable errors',async()=>{const a=setup();await a.restore();a.local.set(a.R.key(a.identity),'{broken');const out=a.capture();assert.equal(out.strategy.saved,true);assert.equal(out.strategy.risk.ok,false);assert.equal(a.local.get(a.R.key(a.identity)),'{broken');assert.equal(a.UI.current(a.p,a.x.trial).ok,false);const b=setup();await b.restore();const k=b.R.settingsKey(b.identity,'USD');b.local.set(k,'{bad');assert.equal(b.UI.saveSettings(b.p,b.limits).ok,false);assert.equal(b.local.get(k),'{bad');});
test('explicit exports use the risk filename/type and demo controls cannot write to real account data',()=>{const a=setup({demo:true});assert.equal(a.UI.simulation(a.p),true);const x=a.UI.current(a.p,a.x.trial);assert.equal(x.entries.length,1);assert.equal(x.entries[0].result.state,'within-limits');assert.equal(a.local.size,0);assert.match(a.UI.markup(a.p,0,a.x.trial),/sold, poziții, stopuri, limite și verdict inventate/);a.button('risk-export').onclick();assert.equal(a.exported().result.version,a.R.VERSION);assert.doesNotMatch(JSON.stringify(a.exported()),/private-account|apiKey|scope/);a.c.HoldingsForecastUI.setContext({...a.ctx,demo:false});assert.equal(a.UI.simulation(a.p),false);assert.equal(a.local.size,0);});
function persistence(){const saved=new Map();return {saved,get:async k=>saved.get(k)??null,write:async changes=>{const staged=new Map();for(const c of changes){let value=c.value,before=saved.get(c.key)??null;if(typeof c.merge==='function')value=c.merge(before,value,c.key);else if(before!==c.before)throw Error('Conflict');staged.set(c.key,value);}for(const [k,v] of staged)saved.set(k,v);return staged;}};}
test('full localStorage retains risk checks and settings durably and a new page restores them',async()=>{const db=persistence(),a=setup({durable:db,quota:true});await a.restore();a.UI.saveSettings(a.p,a.limits);assert.equal(a.capture().strategy.risk.saved,true);for(const adapter of a.adapters)await adapter.settled();assert.equal(a.local.size,0);assert.equal(JSON.parse(db.saved.get(a.R.key(a.identity))).entries.length,1);const b=setup({durable:db,quota:true});await b.restore();const r=b.UI.current(b.p,b.x.trial);assert.equal(r.storage.state,'indexeddb');assert.equal(r.entries[0].result.state,'within-limits');assert.equal(r.input.settings.perDecisionPct,1);});
test('failed durable writes leave the frozen risk check exportable and explicitly session-only',async()=>{const db=persistence(),a=setup({durable:db});await a.restore();db.write=async()=>{throw Error('Aborted');};a.UI.saveSettings(a.p,a.limits);assert.equal(a.capture().strategy.risk.saved,true);for(const adapter of a.adapters)await adapter.settled();assert.equal(a.UI.current(a.p,a.x.trial).storage.state,'session');a.button('risk-export').onclick();assert.equal(a.exported().result.entries.length,1);assert.match(a.UI.markup(a.p,0,a.x.trial),/doar în această sesiune/);});
test('two pages retain the first frozen check and union subsequent decisions without settings conflicts',async()=>{const db=persistence(),a=setup({durable:db}),b=setup({durable:db});await a.restore();await b.restore();a.capture();for(const adapter of a.adapters)await adapter.settled();b.snapshot.summary.available=0;b.capture();for(const adapter of b.adapters)await adapter.settled();const key=a.R.key(a.identity),rows=JSON.parse(db.saved.get(key)).entries;assert.equal(rows.length,1);assert.equal(rows[0].input.snapshot.summary.available,9000);const next=fixture(a.c,{identity:a.identity,day:'2026-09-21'});b.setNow(next.capturedAt);b.snapshot.fetchedAt=new Date(next.capturedAt).toISOString();assert.equal(b.UI.capture(b.p,next.trial,{now:next.capturedAt}).saved,true);for(const adapter of b.adapters)await adapter.settled();assert.equal(JSON.parse(db.saved.get(key)).entries.length,2);});
test('dependencies, currency binding and export formatting are wired into the actual page',()=>{const html=readFileSync('holdings/index.html','utf8'),neural=readFileSync('holdings/neural.js','utf8'),holdings=readFileSync('holdings/holdings.js','utf8');assert.ok(html.indexOf('src="../lib/holdings-account-risk.js')<html.indexOf('src="account-risk.js'));assert.ok(html.indexOf('src="account-risk.js')<html.indexOf('src="strategy.js'));assert.match(holdings,/stopCurrency:p.instrumentCurrency/);assert.match(readFileSync('holdings/account-risk.js','utf8'),/account-risk" tabindex="-1"/);assert.match(neural,/risc-cont-ai-/);assert.match(neural,/'data-risk-field'/);});
