import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const now=Date.parse('2026-10-04T17:00:00Z'),t=Date.parse('2026-10-02T13:30:00Z'),plain=x=>JSON.parse(JSON.stringify(x));
function setup({demo=false,corrupt=false}={}){
 const writes=new Map(),buttons={},core={Date:class extends Date{static now(){return now;}}};vm.createContext(core);for(const path of ['lib/daily-series.js','lib/holdings-neural.js','lib/holdings-forecast.js'])vm.runInContext(readFileSync(path,'utf8'),core);
 let exports=null,refreshes=0,fetches=0,resolveFetch,rejectFetch;
 const bar={t,o:100,h:102,l:99,c:100,v:10000},p={ticker:'TEST_US_EQ',instrumentCurrency:'USD',apiKey:'SECRET',quantity:999};
 const record={symbol:'TEST',currency:'USD',kind:demo?'synthetic':'market',asOf:'2026-10-02',sourceTime:t,sourceClose:100,timezone:'America/New_York',closeMinutes:960,trainedAt:now-1000};
 const neural={usable:true,assessment:{state:'no-edge'},comparison:{state:'no-edge'},record:{...record,result:{version:'holdings-mlp-v3',latest:[0,0,0,0,0,0,0,50,2,1],classIndex:2,report:{train:{confusion:[[2,3,5],[6,7,9],[1,2,4]]}},comparison:{boosting:{version:'holdings-gbt-v1',classIndex:0}}}}};
 const quantile={usable:true,assessment:{state:'no-edge'},record:{...record,result:{version:'holdings-quantile-v1',current:{t,close:100,atrPct:2,x:[],prices:[98,101,104]},baseline:{},baselineCalibration:{delta:0}}}};
 const hmm={usable:true,assessment:{state:'transition'},record:{...record,result:{version:'holdings-hmm-v1',current:{state:0},latest:[1,1,2],profiles:[{state:0,label:'Ascendent',means:[1,1,2]}]}}};
 const isolation={usable:true,assessment:{state:'ordinary'},record:{...record,result:{version:'holdings-isolation-v1',current:{score:.4,votes:0},threshold:.6}}};
 const sandbox={...core,Date:core.Date,HoldingsNeuralUI:{inspect:()=>neural,refresh:()=>refreshes++,exportReport:r=>exports=r},HoldingsQuantile:{predict:()=>[-2,0,2]},HoldingsQuantileUI:{inspect:()=>quantile},HoldingsHMMUI:{inspect:()=>hmm},HoldingsIsolationUI:{inspect:()=>isolation},DailySeries:{...core.DailySeries,read:()=>({bars:[bar],timezone:'America/New_York',closeMinutes:960,asOf:'2026-10-02',currency:'USD'})},localStorage:{getItem:k=>writes.get(k),setItem:(k,v)=>writes.set(k,v)},D:{fetchStock:(symbol,options)=>{fetches++;assert.equal(symbol,'TEST');assert.deepEqual(plain(options),{range:'5y',interval:'1d',ttl:0});return new Promise((resolve,reject)=>{resolveFetch=resolve;rejectFetch=reject;});}},document:{querySelectorAll:q=>buttons[q]||[]}};
 vm.createContext(sandbox);vm.runInContext(readFileSync('holdings/forecast.js','utf8'),sandbox);const ui=sandbox.HoldingsForecastUI,c={scope:'a',demo,positions:[p],symbol:()=> 'TEST',model:()=>({currency:'USD',asOf:'2026-10-02',price:100,atrPct:2,bars:[bar],closeMinutes:960})},e={scope:'a',ticker:p.ticker,symbol:'TEST',currency:'USD',kind:demo?'synthetic':'market'};ui.setContext(c);
 if(corrupt)writes.set(core.HoldingsForecast.key(e),'{broken');
 function button(attr){const b={dataset:{[attr.replace(/-([a-z])/g,(_,s)=>s.toUpperCase())]:'0'}};buttons['[data-'+attr+']']=[b];ui.bind();return b;}
 return {ui,c,p,e,writes,core,sandbox,neural,quantile,hmm,isolation,button,exports:()=>exports,refreshes:()=>refreshes,fetches:()=>fetches,resolve:()=>resolveFetch?.([]),reject:()=>rejectFetch?.(Error('offline'))};
}
test('successful model inspections produce five separate first forecasts without account fields',()=>{const s=setup();s.ui.capture(s.p);const d=s.core.HoldingsForecast.createStore({getItem:k=>s.writes.get(k)}).read(s.e);assert.equal(d.ok,true);assert.equal(d.entries.length,5);assert.ok(!/SECRET|apiKey|quantity/.test(JSON.stringify(d)));assert.equal(d.entries.find(r=>r.model==='neural').estimate.baselineClass,1);});
test('reanalyzing the same EOD cannot replace the original direction or interval',()=>{const s=setup();s.ui.capture(s.p);s.neural.record.result.classIndex=0;s.quantile.record.result.current.prices=[95,100,108];s.ui.capture(s.p);const d=JSON.parse(s.writes.get(s.core.HoldingsForecast.key(s.e)));assert.equal(d.entries.length,5);assert.equal(d.entries.find(r=>r.model==='neural').estimate.classIndex,2);assert.deepEqual(d.entries.find(r=>r.model==='quantile').estimate.prices,[98,101,104]);});
test('drifted forecasts remain absent from the performance registry',()=>{const s=setup();s.neural.assessment.state='drift';s.quantile.assessment.state='drift';s.ui.capture(s.p);const d=JSON.parse(s.writes.get(s.core.HoldingsForecast.key(s.e)));assert.deepEqual(d.entries.map(r=>r.model),['hmm','isolation']);});
test('legacy Neural results lacking verified close metadata are not backfilled',()=>{const s=setup();delete s.neural.record.sourceTime;s.ui.capture(s.p);const d=JSON.parse(s.writes.get(s.core.HoldingsForecast.key(s.e)));assert.ok(!d.entries.some(r=>r.model==='neural'||r.model==='boosting'));});
test('save controls rebuild the current account identity at click time',()=>{const s=setup(),b=s.button('forecast-save');s.ui.setContext({...s.c,scope:'b'});b.onclick();assert.equal(s.writes.has(s.core.HoldingsForecast.key(s.e)),false);assert.equal(s.writes.has(s.core.HoldingsForecast.key({...s.e,scope:'b'})),true);});
test('demo storage never writes to localStorage and synthetic examples are explicitly illustrative',()=>{const s=setup({demo:true});s.ui.capture(s.p);s.ui.simulation(s.p);assert.equal(s.writes.size,0);const html=s.ui.markup(s.p,0);assert.match(html,/estimările.*ilustrative/);assert.match(html,/24 orizonturi separate/);assert.match(html,/Regresie cu cuantile/);});
test('simulation does not duplicate observations when loaded again',()=>{const s=setup({demo:true});s.ui.simulation(s.p);const a=s.ui.markup(s.p,0);s.ui.simulation(s.p);const b=s.ui.markup(s.p,0);assert.match(a,/Registrul estimărilor · 120/);assert.match(b,/Registrul estimărilor · 120/);});
test('private account data and fitted weights never enter exported registry',()=>{const s=setup();s.ui.capture(s.p);s.button('forecast-export').onclick();const r=s.exports();assert.equal(r.result.version,'holdings-forecast-v1');assert.equal(r.result.entries.length,5);assert.ok(!/SECRET|apiKey|quantity|committee|w1/.test(JSON.stringify(r)));});
test('corrupt registry survives save and export actions without fabricated results',()=>{const s=setup({corrupt:true});s.ui.capture(s.p);s.button('forecast-export').onclick();assert.equal(s.exports(),null);assert.equal(s.writes.get(s.core.HoldingsForecast.key(s.e)),'{broken');assert.match(s.ui.markup(s.p,0),/Registru ilizibil/);});
test('selected model filter changes the ledger rows through actual control handlers',()=>{const s=setup({demo:true});s.ui.simulation(s.p);const b=s.button('forecast-model');b.value='hmm';b.onchange();const html=s.ui.markup(s.p,0);assert.match(html,/value="hmm" selected/);assert.match(html,/observație de preț/);});
test('an account change during public fetch cannot write the prior or next account',async()=>{const s=setup();s.ui.capture(s.p);const before=s.writes.get(s.core.HoldingsForecast.key(s.e)),pending=s.ui.check(s.p,true);s.ui.setContext({...s.c,scope:'b'});s.resolve();await pending;assert.equal(s.writes.get(s.core.HoldingsForecast.key(s.e)),before);assert.equal(s.writes.has(s.core.HoldingsForecast.key({...s.e,scope:'b'})),false);});
test('one automatic attempt per EOD avoids repeated fetches; manual retry remains possible',async()=>{const s=setup();s.ui.capture(s.p);s.c.model=()=>({currency:'USD',asOf:'2026-10-05'});let pending=s.ui.check(s.p);assert.equal(s.fetches(),1);s.resolve();await pending;await s.ui.check(s.p);assert.equal(s.fetches(),1);pending=s.ui.check(s.p,true);assert.equal(s.fetches(),2);s.resolve();await pending;});
test('model completion hooks record snapshots and the module loads before Neural UI',()=>{for(const file of ['neural','hmm','isolation','quantile'])assert.match(readFileSync('holdings/'+file+'.js','utf8'),/HoldingsForecastUI\?\.capture/);const html=readFileSync('holdings/index.html','utf8');assert.ok(html.indexOf('src="forecast.js')<html.indexOf('src="neural.js'));});

test('listing currency never falls back to the account wallet currency',()=>{const s=setup();s.c.model=()=>null;delete s.p.instrumentCurrency;s.p.currency='EUR';const snapshot=s.ui.snapshot(s.p);assert.equal(snapshot.identity.currency,undefined);assert.equal(snapshot.ledger.ok,false);assert.equal(s.writes.size,0);});
test('portfolio snapshot reports an unsuccessful verification without deleting saved forecasts',async()=>{const s=setup();s.ui.capture(s.p);const before=s.ui.snapshot(s.p).ledger.entries.length,pending=s.ui.check(s.p,true);assert.equal(s.ui.snapshot(s.p).check.state,'checking');s.reject();const result=await pending;assert.equal(result.state,'error');const snapshot=s.ui.snapshot(s.p);assert.equal(snapshot.ledger.entries.length,before);assert.ok(snapshot.ledger.entries.every(r=>r.verification.state==='pending'));assert.equal(snapshot.check.state,'error');});
