import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const c={};vm.createContext(c);vm.runInContext(readFileSync('lib/holdings-neural.js','utf8'),c);const N=c.HoldingsNeural,plain=x=>JSON.parse(JSON.stringify(x));
const rows=Array.from({length:600},(_,i)=>({t:i*86400000,end:(i+5)*86400000,x:[Math.sin(i),Math.cos(i),0,0,0,0,0,50,2,1],y:i%3}));let fitted;
test('early stopping and score adjustment have purged, chronologically separate labels',()=>{const p=N.split(rows),v=N.validationParts(p.validation);assert.ok(v.earlyStopping.every(r=>r.end<v.calibration[0].t));assert.ok(v.calibration.every(r=>r.end<p.test[0].t));assert.ok(v.earlyStopping.length<v.calibration.length*2);});
test('temperature reduces excessive confidence on its separate adjustment set without changing classes',()=>{const net=plain(N.network(12,1));net.w1=net.w1.map(row=>row.map(()=>0));net.w2=net.w2.map(row=>row.map(()=>0));net.b1=net.b1.map(()=>0);net.b2=[-6,0,6];const committee=[net,net,net],r=N.selectTemperature(rows.slice(0,60),committee);assert.equal(r.temperature,3);assert.ok(r.candidates.at(-1).loss<r.candidates[0].loss);const raw=N.ensemble(committee,rows[0].x),adjusted=N.soften(raw,3);assert.equal(raw.indexOf(Math.max(...raw)),adjusted.indexOf(Math.max(...adjusted)));assert.ok(Math.max(...adjusted)<Math.max(...raw));assert.ok(Math.abs(adjusted.reduce((a,b)=>a+b,0)-1)<1e-10);});
test('too few calibration classes cannot select a tuned temperature',()=>{const committee=[1,2,3].map(seed=>N.network(12,seed)),r=N.selectTemperature(rows.slice(0,50).map(x=>({...x,y:1})),committee);assert.equal(r.eligible,false);assert.equal(r.temperature,1);});
test('test labels do not choose network weights, scaling, epochs or temperature',()=>{const progress=[],p=N.split(rows);fitted=N.fitPartitions(p,rows.at(-1).x,{epochs:20,progress:x=>progress.push(x)});const altered={...p,test:p.test.map(r=>({...r,y:(r.y+1)%3}))},other=N.fitPartitions(altered,rows.at(-1).x,{epochs:20});assert.ok(N.valid(fitted));for(const k of ['committee','scale','memberEpochs','adjustment','support'])assert.deepEqual(plain(fitted[k]),plain(other[k]));assert.deepEqual([...new Set(progress.map(p=>p.member))],[1,2,3]);assert.notEqual(fitted.report.test.loss,other.report.test.loss);});
test('saved ensembles reject missing members and falsified score-adjustment metadata',()=>{for(const mutate of [r=>r.committee.pop(),r=>r.committee[1].w2[0].push(0),r=>r.adjustment.temperature=4,r=>r.adjustment.calibration.from=r.adjustment.earlyStopping.lastLabel,r=>r.adjustment.adjusted.loss+=.1,r=>r.disagreement.votes[0]+=1,r=>r.regularization=0]){const r=plain(fitted);mutate(r);assert.equal(N.valid(r),false);}const old=plain(fitted);old.version='holdings-mlp-v2';assert.equal(N.valid(old),false);});
test('three different class votes block interpretation even when cached evidence claims advantage',()=>{const r=plain(fitted);r.committee.forEach((net,k)=>{net.w1=net.w1.map(row=>row.map(()=>0));net.w2=net.w2.map(row=>row.map(()=>0));net.b1=net.b1.map(()=>0);net.b2=[0,0,0];net.b2[k]=4;});r.network=r.committee[0];const z=N.normalize(r.latest,r.scale);r.support=plain(N.predict(r,z));r.classIndex=r.support.indexOf(Math.max(...r.support));r.disagreement=plain(N.disagreement(r.committee,z));assert.deepEqual(r.disagreement.votes,[1,1,1]);assert.ok(N.valid(r));const now=Date.now();assert.equal(N.assess({symbol:'TEST',currency:'USD',kind:'market',asOf:'2026-10-02',trainedAt:now,result:r},{symbol:'TEST',currency:'USD',asOf:'2026-10-02',demo:false,now}).state,'disagreement');});
