import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {core,e,fixture} from './holdings-strategy-fixtures.mjs';
const tick=()=>new Promise(r=>setImmediate(r));
async function setup({active='b',demo=false,scopes=['a','b'],delay=false}={}){
 const local=new Map(),saved=new Map(),selectors={'[data-strategy-account]':{value:''},'[data-strategy-reload]':{}},host={innerHTML:'',querySelector:q=>selectors[q]};let writes=0,reads=0,release;
 const c=core(['lib/holdings-strategy-demo.js','holdings/strategy-view.js','lib/trading212-snapshot.js'],{URLSearchParams,location:{search:demo?'?aiStrategyDemo=1':''},document:{getElementById:()=>host,addEventListener(){}},localStorage:{getItem:k=>local.get(k)??null,setItem(){writes++;throw Error('Read-only');}},HoldingsForecastStorage:{indexedStore:()=>({get:async k=>{reads++;if(delay&&k!==c.HoldingsStrategy.DIRECTORY){delay=false;await new Promise(resolve=>release=resolve);}return saved.get(k)??null;}})}});
 const S=c.HoldingsStrategy,identities=scopes.map((scope,i)=>({...e,scope,kind:'market',symbol:'TEST'+i}));saved.set(S.DIRECTORY,JSON.stringify({version:S.VERSION,identities}));for(const identity of identities){const x=fixture(c,{identity});saved.set(S.key(identity),JSON.stringify({version:S.VERSION,entries:[x.resolve()]}));}
 const selectAccount=value=>{if(value===null)local.delete('tt_trading212_portfolio_v1');else local.set('tt_trading212_portfolio_v1',JSON.stringify({[value]:{environment:'live',active:true,fetchedAt:new Date().toISOString()}}));};selectAccount(active);
 vm.runInContext(readFileSync('shadow-book/ai-strategy.js','utf8'),c);await tick();return {c,host,selectors,local,saved,selectAccount,release:()=>release?.(),writes:()=>writes,reads:()=>reads};
}
test('the active partial Invest account selects its own registry, with no fallback or account identifier in the view',async()=>{const s=await setup();assert.match(s.host.innerHTML,/TEST1 · USD/);assert.doesNotMatch(s.host.innerHTML,/TEST0 · USD/);assert.match(s.host.innerHTML,/Cont Invest selectat/);assert.equal(s.writes(),0);s.selectors['[data-strategy-account]'].value='0';s.selectors['[data-strategy-account]'].onchange();await tick();assert.match(s.host.innerHTML,/TEST0 · USD/);assert.doesNotMatch(s.host.innerHTML,/TEST1 · USD/);assert.equal(s.writes(),0);});
test('an untracked selected account and multiple registries without an account require an explicit choice',async()=>{for(const active of ['untracked',null]){const s=await setup({active});assert.match(s.host.innerHTML,/Selectează explicit/);assert.doesNotMatch(s.host.innerHTML,/TEST[01] · USD/);}});
test('an account change while the durable read is pending retries before showing stale account results',async()=>{const s=await setup({active:'a',delay:true});assert.equal(s.host.innerHTML,'');s.selectAccount('b');s.release();await tick();await tick();assert.match(s.host.innerHTML,/TEST1 · USD/);assert.doesNotMatch(s.host.innerHTML,/TEST0 · USD/);});
test('the explicit Shadow demo uses no stored account registry and writes nothing',async()=>{const s=await setup({demo:true});assert.equal(s.reads(),0);assert.equal(s.writes(),0);assert.match(s.host.innerHTML,/verdicte inventate/);assert.match(s.host.innerHTML,/12 orizonturi separate/);assert.match(s.host.innerHTML,/8 poziții simulate/);});
test('an unreadable registry is reported without erasing it or showing a partial performance claim',async()=>{const s=await setup();const identity=s.c.HoldingsStrategy.directory(s.saved.get(s.c.HoldingsStrategy.DIRECTORY)).identities[1],k=s.c.HoldingsStrategy.key(identity);s.saved.set(k,'{broken');await s.c.ShadowAIStrategy.render();assert.match(s.host.innerHTML,/registru indisponibil/);assert.equal(s.saved.get(k),'{broken');assert.equal(s.writes(),0);assert.doesNotMatch(s.host.innerHTML,/Rezultat net/);});
