import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const at='2026-10-08T15:00:00Z',now=Date.parse(at),p={ticker:'A',quantity:2,averagePrice:120,currentPrice:100,instrumentCurrency:'USD',currency:'USD',unrealized:-45},n={stop:90,stopCurrency:'USD',targetPrice:115,targetCurrency:'USD'},m={price:102,currency:'USD',asOf:'2026-10-07',support:95,resistance:110};
const opts=extra=>({scope:'account-a',at,now,totalValue:1000,accountCurrency:'USD',...extra});
function setup(){const s={Intl,Date};vm.runInNewContext(readFileSync('lib/holding-scenarios.js','utf8'),s);return s.HoldingScenarios;}
test('price change, price-only P&L and reported broker P&L remain distinct',()=>{const S=setup(),r=S.build(p,n,m,opts({mode:'custom',price:90}));assert.equal(r.change,-20);assert.equal(r.pricePnl,-60);assert.equal(r.brokerPnl,-65);assert.equal(r.impactPct,-2);assert.equal(p.unrealized,-45);});
test('a personal target can reduce a loss without recovering the average cost',()=>{const S=setup(),r=S.build(p,n,m,opts({mode:'target'}));assert.equal(r.price,115);assert.equal(r.change,30);assert.equal(r.pricePnl,-10);assert.equal(r.brokerPnl,-15);assert.equal(r.risk,20);assert.equal(r.reward,30);assert.equal(r.ratio,1.5);assert.match(S.markup(p,n,m,opts()),/raportul dintre ele/);});
test('cost recovery is not falsely labelled a net broker profit',()=>{const r=setup().build(p,n,m,opts({mode:'average'}));assert.equal(r.pricePnl,0);assert.equal(r.brokerPnl,-5);});
test('fractional quantities scale monetary outcomes without rounding quantity to whole shares',()=>{const r=setup().build({...p,quantity:.125,unrealized:-2.5},n,m,opts({mode:'custom',price:90}));assert.equal(r.change,-1.25);assert.equal(r.pricePnl,-3.75);assert.equal(r.brokerPnl,-3.75);});
test('foreign quote and account currencies never produce an invented conversion or portfolio impact',()=>{const r=setup().build({...p,currency:'EUR'},n,m,opts({mode:'target',accountCurrency:'EUR'}));assert.equal(r.change,30);assert.equal(r.pricePnl,-10);assert.equal(r.brokerPnl,null);assert.equal(r.impactPct,null);assert.match(r.brokerReason,/USD \/ EUR/);});
test('pence and GBX keep their denomination while pounds cannot be mixed into P&L',()=>{const S=setup(),q={...p,instrumentCurrency:'GBp',currency:'GBP'},notes={...n,stopCurrency:'GBX',targetCurrency:'GBX'},r=S.build(q,notes,null,opts({mode:'stop',accountCurrency:'GBP'}));assert.equal(r.change,-20);assert.equal(r.reference.currency,'GBp');assert.equal(r.brokerPnl,null);assert.equal(r.impactPct,null);assert.equal(S.build(q,{...notes,stopCurrency:'GBP'},null,opts({mode:'stop'})).price,null);});
test('missing average cost does not hide a valid price change or broker P&L scenario',()=>{const S=setup();for(const averagePrice of [null,0,NaN,'120']){const r=S.build({...p,averagePrice},n,m,opts({mode:'target'}));assert.equal(r.pricePnl,null);assert.equal(r.change,30);assert.equal(r.brokerPnl,-15);}});
test('unknown reported P&L never becomes zero, while an actual zero remains eligible',()=>{const S=setup();for(const unrealized of [null,undefined,NaN,'0'])assert.equal(S.build({...p,unrealized},n,m,opts({mode:'target'})).brokerPnl,null);assert.equal(S.build({...p,unrealized:0},n,m,opts({mode:'target'})).brokerPnl,30);});
test('stale broker prices stay explicitly dated and block extrapolated account P&L and impact',()=>{const S=setup(),r=S.build(p,n,m,opts({now:now+600000,mode:'stop'}));assert.equal(r.reference.kind,'broker');assert.equal(r.reference.stale,true);assert.equal(r.change,-20);assert.equal(r.brokerPnl,null);assert.equal(r.impactPct,null);assert.match(S.markup(p,n,m,opts({now:now+600000})),/DATE VECHI/);});
test('future and invalid quote timestamps fall back only to supplied compatible EOD and never mix its price with broker P&L',()=>{const S=setup();for(const at of [null,'broken','2099-01-01T00:00:00Z']){const r=S.build(p,n,m,opts({at,mode:'target'}));assert.equal(r.reference.kind,'eod');assert.equal(r.change,26);assert.equal(r.brokerPnl,null);assert.equal(r.impactPct,null);assert.equal(S.build(p,n,{...m,currency:'EUR'},opts({at,mode:'target'})).reference,null);}});
test('invalid, zero or missing quantities and hypothetical prices block calculations',()=>{const S=setup();for(const quantity of [0,-1,null,NaN,'2'])assert.equal(S.build({...p,quantity},n,m,opts({mode:'target'})).change,null);for(const price of ['',0,-1,null,NaN,Infinity,[],true,'broken']){const r=S.build(p,n,m,opts({mode:'custom',price}));assert.equal(r.change,null);assert.equal(r.brokerPnl,null);}});
test('a crossed or equal stop cannot manufacture a positive risk or infinite reward ratio',()=>{const S=setup();for(const stop of [100,101]){const r=S.build(p,{...n,stop},m,opts({mode:'stop'}));assert.equal(r.ratio,null);assert.equal(r.risk,null);assert.match(r.warning,/deja atins/);assert.match(r.ratioReason,/risc viitor/);}});
test('targets at or below reference cannot produce a valid future reward ratio',()=>{const S=setup();for(const targetPrice of [100,99]){const r=S.build(p,{...n,targetPrice},m,opts({mode:'target'}));assert.equal(r.ratio,null);assert.equal(r.reward,null);assert.match(r.warning,/Ținta este deja/);}});
test('unverified level currencies disable personal and technical presets independently',()=>{const S=setup(),r=S.levels(p,{...n,stopCurrency:null,targetCurrency:'EUR'},{...m,currency:'EUR'},opts());assert.equal(r.values.stop,null);assert.equal(r.values.target,null);assert.equal(r.values.support,null);assert.equal(r.values.resistance,null);assert.equal(r.values.average,120);});
test('quick scenarios are relative to the current reference, including a genuine zero change',()=>{const S=setup();for(const shock of [-10,0,10]){const r=S.build(p,n,m,opts({mode:'shock',shock}));assert.ok(Math.abs(r.price-(100+shock))<1e-9);assert.ok(Math.abs(r.change-2*shock)<1e-9);}assert.equal(S.build(p,n,m,opts({mode:'shock',shock:-100})).change,null);});
test('numeric overflow is rejected rather than displayed as profit or an infinite ratio',()=>{const S=setup(),r=S.build({...p,quantity:1e308},n,m,opts({mode:'target'}));assert.equal(r.change,null);assert.equal(r.brokerPnl,null);assert.match(r.reason,/limitele/);assert.doesNotMatch(S.markup({...p,quantity:1e308},n,m,opts()),/Infinity|NaN/);});
test('broker freshness boundaries are consistent at five minutes and one minute into the future',()=>{const S=setup();assert.notEqual(S.build(p,n,m,opts({now:now+300000,mode:'target'})).brokerPnl,null);assert.equal(S.build(p,n,m,opts({now:now+300001,mode:'target'})).brokerPnl,null);assert.equal(S.reference(p,m,opts({at:new Date(now+60000).toISOString()})).kind,'broker');assert.equal(S.reference(p,m,opts({at:new Date(now+60001).toISOString()})).kind,'eod');});
test('escaped labels and explicit simulation markers prevent source markup injection',()=>{const S=setup(),html=S.markup({...p,ticker:'<img onerror=x>'},n,m,opts({simulated:true}));assert.doesNotMatch(html,/<img/);assert.match(html,/&lt;img/);assert.match(html,/DATE FICTIVE/);assert.match(html,/aria-label="Preț ipotetic"/);assert.match(html,/Variații rapide/);});
test('live edits preserve the input node, disclosure and custom price through snapshot updates and isolate account preferences',()=>{
 const S=setup(),html=S.markup(p,n,m,opts()),input={value:'90.125',matches:q=>q==='[data-scenario-price]'},select={value:''};let details={open:true};const result={set innerHTML(v){this.html=v;details={open:false};}},buttons=[-10,-5,0,5,10].map(v=>({dataset:{scenarioShock:String(v)},setAttribute(k,v){this[k]=v}})),key=JSON.stringify(['account-a','A','USD']);
 const host={dataset:{holdingScenario:key},innerHTML:html,contains:()=>true,querySelector:q=>q==='[data-scenario-price]'?input:q==='[data-scenario-mode]'?select:q==='[data-scenario-result]'?result:details,querySelectorAll:()=>buttons};S.bind({querySelectorAll:()=>[host]});host.oninput({target:input});assert.equal(host.innerHTML,html);assert.equal(input.value,'90.125');assert.equal(select.value,'custom');assert.equal(details.open,true);assert.match(S.markup({...p,currentPrice:105},n,m,opts()),/value="90.125"/);assert.doesNotMatch(S.markup(p,n,m,opts({scope:'account-b'})),/value="90.125"/);
 host.onclick({target:{closest:()=>buttons[2]}});assert.equal(input.value,'100');assert.equal(buttons[2]['aria-pressed'],'true');assert.equal(select.value,'shock');assert.equal(details.open,true);
});
