import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const c={Date};vm.createContext(c);for(const f of ['lib/holdings-intelligence.js','lib/execution-review.js'])vm.runInContext(readFileSync(f,'utf8'),c);const H=c.HoldingsIntelligence,F=c.ExecutionReview;
test('brief compares different completed sessions and warns on lost structure/support',()=>{const r=H.brief({asOf:'2026-10-02',price:90,medium:'Descendent',short:'Descendent',rvol:1.8,rs20:-2},{asOf:'2026-10-01',price:100,medium:'Ascendent',short:'Ascendent',support:95,rs20:1});assert.equal(r.baseline,true);assert.ok(Math.abs(r.delta+10)<1e-9);assert.equal(r.alerts.length,4);assert.equal(r.changes.length,2);assert.equal(H.brief({asOf:'2026-10-02'},{asOf:'2026-10-02'}).baseline,false);});
test('quality and structure expose missing fields rather than invented neutral values',()=>{const m={asOf:'2026-10-02',price:10,ema21:9,ema50:8};assert.equal(H.quality(m).score,33);assert.equal(H.structure(m).coverage,'3/6');assert.equal(H.structure(m).score,100);});
test('risk never adds different currency stop losses and exposes partial coverage',()=>{const r=H.risk([{ticker:'A',quantity:2,value:200,currency:'USD',instrumentCurrency:'USD',currentPrice:100},{ticker:'B',quantity:4,value:300,currency:'USD',instrumentCurrency:'EUR',currentPrice:50}],1000,'USD',{}, {A:{stop:90,sector:'Tech',earnings:'2026-10-05'},B:{stop:40}},Date.parse('2026-10-03T12:00Z'));assert.equal(r.knownStopRisk,20);assert.equal(r.stopCoverage,1);assert.equal(r.weightCoverage,2);assert.equal(r.earnings.length,1);assert.equal(r.sectors.Tech,20);});
test('correlation requires enough aligned returns and rejects constant series',()=>{const bars=Array.from({length:25},(_,i)=>({t:i,c:100+i+i%3}));assert.ok(H.correlation({bars},{bars}).value>.999);assert.equal(H.correlation({bars:bars.slice(0,10)},{bars}),null);assert.equal(H.correlation({bars:bars.map(x=>({...x,c:100}))},{bars}),null);});
const fill=(id,side,quantity,price,date='2026-10-02',priceCurrency='USD')=>({id,side,quantity,price,ticker:'A',date,priceCurrency});
test('FIFO handles partial entries/exits, dedupes fills and preserves open quantities',()=>{const r=F.fifo([fill('b1','BUY',2,10,'2026-09-30'),fill('b2','BUY',3,12,'2026-10-01'),fill('s1','SELL',4,15),fill('s1','SELL',4,15)]);assert.equal(r.matches.length,2);assert.equal(r.matches.reduce((s,x)=>s+x.gross,0),16);assert.equal(r.open[0].remaining,1);assert.equal(r.unmatched.length,0);});
test('FIFO never matches currencies or fabricated missing purchase history',()=>{const r=F.fifo([fill('b','BUY',2,10,'2026-09-30','EUR'),fill('s','SELL',3,15)]);assert.equal(r.matches.length,0);assert.equal(r.unmatched[0].quantity,3);assert.equal(r.open[0].remaining,2);});
