import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {core,e,dates,fixture,plain} from './holdings-learning-fixtures.mjs';
const now=Date.parse('2026-10-05T18:00:00Z');
function predict(c,state,item,extra={}){return c.HoldingsLearning.predict(state,item,{neural:[.01,.01,.98],boosting:[.01,.01,.98],source:{symbol:e.symbol,currency:e.currency,kind:e.kind,asOf:'2026-10-02',t:Date.parse('2026-10-02T13:30:00Z'),fingerprint:'same-history'},now,...extra});}
function ui(c){c.document={hidden:false,addEventListener(){},querySelectorAll:()=>[]};c.setInterval=()=>1;c.clearInterval=()=>{};vm.runInContext(readFileSync('holdings/learning.js','utf8'),c);return c.HoldingsAutoLearningUI;}
test('probability evidence identifies the exact held-out block, fixed checkpoint scores and class baseline',()=>{const c=core(),item=fixture(c),state=c.HoldingsLearning.update(null,item,now).state,r=predict(c,state,item),proof=r.evidence;assert.equal(proof.phase,'validated');assert.equal(proof.test.n,20);assert.equal(proof.fit.n,20);assert.equal(proof.test.from,state.champion.testOrigins[0]);assert.equal(proof.test.to,state.champion.testOrigins.at(-1));assert.ok(proof.fit.lastOutcome<proof.test.from);assert.deepEqual(plain(proof.scores),plain(state.champion.scores));assert.equal(proof.scores.prior.n,20);assert.equal(proof.monitoring.n,0);assert.doesNotMatch(JSON.stringify(proof),/scope|account|quantity|apiKey|sourceFingerprint|capturedAt/);});
test('collecting, changed checkpoint evidence, source errors and old source dates never expose active test scores',()=>{const c=core(),short=fixture(c,39),state=c.HoldingsLearning.update(null,fixture(c),now).state;assert.equal(predict(c,null,short).evidence.scores,null);const changed=fixture(c);changed.ledger.entries[0].estimate.probabilities=[.1,.85,.05];assert.equal(predict(c,state,changed).evidence.scores,null);const failed=fixture(c);failed.check={state:'error'};assert.equal(predict(c,state,failed).evidence.scores,null);assert.equal(predict(c,state,fixture(c),{source:{symbol:e.symbol,currency:e.currency,kind:e.kind,t:state.champion.reviewEnd}}).evidence.scores,null);});
test('a validated but ambiguous probability distribution keeps its historical evidence and explicitly abstains',()=>{const c=core(),item=fixture(c),state=c.HoldingsLearning.update(null,item,now).state,r=predict(c,state,item,{neural:[.34,.33,.33],boosting:[.34,.33,.33]});assert.equal(r.eligible,false);assert.equal(r.evidence.phase,'abstaining');assert.equal(r.evidence.test.n,20);const html=ui(c).probabilityMarkup(r);assert.match(html,/Validată · abținere/);assert.match(html,/clase prea apropiate/);});
test('twenty poor later outcomes expose the same subsequent block against its fixed baseline and suspend direction',()=>{const c=core(),adopted=dates[239]+9*3600000,state=c.HoldingsLearning.update(null,fixture(c),adopted).state,item=fixture(c,60,{wrong:true}),r=predict(c,state,item),proof=r.evidence;assert.equal(proof.phase,'suspended');assert.equal(r.eligible,false);assert.equal(proof.monitoring.n,20);assert.equal(proof.monitoring.performance.n,20);assert.equal(proof.monitoring.reference.n,20);assert.equal(proof.monitoring.degraded,true);assert.ok(proof.monitoring.from>proof.test.lastOutcome);const html=ui(c).probabilityMarkup(r);assert.match(html,/direcție suspendată/);assert.match(html,/Ambele scoruri/);});
test('evidence appears next to the percentages and never presents simulated class accuracy as profit or real performance',()=>{const c=core(),item=fixture(c),state=c.HoldingsLearning.update(null,item,now).state,r=predict(c,state,item),html=ui(c).probabilityMarkup(r);assert.match(html,/aria-label="Dovezile probabilităților"/);assert.match(html,/20 rezultate pe test ulterior/);assert.match(html,/Reper simplu/);assert.match(html,/DATE FICTIVE/);assert.match(html,/Clasă corectă/);assert.match(html,/nu reprezintă probabilitatea de profit/i);assert.doesNotMatch(html,/profit garantat|performanță reală confirmată/i);assert.ok(html.indexOf('Dovezile probabilităților')<html.indexOf('Avans: cel puțin'));});
test('missing test scores render an explicit unverified message rather than a numeric evidence comparison',()=>{const c=core(),U=ui(c),r={kind:'market',observations:39,probabilities:[.1,.2,.7],evidence:{available:39,minimum:40,scores:null,test:null}};assert.match(U.probabilityEvidenceMarkup(r),/39 \/ minimum 40/);assert.doesNotMatch(U.probabilityEvidenceMarkup(r),/<table>|log loss mai mic/);const broken={...r,evidence:{phase:'validated',test:{n:20},scores:{}}};assert.match(U.probabilityEvidenceMarkup(broken),/nu pot fi verificate/);});
