import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const core={HoldingsNeural:{valid:()=>true},HoldingsModelComparison:{valid:()=>true},HoldingsHMM:{valid:()=>true},HoldingsIsolation:{valid:()=>true},HoldingsQuantile:{valid:()=>true}};
vm.createContext(core);vm.runInContext(readFileSync('lib/holdings-verdict.js','utf8'),core);const V=core.HoldingsVerdict,now=Date.parse('2026-10-05T08:00:00Z');
function fixture(){
 const expected={symbol:'TEST',currency:'USD',asOf:'2026-10-02',kind:'market',t:now-3*86400000,close:100,timezone:'America/New_York',closeMinutes:960,fingerprint:'fixture'};
 const record=result=>({...expected,sourceTime:expected.t,sourceFingerprint:expected.fingerprint,sourceClose:100,trainedAt:now-1000,result,quantity:999,apiKey:'SECRET',accountId:'PRIVATE'});
 return {expected,now,snapshots:{
  neural:{usable:true,record:record({version:'holdings-mlp-v3',classIndex:2,report:{periods:{test:{lastLabel:expected.t}}},comparison:{status:'evaluated',boosting:{version:'holdings-gbt-v1',classIndex:2}}}),assessment:{state:'research',message:'Validat.'},comparison:{state:'research',message:'Validat.'}},
  hmm:{usable:true,record:record({version:'holdings-hmm-v1',current:{t:expected.t,state:0},profiles:[{label:'Ascendent'}]}),assessment:{state:'descriptive',message:'Validat.'}},
  isolation:{usable:true,record:record({version:'holdings-isolation-v1',current:{t:expected.t,close:100,score:.4},threshold:.6}),assessment:{state:'ordinary',message:'În tipar.'}},
  quantile:{usable:true,record:record({version:'holdings-quantile-v1',current:{t:expected.t,close:100,prices:[98,102,106],atrPct:1}}),assessment:{state:'descriptive',message:'Interval validat.'}}
 }};
}
test('five compatible validated models produce an explained experimental direction',()=>{const r=V.build(fixture());assert.equal(r.available,5);assert.equal(r.state,'up');assert.equal(r.direction,2);assert.equal(r.cards[4].medianReturnPct,2.0000000000000018);assert.match(r.limits,/HMM și Isolation.*fără voturi/);assert.equal(r.confidence,undefined);});
test('missing, failed or running models cannot produce a directional final verdict',()=>{const f=fixture();delete f.snapshots.hmm;assert.equal(V.build(f).state,'incomplete');const full=fixture();full.statuses={neural:{state:'error',error:'Eroare'}};assert.equal(V.build(full).available,4);full.running=true;assert.equal(V.build(full).state,'running');});
test('direction, quantile and regime conflicts are explicit',()=>{let f=fixture();f.snapshots.neural.record.result.comparison.boosting.classIndex=0;assert.equal(V.build(f).state,'conflict');f=fixture();f.snapshots.quantile.record.result.current.prices=[94,98,101];assert.equal(V.build(f).state,'conflict');f=fixture();f.snapshots.hmm.record.result.profiles[0].label='Deteriorare';assert.equal(V.build(f).state,'conflict');});
test('anomaly and marginal Isolation do not cast directional votes',()=>{for(const state of ['anomaly','uncertain']){const f=fixture();f.snapshots.isolation.assessment.state=state;assert.equal(V.build(f).state,'caution');assert.equal(V.build(f).direction,null);assert.equal(V.build(f).cards[3].direction,null);}});
test('historical no-edge, weak calibration and drift block combined direction',()=>{for(const [id,state] of [['neural','no-edge'],['neural','fragile'],['neural','drift'],['hmm','weak'],['quantile','limited'],['quantile','no-edge']]){const f=fixture();f.snapshots[id].assessment.state=state;assert.equal(V.build(f).state,'weak',id+state);assert.equal(V.build(f).direction,null);}});
test('provenance, session, price, age, version and validated payload must all match',()=>{const mutations=[r=>r.symbol='OTHER',r=>r.currency='EUR',r=>r.asOf='2026-10-01',r=>r.kind='synthetic',r=>r.sourceFingerprint='other',r=>r.sourceTime++,r=>r.sourceClose++,r=>r.timezone='Europe/London',r=>r.closeMinutes=1000,r=>r.trainedAt=now-1800001,r=>r.trainedAt=now+1,r=>r.result.version='unknown',r=>r.result.current.t++,r=>r.result.current.close++];for(const mutate of mutations){const f=fixture();mutate(f.snapshots.quantile.record);assert.equal(V.build(f).available,4);assert.equal(V.build(f).direction,null);}const f=fixture();f.snapshots.hmm.usable=1;assert.equal(V.build(f).available,4);});
test('cancellation cannot promote previously cached results to final verdict',()=>{const f=fixture();f.statuses=Object.fromEntries(V.IDS.map(id=>[id,{state:'cancelled'}]));assert.equal(V.build(f).available,0);assert.equal(V.build(f).state,'incomplete');});
test('combined output projects no brokerage, credentials or private parameters',()=>{const f=fixture();f.snapshots.neural.record.result.weights='SECRET-WEIGHTS';assert.ok(!/SECRET|PRIVATE|quantity|apiKey|weights/.test(JSON.stringify(V.build(f))));assert.equal(V.build().state,'incomplete');});

test('fingerprint distinguishes adjusted historical data even with identical latest close',()=>{const bars=[{t:1,o:100,h:101,l:99,c:100,v:10},{t:2,o:100,h:102,l:99,c:101,v:11}],copy=structuredClone(bars);assert.equal(V.fingerprint(bars),V.fingerprint(copy));copy[0].c=99.5;assert.notEqual(V.fingerprint(bars),V.fingerprint(copy));});
