import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const ctx={Intl,Date};vm.createContext(ctx);for(const f of ['indicators','daily-series','holdings-regime','holdings-analysis'])vm.runInContext(readFileSync('lib/'+f+'.js','utf8'),ctx);const R=ctx.HoldingsRegime,A=ctx.HoldingsAnalysis,now=Date.parse('2026-10-03T16:00:00Z');
function bars(n=260){const days=[];for(const d=new Date('2026-10-02T13:30:00Z');days.length<n;d.setUTCDate(d.getUTCDate()-1))if(d.getUTCDay()>0&&d.getUTCDay()<6)days.unshift(d.getTime());return days.map((t,i)=>({t,c:70+i*.2,o:70+i*.2-.1,h:70+i*.2+1,l:70+i*.2-1,v:1000}));}
test('regime EMA offsets match the latest complete holding indicators',()=>{const b=bars(),m=A.analyze(b,b,now);assert.equal(m.regime.confirmed,'up');assert.equal(m.regime.ema21,m.ema21);assert.equal(m.regime.ema50,m.ema50);assert.equal(m.regime.asOf,m.asOf);assert.equal(m.rs20,0);assert.equal(m.rs60,0);assert.equal(m.regime.confirmation,3);assert.equal('probability' in m.regime,false);});
test('one or two countertrend observations cannot change confirmed regime',()=>{const rows=['up','up','up','down','down','up','down','down','down'].map((candidate,i)=>({candidate,t:i*86400000,asOf:String(i)})),xs=R.stabilize(rows);assert.equal(xs[2].confirmed,'up');assert.equal(xs[4].confirmed,'up');assert.equal(xs[4].pending,true);assert.equal(xs[8].confirmed,'down');assert.equal(xs[8].from,'up');assert.equal(xs[8].changed,true);});
test('large data gap resets persistence, duplicate render cannot create session count',()=>{const xs=R.stabilize([{candidate:'up',t:0},{candidate:'up',t:86400000},{candidate:'up',t:2*86400000},{candidate:'down',t:15*86400000}]);assert.equal(xs[3].confirmed,null);assert.equal(xs[3].streak,1);});
test('relative returns align the entire 20 and 60-session date windows',()=>{const b=bars(),stock={bars:b,timezone:'America/New_York',asOf:'2026-10-02'},m=R.relative(stock,b,now);assert.equal(m.rs60,0);const missing=b.filter((_,i)=>i!==b.length-10);assert.equal(R.relative(stock,missing,now).rs20,null);assert.equal(R.relative(stock,missing,now).rs60,null);assert.equal(R.relative(stock,b.slice(0,-1),now).rs20,null);assert.equal(R.relative(stock,null,now).rs60,null);});
test('regime follow-up uses source sessions and blocks splits, revisions and wrong currencies',()=>{const b=bars(),series={bars:b,timezone:'America/New_York',currency:'USD'},at=230,e={price:b[at].c,asOf:ctx.DailySeries.date(b[at].t,series.timezone),currency:'USD'},r=R.followup(e,series);assert.ok(r[0].change>0);assert.equal(r[2].change,undefined);assert.match(R.followup(e,series,[b[at+2].t])[0].status,/Split/);assert.throws(()=>R.followup({...e,currency:'EUR'},series),/incompatibile/);assert.throws(()=>R.followup({...e,price:e.price*2},series),/revizuit/);});
test('portfolio map preserves unknown analysis and excludes incompatible values',()=>{const xs=[{ticker:'A',currency:'EUR',value:200},{ticker:'B',currency:'EUR',value:100},{ticker:'C',currency:'USD',value:300}],r=R.exposure(xs,1000,'EUR',p=>p.ticker==='A'?{regime:{confirmed:'up'}}:null);assert.equal(r.sums.up,20);assert.equal(r.sums.unknown,10);assert.equal(r.covered,2);assert.equal(r.rows[2].weight,null);});
