import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function setup(){const s={Intl,Date};vm.createContext(s);for(const f of ['lib/holdings-pulse.js','lib/holdings-notes.js','lib/holdings-events.js','lib/holdings-workspace.js','lib/holdings-review.js','lib/holdings-alerts.js'])vm.runInContext(readFileSync(f,'utf8'),s);return s;}
const p={ticker:'A',currentPrice:102,quantity:2,instrumentCurrency:'USD'},n={stop:100,stopCurrency:'USD',stopAlertPct:3},at='2026-10-08T15:00:00Z',now=Date.parse(at),m={price:101,currency:'USD',asOf:'2026-10-07',short:'Ascendent',medium:'Ascendent',long:'Tranziție',ema50:90,ema21:95,rsi:60,rvol:1.4,rs20:2,ret5:3,atr:2,atrPct:2,adx:27,support:85,resistance:110};
test('stop alerts use the freshest broker quote even when EOD is on the other side of the stop',()=>{const {HoldingsPulse:P}=setup();assert.equal(P.stop(p,n,{...m,price:95},{at,now}).state,'near');assert.equal(P.stop({...p,currentPrice:99},n,m,{at,now}).state,'crossed');assert.equal(P.build({...p,currentPrice:99},m,n,{at,now}).code,'stop');});
test('near and crossed boundaries are inclusive, adjustable and based on distance above stop',()=>{const {HoldingsPulse:P}=setup();assert.equal(P.stop({...p,currentPrice:100},n,m,{at,now}).state,'crossed');assert.equal(P.stop({...p,currentPrice:103},n,m,{at,now}).state,'near');assert.equal(P.stop({...p,currentPrice:104},n,m,{at,now}).state,'safe');assert.equal(P.stop(p,{...n,stopAlertPct:1},m,{at,now}).state,'safe');});
test('unknown stop currency, invalid thresholds and nonpositive stops never emit a live alert',()=>{const {HoldingsPulse:P,HoldingsNotes:N}=setup();for(const patch of [{stop:0},{stop:-1},{stop:Infinity},{stopCurrency:null},{stopCurrency:'EUR'},{stopAlertPct:0},{stopAlertPct:21},{stopAlertPct:'abc'}])assert.equal(P.stop(p,{...n,...patch},m,{at,now}).state,'missing');assert.throws(()=>N.change({}, {stopAlertPct:21}));assert.throws(()=>N.change({}, {stopAlertPct:'abc'}));});
test('expired, future and missing broker quotes fall back only to compatible current EOD supplied by the caller',()=>{const {HoldingsPulse:P}=setup();for(const stamp of ['2026-10-07T15:00:00Z','2099-01-01T00:00:00Z',null]){const r=P.stop(p,n,m,{at:stamp,now});assert.match(r.source,/EOD/);assert.equal(P.stop(p,n,null,{at:stamp,now}).state,'missing');assert.equal(P.stop(p,n,{...m,currency:'EUR'},{at:stamp,now}).state,'missing');}});
test('pence and GBX are equivalent; pounds and pence are never converted implicitly',()=>{const {HoldingsPulse:P}=setup();assert.equal(P.stop({...p,instrumentCurrency:'GBp'},{...n,stopCurrency:'GBX'},m,{at,now}).state,'near');assert.equal(P.stop({...p,instrumentCurrency:'GBp'},{...n,stopCurrency:'GBP'},m,{at,now}).state,'missing');});
test('technical verdicts are directional descriptions, never invented profit probabilities',()=>{const {HoldingsPulse:P}=setup();for(const [medium,code] of [['Ascendent','up'],['Descendent','down'],['Tranziție','mixed']]){const r=P.build(p,{...m,medium},{},{at,now});assert.equal(r.code,code);assert.ok(r.next&&r.confirmation&&r.invalidation);assert.equal(r.indicators.length,6);assert.match(P.markup(r,m),/Ce spun indicatorii/);assert.doesNotMatch(P.markup(r,m),/probabilitatea.*profit/i);}assert.equal(P.build(p,null,{},{}).code,'missing');});
test('ADX never invents a direction and unavailable indicators retain explicit missing explanations',()=>{const {HoldingsPulse:P}=setup(),r=P.build(p,{...m,medium:'Tranziție',adx:40,rsi:null,rvol:null,rs20:null},{});assert.equal(r.code,'mixed');assert.match(r.indicators.find(x=>x.name.startsWith('ADX')).meaning,/nu stabilește direcția/);assert.match(r.indicators.find(x=>x.name.startsWith('RSI')).meaning,/insuficiente/);});
test('review ranking, card stop and persisted alert episodes share the same near-stop rule',()=>{const s=setup(),r=s.HoldingsWorkspace.attention([p],{A:m},{A:n},{},1000,'USD',p=>p.ticker,true,now,at);assert.equal(r[0].priority,90);assert.match(r[0].reasons[0],/zona de alertă/);const review=s.HoldingsReview.assess(p,m,n,null,'A',now,at);assert.equal(review.kind,'review');assert.match(review.reasons[0],/apropie/);let alerts=s.HoldingsAlerts.reconcile([],'a',r,{A:m},now);alerts=s.HoldingsAlerts.reconcile(alerts,'a',r,{A:m},now+60000);assert.equal(alerts.length,1);assert.equal(alerts[0].active,true);alerts=s.HoldingsAlerts.reconcile(alerts,'a',[],{},now+120000);assert.equal(alerts[0].active,false);alerts=s.HoldingsAlerts.reconcile(alerts,'a',r,{A:m},now+180000);assert.equal(alerts.length,2);});
test('markup escapes external indicator and date strings',()=>{const {HoldingsPulse:P}=setup(),model={...m,currency:'<img>',asOf:'<script>'},html=P.markup(P.build(p,model,{}),model);assert.doesNotMatch(html,/<img>|<script>/);assert.match(html,/&lt;script&gt;/);});

test('confirmation progress uses EOD price rather than a newer intraday quote and keeps missing conditions unknown',()=>{const {HoldingsPulse:P}=setup(),r=P.build({...p,currentPrice:120},m,{}, {at,now});assert.equal(r.checks.present,2);assert.equal(r.checks.known,3);assert.equal(r.checks.checks[0].state,'waiting');assert.ok(r.checks.checks[0].gap>8);const missing=P.confirmationChecks({...m,rvol:null,ema21:null});assert.equal(missing.known,1);assert.equal(missing.present,0);assert.equal(missing.checks[1].state,'missing');assert.match(P.markup(r,m),/2\/3 condiții prezente în EOD/);});
test('breakout and EMA require a strict close above the level, while volume includes the 1.2 boundary',()=>{const {HoldingsPulse:P}=setup(),c=P.confirmationChecks({...m,price:110,ema21:110,resistance:110,rvol:1.2});assert.equal(c.present,1);assert.equal(c.checks[0].state,'waiting');assert.equal(c.checks[0].gap,0);assert.equal(c.checks[2].state,'present');assert.equal(P.confirmationChecks({...m,price:111,ema21:110,resistance:110,rvol:1.2}).present,3);});
