import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {webcrypto} from 'node:crypto';

const NOW=Date.parse('2026-10-10T10:00:00Z'),TOKEN='a'.repeat(32),script=readFileSync('lib/operational-checks.js','utf8');
function setup(extra={}){const c={Date,Uint8Array,setTimeout,clearTimeout,crypto:webcrypto,...extra};vm.createContext(c);vm.runInContext(script,c);return c.TTOperationalChecks;}
const plain=x=>JSON.parse(JSON.stringify(x));
function stores(){const ledger=new Map([['tt_journal_v1','[{"id":"original"}]'],['tt_theme','dark']]),privateData=new Map([['session',{secret:'private'}]]);return {ledger,privateData,local:{getItem:k=>ledger.get(k)??null,setItem:(k,v)=>ledger.set(k,v),removeItem:k=>ledger.delete(k)},privateStore:{get:async k=>privateData.get(k)??null,put:async(k,v)=>privateData.set(k,v),remove:async k=>privateData.delete(k)}};}
const item=(r,id)=>r.rows.find(x=>x.id===id);
const cloud=()=>({connected:true,ready:true,lastSync:NOW-1000,conflicts:[],trading212:{cloud:true},monitor:{protocol:'tt-account-monitor-v1',schedulerFresh:true,schedulerAt:NOW-60000},push:{protocol:'tt-web-push-v1',available:true},audit:{protocol:'tt-audit-v1',available:true}});

test('write-read-remove probes preserve every original and remove only their own temporary entries',async()=>{const A=setup(),s=stores(),before=[...s.ledger],privateBefore=[...s.privateData];const r=await A.probe({...s,randomId:()=>TOKEN,now:()=>NOW});assert.equal(r.local.state,'good');assert.equal(r.private.state,'good');assert.deepEqual([...s.ledger],before);assert.deepEqual([...s.privateData],privateBefore);});
test('quota failure is independent from the successful encrypted-store check',async()=>{const A=setup(),s=stores();s.local.setItem=()=>{throw Error('quota');};const r=await A.probe({...s,now:()=>NOW});assert.equal(r.local.state,'blocked');assert.equal(r.local.code,'failed');assert.equal(r.private.state,'good');assert.equal(s.ledger.get('tt_journal_v1'),'[{"id":"original"}]');});
test('an acknowledged write that returns different data cannot pass',async()=>{const A=setup(),s=stores();let saved=false;s.privateStore={get:async()=>saved?{test:'wrong'}:null,put:async()=>{saved=true;},remove:async()=>{saved=false;}};const r=await A.probe({...s,now:()=>NOW});assert.equal(r.private.code,'failed');assert.equal(r.private.state,'blocked');assert.equal(saved,false);});
test('cleanup refusal is reported rather than claiming that the temporary value was removed',async()=>{const A=setup(),s=stores();s.privateStore.remove=async()=>{throw Error('denied');};const r=await A.probe({...s,now:()=>NOW});assert.equal(r.private.code,'cleanup');assert.equal(r.private.state,'blocked');assert.deepEqual(s.privateData.get('session'),{secret:'private'});});
test('a key collision never replaces or removes an existing value',async()=>{const A=setup(),s=stores();s.ledger.set('tt_operational_probe:'+TOKEN,'{"original":true}');s.privateData.set('operational-probe:'+TOKEN,{original:true});const r=await A.probe({...s,randomId:()=>TOKEN,now:()=>NOW});assert.equal(r.local.code,'collision');assert.equal(r.private.code,'collision');assert.equal(s.ledger.get('tt_operational_probe:'+TOKEN),'{"original":true}');assert.deepEqual(s.privateData.get('operational-probe:'+TOKEN),{original:true});});
test('a timed-out write returns unknown and removes its temporary value if the write later completes',async()=>{let release;const gate=new Promise(r=>release=r),A=setup(),s=stores(),put=s.privateStore.put;s.privateStore.put=async(k,v)=>{await gate;return put(k,v);};const r=await A.probe({...s,randomId:()=>TOKEN,timeoutMs:15,now:()=>NOW});assert.equal(r.local.state,'good');assert.equal(r.private.code,'timeout');assert.equal(r.private.state,'unknown');release();for(let i=0;i<3;i++)await new Promise(r=>setImmediate(r));assert.equal(s.privateData.has('operational-probe:'+TOKEN),false);assert.deepEqual(s.privateData.get('session'),{secret:'private'});});
test('missing stores and unsafe probe identifiers never alter real register keys',async()=>{const A=setup(),s=stores();let r=await A.probe({now:()=>NOW});assert.equal(r.local.state,'blocked');assert.equal(r.private.state,'blocked');r=await A.probe({...s,randomId:()=> 'tt_journal_v1',now:()=>NOW});assert.equal(r.local.state,'unknown');assert.equal(s.ledger.size,2);assert.equal(s.privateData.size,1);});
test('conflicts, backup suspension, errors and pending checks take precedence over a recent reconciliation',()=>{const A=setup();for(const [change,state,detail] of [[{conflicts:['journal']},'warning',/cer alegerea/],[{backupPaused:true},'warning',/Suspendată/],[{error:'sensitive secret'},'blocked',/eroare/],[{checking:true},'unknown',/în curs/],[{ready:false},'blocked',/nu este disponibil/]]){const r=A.build({cloud:{...cloud(),...change},now:NOW});assert.equal(item(r,'sync').state,state);assert.match(item(r,'sync').detail,detail);assert.equal(JSON.stringify(r).includes('sensitive secret'),false);}});
test('logout hides stale personal sync and broker confirmations; account mismatch is blocked',()=>{const A=setup();let r=A.build({cloud:{...cloud(),connected:false},now:NOW});assert.equal(item(r,'sync').state,'unknown');assert.equal(item(r,'broker-cloud').state,'unknown');r=A.build({cloud:{...cloud(),connected:false,error:'account_mismatch'},now:NOW});assert.equal(item(r,'session').state,'blocked');assert.match(item(r,'session').action,/contul inițial/);});
test('old, invalid and future sync or scheduler timestamps cannot appear as current checks',()=>{const A=setup();for(const at of [NOW-600001,NOW+60001,'recent',null]){const r=A.build({cloud:{...cloud(),lastSync:at,monitor:{...cloud().monitor,schedulerAt:at}},now:NOW});assert.notEqual(item(r,'sync').state,'good');assert.notEqual(item(r,'scheduler').state,'good');}const r=A.build({cloud:cloud(),now:NOW});assert.equal(item(r,'scheduler').state,'good');assert.match(item(r,'scheduler').action,/nu confirmă/);});
test('partial and old broker snapshots remain warnings and invalid source times are blocked',()=>{const A=setup(),snapshot={environment:'live',fetchedAt:new Date(NOW).toISOString(),positions:[],summary:{currency:'EUR'}};assert.equal(item(A.build({snapshot:['secret-scope',snapshot],now:NOW}),'snapshot').state,'good');for(const change of [{positions:null},{summary:null},{fetchedAt:new Date(NOW-300001).toISOString()}])assert.equal(item(A.build({snapshot:['scope',{...snapshot,...change}],now:NOW}),'snapshot').state,'warning');for(const fetchedAt of ['wrong',new Date(NOW+60001).toISOString()])assert.equal(item(A.build({snapshot:['scope',{...snapshot,fetchedAt}],now:NOW}),'snapshot').state,'blocked');assert.equal(item(A.build({snapshotError:true,now:NOW}),'snapshot').state,'blocked');});
test('push permission and service availability never become proof of receipt',()=>{const A=setup();for(const permission of ['default','granted','unsupported','denied']){const r=A.build({cloud:cloud(),permission,now:NOW});assert.notEqual(item(r,'push').state,'good');if(permission==='denied')assert.equal(item(r,'push').state,'blocked');}const r=A.build({cloud:{...cloud(),audit:{protocol:'old',available:true}},now:NOW});assert.equal(item(r,'audit').state,'unknown');});
test('a failed readiness check hides stale service capabilities while keeping the device permission warning',()=>{const A=setup(),r=A.build({cloud:{...cloud(),ready:false},permission:'granted',now:NOW});for(const id of ['scheduler','audit','push'])assert.equal(item(r,id).state,'unknown');assert.equal(item(A.build({cloud:{...cloud(),ready:false},permission:'denied',now:NOW}),'push').state,'blocked');});
test('storage is unknown before testing and expires after ten minutes',()=>{const A=setup();assert.equal(item(A.build({now:NOW}),'private-storage').state,'unknown');const storage={local:{state:'good',code:'verified',at:NOW-600001},private:{state:'good',code:'verified',at:NOW}};const r=A.build({storage,now:NOW});assert.equal(item(r,'local-storage').state,'warning');assert.equal(item(r,'private-storage').state,'good');assert.match(item(r,'private-storage').action,/backup mare/);});
test('export is a whitelist and never contains Google identity, financial values, credentials, endpoints or raw errors',()=>{const A=setup(),secret='PRIVATE_DO_NOT_EXPORT',s={...cloud(),email:secret,subject:secret,token:secret,error:secret,conflicts:[secret],trading212:{cloud:true,key:secret,secret},push:{protocol:'tt-web-push-v1',available:true,devices:[{endpoint:secret}]}},snapshot=['scope-'+secret,{environment:'live',fetchedAt:new Date(NOW).toISOString(),positions:[{ticker:secret,value:999999}],summary:{total:999999},key:secret}],r=A.report({cloud:s,snapshot,permission:'granted',storage:{local:{state:'blocked',code:'failed',at:NOW,error:secret}},appVersion:'26.10.10.1234',now:NOW,userAgent:secret,local:secret});assert.equal(r.appVersion,'26.10.10.1234');assert.equal(r.protocol,'tt-operational-report-v1');assert.equal(JSON.stringify(r).includes(secret),false);assert.equal(JSON.stringify(r).includes('999999'),false);assert.equal(r.rows.length,10);assert.equal(Object.values(plain(r.counts)).reduce((a,b)=>a+b,0),10);assert.equal(A.report({appVersion:secret,now:NOW}).appVersion,null);});

function ui({recheck=async()=>{},storeFailure=false}={}){const nodes=new Map(),events={},s=cloud(),ls=stores(),downloads=[];const element=(tag='div')=>({tag,children:[],dataset:{},append(...items){this.children.push(...items);},replaceChildren(...items){this.children=items;},click(){if(this.tag==='a')downloads.push(this);}}),get=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};let writes=0;const set=ls.local.setItem;ls.local.setItem=(...args)=>{writes++;if(storeFailure)throw Error('quota');return set(...args);};const c={Date,Uint8Array,setTimeout,clearTimeout,setInterval:()=>0,crypto:webcrypto,Blob,URL:{createObjectURL:b=>{c.download=b;return 'blob:test';},revokeObjectURL(){}},navigator:{onLine:true,serviceWorker:{}},Notification:{permission:'granted'},PushManager:function(){},location:{origin:'https://test.example'},localStorage:ls.local,document:{documentElement:{dataset:{}},createElement:element,getElementById:get,addEventListener:(n,f)=>events[n]=f,hidden:false},addEventListener:(n,f)=>events[n]=f};c.window=c;c.parent={document:{documentElement:{dataset:{appVersion:'26.10.10.1234'}}},TTCloud:{state:()=>s,recheck},TTCloudStore:ls.privateStore,T212Snapshot:{read:()=>null}};vm.createContext(c);vm.runInContext(script,c);vm.runInContext(readFileSync('app/sync/verification.js','utf8'),c);return {c,s,nodes,events,ls,downloads,get,writes:()=>writes};}
const card=(u,title)=>u.get('operationalChecks').children.find(x=>x.children[0].textContent===title);
test('opening diagnostics is read-only; storage is tested only by an explicit action',async()=>{const u=ui();assert.equal(u.writes(),0);assert.equal(card(u,'Stocarea registrelor locale').children[1].textContent,'Neconfirmat');await u.get('operationalStorage').onclick();assert.equal(u.writes(),1);assert.equal(card(u,'Stocarea registrelor locale').children[1].textContent,'Verificat');assert.equal(card(u,'Stocarea privată criptată').children[1].textContent,'Verificat');assert.equal(u.ls.ledger.size,2);});
test('a rejected service recheck still completes the storage test and reenables buttons',async()=>{const u=ui({recheck:async()=>{throw Error('SECRET');},storeFailure:true});await u.get('operationalRefresh').onclick();assert.equal(u.get('operationalExport').disabled,false);assert.match(u.get('operationalMessage').textContent,/serviciul|Serviciul/);assert.equal(card(u,'Stocarea registrelor locale').children[1].textContent,'Blocat');assert.equal(card(u,'Stocarea privată criptată').children[1].textContent,'Verificat');assert.equal(u.get('operationalMessage').textContent.includes('SECRET'),false);});
test('a hanging service recheck has a deadline independent from local storage and is safely retryable',async()=>{const timers=new Map();let id=0;const u=ui({recheck:()=>new Promise(()=>{})});u.c.setTimeout=(fn,ms)=>{timers.set(++id,{fn,ms});return id;};u.c.clearTimeout=i=>timers.delete(i);const job=u.get('operationalRefresh').onclick();for(let i=0;i<3;i++)await new Promise(r=>setImmediate(r));assert.equal(u.get('operationalExport').disabled,true);for(const t of [...timers.values()])if(t.ms===8000)t.fn();await job;assert.equal(u.get('operationalExport').disabled,false);assert.match(u.get('operationalMessage').textContent,/nu a confirmat/);assert.equal(card(u,'Stocarea registrelor locale').children[1].textContent,'Verificat');});
test('export samples current state, not stale displayed state, and drops personal fields',async()=>{const u=ui();u.s.email='PRIVATE_EMAIL';u.s.error='PRIVATE_ERROR';u.s.conflicts=['PRIVATE_LEDGER'];u.get('operationalExport').onclick();const r=JSON.parse(await u.c.download.text());assert.equal(item(r,'sync').state,'blocked');assert.equal(JSON.stringify(r).includes('PRIVATE_'),false);assert.equal(u.downloads.length,1);});
test('only trusted parent notifications rerender diagnostics; corrupt snapshot originals remain untouched',()=>{const u=ui(),raw='{invalid';u.ls.ledger.set('tt_trading212_portfolio_v1',raw);const before=card(u,'Snapshot Invest');u.events.message({source:{},origin:u.c.location.origin,data:{ttCloudState:{}}});assert.equal(card(u,'Snapshot Invest'),before);u.events.message({source:u.c.parent,origin:'https://foreign.example',data:{ttCloudState:{}}});assert.equal(card(u,'Snapshot Invest'),before);u.events.message({source:u.c.parent,origin:u.c.location.origin,data:{ttCloudState:{}}});assert.equal(card(u,'Snapshot Invest').children[1].textContent,'Blocat');assert.equal(u.ls.ledger.get('tt_trading212_portfolio_v1'),raw);});
