import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const at='2026-10-08T15:00:00Z',now=Date.parse(at),p={ticker:'TEST',quantity:2,averagePrice:80,currentPrice:110,instrumentCurrency:'USD',currency:'EUR',unrealized:55};
function setup(){const s={Intl,Date};vm.createContext(s);for(const file of ['lib/trading212-daily.js','lib/position-history.js'])vm.runInContext(readFileSync(file,'utf8'),s);return s;}
const options=(extra={})=>({scope:'a',environment:'live',position:p,at,now,...extra});
function history(s,observations){let d={version:1,accounts:{}};for(const [date,patch] of observations)d=s.T212Daily.record(d,'a','live',patch===null?[]:[{...p,...patch}],date,now);return d;}
test('price and account P&L have distinct units and absolute changes',()=>{const s=setup(),d=history(s,[['2026-10-02T15:00:00Z',{currentPrice:100,unrealized:40}]]),r=s.PositionHistory.build(d,options());assert.equal(r.unit,'USD');assert.equal(r.delta,10);assert.ok(Math.abs(r.pct-10)<1e-8);const pnl=s.PositionHistory.build(d,options({metric:'pnl'}));assert.equal(pnl.unit,'EUR');assert.equal(pnl.delta,15);assert.equal(pnl.pct,null);assert.equal(r.span,7);assert.equal(r.points.length,2);});
test('selected 7, 30 and 90 calendar-day windows exclude older readings without filling gaps',()=>{const s=setup(),d=history(s,[['2026-08-01T15:00:00Z',{}],['2026-09-15T15:00:00Z',{}],['2026-10-01T15:00:00Z',{}],['2026-10-02T15:00:00Z',{}]]);assert.equal(s.PositionHistory.build(d,options({days:7})).points.length,2);assert.equal(s.PositionHistory.build(d,options({days:30})).points.length,4);assert.equal(s.PositionHistory.build(d,options({days:90})).points.length,5);});
test('same Bucharest day keeps its latest reading and current snapshot supersedes stored copies',()=>{const s=setup(),d=history(s,[['2026-10-07T15:00:00Z',{currentPrice:90}],['2026-10-07T16:00:00Z',{currentPrice:100}],['2026-10-08T14:00:00Z',{currentPrice:105}]]),r=s.PositionHistory.build(d,options());assert.equal(r.points.length,2);assert.equal(r.points[0].value,100);assert.equal(r.points[1].value,110);});
test('midnight in Bucharest and DST use calendar dates, not a rolling 24-hour cutoff',()=>{const s=setup(),end='2026-10-09T00:10:00Z',d=history(s,[['2026-10-02T21:10:00Z',{}]]),r=s.PositionHistory.build(d,options({at:end,now:Date.parse(end),days:7}));assert.equal(r.points.length,2);assert.equal(r.points[0].day,'2026-10-03');});
test('a different account cannot contribute observations and a different environment blocks the series',()=>{const s=setup(),d=history(s,[['2026-10-07T15:00:00Z',{}]]);assert.equal(s.PositionHistory.build(d,options({scope:'b'})).points.length,1);assert.equal(s.PositionHistory.build(d,options({environment:'demo'})).points.length,0);});
test('trade, split and cost changes segment the chart and block whole-period comparisons',()=>{for(const patch of [{quantity:4},{averagePrice:81},{averagePrice:null}]){const s=setup(),d=history(s,[['2026-10-06T15:00:00Z',{...patch,currentPrice:100}],['2026-10-07T15:00:00Z',{}]]),r=s.PositionHistory.build(d,options());assert.equal(r.delta,null);assert.ok(r.breaks>0);assert.notEqual(r.points[0].segment,r.points[1].segment);assert.equal(s.PositionHistory.build(d,options({metric:'pnl'})).delta,null);}});
test('a closed and reopened position cannot be joined across an observed absence',()=>{const s=setup(),d=history(s,[['2026-10-05T15:00:00Z',{}],['2026-10-06T15:00:00Z',null],['2026-10-07T15:00:00Z',{}]]),r=s.PositionHistory.build(d,options());assert.equal(r.points.length,3);assert.equal(r.delta,null);assert.notEqual(r.points[0].segment,r.points[1].segment);});
test('missing P&L remains missing while price series stays usable; zero P&L is a valid reading',()=>{const s=setup(),d=history(s,[['2026-10-06T15:00:00Z',{unrealized:0}],['2026-10-07T15:00:00Z',{unrealized:null}]]),r=s.PositionHistory.build(d,options({metric:'pnl'}));assert.equal(r.points[0].value,0);assert.equal(r.points.length,2);assert.equal(r.delta,null);assert.equal(s.PositionHistory.build(d,options()).points.length,3);});
test('a missing current value blocks comparison rather than presenting an older interval as current',()=>{const s=setup(),d=history(s,[['2026-10-06T15:00:00Z',{currentPrice:90}],['2026-10-07T15:00:00Z',{currentPrice:100}]]),r=s.PositionHistory.build(d,options({position:{...p,currentPrice:null}}));assert.equal(r.points.length,2);assert.equal(r.delta,null);assert.match(r.reason,/curentă lipsește/);});
test('account currency changes, missing instrument currency and pounds versus pence break comparisons',()=>{const s=setup(),d=history(s,[['2026-10-06T15:00:00Z',{currency:'USD'}],['2026-10-07T15:00:00Z',{}]]);assert.equal(s.PositionHistory.build(d,options({metric:'pnl'})).points.length,2);const pence=history(s,[['2026-10-06T15:00:00Z',{instrumentCurrency:'GBp'}],['2026-10-07T15:00:00Z',{instrumentCurrency:'GBP'}]]);assert.equal(s.PositionHistory.build(pence,options({position:{...p,instrumentCurrency:'GBp'}})).delta,null);assert.equal(s.PositionHistory.build(d,options({position:{...p,instrumentCurrency:null}})).points.length,0);});
test('future, invalid and duplicate observations cannot provide an extra data point',()=>{const s=setup(),d={version:1,accounts:{a:{environment:'live',days:[{at:'2026-10-09T00:00:00Z',positions:[p]},{at:'invalid',positions:[p]},{at:'2026-10-07T15:00:00Z',positions:[p,p]}]}}};assert.equal(s.PositionHistory.build(d,options()).points.length,1);assert.equal(s.PositionHistory.build(d,options({at:'2099-01-01T00:00:00Z'})).points.length,0);});
test('numeric overflow cannot become a P&L change or invalid SVG coordinate',()=>{const s=setup(),d=history(s,[['2026-10-07T15:00:00Z',{unrealized:-1e308}]]),o=options({metric:'pnl',position:{...p,unrealized:1e308}});assert.equal(s.PositionHistory.build(d,o).delta,null);assert.doesNotMatch(s.PositionHistory.markup(d,o),/NaN|Infinity/);});
test('markup exposes accessible period, metric and observation controls and escapes ticker labels',()=>{const s=setup(),html=s.PositionHistory.markup(null,options({position:{...p,ticker:'<img src=x>'}}));assert.match(html,/aria-label="Perioada istoricului"/);assert.match(html,/aria-valuetext=/);assert.match(html,/Tabelul citirilor/);assert.match(html,/&lt;img/);assert.doesNotMatch(html,/<img/);});
test('range inspection updates the selection and marker without replacing the slider or host',()=>{const s=setup(),d=history(s,[['2026-10-07T15:00:00Z',{currentPrice:100}]]),html=s.PositionHistory.markup(d,options());const key=JSON.stringify(['a','live','TEST']);const slider={value:'1',matches:()=>true,setAttribute(k,v){this[k]=v}},marker={setAttribute(k,v){this[k]=v}},label={textContent:''},back={dataset:{historyStep:'-1'}},next={dataset:{historyStep:'1'}},host={dataset:{positionHistory:key},innerHTML:html,querySelector:q=>q==='[data-history-index]'?slider:q==='[data-history-marker]'?marker:label,querySelectorAll:()=>[back,next]};s.PositionHistory.bind({querySelectorAll:()=>[host]});slider.value='0';host.oninput({target:slider});assert.equal(host.innerHTML,html);assert.match(label.textContent,/100 USD/);assert.equal(back.disabled,true);assert.equal(next.disabled,false);assert.equal(marker.cx,44);const refreshed=s.PositionHistory.markup(d,options());assert.match(refreshed,/value="0" aria-label="Citirea selectată"/);});
test('simulated multi-day history contains explicit gaps and does not mutate persisted data',()=>{const s=setup(),before=history(s,[['2026-10-07T15:00:00Z',{}]]),copy=JSON.stringify(before),d=s.T212Daily.demo('example','demo',[p],at),r=s.PositionHistory.build(d,options({scope:'example',environment:'demo',days:90}));assert.ok(r.points.length>20);assert.ok(r.points.length<r.span);assert.equal(JSON.stringify(before),copy);});
