import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function setup(){const s={Intl,Date};vm.createContext(s);vm.runInContext(readFileSync('lib/trading212-daily.js','utf8'),s);return s.T212Daily;}
const at='2026-10-08T15:00:00Z',before='2026-10-07T15:00:00Z',now=Date.parse(at),p={ticker:'TEST',quantity:2,averagePrice:80,currentPrice:100,instrumentCurrency:'USD',currency:'EUR',unrealized:40};
const saved=D=>D.record({version:1,accounts:{}},'a','live',[p],before,now),compare=(D,data,position={...p,currentPrice:110,unrealized:55},extra={})=>D.compare(data,{scope:'a',position,at,now,...extra});
test('daily observed price movement and broker P&L stay in their respective currencies',()=>{const D=setup(),r=compare(D,saved(D));assert.equal(r.state,'ready');assert.ok(Math.abs(r.pricePct-10)<1e-8);assert.equal(r.priceMove,20);assert.equal(r.priceCurrency,'USD');assert.equal(r.pnlDelta,15);assert.equal(r.pnlCurrency,'EUR');assert.match(D.markup(r),/Citiri observate/);});
test('same-day sync replaces the last quote without changing the prior-day baseline',()=>{const D=setup();let data=saved(D);data=D.record(data,'a','live',[{...p,currentPrice:105}],at,now);data=D.record(data,'a','live',[{...p,currentPrice:110}],at.replace('15:00','15:01'),now+60000);assert.equal(data.accounts.a.days.length,2);assert.equal(data.accounts.a.days.at(-1).positions[0].currentPrice,110);assert.ok(Math.abs(compare(D,data).pricePct-10)<1e-8);});
test('new accounts, new positions and same-day-only data cannot invent yesterday results',()=>{const D=setup(),data=D.record({version:1,accounts:{}},'a','live',[p],at,now);assert.equal(compare(D,data).state,'missing');assert.equal(compare(D,saved(D),{...p,ticker:'NEW'}).state,'missing');assert.equal(compare(D,saved(D),p,{scope:'other'}).state,'missing');assert.equal(compare(D,saved(D),p,{environment:'demo'}).state,'missing');});
test('trades, possible splits and changed cost block misleading return and P&L comparisons',()=>{const D=setup();for(const patch of [{quantity:4,currentPrice:50},{quantity:1},{averagePrice:81},{averagePrice:null}]){const r=compare(D,saved(D),{...p,...patch});assert.equal(r.state,'changed');assert.equal(r.pricePct,null);assert.equal(r.pnlDelta,null);}});
test('gaps between observed days are explicit and cannot be called a one-day profit',()=>{const D=setup(),data=D.record({version:1,accounts:{}},'a','live',[p],'2026-10-02T15:00:00Z',now);assert.match(compare(D,data).reason,/mai multe zile/);assert.equal(compare(D,data).fromDay,'2026-10-02');});
test('Bucharest midnight and daylight saving boundaries define the observation day',()=>{const D=setup();assert.equal(D.day(Date.parse('2026-10-08T21:30:00Z')),'2026-10-09');assert.equal(D.day(Date.parse('2026-10-26T21:30:00Z')),'2026-10-26');});
test('missing, zero, nonnumeric or changed currency prices never become a return',()=>{const D=setup();for(const patch of [{currentPrice:0},{currentPrice:NaN},{currentPrice:'110'},{instrumentCurrency:'EUR'},{instrumentCurrency:null}])assert.equal(compare(D,saved(D),{...p,...patch}).pricePct,null);const r=compare(D,saved(D),{...p,currentPrice:110,currency:'USD'});assert.notEqual(r.pricePct,null);assert.equal(r.pnlDelta,null);});
test('pence retain their denomination and cannot silently compare with pounds',()=>{const D=setup(),data=D.record({version:1,accounts:{}},'a','live',[{...p,instrumentCurrency:'GBp'}],before,now);assert.equal(compare(D,data,{...p,currentPrice:110,instrumentCurrency:'GBp'}).priceCurrency,'GBp');assert.equal(compare(D,data,{...p,instrumentCurrency:'GBP'}).state,'missing');});
test('older/future saves, duplicate instruments and incompatible storage are preserved safely',()=>{const D=setup(),data=saved(D);assert.equal(D.record(data,'a','live',[p],before,now),data);assert.equal(D.record(data,'a','live',[p],'2099-01-01T00:00:00Z',now),data);assert.throws(()=>D.record({version:99},'a','live',[p],at,now));assert.throws(()=>D.record(data,'a','demo',[p],at,now));const duplicate=D.record({version:1},'a','live',[p,p],before,now);assert.equal(compare(D,duplicate).state,'missing');});
test('storage retains at most ninety observed days per account and demo never writes',()=>{const D=setup();let data={version:1};for(let i=0;i<100;i++){const t=new Date(now-(100-i)*86400000).toISOString();data=D.record(data,'a','live',[p],t,now);}assert.equal(data.accounts.a.days.length,90);const beforeData=JSON.stringify(data);D.demo('fake','demo',[p],at);assert.equal(JSON.stringify(data),beforeData);});
test('future readings and stale snapshots are clearly separated',()=>{const D=setup();assert.equal(compare(D,saved(D),p,{at:'2099-01-01T00:00:00Z'}).state,'missing');assert.equal(compare(D,saved(D),p,{now:now+600000}).stale,true);});
test('HTML in a source reason or denomination cannot inject elements',()=>{const D=setup(),html=D.markup({state:'ready',reason:'<script>bad</script>',pricePct:1,priceMove:2,priceCurrency:'<img>',pnlDelta:null,from:before,to:at});assert.doesNotMatch(html,/<script>|<img>/);assert.match(html,/&lt;script&gt;/);});
