import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const NOW=Date.parse('2026-10-08T15:00:00Z'),at=new Date(NOW).toISOString();
function setup(seed={}){const store=new Map(Object.entries(seed).map(([k,v])=>[k,JSON.stringify(v)]));class Clock extends Date{constructor(...a){super(...(a.length?a:[NOW]));}static now(){return NOW;}}const c={Date:Clock,Intl,console,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)}};c.window=c;vm.createContext(c);for(const f of ['lib/trading212-snapshot.js','lib/trading212-performance.js','lib/trading212-capital.js','lib/governor.js'])vm.runInContext(readFileSync(f,'utf8'),c);return {c,store,R:c.T212Capital};}
function input(extra={}){return {scope:'active',snapshot:{environment:'live',fetchedAt:at,summary:{currency:'EUR',totalValue:10000,available:9000,reserved:0,invested:1000},positions:[{ticker:'TEST_US_EQ',quantity:10,currentPrice:100,instrumentCurrency:'EUR',currency:'EUR',value:1000}]},notes:{TEST_US_EQ:{stop:95,stopCurrency:'EUR'}},history:{scope:'active',currency:'EUR',rows:[],complete:true,stale:false,state:'ready'},now:NOW,...extra};}
const fill=(id,realized,extra={})=>({id,orderId:'same-order',ticker:'TEST_US_EQ',type:'TRADE',side:'SELL',currency:'EUR',date:new Date(NOW-1000).toISOString(),realized,...extra});
test('real equity, available cash, concentration and documented stop risk use the wallet currency',()=>{const {R}=setup(),r=R.build(input());assert.equal(r.equity,10000);assert.equal(r.available,9000);assert.equal(r.rows[0].weight,10);assert.equal(r.totalStopRisk,50);assert.equal(r.budgetLeft,200);assert.equal(r.weekBudgetLeft,300);assert.equal(r.stopBudgetLeft,450);assert.equal(r.verdict,'TRADE');assert.equal(r.currency,'EUR');});
test('missing or wrong-currency stop never becomes zero total risk',()=>{const {R}=setup();for(const notes of [{},{TEST_US_EQ:{stop:95,stopCurrency:'USD'}}]){const r=R.build(input({notes}));assert.equal(r.totalStopRisk,null);assert.equal(r.verdict,'HALTED');assert.equal(r.stopCoverage,0);}});
test('a breached stop blocks new risk and remains visible',()=>{const {R}=setup(),r=R.build(input({notes:{TEST_US_EQ:{stop:101,stopCurrency:'EUR'}}}));assert.equal(r.verdict,'HALTED');assert.equal(r.rows[0].breached,true);assert.match(r.reasons.join(' '),/atins/);});
test('stale, partial, duplicated and mismatched snapshots cannot grant an allowance',()=>{const {R}=setup();for(const change of [x=>x.snapshot.fetchedAt=new Date(NOW-300001).toISOString(),x=>x.snapshot.positions=null,x=>x.snapshot.positions.push(x.snapshot.positions[0]),x=>x.snapshot.positions[0].value=500,x=>x.snapshot.positions[0].currency='USD']){const x=input();change(x);const r=R.build(x);assert.equal(r.verdict,'HALTED');assert.equal(R.sizing(r,'USD',1).ok,false);}});
test('foreign quotes show an estimated conversion from the same position and require an explicit sizing rate',()=>{const {R}=setup(),x=input();x.snapshot.positions[0].instrumentCurrency='USD';x.snapshot.positions[0].currentPrice=125;x.notes.TEST_US_EQ={stop:120,stopCurrency:'USD'};const r=R.build(x);assert.equal(r.implicitFX,true);assert.equal(r.totalStopRisk,40);assert.equal(r.verdict,'CAUTION');assert.equal(R.sizing(r,'USD').ok,false);const s=R.sizing(r,'USD',.8,'TEST_US_EQ');assert.equal(s.capital,12500);assert.equal(s.available,1250);assert.equal(s.manualFX,true);});
test('reserved orders prevent a false claim of complete stop exposure',()=>{const {R}=setup(),x=input();x.snapshot.summary.available=8900;x.snapshot.summary.reserved=100;const r=R.build(x);assert.equal(r.totalStopRisk,null);assert.equal(r.verdict,'HALTED');});
test('broker loss budgets use report values and BUY order identity rather than partial-fill count',()=>{const {R}=setup(),x=input();x.history.rows=[fill('s',-160),fill('b1',null,{side:'BUY'}),fill('b2',null,{side:'BUY'})];const r=R.build(x);assert.equal(r.todayPnl,-160);assert.equal(r.budgetLeft,40);assert.equal(r.todayTrades,1);assert.equal(r.verdict,'CAUTION');assert.equal(R.sizing(r,'EUR').ok,false);});
test('missing broker result, incomplete imports and account mismatch block budget calculation',()=>{const {R}=setup();for(const history of [{...input().history,rows:[fill('s',null)]},{...input().history,complete:false},{...input().history,scope:'other'}]){assert.equal(R.build(input({history})).verdict,'HALTED');}});
test('real position count and instrument limits constrain a new allocation',()=>{const {R}=setup(),x=input({cfg:{maxOpenPositions:1}});assert.equal(R.build(x).verdict,'HALTED');const r=R.build(input()),s=R.sizing(r,'EUR',null,'TEST_US_EQ');assert.equal(s.available,1000);});
test('Governor incorporates the real account without adding manual and broker P&L or overwriting USD capital',()=>{const x=input(),seed={tt_trading212_portfolio_v1:{active:{...x.snapshot,active:true}},tt_trading212_fills_v1:{accounts:{active:{environment:'live',items:[],complete:true,fetchedAt:at}}},tt_holdings_theses_v1:{'active|TEST_US_EQ':x.notes.TEST_US_EQ}},b=setup(seed),s=b.c.GV.status();assert.equal(s.broker.currency,'EUR');assert.equal(s.cfg.accountSize,10000);assert.equal(s.todayPnl,0);assert.equal(s.broker.equity,10000);assert.equal(s.openCount,1);assert.equal(s.manualOpenCount,0);b.store.set('tt_holdings_theses_v1','{}');assert.equal(b.c.GV.status().verdict,'HALTED');});
test('a newly selected account cannot inherit the former account equity, history or stops',()=>{const x=input(),b=setup({tt_trading212_portfolio_v1:{old:{...x.snapshot,active:false},active:{environment:'live',active:true,fetchedAt:at,summary:null,positions:null}},tt_trading212_fills_v1:{accounts:{old:{environment:'live',complete:true,fetchedAt:at,items:[]}}}}),r=b.R.read();assert.equal(r.scope,'active');assert.equal(r.equity,null);assert.equal(r.verdict,'HALTED');});
test('pence quotes retain their documented denomination and same-position wallet conversion',()=>{const {R}=setup(),x=input();x.snapshot.summary.currency='GBP';x.snapshot.positions[0]={ticker:'TEST_GB_EQ',quantity:10,currentPrice:10000,instrumentCurrency:'GBp',currency:'GBP',value:1000};x.history.currency='GBP';x.notes={TEST_GB_EQ:{stop:9500,stopCurrency:'GBp'}};const r=R.build(x);assert.equal(r.totalStopRisk,50);assert.equal(r.rows[0].rate,.01);assert.equal(r.implicitFX,true);assert.equal(r.verdict,'CAUTION');});
test('future profits cannot raise risk budgets and overflowing manual FX cannot allow sizing',()=>{const {R}=setup(),x=input();x.history.rows=[fill('future',1000,{date:new Date(NOW+1000).toISOString()})];const r=R.build(x);assert.equal(r.verdict,'HALTED');assert.equal(r.todayPnl,0);assert.equal(r.budgetLeft,200);assert.equal(R.sizing(R.build(input()),'USD',Number.MIN_VALUE).ok,false);});
