import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const NOW=Date.parse('2026-10-08T15:00:00Z');
function setup(){const store=new Map(),storage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},c={Date,Intl,localStorage:storage};c.window=c;vm.createContext(c);vm.runInContext(readFileSync('lib/trade-evidence-schema.js','utf8'),c);vm.runInContext(readFileSync('lib/trade-evidence.js','utf8'),c);return {E:c.TradeEvidence,c,store,storage};}
function record(E,extra={}){const r=E.demo(NOW).records[0];return {...JSON.parse(JSON.stringify(r)),simulation:false,source:{...r.source,kind:'market',checkedAt:NOW-300000},scope:'active',createdAt:NOW-300000,expiresAt:NOW+1500000,baselineAt:NOW-301000,...extra};}
function fill(id,side,extra={}){return {id,orderId:side==='BUY'?'buy-order':'sell-order',ticker:'FICTIVA_US_EQ',type:'TRADE',date:new Date(NOW-240000+(side==='SELL'?60000:0)).toISOString(),side,quantity:2,price:side==='BUY'?100:110,priceCurrency:'USD',currency:'EUR',realized:side==='SELL'?18:null,...extra};}
function history(rows,extra={}){return {scope:'active',currency:'EUR',rows,complete:true,stale:false,state:'ready',...extra};}
test('immutable analyses are saved once and a changed same-ID snapshot cannot replace them',async()=>{const b=setup(),r=record(b.E);await b.E.save(r,{now:NOW});await b.E.save(r,{now:NOW});assert.equal(b.E.read(b.storage,NOW).entries.length,1);await assert.rejects(b.E.save({...r,stop:90},{now:NOW}),/rescrisă/);assert.equal(b.E.read(b.storage,NOW).entries[0].stop,95);});
test('a later BUY and an unambiguous full SELL produce one position result, broker P&L and separately gross quote R',()=>{const {E}=setup(),r=record(E),out=E.evaluate([r],history([fill('b','BUY'),fill('s','SELL')]),NOW);assert.equal(out[0].state,'closed');assert.equal(out[0].pnl,18);assert.equal(out[0].pnlCurrency,'EUR');assert.equal(out[0].priceR,2);assert.equal(E.summarize(out,'EUR').count,1);assert.equal(E.summarize(out,'USD').count,0);});
test('a partial sale is still open and cannot inflate completed position count',()=>{const {E}=setup(),out=E.evaluate([record(E)],history([fill('b','BUY'),fill('s','SELL',{quantity:1,realized:9})]),NOW);assert.equal(out[0].state,'open');assert.equal(out[0].remaining,1);assert.equal(out[0].pnl,null);assert.equal(E.summarize(out,'EUR').count,0);});
test('split BUY fills of the same order and multiple partial SELLs close exactly one position',()=>{const {E}=setup(),rows=[fill('b1','BUY',{quantity:1}),fill('b2','BUY',{quantity:1,date:new Date(NOW-230000).toISOString()}),fill('s1','SELL',{quantity:1,realized:9}),fill('s2','SELL',{quantity:1,realized:8,date:new Date(NOW-1000).toISOString()})],x=E.evaluate([record(E)],history(rows),NOW)[0];assert.equal(x.state,'closed');assert.equal(x.pnl,17);assert.equal(x.buyIds.length,2);assert.equal(x.sellIds.length,2);});
test('pre-existing holdings, another BUY, overselling and corporate actions remain ambiguous',()=>{const {E}=setup();for(const [r,rows] of [[record(E,{baselineQuantity:1}),[fill('b','BUY'),fill('s','SELL')]],[record(E),[fill('b','BUY'),fill('extra','BUY',{orderId:'different',date:new Date(NOW-230000).toISOString()}),fill('s','SELL')]],[record(E),[fill('b','BUY'),fill('s','SELL',{quantity:3})]],[record(E),[fill('b','BUY'),fill('split','SELL',{type:'STOCK_SPLIT'})]]]){const out=E.evaluate([r],history(rows),NOW);assert.equal(out[0].state,'ambiguous');assert.equal(out[0].pnl,null);}});
test('a fill between the baseline account snapshot and the analysis prevents a hindsight attribution',()=>{const {E}=setup(),r=record(E,{baselineAt:NOW-400000}),rows=[fill('old','BUY',{date:new Date(NOW-350000).toISOString()}),fill('b','BUY'),fill('s','SELL')];assert.equal(E.evaluate([r],history(rows),NOW)[0].state,'ambiguous');});
test('historical BUYs and BUYs outside the fixed source window cannot be assigned retrospectively',()=>{const {E}=setup(),r=record(E),rows=[fill('old','BUY',{date:new Date(r.createdAt-1).toISOString()}),fill('late','BUY',{date:new Date(r.expiresAt+1).toISOString()})];assert.equal(E.evaluate([r],history(rows),r.expiresAt+1000)[0].state,'expired');});
test('the last frozen analysis before a BUY owns it, without evaluating the same trade twice',()=>{const {E}=setup(),a=record(E),b=record(E,{id:'new',createdAt:NOW-250000,baselineAt:NOW-251000}),out=E.evaluate([a,b],history([fill('b','BUY'),fill('s','SELL')]),NOW);assert.equal(out.filter(x=>x.state==='closed').length,1);assert.equal(out.find(x=>x.state==='closed').id,'new');});
test('incomplete histories and missing or mixed-currency realised results never become evaluated wins',()=>{const {E}=setup(),r=record(E),rows=[fill('b','BUY'),fill('s','SELL')];assert.equal(E.evaluate([r],history(rows,{complete:false}),NOW)[0].state,'unverified');assert.equal(E.evaluate([r],history([rows[0],{...rows[1],realized:null}]),NOW)[0].state,'ambiguous');const out=E.evaluate([r],history([rows[0],fill('s1','SELL',{quantity:1}),fill('s2','SELL',{quantity:1,currency:'USD',date:new Date(NOW-1000).toISOString()})]),NOW);assert.equal(out[0].state,'ambiguous');});
test('account and synthetic identities cannot leak into real results',async()=>{const b=setup(),r=record(b.E);assert.equal(b.E.evaluate([r],history([fill('b','BUY')],{scope:'other'}),NOW).length,0);const demo=b.E.demo(NOW);assert.equal(b.E.evaluate(demo.records,{...demo.history,simulation:false},NOW).length,0);await assert.rejects(b.E.save(demo.records[0],{now:NOW}),/salvată|păstrată/);});
test('group summaries include KNN abstention and direction as descriptive trade outcomes, preserving each snapshot',()=>{const {E}=setup(),demo=E.demo(NOW),before=JSON.stringify(demo.records),out=E.evaluate(demo.records,demo.history,NOW),s=E.summarize(out,'EUR');assert.equal(s.count,2);assert.equal(s.total,7);assert.equal(s.groups.filter(x=>x.model==='knn').length,2);assert.equal(JSON.stringify(demo.records),before);});
test('a corrupted ledger or unexpected private fields cannot be overwritten by a new capture',async()=>{const b=setup(),r=record(b.E);assert.equal(b.E.valid({...r,apiKey:'SECRET'},NOW),false);b.store.set(b.E.KEY,'broken');await assert.rejects(b.E.save(r,{now:NOW}),{name:'SyntaxError'});assert.equal(b.store.get(b.E.KEY),'broken');});
test('future SELL timestamps and equal-time opposite fills cannot produce an evaluated profit',()=>{const {E}=setup(),r=record(E),b=fill('b','BUY');assert.equal(E.evaluate([r],history([b,fill('future','SELL',{date:new Date(NOW+1000).toISOString()})]),NOW)[0].state,'open');assert.equal(E.evaluate([r],history([b,fill('same','SELL',{date:b.date})]),NOW)[0].state,'ambiguous');});
