import test from 'node:test';
import assert from 'node:assert/strict';
import {EvidenceCloud as C,KEYS,mergeRecord,validateValue} from '../lib/cloud-sync-model.mjs';
import {analysis,ledger} from './trade-evidence-fixtures.mjs';
const S=globalThis.TradeEvidenceSchema;
function storage(value){const map=new Map(value?[[S.KEY,JSON.stringify(value)]]:[]);return {map,getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,String(v))};}
function sameBucket(id){let i=0;while(C.bucket(id+'-'+i)!==C.bucket(id))i++;return id+'-'+i;}
test('all fixed analysis buckets are advertised and routing is stable',()=>{assert.equal(C.keys.length,64);assert.ok(KEYS.includes(S.KEY));assert.equal(new Set(C.keys).size,64);assert.ok(C.keys.every(k=>KEYS.includes(k)));assert.equal(C.bucket('auto_abc'),C.bucket('auto_abc'));});
test('immutable union preserves independent captures and the base even after a local removal',()=>{const a=analysis(),b=analysis(sameBucket('a')),key=C.bucket(a.id),r=mergeRecord(key,ledger(a),ledger(b),ledger(a));assert.equal(r.conflicts.length,0);assert.deepEqual(new Set(r.value.entries.map(x=>x.id)),new Set([a.id,b.id]));});
test('same-ID differences conflict as whole snapshots even when one side is unchanged or both change identically',()=>{const a=analysis(),b={...a,stop:90,models:a.models.map(m=>({...m,available:true,eligible:true,direction:2}))},key=C.bucket(a.id);for(const [l,r] of [[a,b],[b,b]]){const result=mergeRecord(key,ledger(a),ledger(l),ledger(r));assert.deepEqual(result.conflicts,[key+'/entries/a']);assert.ok([a.stop,b.stop].includes(result.value.entries[0].stop));assert.ok(result.value.entries[0].models.every(m=>m.available===result.value.entries[0].models[0].available));}});
test('property order does not create a false immutable conflict',()=>{const a=analysis(),b=Object.fromEntries(Object.entries(a).reverse());assert.equal(mergeRecord(C.bucket('a'),undefined,ledger(a),ledger(b)).conflicts.length,0);});
test('choice preserves every unrelated capture and chooses only disputed originals',()=>{const a=analysis(),b=analysis(sameBucket('a')),c=analysis(sameBucket(b.id)),changed={...a,stop:90},key=C.bucket('a');for(const choice of ['local','remote']){const r=C.resolve(key,ledger(a),ledger(a,b),ledger(changed,c),choice);assert.equal(r.conflicts.length,0);assert.equal(r.value.entries.find(x=>x.id==='a').stop,choice==='local'?95:90);assert.equal(r.value.entries.length,new Set(['a',b.id,c.id]).size);}});
test('synthetic captures, wrong bucket, private fields and malformed originals cannot enter cloud',()=>{const a=analysis(),key=C.bucket('a');for(const value of [ledger({...a,simulation:true,source:{...a.source,kind:'synthetic'}}),ledger({...a,apiKey:'SECRET'}),ledger({...a,baselineAt:a.createdAt+1}),ledger(a,a),{...ledger(a),private:'SECRET'}])assert.throws(()=>validateValue(key,value),/invalid_analysis_ledger/);assert.throws(()=>validateValue(C.keys.find(k=>k!==key),ledger(a)),/invalid_analysis_ledger/);});
test('applying one bucket preserves all other analyses and stops a changed same-bucket write',()=>{const a=analysis(),b=analysis('different'),c=analysis(sameBucket('a'));assert.notEqual(C.bucket(a.id),C.bucket(b.id));const s=storage(ledger(a,b)),store=C.createStore(s),key=C.bucket(a.id),expected=store.value(key);s.setItem(S.KEY,JSON.stringify(ledger(a,b,c)));assert.equal(store.replace(key,expected,ledger(a)),false);assert.equal(JSON.parse(s.getItem(S.KEY)).entries.length,3);assert.equal(store.replace(key,store.value(key),ledger(a,c)),true);assert.equal(JSON.parse(s.getItem(S.KEY)).entries.length,3);assert.equal(s.getItem(key),null);});
test('full local aggregate can exceed one cloud-record limit; buckets still reject oversized writes without truncation',()=>{const rows=Array.from({length:1500},(_,i)=>analysis('capture-'+i)),s=storage(ledger(...rows)),store=C.createStore(s);assert.ok(s.getItem(S.KEY).length>1000000);assert.ok(validateValue(S.KEY,ledger(...rows)));assert.equal(C.keys.reduce((n,k)=>n+(store.value(k)?.entries.length||0),0),1500);const crowded=[];for(let i=0;crowded.length<1200;i++){const r=analysis('large-'+i);if(C.bucket(r.id)===C.bucket('a'))crowded.push(r);}assert.throws(()=>validateValue(C.bucket('a'),ledger(...crowded)),/record_too_large/);assert.equal(JSON.parse(s.getItem(S.KEY)).entries.length,1500);});
test('a corrupted local aggregate blocks imports and retains the exact raw copy',()=>{const s=storage();s.setItem(S.KEY,'broken');assert.throws(()=>C.createStore(s).value(C.bucket('a')),SyntaxError);assert.equal(s.getItem(S.KEY),'broken');});
