import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const NOW=Date.parse('2026-10-08T05:00:00Z'),at=new Date(NOW).toISOString();
function setup(){const store=new Map(),c={localStorage:{getItem:k=>store.get(k)||null},Date};vm.createContext(c);for(const f of ['lib/trading212-snapshot.js','lib/trading212-performance.js'])vm.runInContext(readFileSync(f,'utf8'),c);return {P:c.T212Performance,store};}
function fill(id,realized=10,extra={}){return {id,orderId:'same-order',ticker:'TEST_US_EQ',date:'2026-10-07T15:00:00Z',side:'SELL',quantity:.25,price:100,priceCurrency:'USD',currency:'EUR',type:'TRADE',realized,taxes:[{name:'FX_FEE',quantity:1,currency:'EUR'}],...extra};}
function data(items,extra={}){return {scope:'active',snapshot:{environment:'live',summary:{currency:'EUR'},positions:[]},account:{environment:'live',items,complete:true,fetchedAt:at},now:NOW,...extra};}
test('reported results drive monetary statistics without subtracting costs or inventing R',()=>{const {P}=setup(),r=P.build(data([fill('a',10),fill('b',-5),fill('c',0),fill('buy',999,{side:'BUY'})]));assert.equal(r.count,3);assert.equal(r.total,5);assert.equal(r.average,5/3);assert.ok(Math.abs(r.winRate-100/3)<1e-12);assert.equal(r.factor,2);assert.equal(r.buys,1);assert.equal(r.sells,3);assert.equal(r.currency,'EUR');assert.equal(r.averageR,undefined);});
test('duplicate pages do not duplicate performance, but separate partial fills of one order remain separate exits',()=>{const {P}=setup(),a=fill('a'),r=P.build(data([a,a,fill('b',5)]));assert.equal(r.count,2);assert.equal(r.total,15);assert.equal(r.duplicates,1);assert.equal(r.complete,true);});
test('contradictory duplicates are excluded rather than arbitrarily choosing a result',()=>{const {P}=setup(),r=P.build(data([fill('a',10),fill('a',1000),fill('b',5)]));assert.equal(r.count,1);assert.equal(r.total,5);assert.equal(r.conflicts,1);assert.equal(r.complete,false);});
test('currency selection never adds different wallet currencies or silently converts them',()=>{const {P}=setup(),input=data([fill('a',10),fill('b',100,{currency:'USD'}),fill('missing',99,{currency:null})]),a=P.build(input),b=P.build({...input,selectedCurrency:'USD'});assert.equal(a.total,10);assert.equal(b.total,100);assert.equal(a.missing,1);assert.equal(b.missing,1);assert.equal(a.rows.length,2);assert.equal(b.rows.length,2);assert.deepEqual(Array.from(a.currencies),['EUR','USD']);});
test('unreported P&L remains absent and deposits, unknown types and corporate actions cannot become wins',()=>{const {P}=setup(),r=P.build(data([fill('a',null),fill('split',1000,{type:'STOCK_SPLIT'}),fill('legacy',500,{type:'MARKET'}),fill('text','90')]));assert.equal(r.count,0);assert.equal(r.total,null);assert.equal(r.winRate,null);assert.equal(r.missing,2);assert.equal(r.unsupported,2);assert.equal(r.rows.length,4);});
test('future, malformed and string-valued executions cannot enter financial totals',()=>{const {P}=setup(),r=P.build(data([fill('a',10,{quantity:'2'}),fill('b',10,{price:0}),fill('c',10,{date:new Date(NOW+120000).toISOString()}),fill('d',10)]));assert.equal(r.count,1);assert.equal(r.rejected,3);assert.equal(r.complete,false);});
test('history can remain descriptive and visible during partial imports and later sync errors',()=>{const {P}=setup(),input=data([fill('a',10)]);input.account.complete=false;let r=P.build(input);assert.equal(r.state,'partial');assert.equal(r.total,10);input.account.syncError='Import întrerupt';r=P.build(input);assert.equal(r.state,'error');assert.equal(r.total,10);assert.equal(r.complete,false);});
test('period filtering uses fill date and preserves source completeness separately',()=>{const {P}=setup(),input=data([fill('recent',5),fill('old',100,{date:'2026-01-01T15:00:00Z'})]);assert.equal(P.build(input).total,105);assert.equal(P.build({...input,days:30}).total,5);assert.equal(P.build({...input,days:30}).complete,true);});
test('account switch or key rotation cannot fall back to another account or demo results',()=>{const {P,store}=setup();store.set(P.SNAPSHOT_KEY,JSON.stringify({old:{environment:'live',active:false,fetchedAt:at,summary:{currency:'EUR'}},active:{environment:'live',active:true,fetchedAt:at,summary:{currency:'EUR'}}}));store.set(P.KEY,JSON.stringify({accounts:{old:{environment:'live',complete:true,fetchedAt:at,items:[fill('a',999)]},demo:{environment:'demo',complete:true,fetchedAt:at,items:[fill('d',500)]}}}));assert.equal(P.read({now:NOW}).state,'missing');assert.equal(P.read({now:NOW}).total,null);const raw=JSON.parse(store.get(P.KEY));raw.accounts.active={environment:'live',complete:true,fetchedAt:at,items:[fill('own',7)]};store.set(P.KEY,JSON.stringify(raw));assert.equal(P.read({now:NOW}).total,7);});
test('future import timestamps, corrupted storage and demo-only snapshots cannot produce real statistics',()=>{const {P,store}=setup(),input=data([fill('a',10)]);input.account.fetchedAt=new Date(NOW+120000).toISOString();assert.equal(P.build(input).state,'missing');store.set(P.SNAPSHOT_KEY,'broken');assert.equal(P.read().count,0);store.set(P.SNAPSHOT_KEY,JSON.stringify({demo:{environment:'demo',fetchedAt:at}}));assert.equal(P.read().count,0);});
test('performance calculation leaves imported records intact and exports no private extra fields',()=>{const {P}=setup(),input=data([fill('a',10,{apiKey:'SECRET',notes:'PRIVATE'})]),before=JSON.stringify(input),r=P.build(input);assert.equal(JSON.stringify(input),before);assert.doesNotMatch(JSON.stringify(r),/SECRET|PRIVATE|apiKey/);});

test('FX rates remain descriptive and cannot convert or alter broker P&L',()=>{const {P}=setup(),r=P.build(data([fill('a',10,{fxRate:.9}),fill('b',5,{fxRate:'1.1'})]));assert.equal(r.total,15);assert.equal(r.rows.find(x=>x.id==='a').fxRate,.9);assert.equal(r.rows.find(x=>x.id==='b').fxRate,null);});
