import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {webcrypto} from 'node:crypto';
function setup({demo=false,shared=null,scope='active',positions=[],stale=false,failCache=false,failSave=false}={}){
 let now=Date.now(),model=null,snapshot={environment:'live',active:true,fetchedAt:new Date(now-(stale?300001:1000)).toISOString(),positions},selected=scope?[scope,snapshot]:null;const store=new Map(),handlers={},node={textContent:''},events=[],locks=[],storage={getItem:k=>store.get(k)||null,setItem:(k,v)=>{if(failCache&&k==='ce_results_v2'||failSave&&k==='tt_trade_evidence_v1')throw Error('QuotaExceededError');store.set(k,String(v));}};
 class Clock extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}}
 const c={Date:Clock,Intl,URLSearchParams,TextEncoder,Uint8Array,crypto:webcrypto,structuredClone,localStorage:storage,location:{search:demo?'?demo=1':'',origin:'https://app.test',href:'https://app.test/'},document:{getElementById:id=>id==='entryAutoStatus'?node:null,querySelectorAll:()=>[]},navigator:{locks:{request:async(name,op)=>{locks.push(name);return op();}}},CustomEvent:class{constructor(type,opts){this.type=type;this.detail=opts?.detail;}},StorageEvent:class{constructor(type,opts){this.type=type;Object.assign(this,opts);}},addEventListener:(type,fn)=>(handlers[type]||=[]).push(fn),dispatchEvent:e=>{events.push(e);for(const fn of handlers[e.type]||[])fn(e);}};
 c.window=c;c.parent=shared?{location:{origin:c.location.origin},TTEntryAuto:shared}:c;vm.createContext(c);
 for(const f of ['daily-series','decision-verdict','trade-evidence-schema','trade-evidence'])vm.runInContext(readFileSync('lib/'+f+'.js','utf8'),c);
 c.T212Snapshot={read:()=>selected,fresh:(s,t=now)=>t-Date.parse(s?.fetchedAt)<=300000};c.GV={status:()=>({verdict:'TRADE',reasons:[]})};c.TTDecisionBridge={find:()=>model};vm.runInContext(readFileSync('lib/trade-evidence-auto.js','utf8'),c);
 const bars=Array.from({length:240},(_,i)=>({t:i+1,o:89.05+i*.05,h:89.35+i*.05,l:88.85+i*.05,c:89.05+i*.05,v:1000000})),trend=c.TTDecisionVerdict.trend(bars),candidate={symbol:'AAPL',mode:'momentum',kind:'market',currency:'USD',ts:now,sourceDate:c.DailySeries.expected(now,'America/New_York',960),sourceTimezone:'America/New_York',sourceCloseMinutes:960,price:101,entryLow:100,entryHigh:102,stop:95,target:116,trend,rvol:1.4,rs:3,score:80,actionable:true,earnings:'Niciun eveniment apropiat'};
 const cache={momentum:[candidate],reversal:[],analyses:[],updatedAt:now};
 return {c,cache,candidate,store,node,events,locks,auto:c.TTEntryAuto,records:()=>c.TradeEvidence.read().entries,advance:ms=>{now+=ms;},select:value=>{selected=value;},model(value){model=value;},report(){return {symbol:'AAPL',currency:'USD',asOf:candidate.sourceDate,kind:'market',historyKey:trend.historyKey,generatedAt:now,available:7,total:7,cards:c.TradeEvidence.IDS.map(id=>({id,name:id,available:true,eligible:true,direction:2,state:'up'})),direction:2,state:'up'};}};
}
test('valid scan automatically freezes actual verdict, levels and all seven states including KNN',async()=>{const s=setup();s.model(s.report());await s.auto.observe(s.cache);const r=s.records()[0];assert.equal(s.records().length,1);assert.equal(r.scope,'active');assert.equal(r.models.find(m=>m.id==='knn').direction,2);assert.equal(r.models.filter(m=>m.available).length,7);assert.ok(r.createdAt>r.baselineAt);assert.ok(s.locks.includes(s.c.TradeEvidence.KEY));assert.ok(s.events.some(e=>e.type==='storage'&&e.key===s.c.TradeEvidence.KEY));assert.match(s.node.textContent,/1 analize (noi|deja)/);});
test('same scan is deduplicated and only one primary mode owns a ticker',async()=>{const s=setup();s.cache.reversal=[{...s.candidate,mode:'reversal',score:60}];await Promise.all([s.auto.observe(s.cache),s.auto.observe(s.cache)]);assert.equal(s.records().length,1);assert.equal(s.records()[0].mode,'momentum');assert.match(s.node.textContent,/deja păstrate/);});
test('new compatible AI report preserves the old capture and never assigns earlier BUYs to the new states',async()=>{const s=setup();await s.auto.observe(s.cache);const first=JSON.stringify(s.records()[0]),buyAt=s.records()[0].createdAt+1;s.advance(1000);s.model(s.report());await s.auto.observe(s.cache);assert.equal(s.records().length,2);assert.equal(JSON.stringify(s.records()[0]),first);assert.equal(s.records()[0].models.filter(m=>m.available).length,0);assert.equal(s.records()[1].models.filter(m=>m.available).length,7);const result=s.c.TradeEvidence.evaluate(s.records(),{scope:'active',rows:[{id:'b',orderId:'one',ticker:'AAPL_US_EQ',type:'TRADE',side:'BUY',date:new Date(buyAt).toISOString(),quantity:1,price:101,priceCurrency:'USD'}],complete:true,state:'ready',stale:false});assert.equal(result.find(x=>x.id===JSON.parse(first).id).state,'open');assert.equal(result.find(x=>x.id!==JSON.parse(first).id).state,'pending');});
test('absent and stale account, invalid levels, stale source, foreign currency and synthetic scans cannot save real evidence',async()=>{for(const options of [{scope:null},{stale:true},{positions:[{ticker:'AAPL_US_EQ',quantity:null}]}]){const s=setup(options);await s.auto.observe(s.cache);assert.equal(s.records().length,0);assert.equal(s.auto.state().phase,'account');}for(const patch of [{stop:103},{currency:'EUR'},{kind:'synthetic'},{ts:Date.now()-1800001},{trend:null}]){const s=setup();Object.assign(s.candidate,patch);await s.auto.observe(s.cache);assert.equal(s.records().length,0);}});
test('demo explicitly disables both local captures and a parent real controller',async()=>{let called=0;const s=setup({demo:true,shared:{state:()=>({message:'real'}),observe:()=>{called++;}}});await s.auto.observe(s.cache);assert.equal(s.records().length,0);assert.equal(called,0);assert.match(s.node.textContent,/DEMO FICTIV/);});
test('direct scan payload works when writing the scanner cache is impossible',async()=>{const s=setup({failCache:true});await s.auto.observe(s.cache);assert.equal(s.store.get('ce_results_v2'),undefined);assert.equal(s.records().length,1);});
test('quota errors are visible and retain the existing immutable raw ledger',async()=>{const s=setup({failSave:true});await s.auto.observe(s.cache);assert.equal(s.auto.state().phase,'error');assert.match(s.node.textContent,/QuotaExceededError/);assert.equal(s.store.get(s.c.TradeEvidence.KEY),undefined);});
test('pre-existing position quantity is fixed instead of presenting additions as a new clean trade',async()=>{const s=setup({positions:[{ticker:'AAPL_US_EQ',quantity:2}]});await s.auto.observe(s.cache);assert.equal(s.records()[0].baselineQuantity,2);});
test('embedded pages reuse the parent controller without creating a second register writer',async()=>{let called=0;const s=setup({shared:{state:()=>({message:'Automat: 3 analize păstrate'}),observe:async cache=>{assert.ok(cache);called++;}}});await s.auto.observe(s.cache);assert.equal(called,1);assert.equal(s.records().length,0);assert.match(s.node.textContent,/3 analize/);});
