import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const NOW=Date.parse('2026-10-08T12:00:00Z'),c={Date,Intl};vm.createContext(c);for(const p of ['lib/daily-series.js','lib/trade-review.js'])vm.runInContext(readFileSync(p,'utf8'),c);const R=c.TradeReview,plain=x=>JSON.parse(JSON.stringify(x));
function sample(){const record={scope:'a',simulation:false,ticker:'TEST_US_EQ',symbol:'TEST',currency:'USD',createdAt:Date.parse('2026-10-01T14:00:00Z'),entryLow:99,entryHigh:101,stop:95,target:110,verdict:{code:'PLAN',title:'Plan condițional'}};const rows=[{id:'b',ticker:record.ticker,type:'TRADE',date:'2026-10-01T14:01:00Z',side:'BUY',quantity:2,price:100,priceCurrency:'USD',taxes:[{quantity:1,currency:'EUR'}]},{id:'s',ticker:record.ticker,type:'TRADE',date:'2026-10-07T15:00:00Z',side:'SELL',quantity:2,price:110,priceCurrency:'USD',taxes:[]}];return {history:{scope:'a',simulation:false,rows},outcome:{id:'r',record,state:'closed',buyIds:['b'],sellIds:['s'],pnl:18,pnlCurrency:'EUR',reason:'Închidere asociată.'}};}
function source(){return {symbol:'TEST',currency:'USD',kind:'market',timezone:'America/New_York',closeMinutes:960,asOf:'2026-10-07',retrievedAt:NOW,bars:['2026-10-01','2026-10-02','2026-10-05','2026-10-06','2026-10-07'].map((d,i)=>({t:Date.parse(d+'T13:30:00Z'),o:100,h:i===0||i===4?300:111,l:i===0||i===4?40:94,c:100,v:10000}))};}
test('review uses quantity weighted fills but checks each execution against the original zone',()=>{const {history,outcome}=sample();history.rows[0].price=98;history.rows[0].quantity=1;history.rows.push({...history.rows[0],id:'b2',price:102});outcome.buyIds.push('b2');const r=R.review(outcome,history,{now:NOW});assert.equal(r.entry.average,100);assert.equal(r.entry.inside,0);assert.equal(r.entry.total,2);assert.equal(r.exit.average,110);assert.equal(r.checks.find(x=>x.id==='entry').state,'review');});
test('cost currencies and missing provider costs stay explicit without altering broker P&L',()=>{const {history,outcome}=sample();history.rows[1].taxes=[{currency:'USD',quantity:2}];let r=R.review(outcome,history,{now:NOW});assert.deepEqual(plain(r.costs),[{currency:'EUR',value:1},{currency:'USD',value:2}]);assert.equal(outcome.pnl,18);history.rows[1].taxes=null;r=R.review(outcome,history,{now:NOW});assert.equal(r.missingCosts,1);assert.match(r.checks.at(-1).text,/18 EUR/);});
test('foreign accounts, ambiguity, absent fills, wrong quote currency and future fills are excluded',()=>{const {history,outcome}=sample();for(const change of [x=>x.history.scope='b',x=>x.history.simulation=true,x=>x.outcome.state='ambiguous',x=>x.history.rows.pop(),x=>x.history.rows[0].priceCurrency='EUR',x=>x.history.rows[0].date=new Date(NOW+1).toISOString(),x=>x.history.rows.push(x.history.rows[0])]){const s=plain({history,outcome});change(s);assert.equal(R.review(s.outcome,s.history,{now:NOW}).available,false);}});
test('prices at a stop identify execution facts, never prove a stop order existed',()=>{const {history,outcome}=sample();history.rows[1].price=94;const r=R.review(outcome,history,{now:NOW});assert.equal(r.exit.atOrBelowStop,1);assert.match(r.checks.find(x=>x.id==='exit').text,/nu confirmă existența/);history.rows[0].price=95;assert.equal(R.review(outcome,history,{now:NOW}).entry.riskPerUnit,null);});
test('daily quality excludes entry and exit sessions and measures only three complete covered sessions',()=>{const {history,outcome}=sample(),q=R.excursion(outcome,history,source(),{now:NOW});assert.equal(q.ok,true);assert.equal(q.sessions,3);assert.equal(q.high,111);assert.equal(q.low,94);assert.equal(q.favorableR,2.2);assert.equal(q.adverseR,-1.2);assert.equal(q.stopTouched,true);assert.equal(q.targetTouched,true);assert.match(q.reason,/ordinea stop/);});
test('the last partial BUY determines the start of the covered price window',()=>{const {history,outcome}=sample();history.rows[0].quantity=1;history.rows.push({...history.rows[0],id:'b2',date:'2026-10-05T14:00:00Z'});outcome.buyIds.push('b2');const q=R.excursion(outcome,history,source(),{now:NOW});assert.equal(q.ok,true);assert.equal(q.sessions,1);assert.equal(q.from,'2026-10-06');});
test('same day trades have no fabricated intraday extremes',()=>{const {history,outcome}=sample();history.rows[1].date='2026-10-01T16:00:00Z';const q=R.excursion(outcome,history,source(),{now:NOW});assert.equal(q.ok,false);assert.match(q.reason,/Nicio sesiune completă/);});
test('missing sessions, stale identity and split adjustments after exit block price comparison',()=>{const s=sample();for(const change of [x=>x.symbol='OTHER',x=>x.currency='EUR',x=>x.retrievedAt=NOW-300001,x=>x.bars.shift(),x=>x.bars.pop(),x=>x.bars[1].c=200]){const series=source();change(series);assert.equal(R.excursion(s.outcome,s.history,series,{now:NOW}).ok,false);}const q=R.excursion(s.outcome,s.history,source(),{splits:[NOW-1],now:NOW});assert.equal(q.ok,false);assert.match(q.reason,/Split după captura/);});
test('open positions use complete EOD sessions and unavailable costs do not invent net R',()=>{const s=sample();s.outcome.state='open';s.outcome.sellIds=[];const series=source();series.bars.at(-1).h=111;series.bars.at(-1).l=94;const q=R.excursion(s.outcome,s.history,series,{now:NOW});assert.equal(q.ok,true);assert.equal(q.sessions,4);assert.equal(q.netR,undefined);assert.equal(q.pnlCurrency,undefined);});
