import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function setup(data){const c={localStorage:{getItem:k=>JSON.stringify(data[k]||{})}};vm.createContext(c);vm.runInContext(readFileSync('lib/trading212-snapshot.js','utf8'),c);vm.runInContext(readFileSync('lib/trading212-context.js','utf8'),c);return c.T212C;}
test('held US equities exclude demo, zero positions and ambiguous European symbols',()=>{const c=setup({tt_trading212_portfolio_v1:{live:{environment:'live',fetchedAt:new Date().toISOString(),positions:[{ticker:'TSLA_US_EQ',quantity:1},{ticker:'NVDA_US_EQ',quantity:0},{ticker:'SAP_DE_EQ',quantity:1}]},demo:{environment:'demo',positions:[{ticker:'AAPL_US_EQ',quantity:1}]}}});assert.equal(c.held('TSLA').length,1);assert.equal(c.held('NVDA').length,0);assert.equal(c.held('AAPL').length,0);assert.equal(c.symbol('SAP_DE_EQ'),null);assert.match(c.badge('TSLA'),/DEȚII DEJA/);});
test('exposure rejects incompatible currencies and unavailable account total',()=>{const c=setup({});assert.equal(c.concentration({summary:null,positions:[]}).missing,true);const r=c.concentration({summary:{currency:'EUR',totalValue:100},positions:[{ticker:'AAPL',currency:'EUR',value:25,quantity:1},{ticker:'X',currency:'USD',value:50,quantity:1}]});assert.equal(r.rows.length,1);assert.equal(r.rows[0].weight,25);assert.equal(r.missing,true);});
test('API-key rotation cannot double current holdings or Coach executions',()=>{const now=new Date().toISOString(),old='2026-09-01T12:00:00Z',c=setup({tt_trading212_portfolio_v1:{old:{environment:'live',fetchedAt:old,positions:[{ticker:'TSLA_US_EQ',quantity:1}]},new:{environment:'live',fetchedAt:now,positions:[{ticker:'TSLA_US_EQ',quantity:1}]}},tt_trading212_fills_v1:{accounts:{old:{environment:'live',fetchedAt:old,items:[{id:'a',side:'BUY'}]},new:{environment:'live',fetchedAt:now,items:[{id:'a',side:'BUY'}]}}}});assert.equal(c.held('TSLA').length,1);assert.equal(c.insights().length,1);assert.equal(c.insights()[0].count,1);});

test('partial account snapshot never resurrects holdings or Coach fills from another account',()=>{
 const c=setup({tt_trading212_portfolio_v1:{old:{environment:'live',fetchedAt:'2026-10-02T12:00Z',positions:[{ticker:'TSLA_US_EQ',quantity:1}]},current:{environment:'live',active:true,fetchedAt:new Date().toISOString(),summary:{currency:'EUR'},positions:null}},tt_trading212_fills_v1:{accounts:{old:{environment:'live',items:[{side:'SELL',realized:99,currency:'EUR'}]}}}});
 assert.equal(c.snapshots().length,1);assert.equal(c.snapshots()[0].positions,null);assert.equal(c.held('TSLA').length,0);assert.equal(c.insights().length,0);
});
