import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {webcrypto} from 'node:crypto';
function setup(cryptography=webcrypto){const records=new Map();let initialized=false;const db={createObjectStore(){},close(){},transaction(){const tx={};const request=(fn)=>{const r={};queueMicrotask(()=>{r.result=fn();r.onsuccess();queueMicrotask(()=>tx.oncomplete());});return r;};tx.objectStore=()=>({get:k=>request(()=>records.get(k)),put:(v,k)=>request(()=>records.set(k,structuredClone(v))),delete:k=>request(()=>records.delete(k))});return tx;}};const c={crypto:cryptography,TextEncoder,TextDecoder,btoa,atob,indexedDB:{open(){const r={};queueMicrotask(()=>{r.result=db;if(!initialized){initialized=true;r.onupgradeneeded();}r.onsuccess();});return r;}}};vm.createContext(c);vm.runInContext(readFileSync('lib/trading212-vault.js','utf8'),c);return {vault:c.T212Vault,records};}
const payload={key:'test-key',secret:'test-secret',environment:'live'};
test('device connection encrypts credentials with nonexportable key, restores and deletes',async()=>{const {vault,records}=setup();assert.equal(await vault.read(),null);await vault.save(payload);const record=records.get('connection');assert.equal(record.key.extractable,false);assert.equal(new TextDecoder().decode(record.cipher).includes(payload.secret),false);assert.equal(JSON.stringify(record).includes(payload.secret),false);assert.deepEqual(JSON.parse(JSON.stringify(await vault.read())),payload);await vault.clear();assert.equal(await vault.read(),null);});
test('phone transfer encrypts credentials and rejects wrong password and malformed input',async()=>{const {vault}=setup();await vault.save(payload);const code=await vault.pack('phone-transfer-password');assert.ok(code.startsWith('TT212.'));assert.equal(code.includes(payload.secret),false);const other=setup().vault;assert.deepEqual(JSON.parse(JSON.stringify(await other.unpack(code,'phone-transfer-password'))),payload);await assert.rejects(other.unpack(code,'wrong-password-value'),/incorectă/);await assert.rejects(other.unpack('not-a-code','phone-transfer-password'),/invalid/);await assert.rejects(vault.pack('short'),/12/);});

test('forget invoked during encryption waits for that save and leaves no resurrected connection',async()=>{
 let release,started;const entered=new Promise(r=>started=r),cryptography={getRandomValues:v=>webcrypto.getRandomValues(v),subtle:{generateKey:async(...args)=>{started();await new Promise(r=>release=r);return webcrypto.subtle.generateKey(...args);},encrypt:(...args)=>webcrypto.subtle.encrypt(...args),decrypt:(...args)=>webcrypto.subtle.decrypt(...args)}};
 const {vault}=setup(cryptography),saving=vault.save(payload);await entered;const forgetting=vault.clear();release();await Promise.all([saving,forgetting]);assert.equal(await vault.read(),null);
});
test('failed vault write cannot block subsequent credential save or forget',async()=>{
 const {vault}=setup();const invalid=vault.save({...payload,key:''}),valid=vault.save(payload);await assert.rejects(invalid,/incompatibil/);await valid;assert.equal((await vault.read()).key,payload.key);await vault.clear();assert.equal(await vault.read(),null);
});
